### ISSUE TITLE
calling the grpc Table api's HeadBy function causes an internal error in the server.

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#1002]
The following test case in the new Python client packages fails.
```
   def test_head_tail_by(self):
        ops = [Table.head_by,
               Table.tail_by]
        pa_table = csv.read_csv(self.csv_file)
        test_table = self.session.import_table(pa_table)
        for op in ops:
            result_table = op(test_table, num_rows=50, column_names=["a", "c"])
            self.assertEqual(result_table.size, 50)
```

This is the error the client receives.
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Details Logged w/ID 'ef1830f1-dd4b-48c4-8675-3c6e6965cb51'"
	debug_error_string = "{"created":"@1628546593.560843000","description":"Error received from peer ipv6:[::1]:10000","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Details Logged w/ID 'ef1830f1-dd4b-48c4-8675-3c6e6965cb51'","grpc_status":13}"

```
And this is what's in the server log.
```
grpc-api_1    | 2021-08-09T22:03:13.565Z | heduler-Concurrent-2 | ERROR | i.d.g.s.SessionState      | Internal Error 'ef1830f1-dd4b-48c4-8675-3c6e6965cb51' java.lang.RuntimeException: Error compiling class io.deephaven.temp.c860885561987228486v52_0.Formula:
grpc-api_1    | /io/deephaven/temp/c860885561987228486v52_0/Formula.java:158: error: variable e is already defined in method applyFormulaPerItem(DbLongArray)
grpc-api_1    |         } catch (java.lang.Exception e) {
grpc-api_1    |                                      ^
grpc-api_1    | Note: /io/deephaven/temp/c860885561987228486v52_0/Formula.java uses unchecked or unsafe operations.
grpc-api_1    | Note: Recompile with -Xlint:unchecked for details.
grpc-api_1    | 1 error
grpc-api_1    |
grpc-api_1    |         at io.deephaven.compilertools.CompilerTools.maybeCreateClassHelper(CompilerTools.java:766)
grpc-api_1    |         at io.deephaven.compilertools.CompilerTools.maybeCreateClass(CompilerTools.java:730)
grpc-api_1    |         at io.deephaven.compilertools.CompilerTools.compileHelper(CompilerTools.java:489)
grpc-api_1    |         at io.deephaven.compilertools.CompilerTools.compile(CompilerTools.java:448)
grpc-api_1    |         at io.deephaven.compilertools.CompilerTools.compile(CompilerTools.java:403)
grpc-api_1    |         at io.deephaven.db.v2.select.DhFormulaColumn.lambda$compileFormula$19(DhFormulaColumn.java:759)
grpc-api_1    |         at java.security.AccessController.doPrivileged(AccessController.java:-2)
grpc-api_1    |         at io.deephaven.db.v2.select.DhFormulaColumn.compileFormula(DhFormulaColumn.java:758)
grpc-api_1    |         at io.deephaven.db.v2.select.DhFormulaColumn.createFormulaFactory(DhFormulaColumn.java:723)
grpc-api_1    |         at io.deephaven.db.v2.select.AbstractFormulaColumn.getFormula(AbstractFormulaColumn.java:223)
grpc-api_1    |         at io.deephaven.db.v2.select.AbstractFormulaColumn.getViewColumnSource(AbstractFormulaColumn.java:213)
...
```

**Comment by kosak** [comment]
Let's not have @nbauernfeind and me race to fix this. How about I'll take a look first.

**Comment by jmao-denver** [comment]
good idea, @kosak; removed @nbauernfeind from the assignees list.
