### ISSUE TITLE
Update auto-export for Table to handle TableMapProxy correctly (by attempting to coalesce)

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#1084]
As a user, when I have a `io.deephaven.db.v2.TableMapProxyHandler.TableMapProxy` (resulting from `io.deephaven.db.v2.TransformableTableMap#asTable(boolean, boolean, boolean)`), I want to be able to view my proxy as if it were really a `Table`.

This requires the UI to recognize that an object is a `TableMapProxy` and attempt to `.coalesce()` it before export.

**Comment by rcaudy** [comment]
Note: currently the following happens:
```
heduler-Concurrent-2 | i.d.g.s.SessionState      | Internal Error '8003f931-396c-42fd-897b-001af0b0c6be' java.lang.UnsupportedOperationException: Method is not supported by TableMapProxyHandler: public abstract boolean io.deephaven.db.util.liveness.LivenessReferent.tryRetainReference()
        at io.deephaven.db.v2.TableMapProxyHandler.invoke(TableMapProxyHandler.java:100)
        at com.sun.proxy.$Proxy9.tryRetainReference(null:-1)
        at io.deephaven.db.util.liveness.ReferenceCountedLivenessNode.tryManage(ReferenceCountedLivenessNode.java:79)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.setResult(SessionState.java:854)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:784)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:141)
        at java.lang.Thread.run(Thread.java:748)
```
I could delegate liveness methods to the proxied map, but that wouldn't solve the real issue.

**Comment by rcaudy** [comment]
Probably we should add a marker for tables, e.g. `NeedsCoalesceToExport`. `UncoalescedTable` could implement it, as could the proxy. We could then subsequently offer filtering behavior like in DHE, but not try to export the not-coalesced table.
Except we would only want to do the coalesce for rendering, not for things like getting a handle for client-side QST/table-proxy ops.

**Comment by rcaudy** [comment]
Breadcrumbs from @nbauernfeind regarding where to make this change in the naive way:

https://github.com/deephaven/deephaven-core/blob/main/grpc-api/src/main/java/io/deephaven/grpc_api/console/ConsoleServiceGrpcImpl.java#L244

ConsoleServiceGrpcImpl.java
                        Table table = ColumnPreviewManager.applyPreview((Table) result);
