### ISSUE TITLE
Importing groovy.time.* results in an error

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#1129]
The following code (in a Deephaven Groovy console):

`import groovy.time.*`

Results in the following error and stack trace:
```
r-Scheduler-Serial-1 | .u.GroovyDeephavenSession | Invalid import: "import groovy.time.*;"
r-Scheduler-Serial-1 | i.d.g.s.SessionState      | Internal Error '12e4617c-5ec4-41d3-a2c5-219105f4df9b' java.lang.RuntimeException: Attempting to import a path that does not exist: import groovy.time.*;
        at io.deephaven.db.util.GroovyDeephavenSession.updateScriptImports(GroovyDeephavenSession.java:487)
        at io.deephaven.db.util.GroovyDeephavenSession.grepScriptImports(GroovyDeephavenSession.java:498)
        at io.deephaven.db.util.GroovyDeephavenSession.evaluate(GroovyDeephavenSession.java:229)
        at io.deephaven.db.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:115)
        at io.deephaven.db.util.ScriptSession.evaluateScript(ScriptSession.java:71)
        at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl.lambda$null$8(ConsoleServiceGrpcImpl.java:176)
        at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$1(SessionState.java:1303)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:866)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:146)
        at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce**
1. Launch deephaven-core with Groovy
2. `import groovy.time.*`
3. An error will occur

**Expected results**

Not much to happen.  The import should work, and you should be able to use the groovy time library.

**Actual results**

An error with the stack trace given above.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: community
 - OS: Big Sur
 - Browser: Chrome
 - Docker: 20.10.7

**Comment by mattrunyon** [comment]
Some more info. If you do the following, there is no error. If you start with the wildcard import than there's an error.

```
import groovy.time.TimeCategory
import groovy.time.*
```
