### ISSUE TITLE
TestModelFarm: Racy unit test creates spurious failures in CI

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#1150]
```
io.deephaven.base.verify.RequirementFailure: Requirement failed: required terminated == true, instead terminated == false, testShutdownTimeoutSecs == 1.0.
	at io.deephaven.base.verify.Require.fail(Require.java:108)
	at io.deephaven.base.verify.Require.requirement(Require.java:247)
	at io.deephaven.base.verify.Require.requirement(Require.java:254)
	at io.deephaven.modelfarm.TestModelFarm.testModelFarmNoWorkShutdown(TestModelFarm.java:44)
```
The test in question sleeps for 100 milliseconds and assumes that's enough time for a condition to be met. This isn't a good strategy for reliable, consistent unit testing.

**Comment by niloc132** [comment]
Saw the failure on a nightly run https://github.com/deephaven/deephaven-core/runs/4336000320
