### ISSUE TITLE
Auto complete is unhappy when unexpected character is placed into document

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#1196]
Certain characters make auto-complete unhappy and spit out errors.

For example the character `ç`, placed anywhere but inside of a string or character literal, plops this stack trace into the console log:
```
heduler-Concurrent-2 | i.d.g.s.SessionState      | Internal Error '6ec75246-5560-48ad-bf6c-374c2821d458' java.lang.IllegalStateException: Unable to complete document parsing for inmemory://model/1
        at io.deephaven.lang.parse.CompletionParser.lambda$finish$1(CompletionParser.java:124)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at io.deephaven.lang.parse.CompletionParser.finish(CompletionParser.java:124)
        at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl$1.lambda$onNext$3(ConsoleServiceGrpcImpl.java:308)
        at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1271)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:824)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:147)
        at java.lang.Thread.run(Thread.java:748)
```

Similarly a `#` in a groovy script drops this SIOOBE:
```
2021-09-02T04:40:43.306Z | heduler-Concurrent-3 | ERROR | i.d.g.s.SessionState      | Internal Error '217bf3f1-5b6e-4526-a2f8-c9234a045023' java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at io.deephaven.lang.completion.ChunkerCompleter.identCompletion(ChunkerCompleter.java:639)
        at io.deephaven.lang.completion.ChunkerCompleter.access$500(ChunkerCompleter.java:30)
        at io.deephaven.lang.completion.ChunkerCompleter$1.visitChunkerIdent(ChunkerCompleter.java:421)
        at io.deephaven.lang.generated.ChunkerIdent.jjtAccept(ChunkerIdent.java:25)
        at io.deephaven.lang.completion.ChunkerCompleter.searchForResults(ChunkerCompleter.java:369)
        at io.deephaven.lang.completion.ChunkerCompleter.runCompletion(ChunkerCompleter.java:113)
        at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl$1.lambda$onNext$3(ConsoleServiceGrpcImpl.java:325)
        at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1271)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:824)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:147)
        at java.lang.Thread.run(Thread.java:748)
```

The expected behavior is for there to be no error logs related to auto complete if the developer can't get his fingers to do what his mind wants them to do.

**Comment by abaranec** [comment]
To add to this,  If I have a comment line and I terminate it with a period,  this exception happens ~80% of the time

This string in particular seems to do it

# A simple method to add a city to the set of cities to watch.

Just delete and re-add the period and it will frequently happen
