### ISSUE TITLE
Bug in ChunkColumnSources observed via streaming lastBy

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#1227]
```
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
    at gnu.trove.list.array.TLongArrayList.get(TLongArrayList.java:281)
    at io.deephaven.db.v2.sources.chunkcolumnsource.IntChunkColumnSource.getChunkIndex(IntChunkColumnSource.java:141)
    at io.deephaven.db.v2.sources.chunkcolumnsource.IntChunkColumnSource.lambda$fillChunk$0(IntChunkColumnSource.java:98)
    at io.deephaven.db.v2.utils.OrderedKeys.lambda$forAllLongRanges$1(OrderedKeys.java:219)
    at io.deephaven.db.v2.utils.OrderedKeysKeyIndicesChunkImpl.forEachLongRange(OrderedKeysKeyIndicesChunkImpl.java:231)
    at io.deephaven.db.v2.utils.OrderedKeys.forAllLongRanges(OrderedKeys.java:218)
    at io.deephaven.db.v2.sources.chunkcolumnsource.IntChunkColumnSource.fillChunk(IntChunkColumnSource.java:96)
    at io.deephaven.db.v2.sources.chunk.DefaultChunkSource.getChunkByFilling(DefaultChunkSource.java:38)
    at io.deephaven.db.v2.sources.chunkcolumnsource.IntChunkColumnSource.getChunk(IntChunkColumnSource.java:89)
    at io.deephaven.db.v2.sources.SwitchColumnSource.getChunk(SwitchColumnSource.java:156)
    at io.deephaven.db.v2.by.CopyingPermutedStreamFirstOrLastChunkedOperator.copyStreamToResult(CopyingPermutedStreamFirstOrLastChunkedOperator.java:104)
    at io.deephaven.db.v2.by.StreamLastChunkedOperator.propagateInitialState(StreamLastChunkedOperator.java:81)
    at io.deephaven.db.v2.by.AggregationContext.propagateInitialStateToOperators(AggregationContext.java:227)
    at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.aggregation(ChunkedOperatorAggregationHelper.java:177)
    at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.lambda$aggregation$1(ChunkedOperatorAggregationHelper.java:81)
    at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1163)
    at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1012)
    at io.deephaven.db.v2.BaseTable.initializeWithSnapshot(BaseTable.java:1376)
    at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.aggregation(ChunkedOperatorAggregationHelper.java:78)
    at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.aggregation(ChunkedOperatorAggregationHelper.java:50)
    at io.deephaven.db.v2.QueryTable.lambda$byNoMemo$22(QueryTable.java:630)
    at io.deephaven.db.tables.utils.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:483)
    at io.deephaven.db.v2.QueryTable.byNoMemo(QueryTable.java:578)
    at io.deephaven.db.v2.QueryTable.lambda$by$21(QueryTable.java:571)
    at io.deephaven.db.v2.QueryTable$MemoizedResult.getOrCompute(QueryTable.java:3024)
    at io.deephaven.db.v2.QueryTable.memoizeResult(QueryTable.java:2996)
    at io.deephaven.db.v2.QueryTable.by(QueryTable.java:570)
    at io.deephaven.db.v2.QueryTable.lambda$lastBy$15(QueryTable.java:506)
    at io.deephaven.db.tables.utils.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:483)
    at io.deephaven.db.v2.QueryTable.lastBy(QueryTable.java:502)
    at io.deephaven.db.tables.Table.lastBy(Table.java:1929)
```

**Comment by rcaudy** [comment]
The reported failing script:
```
from deephaven import KafkaTools as kt
from deephaven import Types as dh

trades = kt.consumeToTable(
        {'bootstrap.servers' : 'redpanda:29092',
            'schema.registry.url' : 'http://registry:8080/api/ccompat'},
        'Trade',
        key = kt.IGNORE,
        value = kt.avro('Trade-io.deephaven.crypto.Trade', schema_version='latest'),
        table_type='stream'
    )

quotesLastBy = quotes.lastBy("instrument")
```

Additional notes:
>other columns were working for lastBy
>instrument is a column that has 3 unique values
>and is a string

**Comment by rcaudy** [comment]
@cpwright 
>it’s going to be something index related w/ that source
>the crypto feed he has is likely higher volume and less predictable than our tests

@rcaudy 
>It seems to me like it's either gotta be the underlying source, or the chunked operator.

**Comment by rcaudy** [comment]
The issue is in the `*ChunkColumnSource.fillChunk` method. If we are filling from an ordered keys with a range that is enclosed by the *last* backing chunk, but isn't the final range, we'll incorrectly advance our search start chunk index past the end of the backing chunks list.
