### ISSUE TITLE
deephaven.ParquetTools.readTable() doesn't support Parquet date32 or date64 data types

### ISSUE THREAD

**Issue by mikeblas** [deephaven/deephaven-core#1253]
**Description**

Using `readTable()` I've found that I can't read files that contain columns with the `date32` or `date64` data types. An exception is thrown. If we don't support it that's cool -- let's document it, and try to express a workaround about it if possible. But it would be nice to support the types ...

**Steps to reproduce**

```python
from deephaven.ParquetTools import readTable

s = readTable("/data/equity-quotes-2021-03-04.parquet")
```

**Expected results**

Table is imported successfully

**Actual results**

An exception is thrown; here's how it starts out:
```
r-Scheduler-Serial-1 | i.d.g.s.SessionState      | Internal Error 'c5ef3418-ec87-4e7d-9b81-c1d7da6bfd02' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'RuntimeError'>
Value: io.deephaven.UncheckedDeephavenException: Unable to read column [Date]: DateLogicalType not supported
	at io.deephaven.db.v2.parquet.ParquetSchemaReader.lambda$readParquetSchema$2(ParquetSchemaReader.java:272)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.deephaven.db.v2.parquet.ParquetSchemaReader.readParquetSchema(ParquetSchemaReader.java:266)
	at io.deephaven.db.tables.utils.ParquetTools.convertSchema(ParquetTools.java:650)
	at io.deephaven.db.tables.utils.ParquetTools.readTableInternal(ParquetTools.java:386)
	at io.deephaven.db.tables.utils.ParquetTools.readTable(ParquetTools.java:110)
	at org.jpy.PyLib.executeCode(Native Method)
:
:
```

**Additional details and attachments**

[parquet_date.zip](https://github.com/deephaven/deephaven-core/files/7147092/parquet_date.zip)

**Comment by jcferretti** [comment]
Fixed by #1254
