### ISSUE TITLE
Downsampling throws an error

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#1282]
**Description**

When trying to display a plot with Downsampling, getting an error

**Steps to reproduce**
1. Run the following code snippet (requires Deephaven examples to be set up in your data container):
```python
from deephaven.ParquetTools import readTable
from deephaven.Plot import plot

taxiTable = readTable("/data/examples/taxi/parquet/taxi.parquet")
p = plot("Plot", taxiTable, "tpep_pickup_datetime", "trip_distance").show() 
```

**Expected results**

1. A table and a chart appear

**Actual results**

1. The table appears, the chart panel appears but is blank. Error is output to the logs

**Additional details and attachments**
![image](https://user-images.githubusercontent.com/4505624/133291546-6fb2a857-5729-438c-9c24-d82145ffeb1b.png)
```
heduler-Concurrent-3 | i.d.g.s.SessionState      | Internal Error 'b118e384-0ffc-48d6-a515-ac47456ed326' java.lang.IllegalArgumentException: Can't downsample table of type class io.deephaven.db.v2.SimpleSourceTable
        at io.deephaven.clientsupport.plotdownsampling.RunChartDownsample.call(RunChartDownsample.java:129)
        at io.deephaven.clientsupport.plotdownsampling.RunChartDownsample.call(RunChartDownsample.java:49)
        at io.deephaven.db.tables.Table.apply(Table.java:2468)
        at io.deephaven.grpc_api.table.ops.RunChartDownsampleGrpcImpl.create(RunChartDownsampleGrpcImpl.java:35)
        at io.deephaven.grpc_api.table.ops.RunChartDownsampleGrpcImpl.create(RunChartDownsampleGrpcImpl.java:14)
        at io.deephaven.grpc_api.table.TableServiceGrpcImpl.lambda$null$14(TableServiceGrpcImpl.java:417)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:825)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:147)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by rcaudy** [comment]
`coalesce()` is a no-op or memoized. If you require coalesced input, call `.coalesce()` on it. Then you should be able to safely cast to `QueryTable`.
