### ISSUE TITLE
DBTimeUtils.lastBusinessDateNy() is non functional

### ISSUE THREAD

**Issue by jakemulf** [deephaven/deephaven-core#1298]
**Description**

Python
```python
from deephaven.DBTimeUtils import lastBusinessDateNy

lastBusinessDateNyResult = lastBusinessDateNy()
print(lastBusinessDateNyResult)
```

Groovy
```groovy
lastBusinessDateNyResult = lastBusinessDateNy()
println lastBusinessDateNyResult
```

Both of these cause some type of error when executed

**Expected results**

The `print()`/`println` statements would show a reasonable output

**Actual results**

For Python, the following error is thrown within the console

```
r-Scheduler-Serial-1 | i.d.g.s.SessionState      | Internal Error 'bb5dedaa-6ab9-4b5b-9053-2229de6129f5' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'RuntimeError'>
Value: java.lang.NoClassDefFoundError: Could not initialize class io.deephaven.util.calendar.Calendars
	at io.deephaven.db.tables.utils.DBTimeUtils.lastBusinessDateNy(DBTimeUtils.java:1323)
	at io.deephaven.db.tables.utils.DBTimeUtils.lastBusinessDateNy(DBTimeUtils.java:1305)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.db.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
	at io.deephaven.db.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:173)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
	at io.deephaven.db.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:172)
	at io.deephaven.db.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:104)
	at io.deephaven.db.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
	at io.deephaven.db.util.ScriptSession.evaluateScript(ScriptSession.java:79)
	at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl.lambda$null$8(ConsoleServiceGrpcImpl.java:189)
	at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1271)
	at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:824)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:147)
	at java.lang.Thread.run(Thread.java:748)

Line: 741
Namespace: lastBusinessDateNy
File: /usr/local/lib/python3.7/dist-packages/deephaven/DBTimeUtils/__init__.py
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/local/lib/python3.7/dist-packages/wrapt/wrappers.py", line 567, in __call__
  File "/usr/local/lib/python3.7/dist-packages/deephaven/DBTimeUtils/__init__.py", line 72, in _passThrough
  File "/usr/local/lib/python3.7/dist-packages/deephaven/DBTimeUtils/__init__.py", line 741, in lastBusinessDateNy

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.db.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
        at io.deephaven.db.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:173)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
        at io.deephaven.db.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:172)
        at io.deephaven.db.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:104)
        at io.deephaven.db.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
        at io.deephaven.db.util.ScriptSession.evaluateScript(ScriptSession.java:79)
        at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl.lambda$null$8(ConsoleServiceGrpcImpl.java:189)
        at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1271)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:824)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:147)
        at java.lang.Thread.run(Thread.java:748)
```

For Groovy, the console crashes after about 10 seconds. Refreshing the page shows the following error

```
Error: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup grpc-api on 127.0.0.11:53: no such host"
```

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: latest
 - OS: Windows 10 WSL Ubuntu
 - Browser: Chrome
 - Docker: Docker version 20.10.8, build 3967b7d

**Comment by jakemulf** [comment]
Looks like this extends to anything using the Calendar class. The following python query gives the same result

```
from deephaven.DBTimeUtils import convertDateTime
from deephaven.TableTools import newTable, dateTimeCol

firstTime = convertDateTime("2021-07-04T08:00:00 NY")
secondTime = convertDateTime("2021-09-06T12:30:00 NY")
thirdTime = convertDateTime("2021-12-25T21:15:00 NY")

source = newTable(
    dateTimeCol("DateTimes", firstTime, secondTime, thirdTime)
)

today = source.where("DateTimes = currentDay()")
yesterday = source.where("DateTimes = previousDay()")
previousBusinessDay = source.where("DateTimes = previousBusinessDay()")
```

**Comment by mattrunyon** [comment]
I'll add another example that crashes Python

```
from deephaven.TableTools import newTable, stringCol, intCol, doubleCol, dateTimeCol
from deephaven.DBTimeUtils import convertDateTime, autoEpochToTime

source = newTable(
    stringCol("Ticker", "AAPL", "AAPL", "AAPL", "AAPL", "AAPL"),
    dateTimeCol("Timestamp", convertDateTime("2021-04-05T09:10:39.123456700 NY"), convertDateTime("2021-04-05T09:10:50.123456700 NY"), convertDateTime("2021-04-05T09:11:39.123456700 NY"), convertDateTime("2021-04-05T09:11:50.123456700 NY"), convertDateTime("2021-04-05T09:12:39.123456700 NY")),
    doubleCol("Price", 100.10, 101.0, 102.40, 100.50, 100.30),
    intCol("Size", 52, 14, 73, 11, 6)
)

result = source.update("Time = autoEpochToTime(5000)")
```

**Comment by chipkent** [comment]
I think this is related to #487 and #1085.  Suspect the calendar configs are not present, so no calendar loads, and then the time methods fail when called.
