### ISSUE TITLE
Server exception if I do a FetchTableAsync too soon after an Arrow DoPut

### ISSUE THREAD

**Issue by kosak** [deephaven/deephaven-core#1307]
Hi,

I have a situation that I can repro 100% reliably:
1. Start up a fresh Deephaven instance
2. Do this sequence of steps:
3. Create Table "demo" with Arrow DoPut
4. Fetch table "demo" with fetchTableAsync (do not necessarily wait for the result)
5. Create Table "temp1" with Arrow DoPut
6. Fetch table "temp1" with fetchTableASync
7. Server shows the below internal error; client waits forever for a result from this fetchTableAsync
8. The problem goes away if I add a sleep(250 milliseconds) between steps 5 and 6

I am happy to provide more details, or a running repro.

```
grpc-api_1    | 2021-09-17T18:12:18.478Z | c-nio-worker-ELG-3-2 | ERROR | .g.t.TableServiceGrpcImpl | Internal Error '9b5a83b2-954c-4caa-a114-33eca3bda1bd' io.deephaven.db.tables.select.QueryScope$MissingVariableException: No binding for: temp1
grpc-api_1    |         at io.deephaven.db.util.GroovyDeephavenSession.getVariable(GroovyDeephavenSession.java:185)
grpc-api_1    |         at io.deephaven.grpc_api.console.ScopeTicketResolver.lambda$resolve$2(ScopeTicketResolver.java:100)
grpc-api_1    |         at io.deephaven.util.locks.FunctionalLock.computeLocked(FunctionalLock.java:64)
grpc-api_1    |         at io.deephaven.grpc_api.console.ScopeTicketResolver.resolve(ScopeTicketResolver.java:97)
grpc-api_1    |         at io.deephaven.grpc_api.console.ScopeTicketResolver.resolve(ScopeTicketResolver.java:85)
grpc-api_1    |         at io.deephaven.grpc_api.session.TicketRouter.resolve(TicketRouter.java:57)
grpc-api_1    |         at io.deephaven.grpc_api.session.TicketRouter.resolve(TicketRouter.java:89)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl.lambda$null$12(TableServiceGrpcImpl.java:410)
grpc-api_1    |         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
grpc-api_1    |         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
grpc-api_1    |         at java.util.Collections$2.tryAdvance(Collections.java:4719)
grpc-api_1    |         at java.util.Collections$2.forEachRemaining(Collections.java:4727)
grpc-api_1    |         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
grpc-api_1    |         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
grpc-api_1    |         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
grpc-api_1    |         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
grpc-api_1    |         at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl.lambda$oneShotOperationWrapper$15(TableServiceGrpcImpl.java:411)
grpc-api_1    |         at io.deephaven.grpc_api.util.GrpcUtil.rpcWrapper(GrpcUtil.java:33)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl.oneShotOperationWrapper(TableServiceGrpcImpl.java:396)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl.fetchTable(TableServiceGrpcImpl.java:252)
grpc-api_1    |         at io.deephaven.proto.backplane.grpc.TableServiceGrpc$MethodHandlers.invoke(TableServiceGrpc.java:2835)
grpc-api_1    |         at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
grpc-api_1    |         at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
grpc-api_1    |         at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
grpc-api_1    |         at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
grpc-api_1    |         at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
grpc-api_1    |         at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
grpc-api_1    |         at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797)
grpc-api_1    |         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
grpc-api_1    |         at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
grpc-api_1    |         at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.halfClosed(ServerImpl.java:808)
grpc-api_1    |         at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:231)
grpc-api_1    |         at io.grpc.netty.NettyServerStream$TransportState.deframerClosed(NettyServerStream.java:168)
grpc-api_1    |         at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:233)
grpc-api_1    |         at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:191)
grpc-api_1    |         at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:203)
grpc-api_1    |         at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:258)
grpc-api_1    |         at io.grpc.netty.NettyServerStream$TransportState.inboundDataReceived(NettyServerStream.java:226)
grpc-api_1    |         at io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:498)
grpc-api_1    |         at io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:104)
grpc-api_1    |         at io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:816)
grpc-api_1    |         at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:292)
grpc-api_1    |         at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
grpc-api_1    |         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
grpc-api_1    |         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
grpc-api_1    |         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
grpc-api_1    |         at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
grpc-api_1    |         at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
grpc-api_1    |         at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
grpc-api_1    |         at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
grpc-api_1    |         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
grpc-api_1    |         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
grpc-api_1    |         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
grpc-api_1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
grpc-api_1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
grpc-api_1    |         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
grpc-api_1    |         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
grpc-api_1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
grpc-api_1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
grpc-api_1    |         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
grpc-api_1    |         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
grpc-api_1    |         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
grpc-api_1    |         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
grpc-api_1    |         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
grpc-api_1    |         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
grpc-api_1    |         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
grpc-api_1    |         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
grpc-api_1    |         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
grpc-api_1    |         at java.lang.Thread.run(Thread.java:748)
grpc-api_1    | caused by:
grpc-api_1    | groovy.lang.MissingPropertyException: No such property: temp1 for class: groovy.lang.Binding
grpc-api_1    |         at groovy.lang.Binding.getVariable(Binding.java:61)
grpc-api_1    |         at io.deephaven.db.util.GroovyDeephavenSession.getVariable(GroovyDeephavenSession.java:183)
grpc-api_1    |         at io.deephaven.grpc_api.console.ScopeTicketResolver.lambda$resolve$2(ScopeTicketResolver.java:100)
grpc-api_1    |         at io.deephaven.util.locks.FunctionalLock.computeLocked(FunctionalLock.java:64)
grpc-api_1    |         at io.deephaven.grpc_api.console.ScopeTicketResolver.resolve(ScopeTicketResolver.java:97)
grpc-api_1    |         at io.deephaven.grpc_api.console.ScopeTicketResolver.resolve(ScopeTicketResolver.java:85)
grpc-api_1    |         at io.deephaven.grpc_api.session.TicketRouter.resolve(TicketRouter.java:57)
grpc-api_1    |         at io.deephaven.grpc_api.session.TicketRouter.resolve(TicketRouter.java:89)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl.lambda$null$12(TableServiceGrpcImpl.java:410)
grpc-api_1    |         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
grpc-api_1    |         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
grpc-api_1    |         at java.util.Collections$2.tryAdvance(Collections.java:4719)
grpc-api_1    |         at java.util.Collections$2.forEachRemaining(Collections.java:4727)
grpc-api_1    |         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
grpc-api_1    |         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
grpc-api_1    |         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
grpc-api_1    |         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
grpc-api_1    |         at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl.lambda$oneShotOperationWrapper$15(TableServiceGrpcImpl.java:411)
grpc-api_1    |         at io.deephaven.grpc_api.util.GrpcUtil.rpcWrapper(GrpcUtil.java:33)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl.oneShotOperationWrapper(TableServiceGrpcImpl.java:396)
grpc-api_1    |         at io.deephaven.grpc_api.table.TableServiceGrpcImpl.fetchTable(TableServiceGrpcImpl.java:252)
grpc-api_1    |         at io.deephaven.proto.backplane.grpc.TableServiceGrpc$MethodHandlers.invoke(TableServiceGrpc.java:2835)
grpc-api_1    |         at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
grpc-api_1    |         at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
grpc-api_1    |         at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
grpc-api_1    |         at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
grpc-api_1    |         at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
grpc-api_1    |         at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
grpc-api_1    |         at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797)
grpc-api_1    |         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
grpc-api_1    |         at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
grpc-api_1    |         at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.halfClosed(ServerImpl.java:808)
grpc-api_1    |         at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:231)
grpc-api_1    |         at io.grpc.netty.NettyServerStream$TransportState.deframerClosed(NettyServerStream.java:168)
grpc-api_1    |         at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:233)
grpc-api_1    |         at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:191)
grpc-api_1    |         at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:203)
grpc-api_1    |         at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:258)
grpc-api_1    |         at io.grpc.netty.NettyServerStream$TransportState.inboundDataReceived(NettyServerStream.java:226)
grpc-api_1    |         at io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:498)
grpc-api_1    |         at io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:104)
grpc-api_1    |         at io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:816)
grpc-api_1    |         at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:292)
grpc-api_1    |         at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
grpc-api_1    |         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
grpc-api_1    |         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
grpc-api_1    |         at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
grpc-api_1    |         at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
grpc-api_1    |         at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
grpc-api_1    |         at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
grpc-api_1    |         at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
grpc-api_1    |         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
grpc-api_1    |         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
grpc-api_1    |         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
grpc-api_1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
grpc-api_1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
grpc-api_1    |         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
grpc-api_1    |         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
grpc-api_1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
grpc-api_1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
grpc-api_1    |         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
grpc-api_1    |         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
grpc-api_1    |         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
grpc-api_1    |         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
grpc-api_1    |         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
grpc-api_1    |         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
grpc-api_1    |         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
grpc-api_1    |         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
grpc-api_1    |         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
grpc-api_1    |         at java.lang.Thread.run(Thread.java:748)
grpc-api_1    |
```

**Comment by nbauernfeind** [comment]
I might need more details. I am expecting this pattern to be followed:

1. DoPut to SessionState export (such as "e/1024")
2. if (and only if) you also want to put this DoPut into the query scope, then you `ConsoleService.bindTableToVariable`

This code path waits for the DoPut to complete before trying to write to the query scope.

It sounds like you are DoPutting straight to a QueryScope ticket. There is no way to "know" that a query scope variable is pending a result. So, the server does not wait and simply responds immediately that the variable is not yet set. I don't think I want to change this behavior.
