### ISSUE TITLE
web.shared.fu.MappedIterable exception out of the blue in console

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#1475]
```
heduler-Concurrent-1 | i.d.g.s.SessionState      | Internal Error '55e0f602-6370-4f8a-9d0b-b244783fb82a' java.util.NoSuchElementException: io.deephaven.web.shared.fu.MappedIterable$$Lambda$786/750008865@4fe4fd22 is empty
        at io.deephaven.web.shared.fu.MappedIterable.first(MappedIterable.java:158)
        at io.deephaven.lang.api.ChunkerInvokable.getNameToken(ChunkerInvokable.java:35)
        at io.deephaven.lang.api.ChunkerInvokable.getNameToken(ChunkerInvokable.java:28)
        at io.deephaven.lang.api.ChunkerInvokable.getNameToken(ChunkerInvokable.java:28)
        at io.deephaven.lang.generated.ChunkerInvoke.isCursorInArguments(ChunkerInvoke.java:80)
        at io.deephaven.lang.completion.ChunkerCompleter.invokeComplete(ChunkerCompleter.java:783)
        at io.deephaven.lang.completion.ChunkerCompleter.access$1000(ChunkerCompleter.java:30)
        at io.deephaven.lang.completion.ChunkerCompleter$1.visitChunkerInvoke(ChunkerCompleter.java:457)
        at io.deephaven.lang.generated.ChunkerInvoke.jjtAccept(ChunkerInvoke.java:29)
        at io.deephaven.lang.completion.ChunkerCompleter.searchForResults(ChunkerCompleter.java:369)
        at io.deephaven.lang.completion.ChunkerCompleter.runCompletion(ChunkerCompleter.java:113)
        at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl$1.lambda$onNext$3(ConsoleServiceGrpcImpl.java:324)
        at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1273)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:825)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:145)
        at java.lang.Thread.run(Thread.java:748)
```

![image](https://user-images.githubusercontent.com/37232625/138507785-98303df8-3354-4d13-9c8c-f74440f21549.png)

**Comment by niloc132** [comment]
Should be fixed by #1876, as part of #1196.
