### ISSUE TITLE
QueryTableWhereTest out of band test failures

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#1558]
Can reproduce:

`/gradlew DB:testOutOfBand --tests "io.deephaven.db.v2.QueryTableWhereTest.testCharRangeFilter"`

```
junit.framework.ComparisonFailure: 
Result table has size 5 vs. expected 2
Column CH different from the expected set, first difference at row 0 encountered H expected B
 expected:<...         0|         [3|B         
         1|         4|F]         
> but was:<...         0|         [5|H         
         1|         6|Q         
         2|         7|T         
         3|         8|W         
         4|         9|Z]         
>
	at io.deephaven.db.v2.TstUtils.assertTableEquals(TstUtils.java:2192)
	at io.deephaven.db.v2.TstUtils.assertTableEquals(TstUtils.java:2163)
	at io.deephaven.db.v2.TstUtils.assertTableEquals(TstUtils.java:2155)
	at io.deephaven.db.v2.QueryTableWhereTest.testCharRangeFilter(QueryTableWhereTest.java:1046)
```

`./gradlew DB:testOutOfBand --tests "io.deephaven.db.v2.QueryTableWhereTest.testComparableBinarySearch"`

```
junit.framework.ComparisonFailure:  en_i = 39
Column BD1 different from the expected set, first difference at row 0 encountered 1.7158080123 expected 3.6763776689
Column D2 different from the expected set, first difference at row 0 encountered 5.558368799516423 expected 12.238565979940086 (difference = 6.680197180423663)
Column L3 different from the expected set, first difference at row 0 encountered 91 expected 6
Column CH different from the expected set, first difference at row 0 encountered N expected A
Column DT different from the expected set, first difference at row 0 encountered 2020-01-01T00:58:20.185644049 NY expected 2020-01-01T00:16:11.342319344 NY
...
	at io.deephaven.db.v2.TstUtils.assertTableEquals(TstUtils.java:2192)
	at io.deephaven.db.v2.TstUtils.assertTableEquals(TstUtils.java:2161)
	at io.deephaven.db.v2.QueryTableTestBase$TableComparator.validate(QueryTableTestBase.java:190)
	at io.deephaven.db.v2.TstUtils.validate(TstUtils.java:367)
	at io.deephaven.db.v2.LiveTableTestCase.simulateShiftAwareStep(LiveTableTestCase.java:127)
	at io.deephaven.db.v2.LiveTableTestCase.simulateShiftAwareStep(LiveTableTestCase.java:118)
	at io.deephaven.db.v2.LiveTableTestCase.simulateShiftAwareStep(LiveTableTestCase.java:113)
	at io.deephaven.db.v2.QueryTableWhereTest.testComparableBinarySearch(QueryTableWhereTest.java:994)
```

**Comment by devinrsmith** [comment]
Looks like this was introduced by https://github.com/deephaven/deephaven-core/pull/1535 - I was able to fix locally by reverting.
