### ISSUE TITLE
Support Parquet compression libraries on M1 macs

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#1589]
Trying to write a compressed Parquet file elicits exceptions like:
```
[FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
	at org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:361)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:195)
	at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:167)
	at org.xerial.snappy.Snappy.init(Snappy.java:69)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:46)
	at org.apache.parquet.hadoop.codec.SnappyCompressor.compress(SnappyCompressor.java:67)
	at org.apache.hadoop.io.compress.CompressorStream.compress(CompressorStream.java:81)
	at org.apache.hadoop.io.compress.CompressorStream.finish(CompressorStream.java:92)
	at org.apache.parquet.hadoop.CodecFactory$HeapBytesCompressor.compress(CodecFactory.java:167)
	at io.deephaven.parquet.ColumnWriterImpl.writeDictionaryPage(ColumnWriterImpl.java:125)
	at io.deephaven.parquet.ColumnWriterImpl.addDictionaryPage(ColumnWriterImpl.java:115)
	at io.deephaven.db.v2.parquet.ParquetTableWriter.writeColumnSource(ParquetTableWriter.java:499)
	at io.deephaven.db.v2.parquet.ParquetTableWriter.write(ParquetTableWriter.java:258)
	at io.deephaven.db.v2.parquet.ParquetTableWriter.write(ParquetTableWriter.java:197)
	at io.deephaven.db.v2.parquet.ParquetTableWriter.write(ParquetTableWriter.java:218)
	at io.deephaven.db.tables.utils.ParquetTools.writeParquetTableImpl(ParquetTools.java:672)
	at io.deephaven.db.tables.utils.ParquetTools.writeTable(ParquetTools.java:225)
	at io.deephaven.db.tables.utils.ParquetTools.writeTable(ParquetTools.java:141)
	at io.deephaven.db.tables.utils.TestParquetTools.testWriteTable(TestParquetTools.java:134)
[...]
```

We can workaround by changing the default codec to `UNCOMPRESSED`, by making this change in `ParquetInstructions`:
```
    private static volatile String defaultCompressionCodecName = CompressionCodecName.UNCOMPRESSED.toString();
```

We should find or build native libraries for this architecture, since it's relevant to a few of our devs as well as part of our target audience.

**Comment by rcaudy** [comment]
This is pending release of a newer parquet-mr library.
