### ISSUE TITLE
SessionState ConcurrentModificationException

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#1651]
I'm seeing the following with somewhat regular consistency (by starting and stopping remote java client apps).

```
grpc-api_1    | 2021-12-02T17:27:52.917Z | EFAULT.refreshThread |  INFO | .e.u.UpdateGraphProcessor | Minimal Live Table Monitor cycle times: 25.18194ms / 34 cycles = 0.7406452941176471ms/cycle average
grpc-api_1    | 2021-12-02T17:27:54.416Z | heduler-Concurrent-3 |  INFO | i.d.g.s.SessionState      | SessionState{fcb6b9fb-1734-436d-8703-898c066267cf}: releasing outstanding exports
grpc-api_1    | 2021-12-02T17:27:54.417Z | heduler-Concurrent-3 |  INFO | i.d.g.s.SessionState      | SessionState{fcb6b9fb-1734-436d-8703-898c066267cf}: outstanding exports released
grpc-api_1    | 2021-12-02T17:27:54.418Z | heduler-Concurrent-3 |  INFO | portedTableUpdateListener | ExportedTableUpdateListener(4bbcb167) is complete
grpc-api_1    | Dec 02, 2021 5:27:54 PM io.grpc.internal.ServerCallImpl internalClose
grpc-api_1    | WARNING: Cancelling the stream with status Status{code=INTERNAL, description=Completed without a response, cause=null}
grpc-api_1    | Initiating shutdown due to: Exception while processing concurrentExecutor task
grpc-api_1    | java.util.ConcurrentModificationException
grpc-api_1    |         at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
grpc-api_1    |         at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
grpc-api_1    |         at io.deephaven.util.datastructures.SimpleReferenceManager.forEach(SimpleReferenceManager.java:117)
grpc-api_1    |         at io.deephaven.grpc_api.session.SessionState.onExpired(SessionState.java:426)
grpc-api_1    |         at io.deephaven.grpc_api.session.SessionService$SessionCleanupJob.run(SessionService.java:309)
grpc-api_1    |         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
grpc-api_1    |         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
grpc-api_1    |         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
grpc-api_1    |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
grpc-api_1    |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
grpc-api_1    |         at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:156)
grpc-api_1    |         at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by niloc132** [comment]
java.util.ConcurrentModificationException: null
java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
io.deephaven.util.datastructures.SimpleReferenceManager.forEach(SimpleReferenceManager.java:117)
io.deephaven.grpc_api.session.SessionState.onExpired(SessionState.java:426)
io.deephaven.grpc_api.session.SessionService$SessionCleanupJob.run(SessionService.java:309)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:156)
java.base/java.lang.Thread.run(Thread.java:829)

**Comment by niloc132** [comment]
While we could switch to a concurrent collection, we would have to deal with a race. The race could be fixed by making removeOnCloseCallback give up early (without throwing) if already expired. Then we need to have callers expect that this would return false (for callers that are not idempotent) means that it was not removed, in this case because the expiry is already happening/happened, and will be closed that way.

**Comment by rcaudy** [comment]
```
    /**
     * Remove an on-close callback bound to the life of the session.
     *
     * @param onClose the callback to no longer invoke at end-of-life
     * @return true iff the callback was removed
     * @apiNote If this SessionState has already begun expiration processing, the callback will not be removed and will
     * instead be (or have been) invoked.
     */
    public boolean removeOnCloseCallback(final Closeable onClose) {
        synchronized (onCloseCallbacks) {
            if (isExpired()) {
                return false;
            }
            return onCloseCallbacks.remove(onClose) != null;
        }
    }
```
