### ISSUE TITLE
StatusRuntimeException from inside submit not propogated

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#1871]
Discovered as part of https://github.com/deephaven/deephaven-core/pull/1787, `StatusRuntimeException`s that are thrown during execution of `io.deephaven.server.session.SessionState.ExportBuilder#submit(java.util.concurrent.Callable<T>)` don't have their message propogated to the client.

**Comment by niloc132** [comment]
it looks like SessionState/ExportObject/etc expect instead that `GrpcUtil.safelyError(listener, code, message)` will be called within the lambda passed to submit() rather than throwing. I'm don't recall why that decision was made, but there is other code doing this the "wrong" way.

If we don't change the convention to handling `StatusRuntimeException`s specially (as we do in `GrpcUtil.rpcWrapper(log, observer, lambda)`), we should check for them when running the lambda and warn that the error wasn't sent properly.

Follow-up:
 * ObjectServiceGrpcImpl.serialize
 * Scope/ExportTicketResolver.flightInfoFor
 * SessionState.get(). Also newServerSideExport, via figure object serialization
 * SortTableGrpcImp.create
 * InputTableServiceGrpcImpl.deleteTableFromInputTable, addTableToInputTable
 * ArrowFlightUtil.DoPutObserver.onCancel() - this even has a comment saying `this thrown error propagates to observer`, which doesnt appear to have ever been true
 * ArrowFlightUtil.DoExchangeMarshaller.apply (via onExportResolved)
 * JoinTablesGrpcImpl.create
 * SelectDistinctGrpcImpl.create

Also, it looks like ExportedTableUpdateListener.onNext's contents might need to be in a rpcWrapper.

**Comment by nbauernfeind** [comment]
This is somewhat related to #801. In general, we wanted to avoid leaking internal error information to malicious users.

Note that ExportObjects do not require the use of gRPC. I don't believe that `submit` can throw a StatusRuntimeException; that lambda is deferred to a thread pool. There is a decoupling between errors that occur when the work is processed. These errors are supposed to be passed to the export object's error handler. In gRPCs case these are supposed to pass through StatusRuntimeExceptions to the observer, and other exception types are supposed to be wrapped with the UUID identifier.

I looked at a few items in the follow up list to try and create a repro. I uploaded this to https://github.com/nbauernfeind/deephaven-core/tree/gh1871_repro. Server side gets this error:
```
Internal Error '63ee9a27-e53a-494d-ade3-9ae6771dd200' io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Table can't be used as an input table
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.protobuf.StatusProto.toStatusRuntimeException(StatusProto.java:52)
        at io.deephaven.proto.util.Exceptions.statusRuntimeException(Exceptions.java:14)
        at io.deephaven.extensions.barrage.util.GrpcUtil.statusRuntimeException(GrpcUtil.java:95)
        at io.deephaven.server.table.inputtables.InputTableServiceGrpcImpl.lambda$addTableToInputTable$1(InputTableServiceGrpcImpl.java:56)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1308)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:856)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:162)
        at java.lang.Thread.run(Thread.java:832)
```

The java client gets:
```
Caused by: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Details Logged w/ID '63ee9a27-e53a-494d-ade3-9ae6771dd200'
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

One gotcha here is that the batch API cannot send multiple status results for the single rpc call. The batch's per export response only allows for an error info string.  It seems fair to fail with the first detected error and keep the UUIDs for batch; one shot RPCs should propagate that status runtime exception.
