### ISSUE TITLE
Error when using `i*2` in a formula if `i` is already defined in the script scope

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#1930]
**Description**

**Steps to reproduce**
1. Run the following code:
```python
i = 1
from deephaven.TableTools import emptyTable
t = emptyTable(100).update("A=i*2")
```

**Expected results**
1. Table opens

**Actual results**
1. An error is thrown

Error message:
```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error 'fed4b5b3-3591-4b87-b920-8ccfdc226c72' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'RuntimeError'>
Value: java.lang.RuntimeException: Error compiling class io.deephaven.temp.c2052551320987228486v55_0.Formula:
/io/deephaven/temp/c2052551320987228486v55_0/Formula.java:179: error: int cannot be dereferenced
            return multiply(i.intValue(), 2);
                             ^
1 error

	at io.deephaven.compilertools.CompilerTools.maybeCreateClassHelper(CompilerTools.java:790)
	at io.deephaven.compilertools.CompilerTools.maybeCreateClass(CompilerTools.java:753)
	at io.deephaven.compilertools.CompilerTools.compileHelper(CompilerTools.java:511)
	at io.deephaven.compilertools.CompilerTools.compile(CompilerTools.java:470)
	at io.deephaven.compilertools.CompilerTools.compile(CompilerTools.java:425)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.lambda$compileFormula$19(DhFormulaColumn.java:769)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.compileFormula(DhFormulaColumn.java:768)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.createFormulaFactory(DhFormulaColumn.java:731)
	at io.deephaven.engine.table.impl.select.AbstractFormulaColumn.getFormula(AbstractFormulaColumn.java:230)
	at io.deephaven.engine.table.impl.select.AbstractFormulaColumn.getViewColumnSource(AbstractFormulaColumn.java:217)
	at io.deephaven.engine.table.impl.select.AbstractFormulaColumn.getDataView(AbstractFormulaColumn.java:176)
	at io.deephaven.engine.table.impl.select.SwitchColumn.getDataView(SwitchColumn.java:93)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.<init>(SelectColumnLayer.java:59)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.createLayerForSelect(SelectAndViewAnalyzer.java:196)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:109)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:41)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$36(QueryTable.java:1377)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$37(QueryTable.java:1362)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3152)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1361)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1341)
	at io.deephaven.engine.table.impl.TableWithDefaults.update(TableWithDefaults.java:287)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
	at io.deephaven.engine.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:190)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
	at io.deephaven.engine.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:189)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:147)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:85)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:219)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
	at java.base/java.lang.Thread.run(Thread.java:829)

Line: 2
Namespace: <module>
File: <string>
Traceback (most recent call last):
  File "<string>", line 2, in <module>

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
        at io.deephaven.engine.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:190)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
        at io.deephaven.engine.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:189)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:147)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:85)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:219)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
        at java.lang.Thread.run(Thread.java:829)
```

**Comment by jcferretti** [comment]
For reference: in slack discussion we determined (thanks Colin) that this behavior also exists as-in in DHE.
Charles seemed to remember that this used to work in DHE, and his expectation was that python variables wouldn't alias column constants (eg, a python 'i' variable shouldn't alias the 'i' magic constant like it happens in the error report).
We need to clarify expected behavior here, in general in relation to column names etc.

**Comment by nbauernfeind** [comment]
This has been fixed (probably a long while ago). I cannot pinpoint exactly which commit fixed this specific issue; I suspect one that began filtering QueryScope parameters by valid names.

However, there were still issues like this and effort was put into #5070 to ensure that behavior was well defined by prioritizing `i`,`ii`,`k`, then columns by `column_name`, followed by column arrays by `column_name_` (note that if a table has both columns `C` and `C_` then `C` cannot be accessed as an array since `C_` is also a column name), and finally query scope parameters.
