### ISSUE TITLE
dataFrameToTable can't handle columns of the "category" dtype

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#1972]
**Description**

If a Pandas DataFrame has a 'category' column, the `dataFrameToTable` function will error.

**Steps to reproduce**

In a Deephaven Python session, run the following code:

```
from deephaven import dataFrameToTable
import pandas as pd

df = pd.DataFrame({"A": ["a", "b", "c", "d"]})
df["B"] = df["A"].astype("category")

t = dataFrameToTable(df)
```

**Expected results**

A DataFrame `df` and table `t` with the same data.

**Actual results**

An error.  See below.

**Additional details and attachments**

r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error '6e11129f-a374-4134-ae67-079bb4da4f8a' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'AttributeError'>
Value: 'Categorical' object has no attribute '_get_codes'
Line: 685
Namespace: _handleCategorical
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/conversion_utils.py
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/python_to_java.py", line 124, in dataFrameToTable
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/python_to_java.py", line 108, in extractColumnSource
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/python_to_java.py", line 38, in _createColumnSource
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/conversion_utils.py", line 747, in _convertNdarrayToImmutableSource
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/conversion_utils.py", line 685, in _handleCategorical

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
        at io.deephaven.engine.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:190)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
        at io.deephaven.engine.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:189)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:147)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:85)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:219)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
        at java.lang.Thread.run(Thread.java:829)

**Versions**
 - Deephaven: version on Feb 2, 2022
 - OS: OS X Monterey
 - Browser: Chrome
 - Docker: 20.10.11

**Comment by devinrsmith** [comment]
For reference, https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html

**Comment by jmao-denver** [comment]
Thanks @pete-petey, I ran the same test in v2 and it worked (the PR is yet to be approved). 

Tried to see if a quick fix is possible, got past the initial error with the change below and stoped by another error. So it seems that it has never worked, tested DHE and failed there too.


```
diff --git a/Integrations/python/deephaven/conversion_utils.py b/Integrations/python/deephaven/conversion_utils.py
index 3aae242731..5fda824acc 100644
--- a/Integrations/python/deephaven/conversion_utils.py
+++ b/Integrations/python/deephaven/conversion_utils.py
@@ -682,7 +682,7 @@ def makeJavaArray(data, name, convertUnknownToString=False):
 def _handleCategorical(data, columnName, convertUnknownToString=False):
     # assumed to only be called by _convertNdarrayToImmutableSource
     # fetch the underlying "codes"
-    indices = data._get_codes()  # this is the "index" array - integer type of appropriate bit depth
+    indices = data.codes  # this is the "index" array - integer type of appropriate bit depth
     # fetch the "values"
     values = data.categories.values  # if this isn't a primitive type, then it will very likely be of dtype object
```

**Comment by jmao-denver** [comment]
Fixed in V2
