### ISSUE TITLE
TestConcurrentInstantiation.testPercentileBy and .testAvgBy failures

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#203]
`./gradlew DB:test --tests com.illumon.iris.db.v2.TestConcurrentInstantiation.testPercentileBy`

Non-deterministic.

```
junit.framework.ComparisonFailure: 
Column IntCol different from the expected set, first difference at row 0 encountered 3 expected 6
Column DoubleCol different from the expected set, first difference at row 0 encountered 300.3 expected 600.6 (difference = 300.3)
Column FloatCol different from the expected set, first difference at row 0 encountered 30.3 expected 60.6 (difference = 30.3)
Column ShortCol different from the expected set, first difference at row 0 encountered 30 expected 60
Column ByteCol different from the expected set, first difference at row 0 encountered 13 expected 16
Column CharCol different from the expected set, first difference at row 0 encountered C expected E
Column LongCol different from the expected set, first difference at row 0 encountered 30000000000 expected 60000000000
Column BigDecCol different from the expected set, first difference at row 0 encountered 40000.3 expected 60000.6
Column BigIntCol different from the expected set, first difference at row 0 encountered 300000 expected 600000
 expected:<...         0|         [6|               600.6|      60.6|        60|        16|E         |         60000000000|   60000.6|    6]00000
> but was:<...         0|         [3|               300.3|      30.3|        30|        13|C         |         30000000000|   40000.3|    3]00000
>
```

**Comment by rcaudy** [comment]
We had a similar failure today, and I'm going to group these for now:
```
Exception
junit.framework.ComparisonFailure: 	
Column KeyColumn different from the expected set, first difference at row 2 encountered c expected d	
Column IntCol different from the expected set, first difference at row 0 encountered 2.0 expected 3.3333333333333335 (difference = 1.3333333333333335)	
Column DoubleCol different from the expected set, first difference at row 0 encountered 200.2 expected 333.6666666666667 (difference = 133.4666666666667)	
Column FloatCol different from the expected set, first difference at row 0 encountered 20.199999809265137 expected 33.66666603088379 (difference = 13.466666221618652)	
Column ShortCol different from the expected set, first difference at row 0 encountered 20.0 expected 33.333333333333336 (difference = 13.333333333333336)	
Column ByteCol different from the expected set, first difference at row 0 encountered 12.0 expected 13.333333333333334 (difference = 1.333333333333334)	
Column CharCol different from the expected set, first difference at row 0 encountered 66.0 expected 67.33333333333333 (difference = 1.3333333333333286)	
Column LongCol different from the expected set, first difference at row 0 encountered 2.0E10 expected 3.3333333333333332E10 (difference = 1.3333333333333332E10)	
Column BigDecCol different from the expected set, first difference at row 0 encountered 25000.2 expected 36667.0	
Column BigIntCol different from the expected set, first difference at row 0 encountered 200000 expected 333333	
 expected:<...     0|a         |  [3.3333333333333335|   333.6666666666667|   33.66666603088379|  33.333333333333336|  13.333333333333334|   67.33333333333333|3.333333333333333E10|   36667.0|    333333	
         1|         1|b         |                 4.5|  450.45000000000005|   45.44999885559082|                45.0|                14.5|                67.5|              4.5E10|   45000.5|    450000	
         2|         2|d         |                 5.0|               505.5|                50.5|                50.0|                15.0|                69.0|              5.0E10|   50000.5|    5]00000	
> but was:<...     0|a         |  [               2.0|               200.2|  20.199999809265137|                20.0|                12.0|                66.0|              2.0E10|   25000.2|    200000	
         1|         1|b         |                 2.0|               200.2|  20.200000762939453|                20.0|                12.0|                66.0|              2.0E10|   20000.2|    200000	
         2|         2|c         |                 4.0|               400.4|  40.400001525878906|                40.0|                14.0|                68.0|              4.0E10|   40000.4|    4]00000	
>	
at io.deephaven.engine.testutil.TstUtils.assertTableEquals(TstUtils.java:868)	
at io.deephaven.engine.testutil.TstUtils.assertTableEquals(TstUtils.java:841)	
at io.deephaven.engine.testutil.TstUtils.assertTableEquals(TstUtils.java:788)	
at io.deephaven.engine.table.impl.TestConcurrentInstantiation.testByConcurrent(TestConcurrentInstantiation.java:1297)	
at io.deephaven.engine.table.impl.TestConcurrentInstantiation.testByConcurrent(TestConcurrentInstantiation.java:1183)	
at io.deephaven.engine.table.impl.TestConcurrentInstantiation.testAvgBy(TestConcurrentInstantiation.java:1114)
```

[Build Scan](https://scans.gradle.com/s/dfvxq4cwdwfqo/tests/:engine-table:testOutOfBand/io.deephaven.engine.table.impl.TestConcurrentInstantiation/testAvgBy?expanded-stacktrace=WyIwIl0&top-execution=1)
[CI Log](https://github.com/deephaven/deephaven-core/actions/runs/4977037521/jobs/8905669536)
