### ISSUE TITLE
Inconsistency in determining the Python return value type between list subscription and function call in query strings

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#2044]
```
from deephaven2 import empty_table
n = 40000
x = list(range(n))

def getx(i):
    return x[i]

t = empty_table(n).update(["X = x[i]"])
t1 = empty_table(n).update(["X = getx(i)"])
t2 = t.where(["isNull(X)"])
t2_1 = t1.where(["isNull(X)"])
t3 = t.update(["A = (byte)X", "B = (short)X"])
t3_1 = t1.update(["A = (byte)X", "B = (short)X"])
```

The above test fails on the last statement with the following exception:
```
Error in Python interpreter:
Type: <class 'deephaven2.dherror.DHError'>
Value: table update operation failed. : java.lang.ClassCastException: class java.lang.Short cannot be cast to class java.lang.Byte (java.lang.Short and java.lang.Byte are in module java.base of loader 'bootstrap')
Line: 238
Namespace: update
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven2/table.py
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven2/table.py", line 238, in update

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
```

Note, Python package v1 behaves the same.

**Comment by jakemulf** [comment]
Another potential example coming from our ML docs

```
from deephaven import read_csv

iris_raw = read_csv("https://media.githubusercontent.com/media/deephaven/examples/main/Iris/csv/iris.csv")
classes = {}
num_classes = 0
def get_class_number(c):
    global classes, num_classes
    if c not in classes:
        classes[c] = num_classes
        num_classes += 1
    return classes[c]
iris = iris_raw.update("Class = (int)get_class_number(Class)")
```

```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error '20e0599a-6570-4a89-94e8-ac4be8640c45' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'RuntimeError'>
Value: io.deephaven.engine.table.impl.select.FormulaEvaluationException: In formula: Class = intCast(get_class_number.call(Class))
```

```
caused by java.lang.ClassCastException: class java.lang.Byte cannot be cast to class java.lang.Integer (java.lang.Byte and java.lang.Integer are in module java.base of loader 'bootstrap')
```

Changing the cast to `(int)(byte)` makes it work as expected

**Comment by jmao-denver** [comment]
The new change is still better because we can handle NULL_xxx more correctly and arguable it doesn't make the situation worse because without it we would still have the same problem if we change ```iris = iris_raw.update("Class = (int)get_class_number(Class)")``` to ```iris = iris_raw.update("Class = (long)get_class_number(Class)")```
