### ISSUE TITLE
TableMapTest.testTableMapSupplierListeners 

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#205]
`./gradlew DB:test --tests com.illumon.iris.db.v2.TableMapTest.testTableMapSupplierListeners`

Non-deterministic. Fails sometimes.

```
java.lang.NullPointerException
	at com.illumon.iris.db.tables.utils.TableDiff.diffInternal(TableDiff.java:42)
	at com.illumon.iris.db.tables.utils.TableTools.diffPair(TableTools.java:332)
	at com.illumon.iris.db.v2.TstUtils.assertTableEquals(TstUtils.java:2129)
	at com.illumon.iris.db.v2.TstUtils.assertTableEquals(TstUtils.java:2124)
	at com.illumon.iris.db.v2.TstUtils.assertTableEquals(TstUtils.java:2117)
	at com.illumon.iris.db.v2.TableMapTest.testTableMapSupplierListeners(TableMapTest.java:829)
```

**Comment by rcaudy** [comment]
This will happen as a side-effect of work under #37

**Comment by rcaudy** [comment]
Part of #1762

**Comment by rcaudy** [comment]
This test is gone.
