### ISSUE TITLE
propagateUpdates CME

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#2070]
```
java.util.ConcurrentModificationException: null
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
        at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at io.deephaven.server.appmode.ApplicationServiceGrpcImpl.propagateUpdates(ApplicationServiceGrpcImpl.java:212)
        at io.deephaven.server.appmode.ApplicationServiceGrpcImpl$FieldUpdatePropagationJob.run(ApplicationServiceGrpcImpl.java:298)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by niloc132** [comment]
Looks like its the onCancel() inside ApplicationServiceGrpcImpl.Subscription - if the send() throws (from the observer.onNext), we call onCancel(), which will remove the subscription even though we're currently sending. Probably need to defer that until the loop is over.
