### ISSUE TITLE
Python Deephaven plugins don't work after deephaven_legacy rename

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#2172]
Steps to reproduce: 
 * in the docker container, run `pip install deephaven-plugin`
 * in the web IDE, run `from deephaven.server.plugin.object import *` to try to import these utils

Expected, no error occurs.

Actual:
```
java.lang.RuntimeException: Error in Python interpreter:
server_1      | Type: <class 'ModuleNotFoundError'>
server_1      | Value: No module named 'deephaven.Plot'
server_1      | Line: 5
server_1      | Namespace: <module>
server_1      | File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/server/plugin/object/__init__.py
server_1      | Traceback (most recent call last):
server_1      |   File "<string>", line 1, in <module>
server_1      |   File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/server/plugin/object/__init__.py", line 5, in <module>
server_1      | 
server_1      |         at org.jpy.PyLib.executeCode(PyLib.java:-2)
server_1      |         at org.jpy.PyObject.executeCode(PyObject.java:138)
```

You can also reproduce this by trying to use a plugin like matplotlib.

The bug is that `pyintegration/deephaven/server/plugin/object/__init__.py` references deephaven.Plot, which is now part of deephaven_legacy, which means that this code won't work with the new deephaven plots. The import for deephaven.Plot.figure_wrapper.FigureWrapper should be removed, as should the `_unwrap` method, and both replaced with the new ABC that allows for consistent unwrapping.

**Comment by niloc132** [comment]
As an aside, it isn't clear to me why it is acceptable for deephaven.server.plugin.object to reference deephaven.plugin.object without actually depending on that wheel being installed.
