### ISSUE TITLE
Unable to retrieve format data from table snapshot

### ISSUE THREAD

**Issue by vbabich** [deephaven/deephaven-core#2258]
**Description**

Calling `getFormat` on `SubscriptionTableData$SubscriptionRow` results in an error: `Uncaught TypeError: Cannot read properties of undefined (reading '0')`

**Steps to reproduce**
1. Open the `table_basic` example page, i.e. http://localhost:10000/jsapi/table_basic.html
2. Run this snippet in the browser console to replace the table on the page with another one that has a formatted column:
```
(async () => {
        // Open a connection to the server
        connection = new dh.IdeConnection(
          window.location.protocol + "//" + window.location.host
        );

        var types = await connection.getConsoleTypes();

        if (types.indexOf("python") !== -1) {
          // Start a python session
          ide = await connection.startSession("python");
          // Run code that will create a static table with 10 rows and one formatted column X
          await ide.runCode(`
from deephaven.TableTools import emptyTable
remoteTable = emptyTable(10).update("X = i / 10000").formatColumns("X=Decimal(\`##0.00%\`)")
      `);
        } else if (types.indexOf("groovy") !== -1) {
          // Start a groovy session
          ide = await connection.startSession("groovy");
          // Run code that will create a static table with 10 rows and one formatted column X
          await ide.runCode(
            'remoteTable = emptyTable(10).update("X = i / 10000").formatColumns("X=Decimal(`##0.00%`)")'
          );
        }

        // Retrieve the JS Table object
        table = await ide.getTable("remoteTable");

        // Create a table header element with the table columns
        var header = document.createElement("thead");
        var headerRow = document.createElement("tr");
        table.columns.forEach((column) => {
          // build a very simple header
          var td = document.createElement("td");
          td.innerText = column.name;
          headerRow.appendChild(td);
        });
        header.appendChild(headerRow);

        // Set the viewport and extract data to build the table body.
        // Since the bottom of the viewport specified is inclusive and the table is ten rows, we only need specific `0,9`.
        table.setViewport(0, 9);
        var tbody = document.createElement("tbody");
        var viewportData = await table.getViewportData();
        var rows = viewportData.rows;
        for (var i = 0; i < rows.length; i++) {
          var tr = document.createElement("tr");
          for (var j = 0; j < table.columns.length; j++) {
            var td = document.createElement("td");
            td.textContent = rows[i].get(table.columns[j]);
            tr.appendChild(td);
          }
          tbody.appendChild(tr);
        }

        // Retrieve the element to append the table to
        var tableElement = document.getElementById("simpleTable");
        tableElement.innerHTML = '';
        tableElement.appendChild(header);
        tableElement.appendChild(tbody);
      })();
```
3. Wait for the new table to render, it should have a single column `X` with values `0`,  `0.0001`,  `0.0002`,  `0.0003`, ...
4. Run this snippet to confirm `getFormat` works correctly on the viewport data :
```
f = await table.freeze()
tableSubscription = f.setViewport(0, 10)
viewportData = await tableSubscription.getViewportData()
snapshot = await tableSubscription.snapshot(dh.RangeSet.ofRange(0, 10), f.columns)

console.log('Viewport getFormat 1', viewportData.get(0).getFormat(f.columns[0])); // Displays format object
console.log('Viewport getFormat 2', viewportData.getFormat(0, f.columns[0])); // Displays format object
```
5. Run this snippet to try to access the format data on the table snapshot:
```
console.log('Snapshot SubscriptionTableData$SubscriptionRow', snapshot.get(0)); // Displays snapshot row object
console.log('Snapshot getFormat 1', snapshot.get(0).getFormat(f.columns[0])); // Throws error
console.log('Snapshot getFormat 2', snapshot.getFormat(0, f.columns[0])); // Throws error
```

**Expected results**
`snapshot.get(0).getFormat(f.columns[0])` and `snapshot.getFormat(0, f.columns[0])` return the format object for row 0 col 0.

**Actual results**
`snapshot.get(0).getFormat(f.columns[0])` and `snapshot.getFormat(0, f.columns[0])` throw error:
```
dh-core.js:38977 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.getAt (dh-core.js:38977:13)
    at Object.$getAnyAt (dh-core.js:4831:13)
    at Object.$getFormat_0 (dh-core.js:18690:31)
    at SubscriptionTableData$UpdateEventData.getFormat_4 [as getFormat_0] (dh-core.js:18772:18)
    at Object.$getFormat (dh-core.js:10122:22)
    at SubscriptionTableData$UpdateEventData.getFormat_6 [as getFormat] (dh-core.js:18748:16)
    at <anonymous>:1:10
```

**Comment by mofojed** [comment]
First snippet for new deephaven python lib:
```
(async () => {
    // Open a connection to the server
    connection = new dh.IdeConnection(
      window.location.protocol + "//" + window.location.host
    );

    var types = await connection.getConsoleTypes();

    if (types.indexOf("python") !== -1) {
      // Start a python session
      ide = await connection.startSession("python");
      // Run code that will create a static table with 10 rows and one formatted column X
      await ide.runCode(`
from deephaven import empty_table
remoteTable = empty_table(10).update("X = i / 10000").format_columns("X=Decimal(\`##0.00%\`)")
  `);
    } else if (types.indexOf("groovy") !== -1) {
      // Start a groovy session
      ide = await connection.startSession("groovy");
      // Run code that will create a static table with 10 rows and one formatted column X
      await ide.runCode(
        'remoteTable = empty_table(10).update("X = i / 10000").format_columns("X=Decimal(`##0.00%`)")'
      );
    }

    // Retrieve the JS Table object
    table = await ide.getTable("remoteTable");

    // Create a table header element with the table columns
    var header = document.createElement("thead");
    var headerRow = document.createElement("tr");
    table.columns.forEach((column) => {
      // build a very simple header
      var td = document.createElement("td");
      td.innerText = column.name;
      headerRow.appendChild(td);
    });
    header.appendChild(headerRow);

    // Set the viewport and extract data to build the table body.
    // Since the bottom of the viewport specified is inclusive and the table is ten rows, we only need specific `0,9`.
    table.setViewport(0, 9);
    var tbody = document.createElement("tbody");
    var viewportData = await table.getViewportData();
    var rows = viewportData.rows;
    for (var i = 0; i < rows.length; i++) {
      var tr = document.createElement("tr");
      for (var j = 0; j < table.columns.length; j++) {
        var td = document.createElement("td");
        td.textContent = rows[i].get(table.columns[j]);
        tr.appendChild(td);
      }
      tbody.appendChild(tr);
    }

    // Retrieve the element to append the table to
    var tableElement = document.getElementById("simpleTable");
    tableElement.innerHTML = '';
    tableElement.appendChild(header);
    tableElement.appendChild(tbody);
  })();
```
