### ISSUE TITLE
Non-deterministic test_metrics_get_counters

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#2282]
The following is occasionally failing in PR CI. The failure is that two strings aren't equal. It looks like the NPE may be a fallout, and should likely be addressed as well?

```
2022-04-18T19:08:45.7227689Z ======================================================================
2022-04-18T19:08:45.7229985Z FAIL [0.426s]: test_metrics_get_counters (tests.test_perfmon.PerfmonTestCase)
2022-04-18T19:08:45.7232729Z ----------------------------------------------------------------------
2022-04-18T19:08:45.7234933Z Traceback (most recent call last):
2022-04-18T19:08:45.7236961Z   File "/python/tests/test_perfmon.py", line 36, in test_metrics_get_counters
2022-04-18T19:08:45.7239240Z     self.assertEqual(counters_str, counters_str3)
2022-04-18T19:08:45.7243583Z AssertionError: 'Metr[57 chars]ount=5, orderedLongSetBuilderRandomIntLongSing[7443 chars]=0\n' != 'Metr[57 chars]ount=0, orderedLongSetBuilderRandomIntLongSing[7443 chars]=0\n'
2022-04-18T19:08:45.7246793Z Diff is 8522 characters long. Set self.maxDiff to None to see it.
2022-04-18T19:08:45.7247901Z 
2022-04-18T19:08:45.7249113Z ----------------------------------------------------------------------
2022-04-18T19:08:45.7251478Z java.lang.NullPointerException
2022-04-18T19:08:45.7253838Z 	at io.deephaven.engine.util.PythonDeephavenSession.createDiff(PythonDeephavenSession.java:235)
2022-04-18T19:08:45.7274828Z 	at io.deephaven.engine.util.PythonDeephavenSession.createDiff(PythonDeephavenSession.java:49)
2022-04-18T19:08:45.7277502Z 	at io.deephaven.engine.util.AbstractScriptSession.applyDiff(AbstractScriptSession.java:122)
2022-04-18T19:08:45.7279954Z 	at io.deephaven.engine.util.PythonDeephavenSession.setVariable(PythonDeephavenSession.java:285)
2022-04-18T19:08:45.7282557Z 	at io.deephaven.engine.util.AbstractScriptSession$UnsynchronizedScriptSessionQueryScope.putParam(AbstractScriptSession.java:385)
2022-04-18T19:08:45.7285335Z 	at io.deephaven.engine.table.lang.QueryScope.addParam(QueryScope.java:91)
2022-04-18T19:08:45.7287459Z 	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
2022-04-18T19:08:45.7290291Z 	at io.deephaven.plot.datasets.multiseries.AbstractTableMapHandleMultiSeries.applyTransform(AbstractTableMapHandleMultiSeries.java:91)
2022-04-18T19:08:45.7293647Z 	at io.deephaven.plot.datasets.multiseries.AbstractMultiSeries.applyFunction(AbstractMultiSeries.java:200)
2022-04-18T19:08:45.7296932Z 	at io.deephaven.plot.datasets.multiseries.AbstractMultiSeries.applyFunction(AbstractMultiSeries.java:184)
2022-04-18T19:08:45.7299603Z 	at io.deephaven.plot.datasets.multiseries.AbstractMultiSeries.applyNamingFunction(AbstractMultiSeries.java:167)
2022-04-18T19:08:45.7302698Z 	at io.deephaven.plot.datasets.multiseries.AbstractMultiSeries.applyNamingFunction(AbstractMultiSeries.java:160)
2022-04-18T19:08:45.7305546Z 	at io.deephaven.plot.datasets.multiseries.AbstractTableMapHandleMultiSeries.<init>(AbstractTableMapHandleMultiSeries.java:40)
2022-04-18T19:08:45.7308646Z 	at io.deephaven.plot.datasets.multiseries.MultiXYSeries.<init>(MultiXYSeries.java:41)
2022-04-18T19:08:45.7311004Z 	at io.deephaven.plot.AxesImpl.plotBy(AxesImpl.java:1326)
2022-04-18T19:08:45.7313216Z 	at io.deephaven.plot.FigureImpl.plotBy(FigureImpl.java:2623)
2022-04-18T19:08:45.7315452Z 	at io.deephaven.plot.FigureImpl.plotBy(FigureImpl.java:52)
2022-04-18T19:08:45.7317090Z 
2022-04-18T19:08:45.7318091Z Ran 167 tests in 58.900s
2022-04-18T19:08:45.7319462Z 
2022-04-18T19:08:45.7320511Z FAILED (failures=1)
```

**Comment by jcferretti** [comment]
Fixed by https://github.com/deephaven/deephaven-core/pull/2289
