### ISSUE TITLE
Using Numba's `vectorize` without a function signature puts DHC into a weird state

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#2301]
**Description**

Attempting to use Numba's `vectorize` decorator without a function signature results in strange behavior and errors when trying to create tables in DHC.

**Steps to reproduce**

From a DHC session, run the following code:

```
@vectorize
def func(x, y):
    return x * y
```

Then, try to create a table with `empty_table`:

```
from deephaven import empty_table

t = empty_table(1).update(["X = i"])
```

**Expected results**

Atttempting to use vectorize without a function signature isn't supported.  I'd expect an error if trying to use the function `func` to do anything.  However, I wouldn't expect DHC to be have persisting errors trying to create tables as a result.

**Actual results**

An error stemming from an `empty_table` function call.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: v0.11
 - OS: OS X 12.3.1
 - Browser: Chrome'
 - Docker: 20.10.13

**Comment by jjbrosnan** [comment]
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error 'da040a7e-a50f-46b1-84e6-d0b40e0e2156' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : java.lang.IllegalArgumentException: numba vectorized function must have an explicit signature. 
       io.deephaven.engine.table.impl.select.FormulaCompilationException: Formula compilation error for: i
       java.lang.IllegalArgumentException: numba vectorized function must have an explicit signature.
Line: 313
Namespace: update
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 313, in update

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
        at io.deephaven.engine.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:190)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
        at io.deephaven.engine.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:189)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:147)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:84)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:219)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
        at java.lang.Thread.run(Thread.java:829)

**Comment by chipkent** [comment]
This is strange.  The `update` fails, even though the function is not used?

**Comment by chipkent** [comment]
I confirmed that we fail even if the function is not used.

````
from numba import vectorize

@vectorize
def func(x, y):
    return x * y

from deephaven import empty_table

t = empty_table(1).update(["X = i"])
```
With the error:
```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error '71bb008d-2151-4047-85e6-e84ac589c6c2' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : java.lang.IllegalArgumentException: numba vectorized function must have an explicit signature. 
       io.deephaven.engine.table.impl.select.FormulaCompilationException: Formula compilation error for: i
       java.lang.IllegalArgumentException: numba vectorized function must have an explicit signature.
Line: 313
Namespace: update
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 313, in update

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
        at io.deephaven.engine.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:190)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
        at io.deephaven.engine.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:189)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:147)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:84)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:219)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:145)
        at java.lang.Thread.run(Thread.java:829)
```

**Comment by chipkent** [comment]
The exception is coming from https://github.com/deephaven/deephaven-core/blob/5236ebb00fa7e03361a73930b9424cdb3c8c5941/engine/table/src/main/java/io/deephaven/engine/util/PythonScopeJpyImpl.java#L117

@jmao-denver I think you made the change that is causing this exception.

**Comment by chipkent** [comment]
If the example is ported to use explicit types for the numba calculation, a new error occurs that provides little information.

```
from numba import vectorize, int64, double

@vectorize([int64(int64,int64)])
def func(x, y):
    return x * y

from deephaven import empty_table

t = empty_table(1).update(["X = i"])

t2 = t.update("Y=func(X,X)")
```

With the error:
```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error '0e19a316-b0c1-4928-9853-4f2e1a7fe63b' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : RuntimeError: java.lang.RuntimeException: Error in Python interpreter: 
       
Line: 313
Namespace: update
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 313, in update

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
        at io.deephaven.engine.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:190)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
        at io.deephaven.engine.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:189)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:147)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:84)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:219)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:145)
        at java.lang.Thread.run(Thread.java:829)
```
