### ISSUE TITLE
Boolean columns can't be used in advanced filters

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#2408]
**Description**
Using advanced filters on a deephaven table with Boolean columns results in a console error, while using quick filters works correctly. Example table:
```
t1 = TableTools.emptyTable(10).update("BoolCol = (i % 2) == 0")
```

**Steps to reproduce**
1. Create a table with a java.lang.Boolean column, in the console or in app mode, etc.
2. Right click the column and click advanced filters
3. Toggle the checkboxes next to `true` and `false` to get the UI filtered to only some of the data

**Expected results**

Contents of the table are filtered to only the true or false rows. Example 

**Actual results**

Console error occurs, see below. It appears that the advanced filter treats this data as a string. Note that quick filters do not have this problem by just typing `true` or `false` into them.

**Additional details and attachments**

```
heduler-Concurrent-3 | i.d.s.s.SessionState      | Internal Error '12e53cd1-50fe-4b01-bacc-4894e5321fdd' java.lang.IllegalArgumentException: Failed to convert literal value <"false"> for column "newSession" of type java.lang.Boolean
        at io.deephaven.engine.table.impl.select.MatchFilter.init(MatchFilter.java:141)
        at io.deephaven.engine.table.impl.QueryTable.lambda$whereInternal$32(QueryTable.java:1145)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
        at io.deephaven.engine.table.impl.QueryTable.whereInternal(QueryTable.java:1115)
        at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:1111)
        at io.deephaven.engine.table.impl.TableWithDefaults.where(TableWithDefaults.java:218)
        at io.deephaven.server.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:92)
        at io.deephaven.server.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:23)
        at io.deephaven.server.table.TableServiceGrpcImpl$BatchExportBuilder.doExport(TableServiceGrpcImpl.java:461)
        at io.deephaven.server.table.TableServiceGrpcImpl.lambda$batch$5(TableServiceGrpcImpl.java:313)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
        at java.lang.Thread.run(Thread.java:829)
caused by:
java.lang.IllegalArgumentException: String "false" isn't a valid boolean value (!str.equalsIgnoreCase("true") && !str.equalsIgnoreCase("false"))
        at io.deephaven.engine.table.impl.select.MatchFilter$ColumnTypeConvertorFactory$7.convertStringLiteral(MatchFilter.java:241)
        at io.deephaven.engine.table.impl.select.MatchFilter.init(MatchFilter.java:138)
        at io.deephaven.engine.table.impl.QueryTable.lambda$whereInternal$32(QueryTable.java:1145)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
        at io.deephaven.engine.table.impl.QueryTable.whereInternal(QueryTable.java:1115)
        at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:1111)
        at io.deephaven.engine.table.impl.TableWithDefaults.where(TableWithDefaults.java:218)
        at io.deephaven.server.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:92)
        at io.deephaven.server.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:23)
        at io.deephaven.server.table.TableServiceGrpcImpl$BatchExportBuilder.doExport(TableServiceGrpcImpl.java:461)
        at io.deephaven.server.table.TableServiceGrpcImpl.lambda$batch$5(TableServiceGrpcImpl.java:313)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
        at java.lang.Thread.run(Thread.java:829)
```

**Versions**
 - Deephaven: 0.10.0 tagged docker images
 - OS: Windows
 - Browser: Chrome

**Comment by mofojed** [comment]
Looks like it was caused by my very own change: https://github.com/deephaven/deephaven-core/pull/1229
