### ISSUE TITLE
Parquet file reading may be broken with latest changes

### ISSUE THREAD

**Issue by jakemulf** [deephaven/deephaven-core#2495]
**Description**

Parquet file reading appears to be broken with the most recent `edge` version

```
from deephaven.parquet import read

source = read("/data/examples/Pems/parquet/pems")
```

throws the following error

```
heduler-Concurrent-2 | .b.BarrageMessageProducer | Internal Error 'f7e1dcec-790d-47e0-a6b8-2d2954d4ed9c' io.deephaven.UncheckedDeephavenException: Failure to execute snapshot function with unchanged clock

        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1161)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1020)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:600)
        at io.deephaven.server.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:2144)
        at io.deephaven.server.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:1318)
        at io.deephaven.server.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:995)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:157)
        at java.lang.Thread.run(Thread.java:829)
caused by:
java.io.UncheckedIOException: java.io.EOFException: encountered EOF while reading block data
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPage(VariablePageSizeColumnChunkPageStore.java:121)
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:158)
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:17)
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:72)
        at io.deephaven.parquet.table.region.ParquetColumnRegionBase.fillChunk(ParquetColumnRegionBase.java:47)
        at io.deephaven.engine.table.impl.sources.regioned.DeferredColumnRegionBase.fillChunk(DeferredColumnRegionBase.java:69)
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:76)
        at io.deephaven.engine.table.impl.sources.regioned.RegionedColumnSourceBase.fillChunk(RegionedColumnSourceBase.java:48)
        at io.deephaven.engine.table.impl.sources.regioned.RegionedColumnSourceObject$AsValues.fillChunk(RegionedColumnSourceObject.java:29)
        at io.deephaven.engine.table.impl.sources.RedirectedColumnSource$FillContext.doOrderedFillAscending(RedirectedColumnSource.java:714)
        at io.deephaven.engine.table.impl.sources.RedirectedColumnSource.doFillChunk(RedirectedColumnSource.java:428)
        at io.deephaven.engine.table.impl.sources.RedirectedColumnSource.fillChunk(RedirectedColumnSource.java:406)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.getSnapshotDataAsChunkList(ConstructSnapshot.java:1463)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.serializeAllTable(ConstructSnapshot.java:1345)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.lambda$constructBackplaneSnapshotInPositionSpace$2(ConstructSnapshot.java:595)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1088)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1020)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:600)
        at io.deephaven.server.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:2144)
        at io.deephaven.server.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:1318)
        at io.deephaven.server.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:995)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:157)
        at java.lang.Thread.run(Thread.java:829)
caused by:
java.io.EOFException: encountered EOF while reading block data
        at io.airlift.compress.snappy.HadoopSnappyInputStream.readInput(HadoopSnappyInputStream.java:142)
        at io.airlift.compress.snappy.HadoopSnappyInputStream.readNextChunk(HadoopSnappyInputStream.java:109)
        at io.airlift.compress.snappy.HadoopSnappyInputStream.read(HadoopSnappyInputStream.java:62)
        at java.io.DataInputStream.readFully(DataInputStream.java:200)
        at java.io.DataInputStream.readFully(DataInputStream.java:170)
        at org.apache.parquet.bytes.BytesInput$StreamBytesInput.toByteArray(BytesInput.java:286)
        at org.apache.parquet.bytes.BytesInput.copy(BytesInput.java:202)
        at io.deephaven.parquet.compress.DeephavenCodecFactory$CodecWrappingCompressor.decompress(DeephavenCodecFactory.java:105)
        at io.deephaven.parquet.base.ColumnPageReaderImpl.readDataPage(ColumnPageReaderImpl.java:218)
        at io.deephaven.parquet.base.ColumnPageReaderImpl.materialize(ColumnPageReaderImpl.java:87)
        at io.deephaven.parquet.table.pagestore.topage.ToPage.getResult(ToPage.java:55)
        at io.deephaven.parquet.table.pagestore.topage.ToPageWithDictionary.getResult(ToPageWithDictionary.java:54)
        at io.deephaven.parquet.table.pagestore.topage.ToPage.toPage(ToPage.java:82)
        at io.deephaven.parquet.table.pagestore.ColumnChunkPageStore.toPage(ColumnChunkPageStore.java:88)
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPage(VariablePageSizeColumnChunkPageStore.java:119)
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:158)
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:17)
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:72)
        at io.deephaven.parquet.table.region.ParquetColumnRegionBase.fillChunk(ParquetColumnRegionBase.java:47)
        at io.deephaven.engine.table.impl.sources.regioned.DeferredColumnRegionBase.fillChunk(DeferredColumnRegionBase.java:69)
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:76)
        at io.deephaven.engine.table.impl.sources.regioned.RegionedColumnSourceBase.fillChunk(RegionedColumnSourceBase.java:48)
        at io.deephaven.engine.table.impl.sources.regioned.RegionedColumnSourceObject$AsValues.fillChunk(RegionedColumnSourceObject.java:29)
        at io.deephaven.engine.table.impl.sources.RedirectedColumnSource$FillContext.doOrderedFillAscending(RedirectedColumnSource.java:714)
        at io.deephaven.engine.table.impl.sources.RedirectedColumnSource.doFillChunk(RedirectedColumnSource.java:428)
        at io.deephaven.engine.table.impl.sources.RedirectedColumnSource.fillChunk(RedirectedColumnSource.java:406)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.getSnapshotDataAsChunkList(ConstructSnapshot.java:1463)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.serializeAllTable(ConstructSnapshot.java:1345)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.lambda$constructBackplaneSnapshotInPositionSpace$2(ConstructSnapshot.java:595)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1088)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1020)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:600)
        at io.deephaven.server.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:2144)
        at io.deephaven.server.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:1318)
        at io.deephaven.server.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:995)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:157)
        at java.lang.Thread.run(Thread.java:829)
```

I confirmed that it does work on version 0.12.0, and 0.13.0

**Steps to reproduce**

Shown above

**Expected results**

The parquet files are read properly

**Actual results**

The error above is thrown

**Versions**
 - Deephaven: edge (as of june 8th, 2022)
 - OS: osx
 - Browser: Firefox
 - Docker: Docker version 20.10.8, build 3967b7d

**Comment by devinrsmith** [comment]
I'm seeing something similar on some "old" parquet files I have.

**Comment by devinrsmith** [comment]
I can confirm that `git revert c289b18af1` "fixes" the issue.

**Comment by devinrsmith** [comment]
I've got a similar issue that was first introduced by c289b18af1 afaict (5e1de7aa7c: can't repro, c289b18af1: can repro):
[parquet-requirementfailure.txt](https://github.com/deephaven/deephaven-core/files/8929637/parquet-requirementfailure.txt)
[parquet-requirementfailure2.txt](https://github.com/deephaven/deephaven-core/files/8929642/parquet-requirementfailure2.txt)

I can reproduce it by opening https://deephaven.io/wp-content/2022_place_deephaven.parquet and rapidly changing the viewport in the web UI (sometimes it reproduces on opening). Essentially, grabbing the scroll bar and clicking quickly, or grabbing the scroll bar and moving up and down rapidly without letting go.

**Comment by devinrsmith** [comment]
^ these two failures I can only reproduce with zstd compression.

**Comment by devinrsmith** [comment]
Here's an error on opening a snappy file:
[snappy-failure.txt](https://github.com/deephaven/deephaven-core/files/8931177/snappy-failure.txt)

**Comment by niloc132** [comment]
Splitting zstd off to its own bug since I _think_ this main issue is resolved. #2569 2569
