### ISSUE TITLE
Possible bug seen in `reverse()`

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#2517]
We hit this once from [CI](https://scans.gradle.com/s/rcuqdqxbd2g76/tests/:engine-table:testSerial/io.deephaven.engine.table.impl.FuzzerTest/testLargeSetOfFuzzerQueriesSimTime?anchor=eyJvdXRwdXRMaW5lIjoiMC05OTkifQ&focused-execution=1&top-execution=1#Lundefined) in `io.deephaven.engine.table.impl.FuzzerTest#testLargeSetOfFuzzerQueriesSimTime`:
```
[UpdateGraphProcessor-unitTestRefresh-1] ERROR io.deephaven.engine.table.impl.ShiftObliviousInstrumentedListener - Uncaught exception for entry= reverse(), added.size()=1, modified.size()=0, removed.size()=0, shifted.size()=1, modifiedColumnSet={EMPTY}: |  
-- | --
  | io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted resultSize == rowSet.size(), instead resultSize == 86, rowSet.size() == 87. |  
  | at io.deephaven.base.verify.Assert.fail(Assert.java:100) |  
  | at io.deephaven.base.verify.Assert.eq(Assert.java:458) |  
  | at io.deephaven.engine.table.impl.ReverseOperation.onUpdate(ReverseOperation.java:107) |  
  | at io.deephaven.engine.table.impl.ReverseOperation$2.onUpdate(ReverseOperation.java:97) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:38) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:280) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:258) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:38) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1292) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1453) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1171) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1116) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor.completeCycleForUnitTestsInternal(UpdateGraphProcessor.java:948) |  
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) |  
  | at java.util.concurrent.FutureTask.run(FutureTask.java:264) |  
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) |  
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) |  
  | at java.lang.Thread.run(Thread.java:829)
```

**Comment by nbauernfeind** [comment]
Note the log message says `ShiftObliviousInstrumentedListener` but that's because `InstrumentedTableListenerBase` grabs the wrong logger.

**Comment by devinrsmith** [comment]
This was hit during run https://github.com/deephaven/deephaven-core/actions/runs/3680311658/jobs/6225774398.

```
[UpdateGraphProcessor-unitTestRefresh-1] ERROR io.deephaven.engine.table.impl.QueryTable - Result Size Mismatch: Result rowSet: {159743,160766-160767,161790-161791,162815,163839,164863,165887,166911,167935,168959,169983,171006-171007,172031,173055,174079,175103,176127,177151,178175,179199,180222-180223,181247,182271,183295,184319,185343,186367,187391,188415,189439,190463,191487,192509-192511,193535,194559,195583,196607,197631,198655,199679,200703,201727,202751,203775,204797-204799,205823,207871,208895,209919,210943,211966-211967,212991,214015,215039,216063,217087,218111,219135,220159,221183,222207,223231,224255,225279,226303,227327,228351,229375,230399,231423,232447,233471,234495,235519,236543,237567,238591,239615,240639,241663,242687,243711,244735,245759,246783,247805-247807,248831,249855,250879,251903,252927,253951,254975,255999,257023,258047,259071,260094-260095,261119,262143-262144} size=113, expected result size=112, Original rowSet: {0,1024,2048-2049,3072,4096,5120,6144,7168,8192,9216,10240,11264,12288,13312,14336-14338,15360,16384,17408,18432,19456,20480,21504,22528,23552,24576,25600,26624,27648,28672,29696,30720,31744,32768,33792,34816,35840,36864,37888,38912,39936,40960,41984,43008,44032,45056,46080,47104,48128,49152,50176-50177,51200,52224,53248,54272,57344,58368-58370,59392,60416,61440,62464,63488,64512,65536,66560,67584,68608,69632,70656-70658,71680,72704,73728,74752,75776,76800,77824,78848,79872,80896,81920,82944-82945,83968,84992,86016,87040,88064,89088,90112,91136,92160-92161,93184,94208,95232,96256,97280,98304,99328,100352,101376-101377,102400-102401,103424} size=112, Previous Original rowSet: {0,1024,2048-2049,3072,4096,5120,6144,7168,8192,9216,10240,11264,12288,13312,14336-14338,15360,16384,17408,18432,19456,20480,21504,22528,23552,24576,25600,26624,27648,28672,29696,30720,31744,32768,33792,34816,35840,36864,37888,38912,39936,40960,41984,43008,44032,45056,46080,47104,48128,49152,50176-50177,51200,52224,53248,54272,56320,57344-57346,58368,59392,60416,61440,62464,63488,64512,65536,66560,67584,68608,69632-69634,70656,71680,72704,73728,74752,75776,76800,77824,78848,79872,80896,81920-81921,82944,83968,84992,86016,87040,88064,89088,90112,91136-91137,92160,93184,94208,95232,96256,97280,98304,99328,100352-100353,101376-101377,102400} size=112, Added: {} size=0, Removed: {} size=0
[UpdateGraphProcessor-unitTestRefresh-1] ERROR io.deephaven.engine.table.impl.InstrumentedTableListenerBase - Uncaught exception for entry= reverse(), added.size()=0, modified.size()=0, removed.size()=0, shifted.size()=1, modifiedColumnSet={EMPTY}:
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted Result Size Mismatch is never executed.
        at io.deephaven.base.verify.Assert.fail(Assert.java:86)
        at io.deephaven.base.verify.Assert.statementNeverExecuted(Assert.java:221)
        at io.deephaven.engine.table.impl.ReverseOperation.onUpdate(ReverseOperation.java:123)
        at io.deephaven.engine.table.impl.ReverseOperation$2.onUpdate(ReverseOperation.java:100)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:294)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:272)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1298)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1459)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1177)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1122)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.completeCycleForUnitTestsInternal(UpdateGraphProcessor.java:954)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
```

**Comment by devinrsmith** [comment]
[TEST-io.deephaven.engine.table.impl.FuzzerTest.xml.txt](https://github.com/deephaven/deephaven-core/files/10214453/TEST-io.deephaven.engine.table.impl.FuzzerTest.xml.txt)

**Comment by rcaudy** [comment]
Happened again:
* https://github.com/deephaven/deephaven-core/actions/runs/4625944205/jobs/8182175967
* https://scans.gradle.com/s/cycadq6e3qb2i/tests/:engine-table:testSerial/io.deephaven.engine.table.impl.FuzzerTest/testLargeSetOfFuzzerQueriesSimTime?page=eyJvdXRwdXQiOnsiMCI6IjUifX0&top-execution=1

```
[UpdateGraphProcessor-updateExecutor-1] ERROR io.deephaven.engine.table.impl.QueryTable - Result Size Mismatch: Result rowSet: {169980-169983,172031,173055,174079,175103,176127,177139-177151,178175,179199,180223,181247,182259-182271,183295,184319,185343,186367,187391,188415,189439,190463,191475-191487,192511,193523-193535,194559,195583,196607,197631,198643-198655,199679,200703,201715-201727,202750-202751,203775,204799,205823,206847,207871,208883-208895,209919,210943,211967,212991,214015,215039,216063,217087,218099-218111,219135,220159,221183,222207,223231,224255,225279,226303,227327,228339-228351,229375,230399,231423,232447,233471,234495,235519,236543,237567,238591,239615,240639,241663,242687,243711,244735,245759,246783,247807,248831,249843-249855,250879,251903,252927,253951,254975,255999,257023,258047,259071,260094-260095,261118-261119,262143-262231} size=304, expected result size=216, Original rowSet: {0,1024-1025,2048-2049,3072,4096,5120,6144,7168,8192,9216,10240,11264,12288-12300,13312,14336,15360,16384,17408,18432,19456,20480,21504,22528,23552,24576,25600,26624,27648,28672,29696,30720,31744,32768,33792-33804,34816,35840,36864,37888,38912,39936,40960,41984,43008,44032-44044,45056,46080,47104,48128,49152,50176,51200,52224,53248-53260,54272,55296,56320,57344,58368,59392-59393,60416-60428,61440,62464,63488-63500,64512,65536,66560,67584,68608-68620,69632,70656-70668,71680,72704,73728,74752,75776,76800,77824,78848,79872-79884,80896,81920,82944,83968,84992-85004,86016,87040,88064,89088,90112,91136-91148,93184-93186} size=228, Previous Original rowSet: {0,1024-1025,2048-2049,3072,4096,5120,6144,7168,8192,9216,10240,11264,12288-12300,13312,14336,15360,16384,17408,18432,19456,20480,21504,22528,23552,24576,25600,26624,27648,28672,29696,30720,31744,32768,33792-33804,34816,35840,36864,37888,38912,39936,40960,41984,43008,44032-44044,45056,46080,47104,48128,49152,50176,51200,52224,53248-53260,54272,55296,56320,57344,58368,59392-59393,60416-60428,61440,62464,63488-63500,64512,65536,66560,67584,68608-68620,69632,70656-70668,71680,72704,73728,74752,75776,76800,77824,78848,79872-79884,80896,81920,82944,83968,84992-85004,86016,87040,88064,89088,90112,92160-92163} size=216, Added: {91136-91148} size=13, Removed: {92163} size=1 |  
-- | --
  | [UpdateGraphProcessor-updateExecutor-1] ERROR io.deephaven.engine.table.impl.InstrumentedTableListenerBase - Uncaught exception for entry= reverse(), added.size()=13, modified.size()=0, removed.size()=1, shifted.size()=1, modifiedColumnSet={}: |  
  | io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted Result Size Mismatch is never executed. |  
  | at io.deephaven.base.verify.Assert.fail(Assert.java:86) |  
  | at io.deephaven.base.verify.Assert.statementNeverExecuted(Assert.java:221) |  
  | at io.deephaven.engine.table.impl.ReverseOperation.onUpdate(ReverseOperation.java:123) |  
  | at io.deephaven.engine.table.impl.ReverseOperation$2.onUpdate(ReverseOperation.java:100) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:296) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:274) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37) |  
  | at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1279) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor$ConcurrentNotificationProcessor.processSatisfiedNotifications(UpdateGraphProcessor.java:1330) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor$UpdateGraphProcessorThreadFactory.lambda$newThread$0(UpdateGraphProcessor.java:1817) |  
  | at java.lang.Thread.run(Thread.java:833) |  
  |   |  
  | Received error notification: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted Result Size Mismatch is never executed. |  
  | at io.deephaven.base.verify.Assert.fail(Assert.java:86) |  
  | at io.deephaven.base.verify.Assert.statementNeverExecuted(Assert.java:221) |  
  | at io.deephaven.engine.table.impl.ReverseOperation.onUpdate(ReverseOperation.java:123) |  
  | at io.deephaven.engine.table.impl.ReverseOperation$2.onUpdate(ReverseOperation.java:100) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:296) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:274) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37) |  
  | at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1279) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor$ConcurrentNotificationProcessor.processSatisfiedNotifications(UpdateGraphProcessor.java:1330) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor$UpdateGraphProcessorThreadFactory.lambda$newThread$0(UpdateGraphProcessor.java:1817) |  
  | at java.base/java.lang.Thread.run(Thread.java:833) |  
  |   |  
  | Exception in thread "UpdateGraphProcessor-updateExecutor-1" junit.framework.AssertionFailedError: Assertion failed: asserted Result Size Mismatch is never executed. |  
  | at junit.framework.Assert.fail(Assert.java:57) |  
  | at junit.framework.TestCase.fail(TestCase.java:223) |  
  | at io.deephaven.engine.testutil.testcase.RefreshingTableTestCase.reportUpdateError(RefreshingTableTestCase.java:98) |  
  | at io.deephaven.engine.table.impl.util.AsyncClientErrorNotifier.reportError(AsyncClientErrorNotifier.java:29) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailureInternalWithDependent(InstrumentedTableListenerBase.java:168) |  
  | at io.deephaven.engine.table.impl.BaseTable$ListenerImpl.onFailureInternal(BaseTable.java:898) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailure(InstrumentedTableListenerBase.java:156) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:326) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:274) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37) |  
  | at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1279) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor$ConcurrentNotificationProcessor.processSatisfiedNotifications(UpdateGraphProcessor.java:1330) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor$UpdateGraphProcessorThreadFactory.lambda$newThread$0(UpdateGraphProcessor.java:1817) |  
  | at java.base/java.lang.Thread.run(Thread.java:833) |  
  | [UpdateGraphProcessor-updateExecutor-2] ERROR io.deephaven.engine.table.impl.InstrumentedTableListenerBase - Uncaught exception for entry= by(ROLLUP_REAGGREGATED:[NullColumns{resultColumns={MyString=class java.lang.String, MyBoolean=class java.lang.Boolean, MyChar=char}}, ColumnAggregation{spec=AggSpecStd{}, pair=ColumnName{name=MyBigDecimal}}, ColumnAggregation{spec=AggSpecFirst{}, pair=ColumnName{name=MyInt}}, ColumnAggregation{spec=AggSpecMax{}, pair=ColumnName{name=MyLong}}, ColumnAggregation{spec=AggSpecSum{}, pair=ColumnName{name=MyBigInteger}}, ColumnAggregation{spec=AggSpecLast{}, pair=ColumnName{name=MyShort}}, Count{column=ColumnName{name=MyDouble}}, Partition{column=ColumnName{name=__ROLLUP__}, includeGroupByColumns=true}]), added.size()=1, modified.size()=0, removed.size()=0, shifted.size()=0, modifiedColumnSet={EMPTY}: |  
  | io.deephaven.engine.liveness.LivenessStateException: LivenessScope-579318454[0] (0) failed to add null (-1), because either this manager or referent is no longer live |  
  | at io.deephaven.engine.liveness.LivenessManager.manage(LivenessManager.java:24) |  
  | at io.deephaven.engine.liveness.LivenessArtifact.manageWithCurrentScope(LivenessArtifact.java:52) |  
  | at io.deephaven.engine.liveness.LivenessArtifact.<init>(LivenessArtifact.java:30) |  
  | at io.deephaven.engine.liveness.LivenessArtifact.<init>(LivenessArtifact.java:21) |  
  | at io.deephaven.engine.table.impl.LiveAttributeMap.<init>(LiveAttributeMap.java:59) |  
  | at io.deephaven.engine.table.impl.BaseGridAttributes.<init>(BaseGridAttributes.java:24) |  
  | at io.deephaven.engine.table.impl.BaseTable.<init>(BaseTable.java:112) |  
  | at io.deephaven.engine.table.impl.QueryTable.<init>(QueryTable.java:304) |  
  | at io.deephaven.engine.table.impl.QueryTable.getSubTable(QueryTable.java:3026) |  
  | at io.deephaven.engine.table.impl.by.PartitionByChunkedOperator.makeSubTable(PartitionByChunkedOperator.java:806) |  
  | at io.deephaven.engine.table.impl.by.PartitionByChunkedOperator.lambda$propagateNewDestinations$7(PartitionByChunkedOperator.java:778) |  
  | at io.deephaven.engine.rowset.RowSequence.lambda$forAllRowKeys$0(RowSequence.java:175) |  
  | at io.deephaven.engine.rowset.impl.singlerange.SingleRangeMixin.forEachRowKey(SingleRangeMixin.java:17) |  
  | at io.deephaven.engine.rowset.RowSequence.forAllRowKeys(RowSequence.java:174) |  
  | at io.deephaven.engine.table.impl.by.PartitionByChunkedOperator.propagateNewDestinations(PartitionByChunkedOperator.java:773) |  
  | at io.deephaven.engine.table.impl.by.PartitionByChunkedOperator.propagateUpdates(PartitionByChunkedOperator.java:646) |  
  | at io.deephaven.engine.table.impl.by.AggregationContext.propagateChangesToOperators(AggregationContext.java:292) |  
  | at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.computeDownstreamIndicesAndCopyKeys(ChunkedOperatorAggregationHelper.java:635) |  
  | at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$1.onUpdate(ChunkedOperatorAggregationHelper.java:262) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:296) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:274) |  
  | at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37) |  
  | at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1279) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor$ConcurrentNotificationProcessor.processSatisfiedNotifications(UpdateGraphProcessor.java:1330) |  
  | at io.deephaven.engine.updategraph.UpdateGraphProcessor$UpdateGraphProcessorThreadFactory.lambda$newThread$0(UpdateGraphProcessor.java:1817) |  
  | at java.lang.Thread.run(Thread.java:833) |  
  |   |  
  | Received error notification: io.deephaven.engine.liveness.LivenessStateException: LivenessScope-579318454[0] (0) failed to add null (-1), because either this manager or referent is no longer live
```

**Comment by rcaudy** [comment]
What do you know? If I pay attention to the fact that this is a randomized test that logs its seed, I can reproduce using the same seed:
```
        final long seed1 = 1680761343281446749L; //Clock.system().currentTimeNanos();
        final int iterations = 5; //TstUtils.SHORT_TESTS ? 1 : 5;
```

**Comment by rcaudy** [comment]
@nbauernfeind points out a simpler reproducer:
```
runLargeFuzzerSetWithSeed(1680761343281446749L, 34, 34, false, 180, 0);
```

**Comment by rcaudy** [comment]
Some sleuthing by @nbauernfeind has determined that the sequence of operations triggered by the fuzzer is:
```
table6309590437540887233_0 = tickingValues.select();
table6309590437540887233_0.setAttribute("TESTSEED",-6309590437540887233);
partitioned6309590437540887233_1 = table6309590437540887233_0.partitionBy("MyDouble");
table6309590437540887233_1 = partitioned6309590437540887233_1.table().size() == 0 ? table6309590437540887233_0 : partitioned6309590437540887233_1.table().getColumnSource(partitioned6309590437540887233_1.constituentColumnName()).get(partitioned6309590437540887233_1.table().getRowSet().firstRowKey());
table6309590437540887233_2 = merge(table6309590437540887233_1,randomValues);
table6309590437540887233_3 = table6309590437540887233_2.tailPct(0.90);
table6309590437540887233_4 = table6309590437540887233_3.reverse();
table6309590437540887233_5prime = io.deephaven.engine.table.impl.SelectOverheadLimiter.clampSelectOverhead(table6309590437540887233_4, 10.0d);
table6309590437540887233_5 = table6309590437540887233_5prime.select();
partitioned = merge(table6309590437540887233_5, randomValues.head(1L), tickingValues.head(1L)).partitionBy("MyBoolean");
table6309590437540887233_6 = partitioned.merge();
table6309590437540887233_7 = table6309590437540887233_6.dropColumns("Timestamp","MyString","MyLong","MyBigInteger").flatten().join(randomValues,"MyInt","Timestamp,MyString,MyLong,MyBigInteger");
table6309590437540887233_8 = table6309590437540887233_7.headPct(0.9);
table6309590437540887233_9 = table6309590437540887233_8.reverse();
part2 = table6309590437540887233_9.selectDistinct("MyBigInteger").update("Parent= (String) null","ID= `T`+MyBigInteger").update("Timestamp = (io.deephaven.time.DateTime) null ","MyString = (java.lang.String) null ","MyInt = (java.lang.Integer) null ","MyLong = (java.lang.Long) null ","MyFloat = (java.lang.Float) null ","MyDouble = (java.lang.Double) null ","MyBoolean = (java.lang.Boolean) null ","MyChar = (java.lang.Character) null ","MyShort = (short) null ","MyByte = (byte) null ","MyBigDecimal = (java.math.BigDecimal) null ","MyBigInteger = (java.math.BigInteger) null ");
atomicLong_6309590437540887233 = new java.util.concurrent.atomic.AtomicLong();
part1 = table6309590437540887233_9.update("ID=`a`+atomicLong_6309590437540887233.getAndIncrement()", "Parent = `T`+MyBigInteger");
tree6309590437540887233 = merge(part1,part2).tree("ID","Parent");
```

He was able to determine that the issue happens for the second `reverse`, and that the important part is the `update` followed by `merge`.

This, in turn, caused us to investigate `UnionSourceManager`, which in turn led us to `WritableRowSet.insertWithShift(long, RowSet)`. We've proven that the implementation is mutating other's `innerSet`, which should not be happening.

Debug change to `WritableRowSetImpl` looks like:
```
    @Override
    public final void insertWithShift(final long shiftAmount, final RowSet other) {
        preMutationHook();
        final long otherSize = other.size();
        assign(innerSet.ixInsertWithShift(shiftAmount, getInnerSet(other)));
        if (otherSize != other.size()) {
            throw new IllegalStateException("insertWithShift mutated other");
        }
        postMutationHook();
    }
```

**Comment by rcaudy** [comment]
Further debugging leads us to `SortedRanges.ixInsertWithShift(long, OrderedLongSet)` when called with an `RspBitmap` as `other`.

```
    @Override
    public final OrderedLongSet ixInsertWithShift(final long shiftAmount, final OrderedLongSet other) {
        if (other.ixIsEmpty()) {
            return this;
        }
        if (ixIsEmpty()) {
            return other.ixShiftOnNew(shiftAmount);
        }
        if (other instanceof SingleRange) {
            final long start = other.ixFirstKey() + shiftAmount;
            final long end = other.ixLastKey() + shiftAmount;
            final SortedRanges ans = addRange(start, end);
            if (ans != null) {
                return ans;
            }
            RspBitmap rspAns = toRsp();
            rspAns.addRangeUnsafeNoWriteCheck(start, end);
            rspAns.finishMutations();
            return rspAns;
        }
        if (other instanceof SortedRanges) {
            SortedRanges sr = (SortedRanges) other;
            sr = sr.applyShiftOnNew(shiftAmount);
            return ixInsertImpl(sr);
        }
        RspBitmap rsp = (RspBitmap) other;
        rsp = rsp.applyOffsetOnNew(shiftAmount);
        rsp.insertOrderedLongSetUnsafeNoWriteCheck(this); // THIS IS THE LINE THAT MUTATES OTHER
        rsp.finishMutations();
        return rsp;
    }
```

This line seems to just result in bumping the ref count, when `shiftAmount == 0`: `rsp = rsp.applyOffsetOnNew(shiftAmount);`

The "no write check" insert is probably inappropriate.

**Comment by rcaudy** [comment]
Adding @jcferretti to help propose the most appropriate fix.

**Comment by rcaudy** [comment]
My proposed fix:
```
Index: engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java b/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java
--- a/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java	(revision 0d32e4e40cadbc5a40a0e288b0c3bda275ccbbc7)
+++ b/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java	(date 1681248678357)
@@ -4928,7 +4928,7 @@
         }
         RspBitmap rsp = (RspBitmap) other;
         rsp = rsp.applyOffsetOnNew(shiftAmount);
-        rsp.insertOrderedLongSetUnsafeNoWriteCheck(this);
+        rsp = rsp.ixInsert(this);
         rsp.finishMutations();
         return rsp;
     }

```
That does the appropriate CoW if needed. Maybe we don't need `finishMutations` anymore at this point?

**Comment by jcferretti** [comment]
> My proposed fix:
> 
> ```
> Index: engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java b/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java
> --- a/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java	(revision 0d32e4e40cadbc5a40a0e288b0c3bda275ccbbc7)
> +++ b/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java	(date 1681248678357)
> @@ -4928,7 +4928,7 @@
>          }
>          RspBitmap rsp = (RspBitmap) other;
>          rsp = rsp.applyOffsetOnNew(shiftAmount);
> -        rsp.insertOrderedLongSetUnsafeNoWriteCheck(this);
> +        rsp = rsp.ixInsert(this);
>          rsp.finishMutations();
>          return rsp;
>      }
> ```
> 
> That does the appropriate CoW if needed. Maybe we don't need `finishMutations` anymore at this point?

applyOffsetOnNew should be returning a new RSP.

**Comment by rcaudy** [comment]
> > My proposed fix:
> 
> > 
> 
> > ```
> 
> > Index: engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java
> 
> > IDEA additional info:
> 
> > Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> 
> > <+>UTF-8
> 
> > ===================================================================
> 
> > diff --git a/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java b/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java
> 
> > --- a/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java	(revision 0d32e4e40cadbc5a40a0e288b0c3bda275ccbbc7)
> 
> > +++ b/engine/rowset/src/main/java/io/deephaven/engine/rowset/impl/sortedranges/SortedRanges.java	(date 1681248678357)
> 
> > @@ -4928,7 +4928,7 @@
> 
> >          }
> 
> >          RspBitmap rsp = (RspBitmap) other;
> 
> >          rsp = rsp.applyOffsetOnNew(shiftAmount);
> 
> > -        rsp.insertOrderedLongSetUnsafeNoWriteCheck(this);
> 
> > +        rsp = rsp.ixInsert(this);
> 
> >          rsp.finishMutations();
> 
> >          return rsp;
> 
> >      }
> 
> > ```
> 
> > 
> 
> > That does the appropriate CoW if needed. Maybe we don't need `finishMutations` anymore at this point?
> 
> 
> 
> `applyOffsetOnNew` should be returning a new RSP, so anything after that reassignment to the `rsp` reference should not be mutating the original `other`

That is, unfortunately, not what applyOffsetOnNew does when shiftAmount is 0.
