### ISSUE TITLE
AJ resource leak in unit tests

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#2556]
CI Run: https://github.com/deephaven/deephaven-core/runs/6931137993

Gradle Build Scan: https://scans.gradle.com/s/fjy7sum5bihwe

Stack Trace:
```
io.deephaven.util.datastructures.ReleaseTracker$LeakedException: Leaked 2 resources. Enable `ReleaseTracker.captureStackTraces` to further debug.	
at io.deephaven.util.datastructures.ReleaseTracker$StrictReleaseTracker.check(ReleaseTracker.java:114)	
at io.deephaven.chunk.util.pools.ChunkPoolReleaseTracking.check(ChunkPoolReleaseTracking.java:68)	
at io.deephaven.chunk.util.pools.ChunkPoolReleaseTracking.checkAndDisable(ChunkPoolReleaseTracking.java:74)	
at io.deephaven.engine.table.impl.RefreshingTableTestCase.tearDown(RefreshingTableTestCase.java:71)	
at io.deephaven.test.junit4.EngineCleanup.tearDown(EngineCleanup.java:25)	
at io.deephaven.test.junit4.EngineCleanup$1.evaluate(EngineCleanup.java:45)	
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)	
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)	
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)	
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)	
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)	
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)	
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)	
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)	
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)	
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)	
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)	
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)	
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)	
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)	
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)	
at java.lang.reflect.Method.invoke(Method.java:577)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)	
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)	
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)	
at jdk.proxy1.$Proxy2.processTestClass(Unknown Source)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)	
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)	
at java.lang.reflect.Method.invoke(Method.java:577)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)	
at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)	
at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)	
at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)	
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)	
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)	
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)	
at java.lang.Thread.run(Thread.java:833)
```

**Comment by rcaudy** [comment]
We saw this again:

CI Run: https://github.com/deephaven/deephaven-core/actions/runs/2764804863

Gradle Build Scan: https://scans.gradle.com/s/4pdlqpvgzwapo/tests/:engine-table:testOutOfBand/io.deephaven.engine.table.impl.QueryTableAjTest/testAjRandomLeftStaticRightIncremental?page=eyJvdXRwdXQiOnsiMCI6Mn19&top-execution=1

**Comment by rcaudy** [comment]
Happened again:
CI Run: https://github.com/rcaudy/deephaven-core/actions/runs/3623854096/jobs/6110181589

**Comment by rcaudy** [comment]
Duplicated by https://github.com/deephaven/deephaven-core/issues/2556, which has more recent documentation.
