### ISSUE TITLE
[Python] Kafka simple_spec() doesn't parse values into non string types properly

### ISSUE THREAD

**Issue by jakemulf** [deephaven/deephaven-core#2565]
**Description**

NOTE: To reproduce using our official docker image, set the redpanda image to `latest`. The `-f` flag isn't supported in the version we currently have

```
image: docker.vectorized.io/vectorized/redpanda:latest
```

The following Python code would expect to create a table with Kafka key-value pairs with the `Price` column as a `double` type

```
from deephaven.stream.kafka import consumer as kt
import deephaven.dtypes as dht

result = kt.consume({'bootstrap.servers' : 'redpanda:29092'},
                   'share.price',
                   key_spec=kt.simple_spec('Symbol'),
                   value_spec=kt.simple_spec('Price', data_type=dht.double),
                   table_type=kt.TableType.append())
```

The table creates properly, but adding any entries to the Kafka stream throws an error. For example, running `docker-compose exec redpanda rpk topic produce share.price -f '%k %v\n'` and then adding any expected key-value pair (like `AAPL 135`) and pressing enter throws the following error

```
estershare.price:ALL | i.d.kafka.KafkaTools      | KafkaIngester(share.price, ALL): Exception while polling for Kafka messages:org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition share.price-0 at offset 22. If needed, please seek past the record to continue consumption.

        at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1448)
        at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:135)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1671)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1507)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:733)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:684)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1304)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1238)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
        at io.deephaven.kafka.ingest.KafkaIngester.pollOnce(KafkaIngester.java:306)
        at io.deephaven.kafka.ingest.KafkaIngester.consumerLoop(KafkaIngester.java:274)
        at java.lang.Thread.run(Thread.java:829)
caused by:
org.apache.kafka.common.errors.SerializationException: Size of data received by Deserializer is not 8
        at org.apache.kafka.common.serialization.DoubleDeserializer.deserialize(DoubleDeserializer.java:28)
        at org.apache.kafka.common.serialization.DoubleDeserializer.deserialize(DoubleDeserializer.java:21)
        at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60)
        at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1439)
        at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:135)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1671)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1507)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:733)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:684)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1304)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1238)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
        at io.deephaven.kafka.ingest.KafkaIngester.pollOnce(KafkaIngester.java:306)
        at io.deephaven.kafka.ingest.KafkaIngester.consumerLoop(KafkaIngester.java:274)
        at java.lang.Thread.run(Thread.java:829)
, aborting.
```

**Steps to reproduce**

Described above

**Expected results**

The `AAPL 135` entry is added to the table with the value being of type double

**Actual results**

The above error is thrown

**Additional details and attachments**

A table update can be used to work around this, since the values are read as strings by default. I'm not sure if this is even something on our end

**Versions**
 - Deephaven: latest
 - OS: OSX
 - Browser: Firefox
 - Docker: Docker version 20.10.8, build 3967b7d

**Comment by jcferretti** [comment]
This is wrong:
`docker-compose exec redpanda rpk topic produce share.price -f '%k %v\n'`

That is going to encode the topic as a double but as a string.

In Kafka, the producer does the encoding.  The consumer extracts bytes from the value expecting a certain type.  The platform itself (eg, Kafka) is completely oblivious to types, it just moves key and values around as arrays of bytes.

So, it is necessary for the producer to be doing the right thing. The producer in this case is the rpk tool.  There is nothing in that command line telling the rpk tool to send the data as a double.





[11:58](https://illumon.slack.com/archives/D02DG21LE9W/p1656345520939979)
because the command cannot be possibly be the same for sending strings or doubles.
[11:58](https://illumon.slack.com/archives/D02DG21LE9W/p1656345532510329)
/something/ has to know what type the consumer is going to be expecting.
[11:59](https://illumon.slack.com/archives/D02DG21LE9W/p1656345556066649)
There is no magic here equivalent to what python does of finding the "right" type for the destination and converting automatically for you

**Comment by jcferretti** [comment]
I just tested and this works:
![Deephaven - Google Chrome_176](https://user-images.githubusercontent.com/37232625/175986260-a81a021e-8c1a-43bf-bc01-a2db90a9fe97.png)

I ran our python driver that /can/ provide types via argument tags, like this:

```
$ pwd
/a0/h/cfs/dh/oss1/deephaven-core/redpanda/examples/python

cfs@erke 12:06:42 ~/dh/oss1/deephaven-core/redpanda/examples/python
$ python3 kafka-produce.py prices 0 'str:MSFT' 'double:100.123'
Message key=|b'MSFT'|, value=|b'@Y\x07\xdf;dZ\x1d'| delivered to topic prices partition 0
```
