### ISSUE TITLE
Class cast exception when using `plot_xy(... by=...)` in python

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2636]
A simple test of "plot-by" in python fails with a class cast exception.

```python

from deephaven import empty_table

t = empty_table(100).update(["Label = ii%2==0 ? `A` : `B`", "X=ii", "Y=(ii%2+1)*X+3"])
m = t.meta_table

from deephaven.plot import Figure

p = Figure().plot_xy(series_name="Test Series", t=t, x="X", y="Y", by=["Label"]).show()
```

The error is:

```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error '721ae753-6523-47db-8736-a04328f5269b' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'RuntimeError'>
Value: io.deephaven.engine.table.impl.select.FormulaEvaluationException: In formula: __SERIES_NAME379982805 = (String)(__SERIES_NAME379982805Function.apply(Label))
	at io.deephaven.temp.cm1539864161987228486v55_0.Formula.applyFormulaPerItem(Formula.java:153)
	at io.deephaven.temp.cm1539864161987228486v55_0.Formula.lambda$fillChunkHelper$4(Formula.java:142)
	at io.deephaven.engine.rowset.RowSequence.lambda$forAllRowKeys$0(RowSequence.java:179)
	at io.deephaven.engine.rowset.impl.singlerange.SingleRangeMixin.forEachRowKey(SingleRangeMixin.java:17)
	at io.deephaven.engine.rowset.RowSequence.forAllRowKeys(RowSequence.java:178)
	at io.deephaven.temp.cm1539864161987228486v55_0.Formula.fillChunkHelper(Formula.java:140)
	at io.deephaven.temp.cm1539864161987228486v55_0.Formula.fillChunk(Formula.java:117)
	at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillChunk(ViewColumnSource.java:254)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doApplyUpdate(SelectColumnLayer.java:353)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$doSerialApplyUpdate$1(SelectColumnLayer.java:223)
	at io.deephaven.engine.util.systemicmarking.SystemicObjectTracker.executeSystemically(SystemicObjectTracker.java:56)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doSerialApplyUpdate(SelectColumnLayer.java:222)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$1(SelectColumnLayer.java:180)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$ImmediateJobScheduler.submit(SelectAndViewAnalyzer.java:612)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.onAllRequiredColumnsCompleted(SelectColumnLayer.java:179)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:472)
	at io.deephaven.engine.table.impl.select.analyzers.BaseLayer.applyUpdate(BaseLayer.java:75)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:128)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$32(QueryTable.java:1281)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:518)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$33(QueryTable.java:1239)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3080)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1238)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1218)
	at io.deephaven.engine.table.impl.TableWithDefaults.update(TableWithDefaults.java:279)
	at io.deephaven.plot.datasets.multiseries.AbstractPartitionedTableHandleMultiSeries.lambda$applyTransform$0(AbstractPartitionedTableHandleMultiSeries.java:98)
	at io.deephaven.plot.FigureImpl.lambda$applyFunctionalProperties$0(FigureImpl.java:314)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at io.deephaven.plot.FigureImpl.applyFunctionalProperties(FigureImpl.java:309)
	at io.deephaven.plot.FigureImpl.onDisplay(FigureImpl.java:275)
	at io.deephaven.plot.FigureImpl.show(FigureImpl.java:242)
	at io.deephaven.plot.FigureImpl.show(FigureImpl.java:51)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.engine.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:182)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:49)
	at io.deephaven.engine.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:181)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:165)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:81)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:106)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:188)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:160)
	at java.base/java.lang.Thread.run(Thread.java:829)
caused by java.lang.ClassCastException: class java.lang.String cannot be cast to class [Ljava.lang.Object; (java.lang.String and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
	at io.deephaven.temp.cm1539864161987228486v55_0.Formula.applyFormulaPerItem(Formula.java:151)
	... 49 more

Line: 1859
Namespace: show
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/plot/figure.py
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/plot/figure.py", line 1859, in show

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
        at io.deephaven.engine.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:182)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:49)
        at io.deephaven.engine.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:181)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:165)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:81)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:106)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:188)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:160)
        at java.lang.Thread.run(Thread.java:829)
```

**Comment by niloc132** [comment]
Ryan and I ran into this before, I don't understand at a glance how you're getting it now, but it is a plotting/smartkey issue, not a py issue.

**Comment by niloc132** [comment]
I'm unable to reproduce this at all, on either HEAD or v0.14.0, using either netty or jetty.
