### ISSUE TITLE
InputTable#add stuck waiting for sequence

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#2721]
Carson ran into an issue with an InputTable when working on one of the client API's.

The stack trace had an unresolved export waiting on an input table update:
```
"DeephavenApiServer-Scheduler-Serial-1" #35 daemon prio=5 os_prio=0 cpu=2232.18ms elapsed=337.81s tid=0x00007f28580f6800 nid=0xa0 in Object.wait()  [0x00007f288858e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.16/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@11.0.16/Object.java:328)
	at io.deephaven.engine.table.impl.util.BaseArrayBackedMutableTable$ArrayBackedMutableInputTable.waitForSequence(BaseArrayBackedMutableTable.java:278)
	- waiting to re-lock in wait() <0x0000000705bb9970> (a java.util.Collections$SynchronizedRandomAccessList)
	at io.deephaven.engine.table.impl.util.BaseArrayBackedMutableTable$ArrayBackedMutableInputTable.add(BaseArrayBackedMutableTable.java:201)
	at io.deephaven.server.table.inputtables.InputTableServiceGrpcImpl.lambda$addTableToInputTable$1(InputTableServiceGrpcImpl.java:73)
	at io.deephaven.server.table.inputtables.InputTableServiceGrpcImpl$$Lambda$1049/0x0000000840789c40.run(Unknown Source)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
	at io.deephaven.server.session.SessionState$ExportBuilder$$Lambda$988/0x000000084074fc40.call(Unknown Source)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
	at io.deephaven.server.session.SessionState$ExportObject$$Lambda$1050/0x000000084078a040.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.16/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11.0.16/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.16/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.16/ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:162)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory$$Lambda$490/0x0000000840473c40.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
```

**Comment by rcaudy** [comment]
We've fixed one race condition in the engine-side implementation, but this doesn't seem to have solved @SuperTails 's issue with the Go client. @nbauernfeind will try to reproduce with the Java client later today.
