### ISSUE TITLE
TestTableTools.testMergeIndexShiftingPerformance test failure

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#2732]
Failure in the task `engine-table:testOutOfBand`

https://github.com/deephaven/deephaven-core/runs/7800870316?check_suite_focus=true

> junit.framework.AssertionFailedError: This test is expected to take around 5 seconds on a Mac with the new shift behavior, something is not right.

Looks like things get things get slow at step 125.

```
Step=0, duration=7ms, stepDuration=7ms	
Step=1, duration=17ms, stepDuration=10ms	
Step=2, duration=20ms, stepDuration=3ms	
Step=3, duration=23ms, stepDuration=3ms	
Step=4, duration=27ms, stepDuration=4ms	
Step=5, duration=32ms, stepDuration=5ms	
Step=6, duration=37ms, stepDuration=5ms	
Step=7, duration=43ms, stepDuration=6ms	
Step=8, duration=49ms, stepDuration=6ms	
Step=9, duration=57ms, stepDuration=8ms	
Step=10, duration=67ms, stepDuration=10ms	
Step=11, duration=75ms, stepDuration=8ms	
Step=12, duration=88ms, stepDuration=13ms	
Step=13, duration=104ms, stepDuration=16ms	
Step=14, duration=119ms, stepDuration=15ms	
Step=15, duration=137ms, stepDuration=18ms	
Step=16, duration=158ms, stepDuration=21ms	
Step=17, duration=181ms, stepDuration=23ms	
Step=18, duration=194ms, stepDuration=13ms	
Step=19, duration=224ms, stepDuration=30ms	
Step=20, duration=256ms, stepDuration=32ms	
Step=21, duration=269ms, stepDuration=13ms	
Step=22, duration=310ms, stepDuration=41ms	
Step=23, duration=352ms, stepDuration=42ms	
Step=24, duration=365ms, stepDuration=13ms	
Step=25, duration=408ms, stepDuration=43ms	
Step=26, duration=424ms, stepDuration=16ms	
Step=27, duration=439ms, stepDuration=15ms	
Step=28, duration=456ms, stepDuration=17ms	
Step=29, duration=499ms, stepDuration=43ms	
Step=30, duration=517ms, stepDuration=18ms	
Step=31, duration=535ms, stepDuration=18ms	
Step=32, duration=582ms, stepDuration=47ms	
Step=33, duration=610ms, stepDuration=28ms	
Step=34, duration=636ms, stepDuration=26ms	
Step=35, duration=692ms, stepDuration=56ms	
Step=36, duration=738ms, stepDuration=46ms	
Step=37, duration=762ms, stepDuration=24ms	
Step=38, duration=807ms, stepDuration=45ms	
Step=39, duration=832ms, stepDuration=25ms	
Step=40, duration=857ms, stepDuration=25ms	
Step=41, duration=907ms, stepDuration=50ms	
Step=42, duration=939ms, stepDuration=32ms	
Step=43, duration=962ms, stepDuration=23ms	
Step=44, duration=990ms, stepDuration=28ms	
Step=45, duration=1034ms, stepDuration=44ms	
Step=46, duration=1060ms, stepDuration=26ms	
Step=47, duration=1087ms, stepDuration=27ms	
Step=48, duration=1130ms, stepDuration=43ms	
Step=49, duration=1160ms, stepDuration=30ms	
Step=50, duration=1186ms, stepDuration=26ms	
Step=51, duration=1231ms, stepDuration=45ms	
Step=52, duration=1261ms, stepDuration=30ms	
Step=53, duration=1287ms, stepDuration=26ms	
Step=54, duration=1332ms, stepDuration=45ms	
Step=55, duration=1364ms, stepDuration=32ms	
Step=56, duration=1391ms, stepDuration=27ms	
Step=57, duration=1425ms, stepDuration=34ms	
Step=58, duration=1470ms, stepDuration=45ms	
Step=59, duration=1499ms, stepDuration=29ms	
Step=60, duration=1536ms, stepDuration=37ms	
Step=61, duration=1583ms, stepDuration=47ms	
Step=62, duration=1622ms, stepDuration=39ms	
Step=63, duration=1666ms, stepDuration=44ms	
Step=64, duration=1721ms, stepDuration=55ms	
Step=65, duration=1764ms, stepDuration=43ms	
Step=66, duration=1797ms, stepDuration=33ms	
Step=67, duration=1850ms, stepDuration=53ms	
Step=68, duration=1899ms, stepDuration=49ms	
Step=69, duration=1938ms, stepDuration=39ms	
Step=70, duration=1985ms, stepDuration=47ms	
Step=71, duration=2057ms, stepDuration=72ms	
Step=72, duration=2108ms, stepDuration=51ms	
Step=73, duration=2180ms, stepDuration=72ms	
Step=74, duration=2242ms, stepDuration=62ms	
Step=75, duration=2282ms, stepDuration=40ms	
Step=76, duration=2330ms, stepDuration=48ms	
Step=77, duration=2401ms, stepDuration=71ms	
Step=78, duration=2450ms, stepDuration=49ms	
Step=79, duration=2498ms, stepDuration=48ms	
Step=80, duration=2560ms, stepDuration=62ms	
Step=81, duration=2612ms, stepDuration=52ms	
Step=82, duration=2659ms, stepDuration=47ms	
Step=83, duration=2731ms, stepDuration=72ms	
Step=84, duration=2793ms, stepDuration=62ms	
Step=85, duration=2840ms, stepDuration=47ms	
Step=86, duration=2896ms, stepDuration=56ms	
Step=87, duration=2970ms, stepDuration=74ms	
Step=88, duration=3014ms, stepDuration=44ms	
Step=89, duration=3082ms, stepDuration=68ms	
Step=90, duration=3144ms, stepDuration=62ms	
Step=91, duration=3189ms, stepDuration=45ms	
Step=92, duration=3266ms, stepDuration=77ms	
Step=93, duration=3338ms, stepDuration=72ms	
Step=94, duration=3401ms, stepDuration=63ms	
Step=95, duration=3469ms, stepDuration=68ms	
Step=96, duration=3543ms, stepDuration=74ms	
Step=97, duration=3622ms, stepDuration=79ms	
Step=98, duration=3676ms, stepDuration=54ms	
Step=99, duration=3749ms, stepDuration=73ms	
Step=100, duration=3824ms, stepDuration=75ms	
Step=101, duration=3880ms, stepDuration=56ms	
Step=102, duration=3956ms, stepDuration=76ms	
Step=103, duration=4026ms, stepDuration=70ms	
Step=104, duration=4079ms, stepDuration=53ms	
Step=105, duration=4158ms, stepDuration=79ms	
Step=106, duration=4242ms, stepDuration=84ms	
Step=107, duration=4295ms, stepDuration=53ms	
Step=108, duration=4370ms, stepDuration=75ms	
Step=109, duration=4451ms, stepDuration=81ms	
Step=110, duration=4527ms, stepDuration=76ms	
Step=111, duration=4609ms, stepDuration=82ms	
Step=112, duration=4689ms, stepDuration=80ms	
Step=113, duration=4776ms, stepDuration=87ms	
Step=114, duration=4832ms, stepDuration=56ms	
Step=115, duration=4919ms, stepDuration=87ms	
Step=116, duration=5004ms, stepDuration=85ms	
Step=117, duration=5064ms, stepDuration=60ms	
Step=118, duration=5154ms, stepDuration=90ms	
Step=119, duration=5246ms, stepDuration=92ms	
Step=120, duration=5308ms, stepDuration=62ms	
Step=121, duration=5398ms, stepDuration=90ms	
Step=122, duration=5494ms, stepDuration=96ms	
Step=123, duration=5554ms, stepDuration=60ms	
Step=124, duration=5655ms, stepDuration=101ms	
Step=125, duration=7034ms, stepDuration=1379ms	
Step=126, duration=8973ms, stepDuration=1939ms	
Step=127, duration=10982ms, stepDuration=2009ms	
Step=128, duration=13151ms, stepDuration=2169ms	
Step=129, duration=15095ms, stepDuration=1944ms	
Step=130, duration=15445ms, stepDuration=350ms	
Step=131, duration=17748ms, stepDuration=2303ms	
Step=132, duration=20163ms, stepDuration=2415ms	
Step=133, duration=20513ms, stepDuration=350ms	
Step=134, duration=22472ms, stepDuration=1959ms	
Step=135, duration=24887ms, stepDuration=2415ms	
Step=136, duration=25097ms, stepDuration=210ms	
Step=137, duration=26234ms, stepDuration=1137ms	
Step=138, duration=27627ms, stepDuration=1393ms	
Step=139, duration=27797ms, stepDuration=170ms	
Step=140, duration=28838ms, stepDuration=1041ms	
Step=141, duration=30062ms, stepDuration=1224ms
```

**Comment by rcaudy** [comment]
I ran this 3 times locally without reproducing any delay. It seems most likely that something else was wrong in CI, e.g. GC caused by leaks elsewhere or some kind of service degradation.
I'm going to chalk this up to random failure due to environmental issues until/unless it happens further.

**Comment by devinrsmith** [comment]
Hit again, https://github.com/deephaven/deephaven-core/actions/runs/3087863479/jobs/4993680884

**Comment by rcaudy** [comment]
Another run hit this: https://github.com/rcaudy/deephaven-core/actions/runs/3623854096/jobs/6110181461

**Comment by rcaudy** [comment]
And another:
https://github.com/deephaven/deephaven-core/actions/runs/3723537194/jobs/6315101576#step:8:2103

Build scan:
https://scans.gradle.com/s/6jv6jpvprm3ze

Output:
```
Exception
junit.framework.AssertionFailedError: This test is expected to take around 5 seconds on a Mac with the new shift behavior, something is not right.	
at junit.framework.Assert.fail(Assert.java:57)	
at junit.framework.TestCase.fail(TestCase.java:223)	
at io.deephaven.engine.util.TestTableTools.testMergeIndexShiftingPerformance(TestTableTools.java:1039)	
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)	
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at java.lang.reflect.Method.invoke(Method.java:568)	
at junit.framework.TestCase.runTest(TestCase.java:177)	
at junit.framework.TestCase.runBare(TestCase.java:142)	
at junit.framework.TestResult$1.protect(TestResult.java:122)	
at junit.framework.TestResult.runProtected(TestResult.java:142)	
at junit.framework.TestResult.run(TestResult.java:125)	
at junit.framework.TestCase.run(TestCase.java:130)	
at junit.framework.TestSuite.runTest(TestSuite.java:241)	
at junit.framework.TestSuite.run(TestSuite.java:236)	
at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)	
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)	
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)	
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)	
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at java.lang.reflect.Method.invoke(Method.java:568)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)	
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)	
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)	
at jdk.proxy1.$Proxy2.processTestClass(Unknown Source)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)	
at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)	
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)	
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)	
at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)	
at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)	
Output View rawDownload raw
Step=0, duration=7ms, stepDuration=7ms	
Step=1, duration=12ms, stepDuration=5ms	
Step=2, duration=16ms, stepDuration=4ms	
Step=3, duration=19ms, stepDuration=3ms	
Step=4, duration=22ms, stepDuration=3ms	
Step=5, duration=26ms, stepDuration=4ms	
Step=6, duration=32ms, stepDuration=6ms	
Step=7, duration=38ms, stepDuration=6ms	
Step=8, duration=43ms, stepDuration=5ms	
Step=9, duration=51ms, stepDuration=8ms	
Step=10, duration=60ms, stepDuration=9ms	
Step=11, duration=68ms, stepDuration=8ms	
Step=12, duration=80ms, stepDuration=12ms	
Step=13, duration=93ms, stepDuration=13ms	
Step=14, duration=109ms, stepDuration=16ms	
Step=15, duration=126ms, stepDuration=17ms	
Step=16, duration=146ms, stepDuration=20ms	
Step=17, duration=168ms, stepDuration=22ms	
Step=18, duration=180ms, stepDuration=12ms	
Step=19, duration=208ms, stepDuration=28ms	
Step=20, duration=238ms, stepDuration=30ms	
Step=21, duration=252ms, stepDuration=14ms	
Step=22, duration=289ms, stepDuration=37ms	
Step=23, duration=393ms, stepDuration=104ms	
Step=24, duration=415ms, stepDuration=22ms	
Step=25, duration=453ms, stepDuration=38ms	
Step=26, duration=468ms, stepDuration=15ms	
Step=27, duration=484ms, stepDuration=16ms	
Step=28, duration=501ms, stepDuration=17ms	
Step=29, duration=539ms, stepDuration=38ms	
Step=30, duration=557ms, stepDuration=18ms	
Step=31, duration=575ms, stepDuration=18ms	
Step=32, duration=612ms, stepDuration=37ms	
Step=33, duration=631ms, stepDuration=19ms	
Step=34, duration=649ms, stepDuration=18ms	
Step=35, duration=669ms, stepDuration=20ms	
Step=36, duration=706ms, stepDuration=37ms	
Step=37, duration=726ms, stepDuration=20ms	
Step=38, duration=764ms, stepDuration=38ms	
Step=39, duration=787ms, stepDuration=23ms	
Step=40, duration=808ms, stepDuration=21ms	
Step=41, duration=847ms, stepDuration=39ms	
Step=42, duration=872ms, stepDuration=25ms	
Step=43, duration=896ms, stepDuration=24ms	
Step=44, duration=923ms, stepDuration=27ms	
Step=45, duration=963ms, stepDuration=40ms	
Step=46, duration=991ms, stepDuration=28ms	
Step=47, duration=1019ms, stepDuration=28ms	
Step=48, duration=1060ms, stepDuration=41ms	
Step=49, duration=1090ms, stepDuration=30ms	
Step=50, duration=1117ms, stepDuration=27ms	
Step=51, duration=1159ms, stepDuration=42ms	
Step=52, duration=1191ms, stepDuration=32ms	
Step=53, duration=1219ms, stepDuration=28ms	
Step=54, duration=1264ms, stepDuration=45ms	
Step=55, duration=1298ms, stepDuration=34ms	
Step=56, duration=1328ms, stepDuration=30ms	
Step=57, duration=1363ms, stepDuration=35ms	
Step=58, duration=1412ms, stepDuration=49ms	
Step=59, duration=1450ms, stepDuration=38ms	
Step=60, duration=1495ms, stepDuration=45ms	
Step=61, duration=1552ms, stepDuration=57ms	
Step=62, duration=1599ms, stepDuration=47ms	
Step=63, duration=1647ms, stepDuration=48ms	
Step=64, duration=1705ms, stepDuration=58ms	
Step=65, duration=1755ms, stepDuration=50ms	
Step=66, duration=1797ms, stepDuration=42ms	
Step=67, duration=1855ms, stepDuration=58ms	
Step=68, duration=1926ms, stepDuration=71ms	
Step=69, duration=1972ms, stepDuration=46ms	
Step=70, duration=2025ms, stepDuration=53ms	
Step=71, duration=2088ms, stepDuration=63ms	
Step=72, duration=2134ms, stepDuration=46ms	
Step=73, duration=2189ms, stepDuration=55ms	
Step=74, duration=2260ms, stepDuration=71ms	
Step=75, duration=2301ms, stepDuration=41ms	
Step=76, duration=2353ms, stepDuration=52ms	
Step=77, duration=2412ms, stepDuration=59ms	
Step=78, duration=2468ms, stepDuration=56ms	
Step=79, duration=2535ms, stepDuration=67ms	
Step=80, duration=2607ms, stepDuration=72ms	
Step=81, duration=2672ms, stepDuration=65ms	
Step=82, duration=2722ms, stepDuration=50ms	
Step=83, duration=2788ms, stepDuration=66ms	
Step=84, duration=2849ms, stepDuration=61ms	
Step=85, duration=2895ms, stepDuration=46ms	
Step=86, duration=2960ms, stepDuration=65ms	
Step=87, duration=3033ms, stepDuration=73ms	
Step=88, duration=3090ms, stepDuration=57ms	
Step=89, duration=3171ms, stepDuration=81ms	
Step=90, duration=3246ms, stepDuration=75ms	
Step=91, duration=3304ms, stepDuration=58ms	
Step=92, duration=3380ms, stepDuration=76ms	
Step=93, duration=3464ms, stepDuration=84ms	
Step=94, duration=3543ms, stepDuration=79ms	
Step=95, duration=3622ms, stepDuration=79ms	
Step=96, duration=3712ms, stepDuration=90ms	
Step=97, duration=3786ms, stepDuration=74ms	
Step=98, duration=3839ms, stepDuration=53ms	
Step=99, duration=3914ms, stepDuration=75ms	
Step=100, duration=4029ms, stepDuration=115ms	
Step=101, duration=4091ms, stepDuration=62ms	
Step=102, duration=4179ms, stepDuration=88ms	
Step=103, duration=4262ms, stepDuration=83ms	
Step=104, duration=4325ms, stepDuration=63ms	
Step=105, duration=4411ms, stepDuration=86ms	
Step=106, duration=4516ms, stepDuration=105ms	
Step=107, duration=4575ms, stepDuration=59ms	
Step=108, duration=4664ms, stepDuration=89ms	
Step=109, duration=4760ms, stepDuration=96ms	
Step=110, duration=4851ms, stepDuration=91ms	
Step=111, duration=4944ms, stepDuration=93ms	
Step=112, duration=5038ms, stepDuration=94ms	
Step=113, duration=5141ms, stepDuration=103ms	
Step=114, duration=5307ms, stepDuration=166ms	
Step=115, duration=5456ms, stepDuration=149ms	
Step=116, duration=5572ms, stepDuration=116ms	
Step=117, duration=5647ms, stepDuration=75ms	
Step=118, duration=5760ms, stepDuration=113ms	
Step=119, duration=5867ms, stepDuration=107ms	
Step=120, duration=5944ms, stepDuration=77ms	
Step=121, duration=6061ms, stepDuration=117ms	
Step=122, duration=6174ms, stepDuration=113ms	
Step=123, duration=6246ms, stepDuration=72ms	
Step=124, duration=6359ms, stepDuration=113ms	
Step=125, duration=6479ms, stepDuration=120ms	
Step=126, duration=6587ms, stepDuration=108ms	
Step=127, duration=7846ms, stepDuration=1259ms	
Step=128, duration=10159ms, stepDuration=2313ms	
Step=129, duration=10765ms, stepDuration=606ms	
Step=130, duration=10868ms, stepDuration=103ms	
Step=131, duration=11754ms, stepDuration=886ms	
Step=132, duration=12911ms, stepDuration=1157ms	
Step=133, duration=13131ms, stepDuration=220ms	
Step=134, duration=14720ms, stepDuration=1589ms	
Step=135, duration=18152ms, stepDuration=3432ms	
Step=136, duration=18528ms, stepDuration=376ms	
Step=137, duration=21285ms, stepDuration=2757ms	
Step=138, duration=23811ms, stepDuration=2526ms	
Step=139, duration=24247ms, stepDuration=436ms	
Step=140, duration=26804ms, stepDuration=2557ms	
Step=141, duration=29983ms, stepDuration=3179ms	
Step=142, duration=32315ms, stepDuration=2332ms	
```
