### ISSUE TITLE
Cannot open a table when running Deephaven as a library

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#2782]
**Description**

Running Deephaven as a library, I cannot open a simple table.

**Steps to reproduce**
1. Checkout the latest main of deephaven-core (`5538488ad0c3414d3912c3f103279e5717d93d3e`), and build the deephaven and deephaven server wheels: `./gradlew :py-server:assemble :py-embedded-server:assemble`
2. In a new temporary directory, set up a python venv:
```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home
python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip setuptools
```
2. In the python venv, install the wheels you built, e.g. (replace directory with your build dir): `pip install /Users/bender/dev/deephaven/oss/deephaven-core/py/server/build/wheel/deephaven_core-0.16.0-py3-none-any.whl /Users/bender/dev/deephaven/oss/deephaven-core/py/embedded-server/build/wheel/deephaven_server-0.16.0-py3-none-any.whl`
3. Start up python terminal by running `python`, then start up deephaven server:
```
# Start up the Deephaven Server
from deephaven_server import Server
s = Server(port=8080)
s.start()
```
4. In the browser, navigate to http://localhost:8080/ide/
5. Execute a command to create a simple table, e.g.:
```
from deephaven import empty_table
t = empty_table(1000).update("x=i")
```

**Expected results**
5. Table opens correctly

**Actual results**
5. Table panel opens, but stuck on the spinner and an error is logged in the browser console. See stacktrace and screenshot below:
6. 
```
Uncaught TypeError: java.lang.NullPointerException
    at NullPointerException.createError_0 [as createError] (dh-core.js:1980:10)
    at NullPointerException.initializeBackingError (dh-core.js:1209:46)
    at NullPointerException.Throwable (dh-core.js:1147:8)
    at NullPointerException.Exception (dh-core.js:1221:16)
    at NullPointerException.RuntimeException (dh-core.js:1238:16)
    at NullPointerException.JsException (dh-core.js:1941:23)
    at new NullPointerException (dh-core.js:1967:18)
    at Object.checkCriticalNotNull (dh-core.js:4731:16)
    at Object.$doubleValue (dh-core.js:1639:36)
    at Object.$read (dh-core.js:16714:29)
    at Object.$read_0 (dh-core.js:16889:16)
    at new BarrageUtils$DeltaUpdatesBuilder (dh-core.js:16592:53)
    at Object.$startAndMaybeFlush (dh-core.js:14993:36)
    at Object.$apply_3 (dh-core.js:14978:11)
    at Function.apply_53 (dh-core.js:15007:9)
    at lambda (dh-core.js:149:22)
    at dh-internal.js:1:400692
    at Array.forEach (<anonymous>)
    at dh-internal.js:1:400671
    at dh-internal.js:1:43672
    at Array.forEach (<anonymous>)
    at e.rawOnMessage (dh-internal.js:1:43634)
    at dh-internal.js:1:41447
    at Array.forEach (<anonymous>)
    at e.onTransportChunk (dh-internal.js:1:41322)
    at t.onmessage (dh-internal.js:1:55444)
```
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4505624/187530374-c5bd8664-a205-4fa7-9433-85655ab360ed.png">

A clear and concise description of what actually happened.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: `5538488ad0c3414d3912c3f103279e5717d93d3e`
 - OS: macOS Monterey 12.5.1
 - Browser: Version 104.0.5112.101 (Official Build) (arm64)
 - Docker: probably not relevant, but:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/4505624/187530638-b79a3af6-465d-4e3e-aa38-e728fe134210.png">

**Comment by mofojed** [comment]
I was able to reproduce this after doing a `./gradlew clean` on my mac.

However, I am unable to reproduce this on Ubuntu 20.04.4 LTS...

**Comment by mofojed** [comment]
Copying the wheels from Ubuntu to Mac and then running on Mac, the issue persisted.
Copying the wheels from Mac to Ubuntu, and then running on Ubuntu, the issue was not reproducible.

Seems to be something specific about running on Mac (it is an M1)

**Comment by jjbrosnan** [comment]
I was able to recreate this issue on Mac (intel chip) with DHaaL running in Jupyter.  I tried several table types, with no luck.  Here is the error I get from the dev tools -> browser logs:

```
dh-internal.js:1 Uncaught TypeError: Cannot read properties of null (reading 'slice')
    at Object.typedArrayToLittleEndianByteBuffer (dh-core.js:16477:25)
    at new BarrageUtils$DeltaUpdatesBuilder (dh-core.js:16592:68)
    at Object.$startAndMaybeFlush (dh-core.js:14993:36)
    at Object.$apply_3 (dh-core.js:14978:11)
    at Function.apply_53 (dh-core.js:15007:9)
    at lambda (dh-core.js:149:22)
    at dh-internal.js:1:400692
    at Array.forEach (<anonymous>)
    at dh-internal.js:1:400671
    at dh-internal.js:1:43672
    at Array.forEach (<anonymous>)
    at e.rawOnMessage (dh-internal.js:1:43634)
    at dh-internal.js:1:41447
    at Array.forEach (<anonymous>)
    at e.onTransportChunk (dh-internal.js:1:41322)
    at t.onmessage (dh-internal.js:1:55444)
```
