### ISSUE TITLE
update() with boolean column can fail and break destination column

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#2785]
I have an error where trying to create a boolean column fails, then seems to break the target column name for future attempts at `update()`.

I cannot get a simple reproducer working, but the code is essentially this:

```python
my_table_step1 = tableOf200kKeys.join(tableOf100Dates, 'key', 'date')
my_table = my_table_step1.natural_join(other_data, 'key,date')

test = my_table.update(['Test = 123']) # works
test = my_table.update(['Test = 123']) # works
test = my_table.update(['Test = true']) # fails with a weird ClassCastException
test = my_table.update(['Test = 123']) # no longer works, fails with an IndexOutOfBoundsException
test = my_table.update(['Test2 = 123']) # works
test_step1 = my_table_step1.update(['Test = 123']) # also fails with the IndexOutOfBoundsException
test_orig = tableOf200kKeys.update(['Test = 123']) # works
```

Adding a `.select()` to `my_table_step1` (after the `.join()`) seems to fix it. So does flatten.

The original error (when creating the boolean column) is:

```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error 'd389a100-0cde-46ec-b88b-6468a4fd78e3' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : RuntimeError: java.lang.ClassCastException: class io.deephaven.engine.table.impl.sources.BooleanSparseArraySource$ReinterpretedAsByte cannot be cast to class io.deephaven.engine.table.WritableSourceWithEnsurePrevious (io.deephaven.engine.table.impl.sources.BooleanSparseArraySource$ReinterpretedAsByte and io.deephaven.engine.table.WritableSourceWithEnsurePrevious are in unnamed module of loader 'app')
Traceback (most recent call last):
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 334, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: java.lang.ClassCastException: class io.deephaven.engine.table.impl.sources.BooleanSparseArraySource$ReinterpretedAsByte cannot be cast to class io.deephaven.engine.table.WritableSourceWithEnsurePrevious (io.deephaven.engine.table.impl.sources.BooleanSparseArraySource$ReinterpretedAsByte and io.deephaven.engine.table.WritableSourceWithEnsurePrevious are in unnamed module of loader 'app')
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.copyPreviousValues(SelectColumnLayer.java:534)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.prepareParallelUpdate(SelectColumnLayer.java:196)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$0(SelectColumnLayer.java:176)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$OperationInitializationPoolJobScheduler.lambda$submit$0(SelectAndViewAnalyzer.java:579)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.engine.table.impl.OperationInitializationThreadPool$1.lambda$newThread$0(OperationInitializationThreadPool.java:28)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The subsequent errors when trying to create an int column with the same name as the failed boolean column are:

```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error '953177b1-35aa-405c-b093-7931ad04abeb' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : RuntimeError: java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 32768
Traceback (most recent call last):
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 334, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 32768
	at io.deephaven.engine.table.impl.sources.sparse.IntOneOrN$Block1.ensureIndex(IntOneOrN.java:127)
	at io.deephaven.engine.table.impl.sources.IntegerSparseArraySource.ensureBlock(IntegerSparseArraySource.java:213)
	at io.deephaven.engine.table.impl.sources.IntegerSparseArraySource.fillFromChunkByRanges(IntegerSparseArraySource.java:652)
	at io.deephaven.engine.table.impl.sources.SparseArrayColumnSource.fillFromChunk(SparseArrayColumnSource.java:445)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doApplyUpdate(SelectColumnLayer.java:389)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$doParallelApplyUpdate$2(SelectColumnLayer.java:238)
	at io.deephaven.engine.util.systemicmarking.SystemicObjectTracker.executeSystemically(SystemicObjectTracker.java:56)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doParallelApplyUpdate(SelectColumnLayer.java:237)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$prepareParallelUpdate$0(SelectColumnLayer.java:208)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$OperationInitializationPoolJobScheduler.lambda$submit$0(SelectAndViewAnalyzer.java:579)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.engine.table.impl.OperationInitializationThreadPool$1.lambda$newThread$0(OperationInitializationThreadPool.java:28)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by nbauernfeind** [comment]
I believe this is fixed by #2903 which added `WritableSourceWithPrepareForParallelPopulation` to the list of interfaces that `BooleanSparseArraySource.ReinterpretedAsByte` implement.

I'm not sure about the continued failures.
