### ISSUE TITLE
DynamicTableWriter: Illegal range start=684 > end=683.

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-core#2800]
Colin and I ran into this while debugging #2778. I have no idea how to reproduce it. I was downloading the `weird_broken` table to csv.

```
2022-09-02T19:37:54.942Z | heduler-Concurrent-2 |  INFO | viousInstrumentedListener | 498133652: Snapshot candidate step=11204, rows={85625-85749}/{85625-85749}, cols={0-60}, usePrev=false
Caught exception in thread Thread[DeephavenApiServer-Scheduler-Concurrent-3,5,main]: Unable to write log entry. Shutting down with asynchronous system exit.
java.lang.IllegalArgumentException: Illegal range start=684 > end=683.
	at io.deephaven.engine.rowset.impl.AdaptiveOrderedLongSetBuilderRandom.newRange(AdaptiveOrderedLongSetBuilderRandom.java:100)
	at io.deephaven.engine.rowset.impl.AdaptiveOrderedLongSetBuilderRandom.addRange(AdaptiveOrderedLongSetBuilderRandom.java:155)
	at io.deephaven.engine.rowset.impl.AdaptiveRowSetBuilderRandom.addRange(AdaptiveRowSetBuilderRandom.java:28)
	at io.deephaven.engine.table.impl.UpdateSourceQueryTable.addRowKeyRange(UpdateSourceQueryTable.java:47)
	at io.deephaven.engine.table.impl.util.DynamicTableWriter.addRangeToTableIndex(DynamicTableWriter.java:199)
	at io.deephaven.engine.table.impl.util.DynamicTableWriter$DynamicTableRow.writeRow(DynamicTableWriter.java:809)
	at io.deephaven.tablelogger.TableLoggerImpl2$BaseSetter.writeRow(TableLoggerImpl2.java:71)
	at io.deephaven.tablelogger.TableLoggerImpl2.tryWrite(TableLoggerImpl2.java:186)
	at io.deephaven.tablelogger.TableLoggerImpl2.flush(TableLoggerImpl2.java:132)
	at io.deephaven.extensions.barrage.BarrageSnapshotPerformanceLogger.log(BarrageSnapshotPerformanceLogger.java:125)
	at io.deephaven.extensions.barrage.BarrageSnapshotPerformanceLogger.log(BarrageSnapshotPerformanceLogger.java:107)
	at io.deephaven.extensions.barrage.BarragePerformanceLog$SnapshotMetricsHelper.onWrite(BarragePerformanceLog.java:120)
	at io.deephaven.server.barrage.BarrageStreamGenerator$SnapshotView.forEachStream(BarrageStreamGenerator.java:514)
	at io.deephaven.server.arrow.ArrowModule$1.onNext(ArrowModule.java:46)
	at io.deephaven.server.arrow.ArrowModule$1.onNext(ArrowModule.java:41)
	at io.deephaven.server.arrow.ArrowFlightUtil.createAndSendStaticSnapshot(ArrowFlightUtil.java:181)
	at io.deephaven.server.arrow.ArrowFlightUtil.createAndSendSnapshot(ArrowFlightUtil.java:221)
	at io.deephaven.server.arrow.ArrowFlightUtil$DoExchangeMarshaller$SnapshotRequestHandler.lambda$handleMessage$0(ArrowFlightUtil.java:733)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1308)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:856)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:156)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by rcaudy** [comment]
I'm suspicious that you may have multiple concurrent writers to that performance logger. We probably checked that when the logger was added, but we should re-verify.
