### ISSUE TITLE
Parquet writing is producing invalid files

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#2806]
A Community Slack user has reported that when they use Deephaven to convert a CSV rile to a Parquet file, the resulting file is unreadable in some tools. The sample CSV and Parquet files are attached. I have reproduced the issue locally, with the provided Parquet file and new ones I wrote after loading the CSV file.
[sample_20.zip](https://github.com/deephaven/deephaven-core/files/9485645/sample_20.zip)

Deephaven has no issue loading the resulting Parquet file using `ParquetTools.readTable`, and the contents are identical to those loaded from the corresponding CSV file with `CsvTools.readCsv`.

pyarrow `parquet-tools` (https://pypi.org/project/parquet-tools/) reports:
```
Traceback (most recent call last):
  File "/Users/rcaudy/venv/3.10.6/parquet_tools/bin/parquet-tools", line 8, in <module>
    sys.exit(main())
  File "/Users/rcaudy/venv/3.10.6/parquet_tools/lib/python3.10/site-packages/parquet_tools/cli.py", line 26, in main
    args.handler(args)
  File "/Users/rcaudy/venv/3.10.6/parquet_tools/lib/python3.10/site-packages/parquet_tools/commands/show.py", line 59, in _cli
    with get_datafame_from_objs(pfs, args.head) as df:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/rcaudy/venv/3.10.6/parquet_tools/lib/python3.10/site-packages/parquet_tools/commands/utils.py", line 190, in get_datafame_from_objs
    df: Optional[pd.DataFrame] = stack.enter_context(pf.get_dataframe())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/rcaudy/venv/3.10.6/parquet_tools/lib/python3.10/site-packages/parquet_tools/commands/utils.py", line 71, in get_dataframe
    yield pq.read_table(local_path).to_pandas()
  File "/Users/rcaudy/venv/3.10.6/parquet_tools/lib/python3.10/site-packages/pyarrow/parquet/__init__.py", line 2827, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,
  File "/Users/rcaudy/venv/3.10.6/parquet_tools/lib/python3.10/site-packages/pyarrow/parquet/__init__.py", line 2473, in read
    table = self._dataset.to_table(
  File "pyarrow/_dataset.pyx", line 331, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 2577, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: Dictionary page must be before data page.
```

parquet-mr `parquet-cli` (https://formulae.brew.sh/formula/parquet-cli) reports:
```
$ parquet cat sample_20.parquet
Argument error: Could not determine file format of sample_20.parquet.
```

I have tested with and without the latest Parquet-related commit (#2555).

**Comment by rcaudy** [comment]
My reproducer notebook:
```
import io.deephaven.csv.CsvTools
import io.deephaven.engine.util.TableTools
import io.deephaven.parquet.table.ParquetTools
import io.deephaven.parquet.table.ParquetInstructions

path="/Users/rcaudy/Downloads/tmp/"
codec="LZ4"
iter="3"

c=CsvTools.readCsv(path + "sample_20.csv")

ParquetInstructions.setDefaultCompressionCodecName(codec)
ParquetTools.writeTable(c, path + "sample_20_repro" + iter + ".parquet")

t=ParquetTools.readTable(path + "sample_20_repro" + iter + ".parquet")
println TableTools.diff(t, c, c.size())
```

**Comment by rcaudy** [comment]
I've been debugging this issue extensively. It seems that we are writing the dictionary page at offset 0, and this is disregarded by the relevant code for finding the first page in a column chunk (at least in parquet-hadoop-1.12.3):
`org.apache.parquet.hadoop.metadata.ColumnChunkMetaData#getStartingPos`:
```
  public long getStartingPos() {
    decryptIfNeeded();
    long dictionaryPageOffset = getDictionaryPageOffset();
    long firstDataPageOffset = getFirstDataPageOffset();
    if (dictionaryPageOffset > 0 && dictionaryPageOffset < firstDataPageOffset) {
      // if there's a dictionary and it's before the first data page, start from there
      return dictionaryPageOffset;
    }
    return firstDataPageOffset;
  }
```

**Comment by rcaudy** [comment]
If I change "CUSIP" to not be the first column anymore, the resulting file *can* be read by parquet-cli and parquet-tools. As far as I can tell, however, we are correctly setting the dictionary offset to 0 when CUSIP is first. I need to figure out if that's false, or if there's some workaround.

**Comment by rcaudy** [comment]
I have a solution, adding a tiny bit of padding at the beginning of output files, that seems to address this issue. It feels like a hack, but that's in the spirit of every Parquet implementation I've had the misfortune of reading source code for.

**Comment by rcaudy** [comment]
Ah, the "hack" was almost on the right track after all. It looks to me like we have been writing the `"PAR1"` magic number in the wrong place: at the beginning and end of the metadata footer, instead of the beginning and end of the file.

I'm basing this on:
https://liam-blog.ml/2020/05/31/details-you-need-to-know-about-Apache-Parquet/

With that tiny fix applied, all the tools I've tried are happy with the files we produce.
