### ISSUE TITLE
DH-13126 Web CSV Upload Does not Parse DBDateTime correctly

### ISSUE THREAD

**Issue by vbabich** [deephaven/deephaven-core#2814]
**Description**

This Deephaven produced file is read by readCsv w/o problems, the Web refuses to upload it because it does not like “NY”.

[tde20.csv](https://github.com/deephaven/web-client-ui/files/9507322/tde20.csv)

**Comment by mofojed** [comment]
Actually, time stamps without a time zone do not work either. There seems to be a separate issue on Community preventing any import of DateTimes:
```
[CsvInputBar] Error: java.lang.IllegalArgumentException: 2022-08-31T00:01:18.465
    at IllegalArgumentException_0.createError (dh-core.js:1189:10)
    at IllegalArgumentException_0.initializeBackingError (dh-core.js:1209:46)
    at IllegalArgumentException_0.Throwable_0 (dh-core.js:1154:8)
    at IllegalArgumentException_0.Exception_1 (dh-core.js:1233:18)
    at IllegalArgumentException_0.RuntimeException_1 (dh-core.js:1246:18)
    at new IllegalArgumentException_0 (dh-core.js:1812:25)
    at Object.$parse_4 (dh-core.js:19082:16)
    at Object.$parseWithTimezoneAsLong (dh-core.js:19112:18)
    at Object.$parse_4 (dh-core.js:19073:41)
    at Object.parse_2 (dh-core.js:19244:17)
    at JsDataHandler$2.write_3 [as write_0] (dh-core.js:21154:86)
    at Object.$lambda$63_0 (dh-core.js:14105:94)
    at WorkerConnection$lambda$63$Type.fetch_20 [as fetch_1] (dh-core.js:15847:9)
    at Object.$lambda$36 (dh-core.js:29558:23)
    at ClientTableState$lambda$36$Type.accept_67 [as accept] (dh-core.js:30350:9)
    at Function.onInvoke_17 (dh-core.js:9017:12)
    at lambda (dh-core.js:149:22)
    at new Promise (<anonymous>)
    at Object.$refetch_1 (dh-core.js:29679:13)
    at Object.$newState (dh-core.js:14239:16)
    at Object.$newTable (dh-core.js:14264:16)
    at IdeSession.newTable (dh-core.js:8430:16)
    at e.value (CsvParser.ts:278:8)
    at e.value (CsvParser.ts:224:9)
    at c.parseChunk (papaparse.min.js:7:6346)
    at c._chunkLoaded (papaparse.min.js:7:9318)
    at FileReader.<anonymous> (papaparse.min.js:7:18166)
```
