### ISSUE TITLE
cannot convert a Python 'numpy.bool_' to a Java 'java.lang.Boolean'

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2836]
A user wanted to do numpy calculations on grouped data.  I created a reasonably efficient example for him.  Unfortunately, we are not supporting booleans well.

This is what I had to give him.  Here you can see unnecessary conversion of booleans to ints.
```python
from deephaven import empty_table
import deephaven.dtypes as dht

t = empty_table(100).update("X = randomInt(0,10)")

import numpy as np

def my_logic2(vec):

    a = np.frombuffer(vec.toArray(), dtype=np.int32)

    rst = a[:-1] < a[1:] 
    rst = np.append(rst, False)
    rst = rst.astype(np.int32)

    return dht.array(dht.int32, rst)



t3 = t.group_by().update("Test = (int[])my_logic2(X_)").ungroup()
```

This is what should work:
```python
from deephaven import empty_table
import deephaven.dtypes as dht

t = empty_table(100).update("X = randomInt(0,10)")

import numpy as np

def my_logic2(vec):

    a = np.frombuffer(vec.toArray(), dtype=np.int32)

    rst = a[:-1] < a[1:] 
    rst = np.append(rst, False)

    return dht.array(dht.bool_, rst)

t3 = t.group_by().update("Test = (Boolean[])my_logic2(X_)").ungroup()
```

It returns the following error:
```
Internal Error '374f42f8-dde1-4604-9803-3d33a67b4b21' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : ValueError: cannot convert a Python 'numpy.bool_' to a Java 'java.lang.Boolean'
Traceback (most recent call last):
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 297, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: io.deephaven.engine.table.impl.select.FormulaEvaluationException: In formula: Test = (java.lang.Boolean[])(my_logic2.call(VectorConversions.nullSafeVectorToArray(X_)))
	at io.deephaven.temp.cm1866117382987228486v55_0.Formula.applyFormulaPerItem(Formula.java:149)
	at io.deephaven.temp.cm1866117382987228486v55_0.Formula.lambda$fillChunkHelper$4(Formula.java:138)
	at io.deephaven.engine.rowset.RowSequence.lambda$forAllRowKeys$0(RowSequence.java:180)
	at io.deephaven.engine.rowset.impl.singlerange.SingleRangeMixin.forEachRowKey(SingleRangeMixin.java:14)
	at io.deephaven.engine.rowset.RowSequence.forAllRowKeys(RowSequence.java:179)
	at io.deephaven.temp.cm1866117382987228486v55_0.Formula.fillChunkHelper(Formula.java:136)
	at io.deephaven.temp.cm1866117382987228486v55_0.Formula.fillChunk(Formula.java:114)
	at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillChunk(ViewColumnSource.java:255)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doApplyUpdate(SelectColumnLayer.java:287)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doSerialApplyUpdate(SelectColumnLayer.java:171)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$1(SelectColumnLayer.java:134)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$ImmediateJobScheduler.submit(SelectAndViewAnalyzer.java:573)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.onAllRequiredColumnsCompleted(SelectColumnLayer.java:133)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:433)
	at io.deephaven.engine.table.impl.select.analyzers.BaseLayer.applyUpdate(BaseLayer.java:70)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:85)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$37(QueryTable.java:1281)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$38(QueryTable.java:1242)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3037)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1241)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1221)
	at io.deephaven.engine.table.impl.TableWithDefaults.update(TableWithDefaults.java:287)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
	at io.deephaven.engine.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:187)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
	at io.deephaven.engine.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:186)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:145)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:84)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:187)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:148)
	at java.base/java.lang.Thread.run(Thread.java:829)
caused by java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: failed to create a Java java.lang.Boolean array. : ValueError: cannot convert a Python 'numpy.bool_' to a Java 'java.lang.Boolean'
Traceback (most recent call last):
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/dtypes.py", line 165, in array
    return jpy.array(dtype.j_type, seq)
ValueError: cannot convert a Python 'numpy.bool_' to a Java 'java.lang.Boolean'

Line: 167
Namespace: array
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/dtypes.py
Traceback (most recent call last):
  File "<string>", line 15, in my_logic2
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/dtypes.py", line 167, in array

	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.callMethod(PyObject.java:432)
	at io.deephaven.engine.util.PythonScopeJpyImpl$CallableWrapper.call(PythonScopeJpyImpl.java:85)
	at io.deephaven.temp.cm1866117382987228486v55_0.Formula.applyFormulaPerItem(Formula.java:147)
	... 40 more


Line: 299
Namespace: update
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 299, in update

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
        at io.deephaven.engine.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:187)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
        at io.deephaven.engine.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:186)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:145)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:84)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:187)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1299)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:148)
        at java.lang.Thread.run(Thread.java:829)
```

**Comment by jjbrosnan** [comment]
This may not be the same bug, but this issue has been known of for some time:

[1590](https://github.com/deephaven/deephaven-core/issues/1590)

**Comment by jmao-denver** [comment]
> 

studied #1590 a little and it is not the same bug. What #1590 needs is a way for the engine to recognize numpy.bool_ type either by itself or through JPY.
