### ISSUE TITLE
Python exceptions show the rapper functions and not the source of the problems

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2862]
Python exceptions show the rapper functions and not the source of the problems.  See this exception.

```
2022-09-16 03:01:05.129 MDTTraceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/deephaven/table.py", line 374, in update return Table(j_table=self.j_table.update(*formulas)) RuntimeError: io.deephaven.engine.table.impl.select.FormulaCompilationException: Formula compilation error for: `SHARADAR`
```

**Comment by chipkent** [comment]
Here is a simple example of the poor traceback.

```python
from deephaven import empty_table

def f1():
    return empty_table(10) \
        .update("X=i") \
        .update("Y = X * 3")

def f2():
    return empty_table(10) \
        .update("Y = X * 3")

f1()
f2()
```

Here you will note that there is no python traceback to indicate where the problem is.  The only debugging information is indirect with the query string, but in larger problems, the same query strings occur frequently.

**Comment by jmao-denver** [comment]
What @chipkent was looking for is actually in the traceback output posted in the description but it is really not very easy to spot in the middle of all the Java exception stack and placed near the end of the printed stack.

The reason why is that JPY made the conscious decision to format a Python exception info  in the order to 'type', 'value', 'line', 'namespace', 'file'. The key is  the 'value' component is made up of the formatted strings of all the upstream exceptions/stack traces/tracebacks raised both in Python and Java. The length and volume of these strings  can be quite overwhelming if the execution of a DH operation crosses the boundary of Java/Python a few times, and in effect makes the source info of the top user Python code not so easy to find. 

- The obvious way to make it less painful for a Python user to get a quick idea of where in his/her code receives the exception is to change the above order of formatting a Python exception in JPY but it will surprise existing JPY users who are used to get the exception/traceback info this way. This is obviously not something we would want.  

- My previous attempt at improving DH Python's exception reporting by not exposing the trackback by default was not received very positively by DH core developers and I had to revert the changes.

- Beyond the above two options I really don't another alternative except maybe to produce a document to teach DH users how to process these seemingly noisy and overwhelming exception info.

Some feedback from dev-rel is needed before we can proceed with any level of confidence that we won't screw up again on this tricky issue.

Your thoughts, @chipkent ?

**Comment by chipkent** [comment]
Here is a simple example to look at what pure python does:
```python
import traceback

def f():
    raise Exception("EX f")

def g():
    try:
        f()
    except Exception as e:
        raise RuntimeError("EX g") from e

try:
    g()
except Exception as e:
    print(traceback.format_exc())
```

Which produces:
```
Traceback (most recent call last):
  File "<string>", line 8, in g
  File "<string>", line 4, in f
Exception: EX f

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "<string>", line 10, in g
RuntimeError: EX g
```

... which is basically in the same order and format as our current exception.  Unfortunately, if we make changes, we may be deviating from vanilla python and not just deviating from jpy.

I think part of the confusion is the actual line numbers.  Users will not see `"<string>"` and `<module>` as "my code", but pure python does report similar names like `""` or `"main.py"`.

If we look at a minimalistic example, I think it helps clarify some confusion:
```python
from deephaven import empty_table
from deephaven import DHError

t = empty_table(10)
t.where("X > 3")
```
Which produces:
```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error '28382f7e-774b-4708-898a-2965ec580a1d' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table where operation failed. : RuntimeError: java.lang.RuntimeException: Column "X" doesn't exist in this table, available columns: []
Traceback (most recent call last):
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 502, in where
    return Table(j_table=self.j_table.where(*filters))
RuntimeError: java.lang.RuntimeException: Column "X" doesn't exist in this table, available columns: []
	at io.deephaven.engine.table.impl.select.RangeConditionFilter.init(RangeConditionFilter.java:127)
	at io.deephaven.engine.table.impl.QueryTable.lambda$whereInternal$31(QueryTable.java:1041)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:518)
	at io.deephaven.engine.table.impl.QueryTable.whereInternal(QueryTable.java:1011)
	at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:1007)
	at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:88)
	at io.deephaven.api.TableOperationsDefaults.where(TableOperationsDefaults.java:66)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:185)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:49)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:184)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:146)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:117)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:128)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:116)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:146)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:170)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1308)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:856)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:159)
	at java.base/java.lang.Thread.run(Thread.java:829)


Line: 504
Namespace: where
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 504, in where

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
        at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:185)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:49)
        at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:184)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:146)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:117)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:128)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:116)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:146)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:170)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1308)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:856)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:159)
        at java.lang.Thread.run(Thread.java:829)
```

Here are some funky bits that are certainly confusing.
1) The line number is off by 1.  It says line 5, instead of line 4 as the source of the error.  This off-by-one only happens with some query strings.
2) The header on the last exception is probably confusing because of the `Namespace: where` and other potentially confusing bits.

After digging in, my current thoughts are:
a) Changing the exception output may be bad because it will deviate from vanilla python.  Also hacking the exception may lead to ugliness with exceptions on other threads.
b) Can we fix the off-by one line numbers?
c) I think we need a How-To document on decrypting the error messages since there is a lot of spam for users to dig through.

@jjbrosnan @rbasralian @margaretkennedy Thoughts?

**Comment by jjbrosnan** [comment]
I'm of the opinion that your (b) and (c) should be the priority. I personally don't find those stack traces to be too confusing, because they explicitly mention `Column "X" doesn't exist in this table`, but I'm also biased because I'm used to seeing stack traces like this. I've had other instances where the stack trace isn't as helpful.

A good how-to-guide on decrypting Deephaven errors should be a fairly high priority docs ticket.

**Comment by jmao-denver** [comment]
1. I don't see the 'line number off by 1' issue. It is 5 not 4.
2. the vanilla Python reports the exception in the order of 'traceback' then 'exception', which is clearly different from what JPY does. And the extra 'line', 'namespace', 'file' lines in the JPY output are a bit redundant as the info is mostly already contained in the traceback.

That being said, I don't disagree that we should focus on doc and education at this point.

**Comment by chipkent** [comment]
You are right.  I can't count to five, or I just remove all whitespace when counting.

**Comment by rbasralian** [comment]
fwiw I'd like us to ignore the stack trace until you expand the error, and just show a meaningful message relating to whatever DH operation actually failed, when possible (https://deephaven.atlassian.net/browse/DH-9512).

E.g. in this. case, instead of seeing `r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error '93f01bb6-9d02-4a41-b364-a9edfa52d0b0' java.lang.RuntimeException: Error in Python interpreter` as the top line in your console, we should just show something simple like `Error in where(): Column "X" doesn't exist in this table` until you click to expand the error

**Comment by jmao-denver** [comment]
> 

@niloc132 I think we have spoken about the same desire a while back. I remember that it might have more to do how the WebUI parse and present the output?

**Comment by jmao-denver** [comment]
> fwiw I'd like us to ignore the stack trace until you expand the error, and just show a meaningful message relating to whatever DH operation actually failed, when possible (https://deephaven.atlassian.net/browse/DH-9512).
> 
> E.g. in this. case, instead of seeing `r-Scheduler-Serial-1 | i.d.s.s.SessionState | Internal Error '93f01bb6-9d02-4a41-b364-a9edfa52d0b0' java.lang.RuntimeException: Error in Python interpreter` as the top line in your console, we should just show something simple like `Error in where(): Column "X" doesn't exist in this table` until you click to expand the error

@niloc132 I think we have spoken about the same desire a while back. I remember that it might have more to do how the WebUI parse and present the output?

**Comment by niloc132** [comment]
See also 
https://github.com/deephaven/deephaven-core/issues/788
https://github.com/deephaven/deephaven-core/issues/461

We should plan some specific work here, and break down what exactly we would like to see changed. Here's my short list, @chipkent let's chat tomorrow briefly?
 * server logs should truncate less of the thread name, and/or we should have shorter thread names
 * Messages sent to the web console should probably follow a different format
 * ExecuteCommand calls should not wrap in "Internal Error", but should be directly logged when it goes to the web UI, and emitted as a grpc error without an extra error log. I suspect strongly diminishing returns here...
 * Change the ExecuteCommand proto message to include a stack trace structure, so the UI can expand/collapse sections of the error.

**Comment by chipkent** [comment]
While documenting how to interpret python exceptions, some of our error shortcomings became very clear.  See the TODOs in https://github.com/deephaven/deephaven.io/actions/runs/3743021739/jobs/6354695170.

Key areas for improvement:
1. Errors that occur during real-time updates are not helpful.  They have lost too much information.  See the `AsyncClientErrorNotifier` error in the `Exceptions in Deephaven tables` section of the document.  A few notes:  there is no unique ID, there is no query string, there is no stack for when the query was created, etc.  Given the existing info, it is impossible to locate the root cause if the program has any complexity.  This problem can also be seen in the `One more complex example` section.
2. Python query strings are output in their transformed form, which makes it impossible to grep for the query string in your code.  e.g. `Y = (new io.deephaven.engine.util.PyCallableWrapper(math.getAttribute("sqrt"))).call(X)` instead of `Y = math.sqrt(X)`.  See the `One more complex example` in the PR. 
3. Errors give no information about the position of the clause in the statement.  For example, knowing that the failure is in the 4th arg of `t.update(["X=i","Y=sqrt(X)","X=-i","Y=sqrt(X)"])` would be very helpful.  Complex queries tend to end up with mess like this.

**Comment by chipkent** [comment]
https://peps.python.org/pep-0657/

**Comment by chipkent** [comment]
From @rcaudy:
"Some of that is going to take a lot more descriptive instrumentation in the query DAG. We’ve talked about integrating QST to do it, but it’s not that close to being feasible yet."

**Comment by devinrsmith** [comment]
I think there is potential to capture additional context, whether you are running a pre-built (jar) application, or running a script via groovy or python.

With python specifically, I imagine we could wrap all deephaven.table.Table operations with a "python stack tracebacks" ContextManager, and have the engine record that context (maybe it fits into ExecutionContext?). Upon error, the additional context could be formatted and printed out as appropriate.
