### ISSUE TITLE
ExecutionContext not registered

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2863]
Is this a problem in my code or in Deephaven?  My code should only be operating on static data, and I should have auto-locking enabled.

(sorry for the formatting. I pulled this from GCP logs.)
```
2022-09-16 03:01:05.129 MDTTraceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/deephaven/table.py", line 374, in update return Table(j_table=self.j_table.update(*formulas)) RuntimeError: io.deephaven.engine.table.impl.select.FormulaCompilationException: Formula compilation error for: `SHARADAR`
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:205)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.select.SwitchColumn.initDef(SwitchColumn.java:66)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:78)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:49)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$33(QueryTable.java:1247)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:518)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$34(QueryTable.java:1232)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3091)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1231)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1211)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:88)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.UncoalescedTable.update(UncoalescedTable.java:239)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.engine.table.impl.UncoalescedTable.update(UncoalescedTable.java:34)
Error
2022-09-16 03:01:05.129 MDT at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:105)
Error
2022-09-16 03:01:05.129 MDTcaused by io.deephaven.util.NoExecutionContextRegisteredException: ExecutionContext not registered at io.deephaven.engine.context.PoisonedQueryScope.fail(PoisonedQueryScope.java:20) at io.deephaven.engine.context.PoisonedQueryScope.getParamNames(PoisonedQueryScope.java:25) at io.deephaven.engine.table.impl.select.codegen.FormulaAnalyzer.getCompiledFormula(FormulaAnalyzer.java:97) at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:190) ... 13 more
```

**Comment by chipkent** [comment]
I might have messed the query up, but I am not sure what the whole No Execution Context message is trying to say.  Also, because of #2862, I can't easily figure out where I might have messed my query up.

**Comment by nbauernfeind** [comment]
This is being called in a deferred context but you did not create an execution context.
```python
    return Table(j_table=self.j_table.update(*formulas))
```

Execution context is not yet wrapped in python helpers. See the documentation for what builder methods are appropriate for your use case.

Documentation: https://deephaven.io/core/javadoc/io/deephaven/engine/context/ExecutionContext.Builder.html

Here is a test that re-enables exactly the old behavior:
```python
    def test_nested_scopes(self):
        _JExecutionContext = jpy.get_type("io.deephaven.engine.context.ExecutionContext")
        context = (_JExecutionContext.newBuilder()
                   .captureQueryCompiler()
                   .captureQueryLibrary()
                   .captureQueryScope()
                   .build())

        def inner_func(p) -> str:
            openContext = context.open()
            t = empty_table(1).update("X = p * 10")
            openContext.close()
            return t.to_string().split()[2]

        t = empty_table(1).update("X = i").update("TableString = inner_func(X + 10)")
        self.assertIn("100", t.to_string())
```

**Comment by jmao-denver** [comment]
```
    def test_scope_multi_threads(self):
        thread_results = []

        def thread_update(t: Table, i: int) -> Table:
            t2 = t.update("X = i*i")
            thread_results.append(t2.to_string())

        threads = []
        for i in range(1):
            threads.append(threading.Thread(target=thread_update, args=(empty_table(1), i)))

        for th in threads:
            th.start()
            th.join()

        self.assertTrue(thread_results)
        for i, rlt in enumerate(thread_results):
            self.assertIn(i * i, rlt)
```
@nbauernfeind I added this test case and it failed exactly the same way.

**Comment by nbauernfeind** [comment]
The execution context is stored as a thread local. By default it is poisoned to prevent users from experiencing unintended side effects. It prevents things like variables used in the query scope changing before a formula has the opportunity to initialize their values.

A new thread is a form of deferred context. It requires the user to consider what kind of ExecutionContext they actually want for their use case. This choice is intentional.

**Comment by jmao-denver** [comment]
> The execution context is stored as a thread local. By default it is poisoned to prevent users from experiencing unintended side effects. It prevents things like variables used in the query scope changing before a formula has the opportunity to initialize their values.
> 
> A new thread is a form of deferred context. It requires the user to consider what kind of ExecutionContext they actually want for their use case. This choice is intentional.

Would it make sense for us to check if a query scope is installed on the thread before we drop to the poisonous EC but instead if one is there, we should create a EC on the fly with it?

**Comment by nbauernfeind** [comment]
If you must do something to make it easier for the user, then you need to wrap the creation of new threads so that you can open the context as soon as the thread starts.

**Comment by jmao-denver** [comment]
> If you must do something to make it easier for the user, then you need to wrap the creation of new threads so that you can open the context as soon as the thread starts.

Wrapping the creation of threads isn't very appealing, hard to pull off and is brittle. But we could in the Table operation methods that require an EC (e.g update), check if an EC is installed already, and if not, build one for the operation. Is this something you think is achievable?

**Comment by nbauernfeind** [comment]
If you have access to the script session then you can open the `ExecutionContext` that it owns. There is no convenient way to tell if the current execution context is the poisoned context. Why is it not ok for the user to open a context at the start of their new thread?

**Comment by jmao-denver** [comment]
> If you have access to the script session then you can open the `ExecutionContext` that it owns. There is no convenient way to tell if the current execution context is the poisoned context. Why is it not ok for the user to open a context at the start of their new thread?

Because performing table operations in the main thread doesn't require that, it is definitely an 'unnecessary' mental challenge for a user to have to remember to do that in any other threads.

**Comment by chipkent** [comment]
I agree that the mental hurdle should be as low as possible -- ideally zero.

**Comment by rcaudy** [comment]
This is hardly the only different thing for users to consider when starting their own threads, although UGP auto-locking obfuscates one of of the key differences - which is good, except when it's very, very bad.

There really is no way for us to correctly determine the right context to install if you don't wrap thread creation, which is inadvisable for other reasons.

If users are launching their own threads, they are leaving the "simple" environment we set up for them. I think it's better to require some education than to potentially do the wrong thing.

**Comment by nbauernfeind** [comment]
Closing per our slack conversation. Improvements were made in #2867.
