### ISSUE TITLE
EnsureCapacity validation safety error in static natural join / exact join state manager when used with ticking LHS

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#2868]
User image for the error encountered:
![e2](https://user-images.githubusercontent.com/5342661/190949068-441bb23c-dbcd-4211-bec1-071cefdb92b8.png)

Further details:
LHS is a ticking table read from Kafka
RHS is a static table

**Comment by rcaudy** [comment]
Implementation notes:
1. Natural join and exact join are the same operation, exact join just has extra validation.
2. We use the “static” join hash table implementation any time the RHS is static, unless we hit particular optimization paths.

In this case, LHS is refreshing, RHS is static. We can safely claim that if there is no RHS value for a given LHS value after initialization, there never will be. We thus only need to keep track of which LHS values match actual RHS values, not RHS values that might come into existence later.

I've asked the user for a more complete stack trace, if you have one available. My working theory is that  we’re allocating a tiny hash table due to a tiny RHS, and then overzealously assuming the worst case outcome when hashing the LHS in. I’ll attempt to reproduce this in the morning.

**Comment by rcaudy** [comment]
Super straightforward Groovy reproducer:
```
rhs = emptyTable(100000).update("II=ii")
lhs = emptyTable(2).update("II=ii", "A=(char)ii")
lhs.setRefreshing(true)
j = lhs.naturalJoin(rhs, "II")
```

Exception:
```
java.lang.IllegalStateException: Static naturalJoin does not permit rehashing, table must be allocated with sufficient size at the beginning of initialization.
        at io.deephaven.engine.table.impl.naturaljoin.StaticNaturalJoinStateManagerTypedBase.buildTable(StaticNaturalJoinStateManagerTypedBase.java:187)
        at io.deephaven.engine.table.impl.naturaljoin.StaticNaturalJoinStateManagerTypedBase.buildFromRightSide(StaticNaturalJoinStateManagerTypedBase.java:141)
        at io.deephaven.engine.table.impl.NaturalJoinHelper.naturalJoinInternal(NaturalJoinHelper.java:265)
        at io.deephaven.engine.table.impl.NaturalJoinHelper.naturalJoin(NaturalJoinHelper.java:44)
        at io.deephaven.engine.table.impl.NaturalJoinHelper.naturalJoin(NaturalJoinHelper.java:37)
        at io.deephaven.engine.table.impl.QueryTable.naturalJoinInternal(QueryTable.java:1767)
        at io.deephaven.engine.table.impl.QueryTable.lambda$naturalJoin$45(QueryTable.java:1758)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:445)
        at io.deephaven.engine.table.impl.QueryTable.naturalJoin(QueryTable.java:1756)
        at io.deephaven.engine.table.impl.TableDefaults.naturalJoin(TableDefaults.java:432)
        at io.deephaven.engine.table.impl.TableDefaults.naturalJoin(TableDefaults.java:34)
        at io.deephaven.api.TableOperationsDefaults.naturalJoin(TableOperationsDefaults.java:128)
        at io.deephaven.api.TableOperationsDefaults$naturalJoin.call(null:-1)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
        at io.deephaven.dynamic.Script_10.run(Script_10.groovy:43)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
        at io.deephaven.engine.util.GroovyDeephavenSession.evaluateCommand(GroovyDeephavenSession.java:206)
        at io.deephaven.engine.util.GroovyDeephavenSession.lambda$evaluate$0(GroovyDeephavenSession.java:228)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:49)
        at io.deephaven.engine.util.GroovyDeephavenSession.evaluate(GroovyDeephavenSession.java:228)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:144)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:117)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:128)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:116)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:144)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:170)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1342)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:879)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:156)
        at java.lang.Thread.run(Thread.java:829)
```
