### ISSUE TITLE
Table.snapshot on a static table using liveness incorrectly

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#2888]
```
 | Internal Error '056d44b8-2d86-4af4-8b10-f9eb3c647f0d' io.deephaven.engine.liveness.LivenessStateException: SnapshotInternalListener-snapshot [instrument_token, exchange_token, tradingsymbol, name, last_price, expiry, strike, tick_size, lot_size, instrument_type, segment, exchange] failed to add QueryTable-626412271, because either this manager or referent is no longer live
        at io.deephaven.engine.liveness.LivenessManager.manage(LivenessManager.java:23)
        at io.deephaven.engine.table.impl.snapshot.SnapshotInternalListener.<init>(SnapshotInternalListener.java:51)
        at io.deephaven.engine.table.impl.QueryTable.snapshotInternal(QueryTable.java:2062)
        at io.deephaven.engine.table.impl.QueryTable.lambda$snapshot$61(QueryTable.java:2009)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:518)
        at io.deephaven.engine.table.impl.QueryTable.snapshot(QueryTable.java:1999)
        at io.deephaven.engine.table.impl.QueryTable.snapshot(QueryTable.java:88)
        at io.deephaven.server.table.ops.SnapshotTableGrpcImpl.lambda$create$1(SnapshotTableGrpcImpl.java:63)
        at io.deephaven.server.table.ops.SnapshotTableGrpcImpl.create(SnapshotTableGrpcImpl.java:67)
        at io.deephaven.server.table.ops.SnapshotTableGrpcImpl.create(SnapshotTableGrpcImpl.java:25)
        at io.deephaven.server.table.TableServiceGrpcImpl.lambda$oneShotOperationWrapper$13(TableServiceGrpcImpl.java:400)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:856)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:156)
        at java.lang.Thread.run(Thread.java:833)
```

**Comment by rcaudy** [comment]
Groovy reproducer:
```
c = io.deephaven.engine.liveness.LivenessScopeStack.open()
t=emptyTable(100).update("II=ii")
r=t.select("JJ=II")
c.close()
s=t.snapshot(r, "II")
```

I'm not sure how the user was able to get their input table into a state like this, unless they were intentionally working with liveness scoping.
