### ISSUE TITLE
`partition_by.proxy` table operations do not properly chain 

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2889]
`partition_by().proxy().update()` fails when variables are used in later update clauses.  I suspect this may also be a problem with some other operations.  This behavior is inconsistent with our other table operations and is very inconvenient.

```python
from deephaven import time_table
from deephaven.updateby import ema_time_decay

t1 = time_table("00:00:01").update(["Label = ii%2", "X = ii%2 == 0 ? cos(0.1*ii) : sin(0.01*ii)"])

t2 = t1.partition_by(["Label"]).proxy() \
    .update(["Data=X_.subVector(ii-14,ii)", "H=max(Data)", "L=min(Data)", "ATR=max(H-L, abs(H-X), abs(L-X))"]) \
    .drop_columns("Data") \
    .merge()
```

```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error 'a40ae275-6647-40f8-9bb4-d9789b546b26' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: update operation on the PartitionedTableProxy failed. : Cannot find variable or class Data
Traceback (most recent call last):
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 2130, in update
    return PartitionedTableProxy(j_pt_proxy=self.j_pt_proxy.update(*formulas))
RuntimeError: io.deephaven.engine.table.impl.select.FormulaCompilationException: Formula compilation error for: max(Data)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:205)
	at io.deephaven.engine.table.impl.select.SwitchColumn.initDef(SwitchColumn.java:66)
	at io.deephaven.engine.table.impl.partitioned.PartitionedTableProxyImpl.toSelectColumns(PartitionedTableProxyImpl.java:437)
	at io.deephaven.engine.table.impl.partitioned.PartitionedTableProxyImpl.update(PartitionedTableProxyImpl.java:456)
	at io.deephaven.engine.table.impl.partitioned.PartitionedTableProxyImpl.update(PartitionedTableProxyImpl.java:39)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:105)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:185)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:49)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:184)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:146)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:117)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:128)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:116)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:146)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:170)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1308)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:856)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:159)
	at java.base/java.lang.Thread.run(Thread.java:829)
caused by io.deephaven.engine.table.impl.lang.QueryLanguageParser$QueryLanguageParseException: 

Having trouble with the following expression:
Full expression           : max(Data)
Expression having trouble : io.deephaven.engine.table.impl.lang.QueryLanguageParser$VisitArgs@5d7748d
Exception message         : Cannot find variable or class Data

	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.visit(QueryLanguageParser.java:978)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.visit(QueryLanguageParser.java:41)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:79)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.printArguments(QueryLanguageParser.java:285)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.visit(QueryLanguageParser.java:1680)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.visit(QueryLanguageParser.java:41)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.<init>(QueryLanguageParser.java:132)
	at io.deephaven.engine.table.impl.lang.QueryLanguageParser.<init>(QueryLanguageParser.java:85)
	at io.deephaven.engine.table.impl.select.codegen.FormulaAnalyzer.getCompiledFormula(FormulaAnalyzer.java:131)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:190)
	... 27 more


Line: 2132
Namespace: update
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 2132, in update

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
        at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:185)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:49)
        at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:184)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:146)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:117)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:128)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:116)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:146)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:170)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1308)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:856)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:159)
        at java.lang.Thread.run(Thread.java:829)
```

If all of the updates are separated, the query can be made to work:
```python
from deephaven import time_table
from deephaven.updateby import ema_time_decay

t1 = time_table("00:00:01").update(["Label = ii%2", "X = ii%2 == 0 ? cos(0.1*ii) : sin(0.01*ii)"])

t2 = t1.partition_by(["Label"]).proxy() \
    .update(["Data=X_.subVector(ii-14,ii)"]) \
    .update(["H=max(Data)"]) \
    .update(["L=min(Data)"]) \
    .update(["ATR=max(H-L, abs(H-X), abs(L-X))"]) \
    .target \
    .merge() \
    .drop_columns("Data")
```

**Comment by rcaudy** [comment]
This is likely a result of the change to formula initialization in order to make ExecutionContext recording unnecessary for proxied ops.
