### ISSUE TITLE
NullPointerException in `natural_join`

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2897]
The query looks like:
```python
    rst = rst \
        .join(dates_downsampled, joins="date") \
        .natural_join(raw, on=["date", "Sym1=symbol"], joins=f"Change1={col_ret}") \
        .natural_join(raw, on=["date", "Sym2=symbol"], joins=f"Change2={col_ret}") \
```

```
2022-09-22 07:44:59.653 MDTDeephaven Version: 0.16.1
Error
2022-09-22 07:44:59.655 MDTTraceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/deephaven/table.py", line 757, in natural_join table.j_table, ",".join(on), ",".join(joins) RuntimeError: java.lang.NullPointerException
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.sources.AbstractLongArraySource.set(AbstractLongArraySource.java:57)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.by.typed.staticopen.gen.cm22093324970514590v55_0.StaticNaturalJoinHasherObjectObject.decorateLeftSide(StaticNaturalJoinHasherObjectObject.java:124)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.naturaljoin.StaticNaturalJoinStateManagerTypedBase$LeftProbeHandler.doProbe(StaticNaturalJoinStateManagerTypedBase.java:117)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.naturaljoin.StaticNaturalJoinStateManagerTypedBase.probeTable(StaticNaturalJoinStateManagerTypedBase.java:219)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.naturaljoin.StaticNaturalJoinStateManagerTypedBase.decorateLeftSide(StaticNaturalJoinStateManagerTypedBase.java:153)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.NaturalJoinHelper.naturalJoinInternal(NaturalJoinHelper.java:266)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.NaturalJoinHelper.naturalJoin(NaturalJoinHelper.java:44)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.NaturalJoinHelper.naturalJoin(NaturalJoinHelper.java:37)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.QueryTable.naturalJoinInternal(QueryTable.java:1767)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.QueryTable.lambda$naturalJoin$45(QueryTable.java:1758)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:445)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.QueryTable.naturalJoin(QueryTable.java:1756)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.TableDefaults.naturalJoin(TableDefaults.java:433)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.TableDefaults.naturalJoin(TableDefaults.java:34)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.api.TableOperationsDefaults.naturalJoin(TableOperationsDefaults.java:133)
2022-09-22 07:44:59.655 MDT{}
Error
2022-09-22 07:44:59.655 MDT{}
2022-09-22 07:44:59.655 MDTThe above exception was the direct cause of the following exception:
Error
2022-09-22 07:44:59.655 MDT{}
2022-09-22 07:44:59.655 MDTTraceback (most recent call last): File "/scripts/downloader.py", line 54, in <module> data_source_pairs=data_source_pairs) File "/usr/local/lib/python3.7/site-packages/cecropia/pairs/selection.py", line 106, in pairs_correlations .natural_join(raw, on=["date", "Sym1=symbol"], joins=f"Change1={col_ret}") \ File "/usr/local/lib/python3.7/site-packages/deephaven/table.py", line 765, in natural_join raise DHError(e, "table natural_join operation failed.") from e deephaven.dherror.DHError: table natural_join operation failed. : RuntimeError: java.lang.NullPointerException
Error
2022-09-22 07:44:59.655 MDTTraceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/deephaven/table.py", line 757, in natural_join table.j_table, ",".join(on), ",".join(joins) RuntimeError: java.lang.NullPointerException
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.sources.AbstractLongArraySource.set(AbstractLongArraySource.java:57)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.by.typed.staticopen.gen.cm22093324970514590v55_0.StaticNaturalJoinHasherObjectObject.decorateLeftSide(StaticNaturalJoinHasherObjectObject.java:124)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.naturaljoin.StaticNaturalJoinStateManagerTypedBase$LeftProbeHandler.doProbe(StaticNaturalJoinStateManagerTypedBase.java:117)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.naturaljoin.StaticNaturalJoinStateManagerTypedBase.probeTable(StaticNaturalJoinStateManagerTypedBase.java:219)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.naturaljoin.StaticNaturalJoinStateManagerTypedBase.decorateLeftSide(StaticNaturalJoinStateManagerTypedBase.java:153)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.NaturalJoinHelper.naturalJoinInternal(NaturalJoinHelper.java:266)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.NaturalJoinHelper.naturalJoin(NaturalJoinHelper.java:44)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.NaturalJoinHelper.naturalJoin(NaturalJoinHelper.java:37)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.QueryTable.naturalJoinInternal(QueryTable.java:1767)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.QueryTable.lambda$naturalJoin$45(QueryTable.java:1758)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:445)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.QueryTable.naturalJoin(QueryTable.java:1756)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.TableDefaults.naturalJoin(TableDefaults.java:433)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.engine.table.impl.TableDefaults.naturalJoin(TableDefaults.java:34)
Error
2022-09-22 07:44:59.655 MDT at io.deephaven.api.TableOperationsDefaults.naturalJoin(TableOperationsDefaults.java:133)
```

**Comment by rcaudy** [comment]
This is in decorating from the left after building from the right with a static RHS and a LHS that is either ticking or bigger than RHS.
We *just* fixed a bug here wherein we were sizing the hash table improperly. Maybe we have a new and exciting ensure capacity bug exposed by the prior fix?

**Comment by rcaudy** [comment]
It looks to me like `io.deephaven.engine.table.impl.naturaljoin.StaticNaturalJoinStateManagerTypedBase.LeftProbeHandler#doProbe` handles this correctly. Still digging.

**Comment by rcaudy** [comment]
@chipkent I'm going to need more help from you to reproduce this:
1. Were both sides static, or just the RHS?
2. How big are the tables?
3. How many unique key values were there?
4. What were the types of the key columns? It looks like 2 `Object` columns to me, from the stack trace.
5. Was there a pattern to how the keys were distributed?

Ideally, you could give me a script that reproduces this.

**Comment by chipkent** [comment]
@rcaudy After a few hours of messing with it, I have created a compact reproducer.  The input files are large and proprietary.  Talk to me tomorrow, and we can figure out how to get them to you.

```python

from deephaven import parquet

diff_days = 4
col_ret = f"return_split_div_adj_{diff_days}d"

raw_filename = "/nfs/data/quandl/2022-09-22/DEBUG_RAW.parquet"
dbg1_filename = "/nfs/data/quandl/2022-09-22/DEBUG_DBG1.parquet"

raw = parquet.read(path=raw_filename)
dbg1 = parquet.read(path=dbg1_filename)

#dbg1.size = 3787803476
#raw.size = 40610683

rst = dbg1 \
    .natural_join(raw, on=["date", "Sym1=symbol"], joins=f"Change1={col_ret}") \
    .natural_join(raw, on=["date", "Sym2=symbol"], joins=f"Change2={col_ret}") 
```

**Comment by rcaudy** [comment]
This is an `int` overflow issue when dealing with static RHS + large LHS.
