### ISSUE TITLE
Assertion failed: asserted Could not find existing state for removed left row is never executed

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2919]
Exception when trying to use `deephaven-ib`.

```python
from typing import Dict

from deephaven.time import to_datetime
from ibapi.contract import Contract
from ibapi.order import Order

import deephaven_ib as dhib
from deephaven.updateby import ema_time_decay
from deephaven import time_table
from deephaven.plot import Figure


###########################################################################
# WARNING: THIS SCRIPT EXECUTES TRADES!! ONLY USE ON PAPER TRADING ACCOUNTS
###########################################################################

print("==============================================================================================================")
print("==== Create a client and connect.")
print("==== ** Accept the connection in TWS **")
print("==============================================================================================================")

client = dhib.IbSessionTws(host="host.docker.internal", port=7497, client_id=0, download_short_rates=False, read_only=False)
print(f"IsConnected: {client.is_connected()}")

client.connect()
print(f"IsConnected: {client.is_connected()}")

## Setup

account = "DU4943848"
ticks_bid_ask = client.tables["ticks_bid_ask"]
orders_submitted = client.tables["orders_submitted"]
orders_status = client.tables["orders_status"]
positions = client.tables["accounts_positions"].where("Account = account")

print("==============================================================================================================")
print("==== Request data.")
print("==============================================================================================================")

registered_contracts = {}

def add_contract(symbol):

    contract = Contract()
    contract.symbol = symbol
    contract.secType = "STK"
    contract.currency = "USD"
    contract.exchange = "SMART"

    rc = client.get_registered_contract(contract)
    id = rc.contract_details[0].contract.conId
    registered_contracts[id] = rc
    client.request_tick_data_realtime(rc, dhib.TickDataType.BID_ASK)
    print(f"Registered contract: id={id} rc={rc}")

add_contract("GOOG")

print("==============================================================================================================")
print("==== Compute predictions.")
print("==============================================================================================================")

preds = ticks_bid_ask \
    .update_view(["MidPrice=0.5*(BidPrice+AskPrice)", "MidPrice2=MidPrice*MidPrice"]) \
    .update_by([ema_time_decay("Timestamp", "00:02:00", ["PredPrice=MidPrice","MidPrice2Bar=MidPrice2"])], by="Symbol") \
    .view(["ReceiveTime", "Timestamp", "ContractId", "Symbol", "BidPrice", "AskPrice", "MidPrice", "PredPrice", "PredSD = sqrt(MidPrice2Bar-PredPrice*PredPrice)", "PredLow=PredPrice-PredSD", "PredHigh=PredPrice+PredSD"])

#TODO: make it a oneclick
preds_plot = Figure() \
    .plot_xy("BidPrice", t=preds, x="Timestamp", y="BidPrice") \
    .plot_xy("AskPrice", t=preds, x="Timestamp", y="AskPrice") \
    .plot_xy("MidPrice", t=preds, x="Timestamp", y="MidPrice") \
    .plot_xy("PredPrice", t=preds, x="Timestamp", y="PredPrice") \
    .plot_xy("PredLow", t=preds, x="Timestamp", y="PredLow") \
    .plot_xy("PredHigh", t=preds, x="Timestamp", y="PredHigh") \
    .show()

print("==============================================================================================================")
print("==== Generate orders.")
print("==============================================================================================================")

open_orders = {}

def update_orders(contract_id: int, pred_low: float, pred_high: float, buy_order: bool, sell_order:bool) -> int:

    if contract_id in open_orders:
        for order in open_orders[contract_id]:
            order.cancel()

    new_orders = []
    rc = registered_contracts[contract_id]

    if sell_order:
        order_sell = Order()
        order_sell.account = account
        order_sell.action = "SELL"
        order_sell.orderType = "LIMIT"
        order_sell.totalQuantity = 100
        order_sell.lmtPrice = pred_high

        print(f"Placing sell order: {rc} {order_sell}")
        order = client.order_place(rc, order_sell)
        new_orders.append(order)

    if buy_order:
        order_buy = Order()
        order_buy.account = account
        order_buy.action = "BUY"
        order_buy.orderType = "LIMIT"
        order_buy.totalQuantity = 100
        order_buy.lmtPrice = pred_low

        print(f"Placing buy order: {rc} {order_buy}")
        order = client.order_place(rc, order_buy)
        new_orders.append(order)

    open_orders[contract_id] = new_orders
    return len(new_orders)


orders = time_table("00:01:00") \
    .rename_columns("SnapTime=Timestamp") \
    .snapshot(preds.last_by(["Symbol"])) \
    .natural_join(positions, on="ContractId", joins="Position") \
    .update_view([
        "PositionDollars = Position * MidPrice",
        "MaxPositionDollars = 5000.0",
        "BuyOrder = PositionDollars < MaxPositionDollars",
        "SellOrder = PositionDollars > -MaxPositionDollars",
    ]) \
    .update("NumNewOrders = (long)update_orders(ContractId, PredLow, PredHigh, BuyOrder, SellOrder)")



# print("==============================================================================================================")
# print("==== Make all tables visible in the UI.")
# print("==============================================================================================================")
#
# for k, v in client.tables_raw.items():
#     globals()[k] = v
#
# for k, v in client.tables.items():
#     globals()[k] = v

```

```
EFAULT.refreshThread | i.d.e.t.i.MergedListener  | 1007398524 naturalJoin([ContractId], [Position]) Merged Listener: Uncaught exception for entry= PerformanceEntry{, id=145, evaluationNumber=20, operationNumber=4, description='naturalJoin([ContractId], [Position])', callerLine='PyLib.java:-2', intervalUsageNanos=3147100, intervalCpuNanos=3144689, intervalUserCpuNanos=10000000, intervalInvocationCount=1, intervalAdded=1, intervalRemoved=0, intervalModified=1, intervalShifted=0, intervalAllocatedBytes=-9223372036854775808, intervalPoolAllocatedBytes=-9223372036854775808, maxTotalMemory=417333248, minFreeMemory=152216152, collections=0, collectionTimeNanos=0, startCpuNanos=0, startUserCpuNanos=0, startTimeNanos=0, startAllocatedBytes=0, startPoolAllocatedBytes=0}: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted Could not find existing state for removed left row is never executed.
        at io.deephaven.base.verify.Assert.fail(Assert.java:86)
        at io.deephaven.base.verify.Assert.statementNeverExecuted(Assert.java:221)
        at io.deephaven.engine.table.impl.naturaljoin.typed.incopen.gen.IncrementalNaturalJoinHasherLong.removeLeft(IncrementalNaturalJoinHasherLong.java:469)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.probeTable(IncrementalNaturalJoinStateManagerTypedBase.java:206)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.removeLeft(IncrementalNaturalJoinStateManagerTypedBase.java:548)
        at io.deephaven.engine.table.impl.NaturalJoinHelper$ChunkedMergedJoinListener.process(NaturalJoinHelper.java:964)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:258)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1292)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1453)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1171)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1116)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$10(UpdateGraphProcessor.java:1730)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:31)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1720)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1707)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1561)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$1.run(UpdateGraphProcessor.java:278)
EFAULT.refreshThread | .AsyncClientErrorNotifier | Error in table update: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted Could not find existing state for removed left row is never executed.
        at io.deephaven.base.verify.Assert.fail(Assert.java:86)
        at io.deephaven.base.verify.Assert.statementNeverExecuted(Assert.java:221)
        at io.deephaven.engine.table.impl.naturaljoin.typed.incopen.gen.IncrementalNaturalJoinHasherLong.removeLeft(IncrementalNaturalJoinHasherLong.java:469)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.probeTable(IncrementalNaturalJoinStateManagerTypedBase.java:206)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.removeLeft(IncrementalNaturalJoinStateManagerTypedBase.java:548)
        at io.deephaven.engine.table.impl.NaturalJoinHelper$ChunkedMergedJoinListener.process(NaturalJoinHelper.java:964)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:258)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1292)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1453)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1171)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1116)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$10(UpdateGraphProcessor.java:1730)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:31)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1720)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1707)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1561)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$1.run(UpdateGraphProcessor.java:278)
heduler-Concurrent-3 | i.d.s.s.SessionState      | Failed to notify listener: java.lang.IllegalStateException: Can not listen to failed table QueryTable
        at io.deephaven.engine.table.impl.BaseTable.listenForUpdates(BaseTable.java:670)
        at io.deephaven.engine.table.impl.SwapListener.subscribeForUpdates(SwapListener.java:35)
        at io.deephaven.server.table.ExportedTableUpdateListener.onNewTableExport(ExportedTableUpdateListener.java:133)
        at io.deephaven.server.table.ExportedTableUpdateListener.onNext(ExportedTableUpdateListener.java:79)
        at io.deephaven.server.table.ExportedTableUpdateListener.onNext(ExportedTableUpdateListener.java:38)
        at io.deephaven.server.session.SessionState$ExportListener.notify(SessionState.java:1068)
        at io.deephaven.server.session.SessionState$ExportObject.lambda$setState$0(SessionState.java:733)
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
        at io.deephaven.server.session.SessionState$ExportObject.setState(SessionState.java:733)
        at io.deephaven.server.session.SessionState$ExportObject.setResult(SessionState.java:932)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:856)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:156)
        at java.lang.Thread.run(Thread.java:829)
heduler-Concurrent-4 | i.d.s.s.SessionState      | Internal Error '3d0e9a3b-e9cf-49f7-903c-4e71fe544bb6' java.lang.IllegalStateException: Can not listen to failed table QueryTable
        at io.deephaven.engine.table.impl.BaseTable.listenForUpdates(BaseTable.java:670)
        at io.deephaven.engine.table.impl.SwapListener.subscribeForUpdates(SwapListener.java:35)
        at io.deephaven.engine.table.impl.QueryTable.lambda$getResultNoMemo$73(QueryTable.java:3172)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:518)
        at io.deephaven.engine.table.impl.QueryTable.getResultNoMemo(QueryTable.java:3166)
        at io.deephaven.engine.table.impl.QueryTable.lambda$getResult$71(QueryTable.java:3160)
        at io.deephaven.engine.table.impl.QueryTable$MemoizedResult.getOrCompute(QueryTable.java:3128)
        at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3095)
        at io.deephaven.engine.table.impl.QueryTable.getResult(QueryTable.java:3159)
        at io.deephaven.engine.table.impl.QueryTable.flatten(QueryTable.java:1168)
        at io.deephaven.server.table.ops.FlattenTableGrpcImpl.create(FlattenTableGrpcImpl.java:27)
        at io.deephaven.server.table.ops.FlattenTableGrpcImpl.create(FlattenTableGrpcImpl.java:15)
        at io.deephaven.server.table.TableServiceGrpcImpl$BatchExportBuilder.doExport(TableServiceGrpcImpl.java:466)
        at io.deephaven.server.table.TableServiceGrpcImpl.lambda$batch$5(TableServiceGrpcImpl.java:318)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:856)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:156)
        at java.lang.Thread.run(Thread.java:829)
```

**Comment by chipkent** [comment]
Tried a join on `Symbol`, and it also failed:

```python
orders = time_table("00:01:00") \
    .rename_columns("SnapTime=Timestamp") \
    .snapshot(preds.last_by(["Symbol"])) \
    .natural_join(positions, on="Symbol", joins="Position")
```
```
EFAULT.refreshThread | i.d.e.t.i.MergedListener  | 884292960 naturalJoin([Symbol], [Position]) Merged Listener: Uncaught exception for entry= PerformanceEntry{, id=220, evaluationNumber=124, operationNumber=3, description='naturalJoin([Symbol], [Position])', callerLine='PyLib.java:-2', intervalUsageNanos=994900, intervalCpuNanos=1050186, intervalUserCpuNanos=0, intervalInvocationCount=1, intervalAdded=1, intervalRemoved=0, intervalModified=1, intervalShifted=0, intervalAllocatedBytes=-9223372036854775808, intervalPoolAllocatedBytes=-9223372036854775808, maxTotalMemory=417333248, minFreeMemory=189430968, collections=0, collectionTimeNanos=0, startCpuNanos=0, startUserCpuNanos=0, startTimeNanos=0, startAllocatedBytes=0, startPoolAllocatedBytes=0}: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted Could not find existing state for removed left row is never executed.
        at io.deephaven.base.verify.Assert.fail(Assert.java:86)
        at io.deephaven.base.verify.Assert.statementNeverExecuted(Assert.java:221)
        at io.deephaven.engine.table.impl.naturaljoin.typed.incopen.gen.IncrementalNaturalJoinHasherObject.removeLeft(IncrementalNaturalJoinHasherObject.java:471)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.probeTable(IncrementalNaturalJoinStateManagerTypedBase.java:206)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.removeLeft(IncrementalNaturalJoinStateManagerTypedBase.java:548)
        at io.deephaven.engine.table.impl.NaturalJoinHelper$ChunkedMergedJoinListener.process(NaturalJoinHelper.java:964)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:258)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1292)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1453)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1171)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1116)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$10(UpdateGraphProcessor.java:1730)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:31)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1720)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1707)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1561)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$1.run(UpdateGraphProcessor.java:278)
EFAULT.refreshThread | .AsyncClientErrorNotifier | Error in table update: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted Could not find existing state for removed left row is never executed.
        at io.deephaven.base.verify.Assert.fail(Assert.java:86)
        at io.deephaven.base.verify.Assert.statementNeverExecuted(Assert.java:221)
        at io.deephaven.engine.table.impl.naturaljoin.typed.incopen.gen.IncrementalNaturalJoinHasherObject.removeLeft(IncrementalNaturalJoinHasherObject.java:471)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.probeTable(IncrementalNaturalJoinStateManagerTypedBase.java:206)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.removeLeft(IncrementalNaturalJoinStateManagerTypedBase.java:548)
        at io.deephaven.engine.table.impl.NaturalJoinHelper$ChunkedMergedJoinListener.process(NaturalJoinHelper.java:964)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:258)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1292)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1453)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1171)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1116)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$10(UpdateGraphProcessor.java:1730)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:31)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1720)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1707)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1561)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$1.run(UpdateGraphProcessor.java:278)
heduler-Concurrent-4 | i.d.s.s.SessionState      | Internal Error 'e044b548-2c3b-49c8-addc-34b728757337' java.lang.IllegalStateException: Can not listen to failed table QueryTable
        at io.deephaven.engine.table.impl.BaseTable.listenForUpdates(BaseTable.java:670)
        at io.deephaven.engine.table.impl.SwapListener.subscribeForUpdates(SwapListener.java:35)
        at io.deephaven.engine.table.impl.QueryTable.lambda$getResultNoMemo$73(QueryTable.java:3172)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:518)
        at io.deephaven.engine.table.impl.QueryTable.getResultNoMemo(QueryTable.java:3166)
        at io.deephaven.engine.table.impl.QueryTable.lambda$getResult$71(QueryTable.java:3160)
        at io.deephaven.engine.table.impl.QueryTable$MemoizedResult.getOrCompute(QueryTable.java:3128)
        at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3095)
        at io.deephaven.engine.table.impl.QueryTable.getResult(QueryTable.java:3159)
        at io.deephaven.engine.table.impl.QueryTable.flatten(QueryTable.java:1168)
        at io.deephaven.server.table.ops.FlattenTableGrpcImpl.create(FlattenTableGrpcImpl.java:27)
        at io.deephaven.server.table.ops.FlattenTableGrpcImpl.create(FlattenTableGrpcImpl.java:15)
        at io.deephaven.server.table.TableServiceGrpcImpl$BatchExportBuilder.doExport(TableServiceGrpcImpl.java:466)
        at io.deephaven.server.table.TableServiceGrpcImpl.lambda$batch$5(TableServiceGrpcImpl.java:318)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:856)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:156)
        at java.lang.Thread.run(Thread.java:829)
```

**Comment by chipkent** [comment]
Here is a compact reproducer: 
```python

from deephaven import time_table

preds = time_table("00:00:00.5").update(["ContractId = ii%2", "Symbol=ContractId==0 ? `A` : `B`", "Pred = 0.1*ii"])
positions = time_table("00:00:01").update(["ContractId = ii%2", "Position = 0.7*ii"])

orders = time_table("00:01:00") \
    .rename_columns("SnapTime=Timestamp") \
    .snapshot(preds.last_by(["Symbol"])) \
    .natural_join(positions, on="ContractId", joins="Position")

```

**Comment by rcaudy** [comment]
Groovy version of the above:
```
preds = timeTable("00:00:00.5").update("ContractId = ii%2", "Symbol=ContractId==0 ? `A` : `B`", "Pred = 0.1*ii")
positions = timeTable("00:00:01").update("ContractId = ii%2", "Position = 0.7*ii")

orders = timeTable("00:01:00")
    .renameColumns("SnapTime=Timestamp")
    .snapshot(preds.lastBy("Symbol"))
    .naturalJoin(positions, "ContractId", "Position")
```
