### ISSUE TITLE
Parquet compression followup

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#2920]
Some follow-up items after https://github.com/deephaven/deephaven-core/pull/2792:
- [ ] Disable/fix meaningless "Got brand-new [de]compressor" messages. `zstd`, `lzo`, and `gzip` end up logging multiple times when decompressing each table, and `zstd` and `gzip` also multiple times when compressing.  Also, one of the messages may be *wrong*: GZip read is printing the wrong message Got brand-new decompressor [.zst]
- [ ] Once we find that we can't ask the pool for a compressor, quit asking. This will somewhat mitigate the above, but also keeps us from doing the extra work of asking the pool for an instance we know we can't find (which itself requires taking the lock, etc). Specifically, if `innerCompressor` is null and the compress method ends up calling `compressionCodec.createOutputStream(os)`, we should keep track of that fact. This will specifically protect the zstd and gzip codecs from having to rediscover this for each page within each column, as well as for the dictionary for each column.
- [ ] For x86, investigate providing the native codec, which will enable the gzip codec not worry about the above case and pool its de/compressors.

**Comment by devinrsmith** [comment]
Related https://github.com/deephaven/deephaven-core/issues/2803

**Comment by devinrsmith** [comment]
Note: aircompressor seems to think that Compressor / Decompressor is never used by hadoop. Not sure if that's true, or if there are parquet cases where it needs to be used?

https://github.com/airlift/aircompressor/blob/df34962aeee829c366b7d9ae8387176c57fea33e/src/main/java/io/airlift/compress/hadoop/CodecAdapter.java#L133-L139

https://github.com/airlift/aircompressor/blob/df34962aeee829c366b7d9ae8387176c57fea33e/src/main/java/io/airlift/compress/hadoop/CodecAdapter.java#L200-L206

**Comment by devinrsmith** [comment]
Learning more about the codecs w/ my work in https://github.com/deephaven/deephaven-core/pull/3575

**Comment by devinrsmith** [comment]
Note: the lz4 support is outdated - we aren't able to read the "proper" format. See details and links that stem from
 
 https://issues.apache.org/jira/browse/PARQUET-2032
 
 ```
 java.lang.IllegalArgumentException: No enum constant org.apache.parquet.hadoop.metadata.CompressionCodecName.LZ4_RAW                                                                                                       
        at java.base/java.lang.Enum.valueOf(Enum.java:240)                                                                                                                                                                               
        at org.apache.parquet.hadoop.metadata.CompressionCodecName.valueOf(CompressionCodecName.java:26)                                                                                                                                 
        at io.deephaven.parquet.base.tempfix.ParquetMetadataConverter.fromFormatCodec(ParquetMetadataConverter.java:535)                                                                                                                 
        at io.deephaven.parquet.base.tempfix.ParquetMetadataConverter.fromParquetMetadata(ParquetMetadataConverter.java:1195)                                                                                                            
        at io.deephaven.parquet.table.location.ParquetTableLocationKey.getMetadata(ParquetTableLocationKey.java:99)                                                                                                                      
        at io.deephaven.parquet.table.ParquetTools.readTableInternal(ParquetTools.java:386)                                                                                                                                              
        at io.deephaven.parquet.table.ParquetTools.readTable(ParquetTools.java:77)
```
