### ISSUE TITLE
EPIC: Parquet Support

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#294]
Related to reading:
- I want to be able to read a single Parquet file in-situ via a simple readFile() command where I provide a file path.  I want to be able to handle “dictionary-overload” scenarios.
- I want to be able to read a sharded Parqet set -- taking advantage of the metadata provided to determine which files to actually read.
- I want to read a hierarchical set of Parquet files and take advantage of the metadata accordingly.  

Related to writing:
- I want to be able to write the same Parquet-writing capabilities inherent in PyArrows implementation.

**Comment by rcaudy** [comment]
Brainstorming further about requirements:
1. Sync-up with Paul about work he has done and maybe not merged.
2. (High-level) Research "standard" hierarchical layout formats used by other tools, and understand how this can map to partitioning, especially column partitions.
3. (High-level) Adapt `TableLocation`, `SourceTable`, and related factories to accommodate formats found in #1.
4. (Low-level) Continue researching the variety of formats for complex, repeating, and dictionary fields, design a complete mapping solution.
5. (Low-level) Implement the mapping solution, possibly with multiple tickets.
6. (High-level) Infer grouping information from #1.

**Comment by rcaudy** [comment]
Note that the following linked issues are on the backlog and are *not* intended to keep this epic from completing:
* #806
* #867
* #871
* #877

We *do* intend to close the following open issues as part of this epic:
* #878
* #857
* #866
* #723

**Comment by rcaudy** [comment]
I have entered a number of backlog tickets for future work. Will plan to close out this epic when support for multiple row groups and metadata-driven hierarchy land in main.

Note that our reading capabilities should allow us to look at most parquet files, as long as they don't have repetition or definition levels greater than one. We lack some performance optimizations we'd like to add in the future, especially predicate pushdown.

Our writing capabilities are more primitive, without statistics or any helpers for hierarchical partitioning or metadata files. That said, we guarantee that we can faithfully read back anything we write, and we have APIs for bulk-writing multiple files that can easily be used to implement partitioning.

This epic has also allowed us to migrate table definitions to a far simpler format that does not dictate encoding, and as such we can expect a much easier path to integration for future columnar data sources.

**Comment by rcaudy** [comment]
At this stage, I'm keeping this epic open only for a bit more testing under #723 . I noted one NPE, which I want to check into (maybe truncated input file):
```
java.lang.NullPointerException: null
        at io.deephaven.parquet.ColumnChunkReaderImpl$ColumnPageReaderIteratorImpl.next(ColumnChunkReaderImpl.java:197)
        at io.deephaven.parquet.ColumnChunkReaderImpl$ColumnPageReaderIteratorImpl.next(ColumnChunkReaderImpl.java:164)
        at io.deephaven.db.v2.locations.parquet.VariablePageSizeColumnChunkPageStore.extendOnePage(VariablePageSizeColumnChunkPageStore.java:59)
        at io.deephaven.db.v2.locations.parquet.VariablePageSizeColumnChunkPageStore.fillToRow(VariablePageSizeColumnChunkPageStore.java:94)
        at io.deephaven.db.v2.locations.parquet.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:141)
        at io.deephaven.db.v2.locations.parquet.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:17)
        at io.deephaven.db.v2.sources.chunk.page.PageStore.fillChunk(PageStore.java:67)
        at io.deephaven.db.v2.sources.regioned.ParquetColumnRegionBase.fillChunk(ParquetColumnRegionBase.java:42)
        at io.deephaven.db.v2.sources.regioned.DeferredColumnRegionBase.fillChunk(DeferredColumnRegionBase.java:66)
        at io.deephaven.db.v2.sources.chunk.page.PageStore.fillChunk(PageStore.java:71)
        at io.deephaven.db.v2.sources.regioned.RegionedColumnSourceBase.fillChunk(RegionedColumnSourceBase.java:44)
        at io.deephaven.db.v2.sources.regioned.RegionedColumnSourceObject$AsValues.fillChunk(RegionedColumnSourceObject.java:32)
        at io.deephaven.db.v2.remote.ConstructSnapshot.getSnapshotDataAsChunk(ConstructSnapshot.java:1365)
        at io.deephaven.db.v2.remote.ConstructSnapshot.serializeAllTable(ConstructSnapshot.java:1285)
        at io.deephaven.db.v2.remote.ConstructSnapshot.lambda$constructBackplaneSnapshotInPositionSpace$2(ConstructSnapshot.java:575)
        at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1045)
        at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:977)
        at io.deephaven.db.v2.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:578)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:1524)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:926)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer.access$1400(BarrageMessageProducer.java:89)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:790)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by rcaudy** [comment]
All done with the MVP goals.
