### ISSUE TITLE
Internal error "call already cancelled" 

### ISSUE THREAD

**Issue by kosak** [deephaven/deephaven-core#2972]
When subscribing to updates from a "busy" table with the C++ client, the Web console shows the Internal Error shown below.

Note that this Internal error is *not* fatal to the server or the C++ client; it seems like things continue to operate just fine. But the message seems like a bug (I'm assuming a server bug, not a client bug)... and ideally we'd prefer to record our demo video without this Internal Error showing up.

Repro steps:

Running server code at commit `a65a9e6015d30fbe79b1ac103f16b1a7a1abec0d`
(Commit is from Nate's PR https://github.com/deephaven/deephaven-core/pull/2942 )

Query (running in Web Console)
```
demo3 = time_table("00:00:00.000001").update_view(["IntValue = (long)(Math.random() * 1000)"]).tail(3000000)
```

I subscribe to the table with the C++ client. "Immediately" I see the below exception reported in the Web Console. (As mentioned above, this exception does *not* seem fatal to the client or server, as they both keep going).

I can provide a runnable copy of the C++ client in a VM if it helps.

```
heduler-Concurrent-3 | i.d.s.s.SessionState      | Internal Error '86ef9d8a-658e-47f7-91b5-ce2ebbb85ad9' io.grpc.StatusRuntimeException: CANCELLED: call already cancelled. Use ServerCallStreamObserver.setOnCancelHandler() to disable this exception
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:366)
        at io.deephaven.server.barrage.BarrageStreamGenerator.processBatches(BarrageStreamGenerator.java:772)
        at io.deephaven.server.barrage.BarrageStreamGenerator$SnapshotView.forEachStream(BarrageStreamGenerator.java:519)
        at io.deephaven.server.arrow.ArrowModule$1.onNext(ArrowModule.java:46)
        at io.deephaven.server.arrow.ArrowModule$1.onNext(ArrowModule.java:41)
        at io.deephaven.server.arrow.ArrowFlightUtil.createAndSendSnapshot(ArrowFlightUtil.java:247)
        at io.deephaven.server.arrow.ArrowFlightUtil.lambda$DoGetCustom$0(ArrowFlightUtil.java:116)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1342)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:879)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:161)
        at java.lang.Thread.run(Thread.java:829)
```

**Comment by nbauernfeind** [comment]
This was due to the C++ client using a DoGet to request the Schema. The C++ client now calls the flight method to fetch the schema.
