### ISSUE TITLE
UGP lock error when trying to use `time_table` with an `.update` call when using Deephaven as a library

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#2996]
**Description**

When you launch Deephaven as a library, you get an error when trying to add an `update` on a `time_table`.

**Steps to reproduce**
1. Launch a python console with `deephaven_server` installed (run `python` from the command line)
2. Start up the server:
```
from deephaven_server import Server
s = Server(port=8080)
s.start()
```
3. Create a `time_table` with an `.update`:
```
from deephaven import time_table
tt = time_table("00:00:01").update("x=i")
```

**Expected results**

The table is created and no error is output

**Actual results**

An error is outputted, table does not get created:
```
Traceback (most recent call last):
  File "/private/tmp/jupyter/lib/python3.9/site-packages/deephaven/table.py", line 382, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: java.lang.IllegalStateException: May not initiate table operations: UGP exclusiveLockHeld=false, sharedLockHeld=false, refreshThread=false
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.checkInitiateTableOperation(UpdateGraphProcessor.java:446)
        at io.deephaven.engine.table.impl.QueryTable.checkInitiateOperation(QueryTable.java:3312)
        at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$33(QueryTable.java:1240)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:518)
        at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$34(QueryTable.java:1239)
        at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3098)
        at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1238)
        at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1218)
        at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:88)
        at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:105)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/jupyter/lib/python3.9/site-packages/deephaven/table.py", line 384, in update
    raise DHError(e, "table update operation failed.") from e
deephaven.dherror.DHError: table update operation failed. : RuntimeError: java.lang.IllegalStateException: May not initiate table operations: UGP exclusiveLockHeld=false, sharedLockHeld=false, refreshThread=false
Traceback (most recent call last):
  File "/private/tmp/jupyter/lib/python3.9/site-packages/deephaven/table.py", line 382, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: java.lang.IllegalStateException: May not initiate table operations: UGP exclusiveLockHeld=false, sharedLockHeld=false, refreshThread=false
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.checkInitiateTableOperation(UpdateGraphProcessor.java:446)
        at io.deephaven.engine.table.impl.QueryTable.checkInitiateOperation(QueryTable.java:3312)
        at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$33(QueryTable.java:1240)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:518)
        at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$34(QueryTable.java:1239)
        at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3098)
        at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1238)
        at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1218)
        at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:88)
        at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:105)
```

**Additional details and attachments**

Was reproducible on both my Ubuntu box and macOS

**Versions**
 - Deephaven: 0.17.0
 - OS: macOS Monterey 12.6
 - Browser: Version 106.0.5249.91

**Comment by rcaudy** [comment]
Turn on auto-locking. Update requires the lock.

**Comment by rcaudy** [comment]
```
# UGP lock is automatically acquired for each query operation
from deephaven import ugp
ugp.auto_locking = True
```
