### ISSUE TITLE
Bad state with execution context and python threading

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#3013]
gist for example code: https://gist.github.com/devinrsmith/8b8180febd39ab07c1436a390126da9d#file-app-noop-example-py

Note: `websocket-client` needs to be installed.

After running the above code, notice that
1. matches_table is _not_ reversed
2. matches_stats does not show up in panel
3. running `matches_stats = matches_table.update_view(["volume=price*size"])` after executing the script causes the NOOP error below.

```
java.lang.IllegalStateException: Expected state=CREATED, actual=NOOP
        at io.deephaven.server.appmode.ApplicationServiceGrpcImpl$State.check(ApplicationServiceGrpcImpl.java:369)
        at io.deephaven.server.appmode.ApplicationServiceGrpcImpl$State.update(ApplicationServiceGrpcImpl.java:322)
        at io.deephaven.server.appmode.ApplicationServiceGrpcImpl.update(ApplicationServiceGrpcImpl.java:265)
        at io.deephaven.server.appmode.ApplicationServiceGrpcImpl.onScopeChanges(ApplicationServiceGrpcImpl.java:81)
        at io.deephaven.engine.util.AbstractScriptSession.applyDiff(AbstractScriptSession.java:128)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:150)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:170)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1342)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:879)
```

It's possible that I'm using execution context wrong, or something funky is going on w/ global / scopes.

**Comment by rcaudy** [comment]
@jmao-denver In case it's relevant, I looked at the implementation of the context in Python... we might have an issue if we tried to use it from multiple threads or in a reentrant way. I don't see that your code is doing that, though, @devinrsmith .

**Comment by devinrsmith** [comment]
This might be a race because the variable types change on a separate python thread. I added a semphore and that "fixed" things, but we should be able to better handle this from the server point of view... (likely need to thinking about scoping in a python-threaded world...).
