### ISSUE TITLE
IllegalStateException in AJ update processing

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#3080]
Community user reported a failure in update propagation for an as-of join, with the following stack trace:
```
EFAULT.refreshThread | i.d.e.t.i.MergedListener  | 620087432 aj([[option_symbol, tdate2], tdate2], [[open_interest]]) Merged Listener: Uncaught exception for entry= PerformanceEntry{, id=173, evaluationNumber=128, operationNumber=1, description='aj([[option_symbol, tdate2], tdate2], [[open_interest]])', callerLine='PyLib.java:-2', intervalUsageNanos=1367200, intervalCpuNanos=1365800, intervalUserCpuNanos=0, intervalInvocationCount=1, intervalAdded=2, intervalRemoved=0, intervalModified=0, intervalShifted=0, intervalAllocatedBytes=-9223372036854775808, intervalPoolAllocatedBytes=-9223372036854775808, maxTotalMemory=49056579584, minFreeMemory=22606806136, collections=0, collectionTimeNanos=0, startCpuNanos=0, startUserCpuNanos=0, startTimeNanos=0, startAllocatedBytes=0, startPoolAllocatedBytes=0}: java.lang.IllegalStateException: Bad state: 17, slot=18341, slotIndex=1
        at io.deephaven.engine.table.impl.asofjoin.BucketedChunkedAjMergedListener.process(BucketedChunkedAjMergedListener.java:669)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:258)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1292)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1453)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1171)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1116)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$10(UpdateGraphProcessor.java:1730)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:31)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1720)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1707)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1561)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$1.run(UpdateGraphProcessor.java:278)
```

This is on version `0.17.0`.

**Comment by rcaudy** [comment]
From the reporting user:
(https://deephavencommunity.slack.com/archives/C036HT73T43/p1668460092237839?thread_ts=1668446111.841039&cid=C036HT73T43)
>Here is my scenerio...
My parent table has live data streamed from redpanda. I have multiple rows of the same option data. I am using option_symbol and tdate2 which is today's data in yyyy-mm-dd format to join to the open_interest table. Again, this table would have multiple rows with the same option_symbol and tdate2 and I want all of them matched/joined with open_interest
open_interest only has max 1 row per option_symbol and tdate2 It could have no matches at times.
Let me know if this makes sense. I can do a hangout/huddle to show you the table structure if you need further clarification.

We should reach out once we've done a first pass at understanding the nature of the issue.

**Comment by rcaudy** [comment]
A bit more from our user:
(https://deephavencommunity.slack.com/archives/C036HT73T43/p1668465477667169?thread_ts=1668446111.841039&cid=C036HT73T43)
> I have an update for you. I can run the .aj if I remove tdate2 as the join and only keep option_symbol as the join criteria. While I am not getting errors, the join is incorrect. Just thought I would share this.

> some more update. Since the table no longer has live data streaming in (market is closed), .aj seems to be running without any errors however the join is still incorrect. Not sure why...

> Here is some info on the two tables and also my .aj line of code
```
options_agg_sec = options_agg_sec.aj(table=open_interest, on=["option_symbol", "tdate2"], joins=["open_interest"])
```

![image](https://user-images.githubusercontent.com/5342661/201824491-6f72b7d0-5d8a-49c2-8a24-2c252ed772e2.png)

![image (1)](https://user-images.githubusercontent.com/5342661/201824502-c3e2cfc1-b0a6-4dac-800b-3158ebe55156.png)
