### ISSUE TITLE
Python module methods don't work in query strings

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#3103]
**Description**

Python module methods (such as `random.randint()` and `numpy.sin()`) don't work in query strings. They do work in a function that gets called in a query string, but not directly.

**Steps to reproduce**

Build from the latest source, start a Python session, and run the following code:

```
from deephaven import empty_table
import numpy as np

t = empty_table(1).update(["X = i", "Y = np.sin(X)"])
```

**Expected results**

A table with a single row and two columns.

**Actual results**

The following error stack trace:

```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error '8f84d266-566f-4494-8177-bee599421a55' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : RuntimeError: java.lang.RuntimeException: Error compiling class io.deephaven.temp.c_99cc94d00c7495c92e45637671ea821ca5802d62aad9a280e25b64104be6b29av55_0.Formula:
Traceback (most recent call last):
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 469, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: java.lang.RuntimeException: Error compiling class io.deephaven.temp.c_99cc94d00c7495c92e45637671ea821ca5802d62aad9a280e25b64104be6b29av55_0.Formula:
/io/deephaven/temp/c_99cc94d00c7495c92e45637671ea821ca5802d62aad9a280e25b64104be6b29av55_0/Formula.java:161: error: cannot find symbol
            return doubleCast((new io.deephaven.engine.util.PythonScopeJpyImpl.CallableWrapper(np.getAttribute("sin"))).call(multiply(0.1, X)));
                                                                              ^
  symbol:   class CallableWrapper
  location: class PythonScopeJpyImpl
Note: /io/deephaven/temp/c_99cc94d00c7495c92e45637671ea821ca5802d62aad9a280e25b64104be6b29av55_0/Formula.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

	at io.deephaven.engine.context.QueryCompiler.maybeCreateClassHelper(QueryCompiler.java:708)
	at io.deephaven.engine.context.QueryCompiler.maybeCreateClass(QueryCompiler.java:676)
	at io.deephaven.engine.context.QueryCompiler.compileHelper(QueryCompiler.java:455)
	at io.deephaven.engine.context.QueryCompiler.compile(QueryCompiler.java:262)
	at io.deephaven.engine.context.QueryCompiler.compile(QueryCompiler.java:215)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.compileFormula(DhFormulaColumn.java:778)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.createFormulaFactory(DhFormulaColumn.java:741)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:211)
	at io.deephaven.engine.table.impl.select.SwitchColumn.initDef(SwitchColumn.java:66)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:90)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:61)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$33(QueryTable.java:1255)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:518)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$34(QueryTable.java:1240)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3110)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1239)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1219)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:89)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:105)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:183)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:50)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:182)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:145)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:123)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:134)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:122)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:145)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:169)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1343)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:880)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:164)
	at java.base/java.lang.Thread.run(Thread.java:829)


Line: 471
Namespace: update
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/table.py", line 471, in update

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
        at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:183)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:50)
        at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:182)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:145)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:123)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:134)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:122)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:145)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:169)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1343)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:880)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:164)
        at java.lang.Thread.run(Thread.java:829)
```

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: latest (built from source)
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by jmao-denver** [comment]
Fixed by #3104
