### ISSUE TITLE
TableReplayer assertion error if start and end time are *after* times in the table

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#3135]
**Description**

The `TableReplayer.add_table()` method will fail with a confusing assertion error when the times in the table are all *before* the start and end time used to construct the TableReplayer.  For instance, if a table has dates spanning all of October this year, and I give it November, the following error is produced:

```
r-Scheduler-Serial-1 | i.d.s.s.SessionState      | Internal Error 'c710acf1-1626-4859-9a80-c87ad0be7b77' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: failed to add a historical table. : RuntimeError: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < LogicalClock.DEFAULT.currentStep(), instead lastNotificationStep == 382, LogicalClock.DEFAULT.currentStep() == 382.
Traceback (most recent call last):
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/replay.py", line 60, in add_table
    replay_table = Table(j_table=self._j_replayer.replay(table.j_table, col))
RuntimeError: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < LogicalClock.DEFAULT.currentStep(), instead lastNotificationStep == 382, LogicalClock.DEFAULT.currentStep() == 382.
	at io.deephaven.base.verify.Assert.fail(Assert.java:99)
	at io.deephaven.base.verify.Assert.lt(Assert.java:673)
	at io.deephaven.engine.table.impl.BaseTable.notifyListeners(BaseTable.java:753)
	at io.deephaven.engine.table.impl.BaseTable.notifyListeners(BaseTable.java:726)
	at io.deephaven.engine.table.impl.replay.ReplayTable.run(ReplayTable.java:69)
	at io.deephaven.engine.table.impl.replay.ReplayTable.<init>(ReplayTable.java:40)
	at io.deephaven.engine.table.impl.replay.Replayer.replay(Replayer.java:190)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:183)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:50)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:182)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:145)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:123)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:134)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:122)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:145)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:169)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1343)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:880)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:164)
	at java.base/java.lang.Thread.run(Thread.java:829)


Line: 63
Namespace: add_table
File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven/replay.py
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven/replay.py", line 63, in add_table

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
        at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:183)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:50)
        at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:182)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:145)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:123)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:134)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:122)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:145)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:169)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1343)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:880)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:164)
        at java.lang.Thread.run(Thread.java:829)
```

**Steps to reproduce**

The following code reproduces the error above. It occurs on line 17.

```
from deephaven.replay import TableReplayer
from deephaven import time as dhtu
from deephaven import read_csv

bikeride = read_csv("https://media.githubusercontent.com/media/deephaven/examples/main/MetricCentury/csv/metriccentury.csv")

early_start_time = dhtu.to_datetime("2019-01-01T00:00:00 NY")
early_end_time = dhtu.to_datetime("2019-01-01T00:01:00 NY")

late_start_time = dhtu.to_datetime("2020-01-01T00:00:00 NY")
late_end_time = dhtu.to_datetime("2020-01-01T00:01:00 NY")

early_replayer = TableReplayer(early_start_time, early_end_time)

late_replayer = TableReplayer(late_start_time, late_end_time)

replay_early = early_replayer.add_table(bikeride, "Time")
replay_late = late_replayer.add_table(bikeride, "Time")

early_replayer.start()
late_replayer.start()
```

**Expected results**

The early and late replayers in the code above exhibit different behavior. If the times supplied are early, the table will remain empty. This would lead a user to believe that if the times are late, the table should instantly populate. So, I expected the table to just instantly populate.

**Actual results**

The error with the stack trace given above.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: edge
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by rcaudy** [comment]
The table should instantly populate with any rows that are in window, but shouldn't modify on construction.
