### ISSUE TITLE
Random unit test failures in parallel select/update

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#3182]
I encountered 3 distinct hard-to-reproduce errors whole testing `io.deephaven.engine.table.impl.QueryTableSelectUpdateTest.testUpdateIncrementalRandomizedLarge` with `OperationInitializationThreadPool.threads=10`.

The first one occurred twice during nightly unit test runs (once for the `Integer` source, once for the `Double` source):
```
java.lang.IllegalStateException: May not call ensurePrevious twice on one clock cycle!	
at io.deephaven.engine.table.impl.sources.DoubleSparseArraySource.prepareForParallelPopulation(DoubleSparseArraySource.java:414)	
at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.prepareSourcesForParallelPopulation(SelectColumnLayer.java:551)	
at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.prepareParallelUpdate(SelectColumnLayer.java:211)	
at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$0(SelectColumnLayer.java:188)	
at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$OperationInitializationPoolJobScheduler.lambda$submit$0(SelectAndViewAnalyzer.java:608)	
•••
at io.deephaven.engine.table.impl.OperationInitializationThreadPool$1.lambda$newThread$0(OperationInitializationThreadPool.java:45)	
•••
```
This looks like a double-invocation of `io.deephaven.engine.table.impl.sources.IntegerSparseArraySource.prepareForParallelPopulation`, but from *initialization*.

In (unsuccessfully) attempting to reproduce this error, I also encountered two other issues once each:
```
[UpdateGraphProcessor-randomizedUpdateExecutor-4] ERROR io.deephaven.engine.updategraph.UpdateGraphProcessor - UpdateGraphProcessor-randomizedUpdateExecutor-4: Exception while executing UpdateGraphProcessor notification: NotificationAdapter{1048384592} of Notification{1939828426}: java.lang.NullPointerException: null
        at java.util.Arrays.fill(Arrays.java:3354)
        at io.deephaven.engine.table.impl.sources.SparseArrayColumnSource.lambda$static$1(SparseArrayColumnSource.java:125)
        at io.deephaven.util.SoftRecycler.returnItem(SoftRecycler.java:66)
        at io.deephaven.engine.table.impl.sources.IntegerSparseArraySource.commitUpdates(IntegerSparseArraySource.java:319)
        at io.deephaven.engine.updategraph.UpdateCommitter.run(UpdateCommitter.java:32)
        at io.deephaven.engine.updategraph.NotificationAdapter.run(NotificationAdapter.java:35)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$2$1.run(UpdateGraphProcessor.java:330)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1298)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$ConcurrentNotificationProcessor.processSatisfiedNotifications(UpdateGraphProcessor.java:1347)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$UpdateGraphProcessorThreadFactory.lambda$newThread$0(UpdateGraphProcessor.java:1813)
        at java.lang.Thread.run(Thread.java:829)
```
and
```
[UpdateGraphProcessor-randomizedUpdateExecutor-3] ERROR io.deephaven.engine.updategraph.UpdateGraphProcessor - UpdateGraphProcessor-randomizedUpdateExecutor-3: Exception while executing UpdateGraphProcessor notification: NotificationAdapter{1689326172} of {Notification(974555883 for {SelectColumnLayer: newCol=7, layerIndex=5}}: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < LogicalClock.DEFAULT.currentStep(), instead lastNotificationStep == 15, LogicalClock.DEFAULT.currentStep() == 15.
        at io.deephaven.base.verify.Assert.fail(Assert.java:99)
        at io.deephaven.base.verify.Assert.lt(Assert.java:673)
        at io.deephaven.engine.table.impl.BaseTable.notifyListenersOnError(BaseTable.java:901)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailureInternalWithDependent(InstrumentedTableListenerBase.java:163)
        at io.deephaven.engine.table.impl.BaseTable$ListenerImpl.onFailureInternal(BaseTable.java:1039)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailure(InstrumentedTableListenerBase.java:156)
        at io.deephaven.engine.table.impl.SelectOrUpdateListener.handleException(SelectOrUpdateListener.java:105)
        at io.deephaven.engine.table.impl.SelectOrUpdateListener$1.onError(SelectOrUpdateListener.java:99)
        at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onError(SelectAndViewAnalyzer.java:495)
        at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onError(SelectAndViewAnalyzer.java:495)
        at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onError(SelectAndViewAnalyzer.java:495)
        at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onError(SelectAndViewAnalyzer.java:495)
        at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$UpdateGraphProcessorJobScheduler$1.run(SelectAndViewAnalyzer.java:559)
        at io.deephaven.engine.updategraph.NotificationAdapter.run(NotificationAdapter.java:35)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$2$1.run(UpdateGraphProcessor.java:330)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1298)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$ConcurrentNotificationProcessor.processSatisfiedNotifications(UpdateGraphProcessor.java:1347)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$UpdateGraphProcessorThreadFactory.lambda$newThread$0(UpdateGraphProcessor.java:1813)
        at java.lang.Thread.run(Thread.java:829)


Assertion failed: asserted rowSet.equals(tableToValidate.build()), instead rowSet == {0-5,7-43,45-81,83-91,93-112,114,116-125,127-138,140-154,156-161,163-193,195-206,208-224,226-236,238,240-278,280-283,285-289,291-310,312-381,383-388,390-443,445-448,450-503,505-507,509-567,569-582,584-647,650-678,680-681,683-685,687-691,693-703,705-729,731-736,738-745,747-748,750-752,754-763,766-770,772-782,784-793,795,797-819,822-865,867-933,935-953,955-1000,1002-1005,1007-1010,1012,1014-1054,1056-1168,1170-1207,1209-1264,1266-1284,1286-1296,1299-1326,1328-1362,1364-1404,1406-1435,1437-1438,1440-1454,1456-1473,1476-1556,1558-1576,1578-1596,1598,1600-1621,1623-1649,1651-1654,1656-1698,1700-1755,1757-1870,1872,1874-1919,1921-1969,1971-1975,1977-1990,1992-2013,2015-2035,2037-2042,2044-2050,2052-2072,2074-2107,2109-2125,2127-2149,2151-2161,2163-2179,2181-2202,2204-2207,2209-2211,2213-2271,2273-2279,2281-2311,2313-2348,2350-2361,2363-2365,2367-2426,2428-2446,2449-2450,2452-2458,2460-2519,2521,2523-2532,2534-2552,2554-2582,2584-2585,2587,2589-2608,2610-2624,2626-2642,2644-2656,2658-2667,2669-2675,2677-2680,2682,2684-2706,2708-2726,2728-2748,2750-2753,2755-2769}, tableToValidate.build() == {2,4-7,11-18,22-26,28-29,31,34-36,40,42,45,49-55,58,61-62,65,67,72,75,77,81-83,86-87,91-92,96-98,101-104,110,115,117,121-122,124,129-131,136,138-141,143-144,147,149,151-152,154,156,162,169-170,173-175,179-180,183-185,188,190,199-200,205-206,208,213-218,220,222-224,226-227,229-231,234-235,237,240,242-243,246,248-249,251,253-255,257-260,268-273,276,279-280,282-283,285,288-289,294-295,297-298,300-303,305,310-312,314,316-317,320-322,325-327,329-330,332-337,339,341-344,347,351,354,356-358,360,362,364,369-370,372-373,376,379-380,382,384,386,388-392,394-395,397-401,403-404,406-410,412-413,415,418,420-423,426-428,432-435,437,442,444-446,448,453,456-460,462,464,466-469,471-472,474,476,478-479,483-487,489,491-494,497,499-504,506,508,511,513,516,518-519,521,523,525-528,530-538,541,543,546-551,554,557-560,563-564,567,571-573,575-576,579-580,585,587-588,590-592,594-598,600,603,605,608-610,613,615-616,618-622,624-628,630,636-637,640-641,643-645,648-650,652-653,657-658,660,663-668,670,672-676,680,684-685,687,690-692,695,702,704,706-709,711-712,714,716-717,719-720,723-725,727,730-731,738-741,744,746,750,752,754,758-760,762-765,768,770-771,774,778-780,782,784,787-788,791-794,799,804-807,810,813,815...}.
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted rowSet.equals(tableToValidate.build()), instead rowSet == {0-5,7-43,45-81,83-91,93-112,114,116-125,127-138,140-154,156-161,163-193,195-206,208-224,226-236,238,240-278,280-283,285-289,291-310,312-381,383-388,390-443,445-448,450-503,505-507,509-567,569-582,584-647,650-678,680-681,683-685,687-691,693-703,705-729,731-736,738-745,747-748,750-752,754-763,766-770,772-782,784-793,795,797-819,822-865,867-933,935-953,955-1000,1002-1005,1007-1010,1012,1014-1054,1056-1168,1170-1207,1209-1264,1266-1284,1286-1296,1299-1326,1328-1362,1364-1404,1406-1435,1437-1438,1440-1454,1456-1473,1476-1556,1558-1576,1578-1596,1598,1600-1621,1623-1649,1651-1654,1656-1698,1700-1755,1757-1870,1872,1874-1919,1921-1969,1971-1975,1977-1990,1992-2013,2015-2035,2037-2042,2044-2050,2052-2072,2074-2107,2109-2125,2127-2149,2151-2161,2163-2179,2181-2202,2204-2207,2209-2211,2213-2271,2273-2279,2281-2311,2313-2348,2350-2361,2363-2365,2367-2426,2428-2446,2449-2450,2452-2458,2460-2519,2521,2523-2532,2534-2552,2554-2582,2584-2585,2587,2589-2608,2610-2624,2626-2642,2644-2656,2658-2667,2669-2675,2677-2680,2682,2684-2706,2708-2726,2728-2748,2750-2753,2755-2769}, tableToValidate.build() == {2,4-7,11-18,22-26,28-29,31,34-36,40,42,45,49-55,58,61-62,65,67,72,75,77,81-83,86-87,91-92,96-98,101-104,110,115,117,121-122,124,129-131,136,138-141,143-144,147,149,151-152,154,156,162,169-170,173-175,179-180,183-185,188,190,199-200,205-206,208,213-218,220,222-224,226-227,229-231,234-235,237,240,242-243,246,248-249,251,253-255,257-260,268-273,276,279-280,282-283,285,288-289,294-295,297-298,300-303,305,310-312,314,316-317,320-322,325-327,329-330,332-337,339,341-344,347,351,354,356-358,360,362,364,369-370,372-373,376,379-380,382,384,386,388-392,394-395,397-401,403-404,406-410,412-413,415,418,420-423,426-428,432-435,437,442,444-446,448,453,456-460,462,464,466-469,471-472,474,476,478-479,483-487,489,491-494,497,499-504,506,508,511,513,516,518-519,521,523,525-528,530-538,541,543,546-551,554,557-560,563-564,567,571-573,575-576,579-580,585,587-588,590-592,594-598,600,603,605,608-610,613,615-616,618-622,624-628,630,636-637,640-641,643-645,648-650,652-653,657-658,660,663-668,670,672-676,680,684-685,687,690-692,695,702,704,706-709,711-712,714,716-717,719-720,723-725,727,730-731,738-741,744,746,750,752,754,758-760,762-765,768,770-771,774,778-780,782,784,787-788,791-794,799,804-807,810,813,815...}.
	at app//io.deephaven.base.verify.Assert.fail(Assert.java:99)
	at app//io.deephaven.base.verify.Assert.equals(Assert.java:1453)
	at app//io.deephaven.engine.table.impl.TableUpdateValidator.validate(TableUpdateValidator.java:127)
	at app//io.deephaven.engine.testutil.EvalNugget.validate(EvalNugget.java:111)
	at app//io.deephaven.engine.testutil.TstUtils.validate(TstUtils.java:373)
	at app//io.deephaven.engine.testutil.testcase.RefreshingTableTestCase.simulateShiftAwareStep(RefreshingTableTestCase.java:159)
	at app//io.deephaven.engine.testutil.testcase.RefreshingTableTestCase.simulateShiftAwareStep(RefreshingTableTestCase.java:150)
	at app//io.deephaven.engine.testutil.testcase.RefreshingTableTestCase.simulateShiftAwareStep(RefreshingTableTestCase.java:145)
	at app//io.deephaven.engine.table.impl.QueryTableSelectUpdateTest.testUpdateIncrementalRandomized(QueryTableSelectUpdateTest.java:715)
	at app//io.deephaven.engine.table.impl.QueryTableSelectUpdateTest.testUpdateIncrementalRandomized(QueryTableSelectUpdateTest.java:688)
	at app//io.deephaven.engine.table.impl.QueryTableSelectUpdateTest.lambda$testUpdateIncrementalRandomizedLarge$46(QueryTableSelectUpdateTest.java:672)
	at java.base@11.0.16/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base@11.0.16/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:593)
	at app//io.deephaven.engine.table.impl.QueryTableSelectUpdateTest.testUpdateIncrementalRandomizedLarge(QueryTableSelectUpdateTest.java:662)
```

**Comment by devinrsmith** [comment]
Hit again https://scans.gradle.com/s/c27vytxog6aee / https://github.com/deephaven/deephaven-core/actions/runs/3944846929/jobs/6751180820
