### ISSUE TITLE
Assertion failure in natural join update processing

### ISSUE THREAD

**Issue by lbooker42** [deephaven/deephaven-core#3202]
Community user reported an assertion failure in update propagation for a natural join, with the following error message:

```
EFAULT.refreshThread | i.d.e.t.i.MergedListener  | 280842020 naturalJoin([option_symbol, tdate2], [open_interest, shares_per_contract]) Merged Listener: Uncaught exception for entry= PerformanceEntry{, id=226, evaluationNumber=67, operationNumber=14, description='naturalJoin([option_symbol, tdate2], [open_interest, shares_per_contract])', callerLine='PyLib.java:-2', intervalUsageNanos=3512277600, intervalCpuNanos=3502458000, intervalUserCpuNanos=3450000000, intervalInvocationCount=1, intervalAdded=587738, intervalRemoved=0, intervalModified=0, intervalShifted=805607, intervalAllocatedBytes=-9223372036854775808, intervalPoolAllocatedBytes=-9223372036854775808, maxTotalMemory=58250493952, minFreeMemory=41594142264, collections=0, collectionTimeNanos=0, startCpuNanos=0, startUserCpuNanos=0, startTimeNanos=0, startAllocatedBytes=0, startPoolAllocatedBytes=0}: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted rehashPointer == 0, instead rehashPointer == 53583.
EFAULT.refreshThread | .AsyncClientErrorNotifier | Error in table update: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted rehashPointer == 0, instead rehashPointer == 53583.
```

This is on version `0.19.0`.

**Comment by lbooker42** [comment]
Found this reproducer:
```
source = empty_table(2_000_000).update(["idx=ii", "Value=(double)ii"])
ticking = time_table("00:00:0.0001") \
    .update("idx=ii") \
    .drop_columns("Timestamp")
source_ticking = ticking.natural_join(source, ["idx=idx"], ["Value"])
source_summary = source_ticking.update("idx=idx%100000").agg_by([agg.avg(["Avg_Value=Value"])], "idx")
failing_join = source_ticking.natural_join(source_summary, ["idx=idx"], ["Avg_Value"])
```

full failure trace is:
```
2022-12-15T17:39:41.849Z | EFAULT.refreshThread | ERROR | i.d.e.t.i.MergedListener  | 569445106 naturalJoin([idx], [Avg_Value]) Merged Listener: Uncaught exception for entry= PerformanceEntry{, id=422, evaluationNumber=747, operationNumber=9, description='naturalJoin([idx], [Avg_Value])', callerLine='PyLib.java:-2', intervalUsageNanos=128469156625, intervalCpuNanos=30329000, intervalUserCpuNanos=30140000, intervalInvocationCount=11, intervalAdded=200417, intervalRemoved=0, intervalModified=417, intervalShifted=0, intervalAllocatedBytes=-9223372036854775808, intervalPoolAllocatedBytes=-9223372036854775808, maxTotalMemory=3577741312, minFreeMemory=9524224, collections=1, collectionTimeNanos=17000000, startCpuNanos=0, startUserCpuNanos=0, startTimeNanos=0, startAllocatedBytes=0, startPoolAllocatedBytes=0}: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted rehashPointer == 0, instead rehashPointer == 6662.
        at io.deephaven.base.verify.Assert.fail(Assert.java:99)
        at io.deephaven.base.verify.Assert.eqZero(Assert.java:1080)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.doRehash(IncrementalNaturalJoinStateManagerTypedBase.java:265)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.buildTable(IncrementalNaturalJoinStateManagerTypedBase.java:175)
        at io.deephaven.engine.table.impl.naturaljoin.IncrementalNaturalJoinStateManagerTypedBase.addLeftSide(IncrementalNaturalJoinStateManagerTypedBase.java:535)
        at io.deephaven.engine.table.impl.NaturalJoinHelper$ChunkedMergedJoinListener.process(NaturalJoinHelper.java:1002)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:306)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1298)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1459)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1177)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1122)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$10(UpdateGraphProcessor.java:1736)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:32)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1726)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1713)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1567)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$1.run(UpdateGraphProcessor.java:276)
```

**Comment by lbooker42** [comment]
The root cause was failing to perform enough reshash work each cycle and falling behind when updates are large.  The bug also affected `AsOfjoin` and `UpdateBy` hashing which were also corrected with the merged PR.
