### ISSUE TITLE
Table cannot be written to Parquet

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#3328]
The following file contains a CSV of a one-column, 519k-row table that cannot be written to Parquet:

[2022-12-04_PullRequests_truncated_bad.csv.7z.zip](https://github.com/deephaven/deephaven-core/files/10453437/2022-12-04_PullRequests_truncated_bad.csv.7z.zip)

The file is 7zipped to make it sufficiently small to upload (from 2.3gb to 18mb), and then zipped again so that GitHub is happy with the file type. So to import it, you have to decompress it twice:

```shell
unzip 2022-12-04_PullRequests_truncated_bad.csv.7z.zip
7za x 2022-12-04_PullRequests_truncated_bad.csv.7z
```

(You can't read the 7zipped version directly; there is some error in `SevenZipInputStream`. It was compressed with `7za a -md=64m -mx=9` FWIW.)

Then you can read it:

```groovy
pr_body_col_broken_fromcsv = io.deephaven.csv.CsvTools.readCsv("/dh/data/shared/github-data/2022-12-04_PullRequests_truncated_bad.csv")
```

And if you try writing it to Parquet, it will fail. (Note that if you don't set it to UNCOMPRESSED, it winds up taking forever — from a cursory glance at a thread dump, it looked like it wound up calling `org.apache.parquet.hadoop.codec.SnappyCompressor#setInput` in a way that leads to a ludicrous amount of copying.)

```groovy
import io.deephaven.parquet.table.ParquetInstructions
import io.deephaven.parquet.table.ParquetTools
ParquetTools.writeTable(
    pr_body_col_broken_fromcsv,
    new File("/dh/data/shared/github-data/2022-12-04_PullRequests_bad.parquet"),
    ParquetInstructions.builder()
        .useDictionary("body", false)
        .setCompressionCodecName("UNCOMPRESSED")
        .build()
)
```

and it fails with this exception (using [this branch](https://github.com/deephaven/deephaven-core/compare/main...rbasralian:deephaven-core:raffi_parquet_write_overflow) to trigger the exception — without that change, integer overflow causes it to get stuck in a loop):
```
io.deephaven.UncheckedDeephavenException: Error writing table to /dh/data/shared/github-data/2022-12-04_PullRequests_bad.parquet
        at io.deephaven.parquet.table.ParquetTools.writeParquetTableImpl(ParquetTools.java:673)
        at io.deephaven.parquet.table.ParquetTools.writeTable(ParquetTools.java:223)
        at io.deephaven.parquet.table.ParquetTools.writeTable(ParquetTools.java:184)
        at io.deephaven.parquet.table.ParquetTools$writeTable.call(null:-1)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
        at io.deephaven.dynamic.Script_64.run(Script_64.groovy:66)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
        at io.deephaven.engine.util.GroovyDeephavenSession.evaluateCommand(GroovyDeephavenSession.java:203)
        at io.deephaven.engine.util.GroovyDeephavenSession.lambda$evaluate$0(GroovyDeephavenSession.java:225)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:50)
        at io.deephaven.engine.util.GroovyDeephavenSession.evaluate(GroovyDeephavenSession.java:225)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:145)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:129)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:140)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:128)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:145)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$7(ConsoleServiceGrpcImpl.java:152)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1348)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:891)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:165)
        at java.lang.Thread.run(Thread.java:829)
caused by:
java.lang.IllegalStateException: Unable to write 2147484412 values. (Maximum capacity: 2147483639.)
        at io.deephaven.parquet.base.PlainBinaryChunkedWriter.ensureCapacityFor(PlainBinaryChunkedWriter.java:136)
        at io.deephaven.parquet.base.PlainBinaryChunkedWriter.writeBytes(PlainBinaryChunkedWriter.java:42)
        at io.deephaven.parquet.base.PlainBinaryChunkedWriter.writeBulk(PlainBinaryChunkedWriter.java:93)
        at io.deephaven.parquet.base.PlainBinaryChunkedWriter.writeBulk(PlainBinaryChunkedWriter.java:22)
        at io.deephaven.parquet.base.ColumnWriterImpl.addDictionaryPage(ColumnWriterImpl.java:126)
        at io.deephaven.parquet.table.ParquetTableWriter.tryEncodeDictionary(ParquetTableWriter.java:696)
        at io.deephaven.parquet.table.ParquetTableWriter.writeColumnSource(ParquetTableWriter.java:528)
        at io.deephaven.parquet.table.ParquetTableWriter.write(ParquetTableWriter.java:293)
        at io.deephaven.parquet.table.ParquetTableWriter.write(ParquetTableWriter.java:263)
        at io.deephaven.parquet.table.ParquetTableWriter.write(ParquetTableWriter.java:196)
        at io.deephaven.parquet.table.ParquetTableWriter.write(ParquetTableWriter.java:228)
        at io.deephaven.parquet.table.ParquetTools.writeParquetTableImpl(ParquetTools.java:669)
        at io.deephaven.parquet.table.ParquetTools.writeTable(ParquetTools.java:223)
        at io.deephaven.parquet.table.ParquetTools.writeTable(ParquetTools.java:184)
        at io.deephaven.parquet.table.ParquetTools$writeTable.call(null:-1)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
        at io.deephaven.dynamic.Script_64.run(Script_64.groovy:66)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
        at io.deephaven.engine.util.GroovyDeephavenSession.evaluateCommand(GroovyDeephavenSession.java:203)
        at io.deephaven.engine.util.GroovyDeephavenSession.lambda$evaluate$0(GroovyDeephavenSession.java:225)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:50)
        at io.deephaven.engine.util.GroovyDeephavenSession.evaluate(GroovyDeephavenSession.java:225)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:145)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:129)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:140)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:128)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:145)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$7(ConsoleServiceGrpcImpl.java:152)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1348)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:891)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:165)
        at java.lang.Thread.run(Thread.java:829)
```

I ran the following updateBys to get a sense of how big the data is (both total length and unique values). I tried using them as a guideline for how to use `head()` to find the cutoff of where the table breaks parquet writing, but still couldn't easily find the exact row that crosses the line.

```groovy
pr_body_col_broken_fromcsv_withLen = pr_body_col_broken_fromcsv
    .updateView("body_len = isNull(body) ? null : body.length()", "Idx=ii")
    .updateBy(io.deephaven.api.updateby.UpdateByOperation.CumSum("len_cum_sum = body_len"))

pr_body_col_broken_fromcsv_withLen_firsts = pr_body_col_broken_fromcsv_withLen
    .firstBy("body")
    .updateBy(io.deephaven.api.updateby.UpdateByOperation.CumSum("len_cum_sum = body_len"))
```

So it appears there are three issues here:

- writing the table cause the parquet writing to land in an infinite loop
- after working around that, the table is impossible to write and causes an exception
- separate from both of those, writing the compressed seems to take forever (think an hour was the longest I let it run)
- (well, also the potential 7zip reading bug)

**Comment by rbasralian** [comment]
I added a PR (#3332) with a fix for the infinite loop.

**Comment by malhotrashivam** [comment]
The file has more than 400,000 rows and each row is an html page, so large number of bytes.
When this csv is written as a Parquet file, our code uses dictionary encoding to represent the string column. So each html page is stored as a string in a dictionary (more details about dictionary encoding can be found [here](https://dataninjago.com/2021/12/07/databricks-deep-dive-3-parquet-encoding/#:~:text=Dictionary%20encoding%20builds%20a%20dictionary,the%20names%20of%20the%20products)).
As we write this very large file, we hit the `OutOfMemoryError`.

The code currently has a limit on maximum number of keys in the dictionary such that if the number of keys exceed 2^20, it will throw a DictionarySizeExceededException.
The correct way to handle this scenario (as explained in Parquet docs [here](https://parquet.apache.org/docs/file-format/data-pages/encodings/)) is that "If the dictionary grows too big, whether in size or number of distinct values, the encoding will fall back to the plain encoding."

So we need to introduce a limit on number of bytes in the dictionary and fall back to plain encoding if we hit either of the limits.

**Comment by malhotrashivam** [comment]
**More analysis:**
I tried disabling dictionary encoding and still hit java out of memory error at more places:
1. In ParquetTableWriter::encodePlain, we collect all our data for one page into "transferObject" and then pass on this buffer to columnWriter. 
2. PlainBinaryChunkedWriter::writeBytes : We do the processing for nulls and copy all our data to innerBuffer. 
3. Finally we create another buffer where we keep the compressed data.

Overall, we have a few places in the code where we populate the data structure for all the data in a single page. So when we make these copies internally, we hit the out of memory error. 


**Approach:**

- There seems to be a bug in how we calculate the maximum number of rows in a page for string data type. The default maximum page size is 2^20 bytes. For strings, we divide this number by Integer.Bytes and that gives us the maximum number of rows in the parquet file. This is incorrect since we should have accounted for length of strings as well. This should be fixed.
- There might be opportunities to remove some of these copies, particularly copy 1 might be avoidable. This will partially solve the out of memory error and improve the performance for writing these pages out.

**Comment by malhotrashivam** [comment]
Overall, we introduced two changes which completely fix the original issue:
1. #4334
2. #4344

We found a similar issue for encoding vector columns with very large entries which we will tackle as part of #4495, and found an optimization opportunity for dictionary encodings which I have mentioned as a comment on #946.
