### ISSUE TITLE
Hierarchical table sometimes crashes when mashing collapse/expand

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/deephaven-core#3348]
**Description**

Sorry, I don't have great steps to reproduce. Table dies, and takes the whole UI with it.

```
qtp210474732-26      | i.d.s.a.ArrowFlightUtil   | Internal Error '6ed9f594-50be-4f51-ba04-f64eea19695d' java.lang.StringIndexOutOfBoundsException: offset 5, count -5, length 8
        at java.lang.String.checkBoundsOffCount(String.java:3304)
        at java.lang.String.<init>(String.java:505)
        at io.deephaven.extensions.barrage.chunk.ChunkInputStreamGenerator.lambda$extractChunkFromInputStream$14(ChunkInputStreamGenerator.java:279)
        at io.deephaven.extensions.barrage.chunk.VarBinaryChunkInputStreamGenerator.extractChunkFromInputStream(VarBinaryChunkInputStreamGenerator.java:480)
        at io.deephaven.extensions.barrage.chunk.ChunkInputStreamGenerator.extractChunkFromInputStream(ChunkInputStreamGenerator.java:278)
        at io.deephaven.extensions.barrage.util.ArrowToTableConverter.createBarrageMessage(ArrowToTableConverter.java:208)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoPutObserver.lambda$onNext$0(ArrowFlightUtil.java:169)
        at io.deephaven.extensions.barrage.util.GrpcUtil.rpcWrapper(GrpcUtil.java:36)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoPutObserver.onNext(ArrowFlightUtil.java:132)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoPutObserver.onNext(ArrowFlightUtil.java:106)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
        at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
        at io.grpc.Contexts$ContextualizedServerCallListener.onMessage(Contexts.java:76)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:333)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:316)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:835)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.messagesAvailable(ServerImpl.java:846)
        at io.grpc.internal.AbstractStream$TransportState.messagesAvailable(AbstractStream.java:182)
        at io.grpc.internal.MessageDeframer.processBody(MessageDeframer.java:413)
        at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:276)
        at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:178)
        at io.grpc.internal.AbstractStream$TransportState.deframe(AbstractStream.java:210)
        at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:262)
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl$WebsocketTransportState.inboundDataReceived(AbstractWebsocketStreamImpl.java:25)
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl.inboundDataReceived(AbstractWebsocketStreamImpl.java:99)
        at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.onMessage(MultiplexedWebSocketServerStream.java:218)
        at io.grpc.servlet.web.websocket.AbstractWebSocketServerStream.lambda$onOpen$0(AbstractWebSocketServerStream.java:115)
        at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.invoke(AbstractDecodedMessageSink.java:61)
        at org.eclipse.jetty.websocket.jakarta.common.messages.DecodedBinaryMessageSink.onWholeMessage(DecodedBinaryMessageSink.java:60)
        at org.eclipse.jetty.websocket.core.internal.messages.ByteBufferMessageSink.accept(ByteBufferMessageSink.java:64)
        at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.accept(AbstractDecodedMessageSink.java:80)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.acceptMessage(JakartaWebSocketFrameHandler.java:592)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onBinary(JakartaWebSocketFrameHandler.java:642)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onFrame(JakartaWebSocketFrameHandler.java:243)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.lambda$onFrame$1(WebSocketCoreSession.java:671)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1465)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1484)
        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.onFrame(WebSocketCoreSession.java:671)
        at org.eclipse.jetty.websocket.core.AbstractExtension.nextIncomingFrame(AbstractExtension.java:145)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:236)
        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.emitFrame(DemandingFlusher.java:145)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.inflate(PerMessageDeflateExtension.java:480)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.handle(PerMessageDeflateExtension.java:413)
        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.process(DemandingFlusher.java:169)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232)
        at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:350)
        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.onFrame(DemandingFlusher.java:104)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.onFrame(PerMessageDeflateExtension.java:93)
        at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:120)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onFrame(WebSocketCoreSession.java:481)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:262)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:455)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)
        at java.lang.Thread.run(Thread.java:829)
```

**Steps to reproduce**
I was using this query:
```
from deephaven import empty_table, time_table

size = 100
scale = 1000

random_values_with_null_NaN = empty_table(size).update([
    "MyString=(i%11==0? null : `a`+(int)(scale*(Math.random()*2-1)))",
    "MyInt=(i%12==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyLong=(i%13==0 ? null : (long)(scale*(Math.random()*2-1)))",
    "MyFloat=(float)(i%14==0 ? null : i%10==0 ? 1.0F/0.0F: i%5==0 ? -1.0F/0.0F : (float) scale*(Math.random()*2-1))",
    "MyDouble=(double)(i%16==0 ? null : i%10==0 ? 1.0D/0.0D: i%5==0 ? -1.0D/0.0D : (double) scale*(Math.random()*2-1))",
    "MyBoolean = (i%17==0 ? null : (int)(10*Math.random())%2==0)",
    "MyChar = (i%18==0 ? null : new Character((char) (((26*Math.random())%26)+97)) )",
    "MyShort=(short)(i%19==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyByte=(Byte)(i%19==0 ? null : new Byte( Integer.toString((int)(Byte.MAX_VALUE*(Math.random()*2-1)))))",
    "MyBigDecimal=(i%21==0 ? null : new java.math.BigDecimal(scale*(Math.random()*2-1)))",
    "MyBigInteger=(i%22==0 ? null : new java.math.BigInteger(Integer.toString((int)(scale*(Math.random()*2-1)))))"
])
```

I created a rollup table in the UI, something like this:

![image](https://user-images.githubusercontent.com/1576283/214136352-2192662b-af31-46fe-8754-cec30127146f.png)

Then was just clicking around expanding and collapsing stuff, and it would sporadically happen after 1-5 minutes of clicking around expanding and collapsing rows.

**Versions**
Engine Version: 0.21.0
Web UI Version: 0.26.0
Java Version: 11.0.16
Barrage Version: 0.5.0

**Comment by niloc132** [comment]
This was fixed by #3381.
