### ISSUE TITLE
`Failure to execute snapshot function with unchanged clock` error when attempting to scroll through sufficiently large table with a formula column.

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#3427]
**Description**

*When I first filed this, I forgot about `i` vs `ii`. This is a user error, and is not a bug, but the error message could be improved.*

Attempting to scroll quickly (with the scroll bar on the RHS of the table view) through a sufficiently large single-formula-column table always results in a `Failure to execute snapshot function with unchanged clock` error.

**Steps to reproduce**

```python
from deephaven import empty_table

t = empty_table(10_000_000_000).update_view(["X = i"])
```

Then, try to quickly scroll to the bottom of the table with the scroll bar at the RHS of the table window.

**Expected results**

A view of rows containing large numbers near or at the bottom of the table.

**Actual results**

The following error (and stack trace):

```
heduler-Concurrent-4 | .b.BarrageMessageProducer | Internal Error 'e80c8d43-9d2d-4fbd-9991-d98766b76f2f' io.deephaven.UncheckedDeephavenException: Failure to execute snapshot function with unchanged clock
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1166)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1019)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:599)
        at io.deephaven.server.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:2143)
        at io.deephaven.server.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:1269)
        at io.deephaven.server.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:945)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:162)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
caused by:
io.deephaven.util.datastructures.SizeException: FormulaColumn ii usage cannot proceed without losing precision: Input size 9999999947 larger than maximum 2147483647
        at io.deephaven.util.datastructures.LongSizedDataStructure.intSize(LongSizedDataStructure.java:58)
        at io.deephaven.temp.c_5a66f17567954fbb165c5410a2e247f231816cc053a5ab7aceba4947b6112883v61_0.Formula.__intSize(Formula.java:191)
        at io.deephaven.temp.c_5a66f17567954fbb165c5410a2e247f231816cc053a5ab7aceba4947b6112883v61_0.Formula.lambda$fillChunkHelper$2(Formula.java:143)
        at io.deephaven.engine.rowset.RowSet.lambda$forAllRowKeys$0(RowSet.java:306)
        at io.deephaven.engine.rowset.impl.singlerange.SingleRange.ixForEachLong(SingleRange.java:105)
        at io.deephaven.engine.rowset.impl.WritableRowSetImpl.forEachRowKey(WritableRowSetImpl.java:320)
        at io.deephaven.engine.rowset.RowSet.forAllRowKeys(RowSet.java:305)
        at io.deephaven.temp.c_5a66f17567954fbb165c5410a2e247f231816cc053a5ab7aceba4947b6112883v61_0.Formula.fillChunkHelper(Formula.java:143)
        at io.deephaven.temp.c_5a66f17567954fbb165c5410a2e247f231816cc053a5ab7aceba4947b6112883v61_0.Formula.fillChunk(Formula.java:127)
        at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillChunk(ViewColumnSource.java:219)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.getSnapshotDataAsChunkList(ConstructSnapshot.java:1475)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.serializeAllTable(ConstructSnapshot.java:1356)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.lambda$constructBackplaneSnapshotInPositionSpace$2(ConstructSnapshot.java:594)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1087)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1019)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:599)
        at io.deephaven.server.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:2143)
        at io.deephaven.server.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:1269)
        at io.deephaven.server.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:945)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:162)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
```

**Additional details and attachments**

This issue does _not_ occur if the data is sourced from Parquet. This can be verified in our [demo system](demo.deephaven.app) in notebook `02 Stream and Batch Together.md`.

Also, if you attempt to keep scrolling through the table with the error now showing in it, the error repeatedly appears in the console window.

**Versions**
 - Deephaven: latest (0.21.0)
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by rcaudy** [comment]
The error should say "i" not "ii". It's otherwise giving you good information. You cannot evaluate "i" past Integer.MAX_VALUE.

**Comment by rcaudy** [comment]
Maybe we should give you just the cause instead of the extra information about the snapshot. That's more of an implementation detail.

**Comment by jjbrosnan** [comment]
Good point. I completely forgot about `i` vs `ii` when I first found this. So, it's not a bug, but the error doesn't really help much.
