### ISSUE TITLE
Unable to import DHError in pip-installed python

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#3553]
Unable to import DHError in pip-installed python.

```
Deephaven Server Version: ['DEFAULT_JVM_ARGS', 'DEFAULT_JVM_PROPERTIES', 'Server', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'server', 'start_jvm']
Deephaven Server Version: 0.22.0
# Starting io.deephaven.python.server.EmbeddedServer
deephaven.cacheDir=/root/.cache/deephaven
deephaven.configDir=/root/.config/deephaven
deephaven.dataDir=/root/.local/share/deephaven
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: searching for 'io.deephaven.internal.log.LoggerFactory'...
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: found 'io.deephaven.internal.log.LoggerFactorySlf4j'
Traceback (most recent call last):
  File "/scripts/downloader.py", line 3, in <module>
    start_dh()
  File "/usr/local/lib/python3.7/site-packages/cecropia/deephaven/__init__.py", line 23, in start_dh
    server.start()
  File "/usr/local/lib/python3.7/site-packages/deephaven_server/server.py", line 60, in start
    self.j_server.start()
RuntimeError: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'ImportError'>
Value: cannot import name 'DHError' from 'deephaven' (/usr/local/lib/python3.7/site-packages/deephaven/__init__.py)
Line: 17
Namespace: <module>
File: /usr/local/lib/python3.7/site-packages/deephaven/dtypes.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/deephaven/server/plugin/__init__.py", line 18, in initialize_all_and_register_into
  File "/usr/local/lib/python3.7/site-packages/deephaven/server/plugin/register.py", line 17, in initialize_all_and_register_into
  File "/usr/local/lib/python3.7/site-packages/deephaven/plugin/__init__.py", line 67, in register_all_into
  File "/usr/local/lib/python3.7/site-packages/deephaven/plugin/__init__.py", line 63, in collect_registration_classes
  File "/usr/local/lib/python3.7/site-packages/deephaven/plugin/__init__.py", line 63, in <listcomp>
  File "/usr/local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 208, in load
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/deephaven/pandasplugin/__init__.py", line 6, in <module>
  File "/usr/local/lib/python3.7/site-packages/deephaven/pandasplugin/pandas_as_table.py", line 5, in <module>
  File "/usr/local/lib/python3.7/site-packages/deephaven/pandas.py", line 13, in <module>
  File "/usr/local/lib/python3.7/site-packages/deephaven/dtypes.py", line 17, in <module>

	at org.jpy.PyLib.callAndReturnValue(Native Method)
	at org.jpy.PyProxyHandler.invoke(PyProxyHandler.java:120)
	at io.deephaven.server.plugin.python.$Proxy5.initialize_all_and_register_into(Unknown Source)
	at io.deephaven.server.plugin.python.PythonPluginsRegistration.registerInto(PythonPluginsRegistration.java:33)
	at io.deephaven.server.plugin.PluginRegistration.registerAll(PluginRegistration.java:40)
	at io.deephaven.server.runner.DeephavenApiServer.run(DeephavenApiServer.java:128)
	at io.deephaven.python.server.EmbeddedServer.start(EmbeddedServer.java:104)
```

**Comment by chipkent** [comment]
@jmao-denver did a very nice job of figuring out what happened.
1. Using pip-installed DHC (`pip install deephaven-server`) in a python script run from the command line.
2. The script used some python packaged in a wheel.
3. The `setup.py` for the wheel specified a pip dependency on `deephaven`
4. Python 3.7 was used.

All of this looks benign, right?  First problem is that DHC 0.22.0 does not support python 3.7, and this was not updated in our wheels.  Furthermore, we are only testing against 3.10, which is not good and causes us to miss problems like this.  At a minimum, we should also be testing our minimally supported version.  

The bigger problem is #3.  The `deephaven` pypi package is our DHE package.  In this case, `deephaven-server` correctly installed `deephaven-core`.  After this, the wheel dependency caused the DHE python package `deephaven` to be installed OVER the already installed DHC python package.  :face_vomiting:

We were brainstorming some ways forward:
1. Rename the DHE package to `deephaven-enterprise` or `deephaven-legacy` or something else that makes it very clear that it is not DHC.  This would then avoid accidental collisions with the most important name `deephaven`.
2. Add code to setup.py for both DHC and DHE to determine if the conflicting package is already installed.
3. #1 and #2

I'm very much in favor of #3, but I don't know how many problems it will cause for DHE users.

**Comment by jmao-denver** [comment]
```
Python 3.10.8 (main, Nov  6 2022, 19:40:56) [Clang 13.1.6 (clang-1316.0.21.2.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib import metadata
>>> metadata.version('deephaven')
'1.20221001.62'
>>> metadata.version('deephaven-core')
'0.22.0'
```
The above code could be used to check that DHC and DHE are not stepping over each other's toes during their respective initialization/startup.

**Comment by AdrianOrenstein** [comment]
Having the same issue. Are there any workarounds known to anyone?

**Comment by AdrianOrenstein** [comment]
Figured out a work around. If are using the python docker container to host the server, and you just need a python client to send and receive data, you can follow the install steps for the client here https://github.com/deephaven/deephaven-core/tree/main/py/client.
