### ISSUE TITLE
Python client tests failed for nightly CI

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#3571]
```
 ======================================================================
  FAIL [0.000s]: test_ema (test_updateby.UpdateByTestCase) [<pydeephaven.table.Table object at 0x7f14d43c8790> <pydeephaven.updateby.UpdateByOperation object at 0x7f14d43c8b10>]
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/project/tests/test_updateby.py", line 52, in test_ema
      self.assertEqual(rt.size, t.size)
  AssertionError: 1028 != 1
  
  ======================================================================
  FAIL [2.191s]: test_ema (test_updateby.UpdateByTestCase) [<pydeephaven.table.Table object at 0x7f14d43c8790> <pydeephaven.updateby.UpdateByOperation object at 0x7f14d43c8b90>]
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/project/tests/test_updateby.py", line 52, in test_ema
      self.assertEqual(rt.size, t.size)
  AssertionError: 1028 != 1
  
  ----------------------------------------------------------------------
  Ran 47 tests in 32.033s
  
  FAILED (failures=2, skipped=5)
```

**Comment by jmao-denver** [comment]
Fixed by #3572
