### ISSUE TITLE
Failed to create InputTable if the provided Arrow schema includes mapped DH DateTime fields

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#3605]
The server would throw an exception:
```
core-server-1  | 2023-03-27T20:25:24.874Z | heduler-Concurrent-4 | ERROR | i.d.s.s.SessionState      | Internal Error '71c948a8-e1e8-449b-a00e-696f02ea9606' java.lang.ClassCastException: class io.deephaven.engine.table.impl.sources.DateTimeArraySource cannot be cast to class io.deephaven.engine.table.impl.sources.ArrayBackedColumnSource (io.deephaven.engine.table.impl.sources.DateTimeArraySource and io.deephaven.engine.table.impl.sources.ArrayBackedColumnSource are in unnamed module of loader 'app')
core-server-1  |         at io.deephaven.engine.table.impl.util.KeyedArrayBackedMutableTable.lambda$processPendingTable$4(KeyedArrayBackedMutableTable.java:188)
core-server-1  |         at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
core-server-1  |         at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
core-server-1  |         at io.deephaven.engine.table.impl.util.KeyedArrayBackedMutableTable.processPendingTable(KeyedArrayBackedMutableTable.java:187)
core-server-1  |         at io.deephaven.engine.table.impl.util.BaseArrayBackedMutableTable.processInitial(BaseArrayBackedMutableTable.java:91)
core-server-1  |         at io.deephaven.engine.table.impl.util.KeyedArrayBackedMutableTable.make(KeyedArrayBackedMutableTable.java:100)
core-server-1  |         at io.deephaven.engine.table.impl.util.KeyedArrayBackedMutableTable.make(KeyedArrayBackedMutableTable.java:81)
core-server-1  |         at io.deephaven.engine.table.impl.util.KeyedArrayBackedMutableTable.make(KeyedArrayBackedMutableTable.java:50)
core-server-1  |         at io.deephaven.server.table.ops.CreateInputTableGrpcImpl.create(CreateInputTableGrpcImpl.java:76)
core-server-1  |         at io.deephaven.server.table.ops.CreateInputTableGrpcImpl.create(CreateInputTableGrpcImpl.java:29)
core-server-1  |         at io.deephaven.server.table.ops.TableServiceGrpcImpl.lambda$oneShotOperationWrapper$9(TableServiceGrpcImpl.java:597)
core-server-1  |         at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:896)
core-server-1  |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
core-server-1  |         at java.util.concurrent.FutureTask.run(FutureTask.java:264)
core-server-1  |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
core-server-1  |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
core-server-1  |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
core-server-1  |         at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:162)
core-server-1  |         at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
core-server-1  |         at org.jpy.PyObject.call(PyObject.java:449)
core-server-1  |         at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
core-server-1  |         at java.lang.Thread.run(Thread.java:833)
```

**Comment by devinrsmith** [comment]
It looks like input tables logic assumes `ArrayBackedColumnSource`s, which is not the case. Even though the column source is created via

```
io.deephaven.engine.table.impl.sources.ArrayBackedColumnSource#getMemoryColumnSource(long, java.lang.Class<T>)
```

Looks like this is a regression introduced by #3385, the return type changed.

**Comment by rcaudy** [comment]
This patch is probably the entirety of the fix, but it needs testing:
```
Index: engine/table/src/main/java/io/deephaven/engine/table/impl/util/AppendOnlyArrayBackedMutableTable.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/engine/table/src/main/java/io/deephaven/engine/table/impl/util/AppendOnlyArrayBackedMutableTable.java b/engine/table/src/main/java/io/deephaven/engine/table/impl/util/AppendOnlyArrayBackedMutableTable.java
--- a/engine/table/src/main/java/io/deephaven/engine/table/impl/util/AppendOnlyArrayBackedMutableTable.java	(revision 6d14a68a4820fe0f63ae6c5bc4306ef8911e27eb)
+++ b/engine/table/src/main/java/io/deephaven/engine/table/impl/util/AppendOnlyArrayBackedMutableTable.java	(date 1684792143993)
@@ -11,7 +11,6 @@
 import io.deephaven.engine.rowset.RowSequenceFactory;
 import io.deephaven.engine.util.config.InputTableStatusListener;
 import io.deephaven.engine.table.impl.QueryTable;
-import io.deephaven.engine.table.impl.sources.ArrayBackedColumnSource;
 import io.deephaven.engine.table.impl.sources.NullValueColumnSource;
 import io.deephaven.engine.table.ChunkSink;
 import io.deephaven.chunk.*;
@@ -104,16 +103,16 @@
                 final int chunkCapacity = table.intSize();
 
                 getColumnSourceMap().forEach((name, cs) -> {
-                    final ArrayBackedColumnSource<?> arrayBackedColumnSource = (ArrayBackedColumnSource<?>) cs;
-                    arrayBackedColumnSource.ensureCapacity(nextRow);
+                    final WritableColumnSource<?> writableColumnSource = (WritableColumnSource<?>) cs;
+                    writableColumnSource.ensureCapacity(nextRow);
                     final ColumnSource<?> sourceColumnSource = table.getColumnSource(name);
                     try (final ChunkSink.FillFromContext ffc =
-                            arrayBackedColumnSource.makeFillFromContext(chunkCapacity);
+                            writableColumnSource.makeFillFromContext(chunkCapacity);
                             final ChunkSource.GetContext getContext =
                                     sourceColumnSource.makeGetContext(chunkCapacity, sharedContext)) {
                         final Chunk<? extends Values> valuesChunk =
                                 sourceColumnSource.getChunk(getContext, addRowSet);
-                        arrayBackedColumnSource.fillFromChunk(ffc, valuesChunk, destinations);
+                        writableColumnSource.fillFromChunk(ffc, valuesChunk, destinations);
                     }
                 });
             }
Index: engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedMutableTable.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedMutableTable.java b/engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedMutableTable.java
--- a/engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedMutableTable.java	(revision 6d14a68a4820fe0f63ae6c5bc4306ef8911e27eb)
+++ b/engine/table/src/main/java/io/deephaven/engine/table/impl/util/BaseArrayBackedMutableTable.java	(date 1684792143995)
@@ -14,13 +14,12 @@
 import io.deephaven.engine.table.Table;
 import io.deephaven.engine.table.TableDefinition;
 import io.deephaven.engine.table.WritableColumnSource;
+import io.deephaven.engine.table.impl.sources.ArrayBackedColumnSource;
 import io.deephaven.engine.updategraph.UpdateGraphProcessor;
-import io.deephaven.engine.util.TableTools;
 import io.deephaven.engine.util.config.InputTableStatusListener;
 import io.deephaven.engine.util.config.MutableInputTable;
 import io.deephaven.engine.table.impl.QueryTable;
 import io.deephaven.engine.table.impl.UpdatableTable;
-import io.deephaven.engine.table.impl.sources.ArrayBackedColumnSource;
 import io.deephaven.engine.table.ColumnSource;
 import io.deephaven.util.annotations.TestUseOnly;
 import org.jetbrains.annotations.NotNull;
@@ -319,8 +318,8 @@
             final String[] kabmtColumns =
                     getTableDefinition().getColumnNames().toArray(CollectionUtil.ZERO_LENGTH_STRING_ARRAY);
             // noinspection unchecked
-            final ArrayBackedColumnSource<Object>[] sourcesByPosition =
-                    Arrays.stream(kabmtColumns).map(sources::get).toArray(ArrayBackedColumnSource[]::new);
+            final WritableColumnSource<Object>[] sourcesByPosition =
+                    Arrays.stream(kabmtColumns).map(sources::get).toArray(WritableColumnSource[]::new);
 
             final Set<String> missingColumns = new HashSet<>(getTableDefinition().getColumnNames());
 
@@ -389,7 +388,7 @@
                 WritableColumnSource<?> cs = ArrayBackedColumnSource.getMemoryColumnSource(
                         capacity, columnDefinition.getDataType());
                 // noinspection unchecked
-                final ArrayBackedColumnSource<Object> memoryColumnSource = (ArrayBackedColumnSource<Object>) cs;
+                final WritableColumnSource<Object> memoryColumnSource = (WritableColumnSource<Object>) cs;
                 memoryColumnSource.ensureCapacity(capacity);
                 sources.put(columnDefinition.getName(), memoryColumnSource);
             }
Index: engine/table/src/main/java/io/deephaven/engine/table/impl/util/KeyedArrayBackedMutableTable.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/engine/table/src/main/java/io/deephaven/engine/table/impl/util/KeyedArrayBackedMutableTable.java b/engine/table/src/main/java/io/deephaven/engine/table/impl/util/KeyedArrayBackedMutableTable.java
--- a/engine/table/src/main/java/io/deephaven/engine/table/impl/util/KeyedArrayBackedMutableTable.java	(revision 6d14a68a4820fe0f63ae6c5bc4306ef8911e27eb)
+++ b/engine/table/src/main/java/io/deephaven/engine/table/impl/util/KeyedArrayBackedMutableTable.java	(date 1684792143991)
@@ -24,7 +24,7 @@
 
 /**
  * An in-memory table that has keys for each row, which can be updated on the UGP.
- *
+ * <p>
  * This is used to implement in-memory editable table columns from web plugins.
  */
 public class KeyedArrayBackedMutableTable extends BaseArrayBackedMutableTable {
@@ -185,16 +185,16 @@
             sharedContext.reset();
 
             getColumnSourceMap().forEach((name, cs) -> {
-                final ArrayBackedColumnSource<?> arrayBackedColumnSource = (ArrayBackedColumnSource<?>) cs;
-                arrayBackedColumnSource.ensureCapacity(nextRow);
+                final WritableColumnSource<?> writableColumnSource = (WritableColumnSource<?>) cs;
+                writableColumnSource.ensureCapacity(nextRow);
                 final ColumnSource<?> sourceColumnSource = table.getColumnSource(name);
                 try (final ChunkSink.FillFromContext ffc =
-                        arrayBackedColumnSource.makeFillFromContext(chunkCapacity);
+                        writableColumnSource.makeFillFromContext(chunkCapacity);
                         final ChunkSource.GetContext getContext =
                                 sourceColumnSource.makeGetContext(chunkCapacity, sharedContext)) {
                     final Chunk<? extends Values> valuesChunk =
                             sourceColumnSource.getChunk(getContext, addRowSet);
-                    arrayBackedColumnSource.fillFromChunkUnordered(ffc, valuesChunk, destinations);
+                    writableColumnSource.fillFromChunkUnordered(ffc, valuesChunk, destinations);
                 }
             });
         }
```

**Comment by rcaudy** [comment]
@jmao-denver Can you post a simple reproducer I can test the fix with?

**Comment by devinrsmith** [comment]
@rcaudy, see the commented out parts of test_input_table in `py/client/tests/test_session.py`

**Comment by jmao-denver** [comment]
@rcaudy, after you uncomment the code in test_session.py, run `./gradlew :py-client:testPyClient
