### ISSUE TITLE
URI / java barrage subscription unexpectedly closed after 30 seconds

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#3733]
A user reported that a URI subscription was being cancelled. This can be reproduced locally with:

server
```python
from deephaven import time_table

t60 = time_table("00:01:00")
```

client
```python
from deephaven import uri

# replace with appropriate URI
t60 = uri.resolve("dh://<server>/scope/t60")
```

After 30 seconds of inactivity, the client subscription gets closed with the error

```
13:42:48.367 ERROR c-default-executor-0 | i.BarrageSubscriptionImpl | Barrage/ClientSubscription/Table:export/1/1534798306/: Error detected in subscription: io.grpc.StatusRuntimeException: CANCELLED: client cancelled
        at io.grpc.Status.asRuntimeException(Status.java:539)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.deephaven.client.impl.BearerHandler$BearerListener.onClose(BearerHandler.java:121)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:829)
13:42:48.368 ERROR c-default-executor-0 | i.BarrageSubscriptionImpl | Barrage/ClientSubscription/Table:export/1/1534798306/: unexpectedly closed by other host
```

This behavior does not happen via JS / web UI subscriptions, nor with faster ticking tables (for example, `time_table("00:00:01")`).

Upon further debugging, it was found that the jetty http2 idle timeout default of 30 seconds was causing this issue:

```
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:288)
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
        at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.lambda$onCancel$2(SessionServiceGrpcImpl.java:362)
        at io.deephaven.server.session.SessionServiceGrpcImpl.rpcWrapper(SessionServiceGrpcImpl.java:393)
        at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.onCancel(SessionServiceGrpcImpl.java:362)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:378)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:365)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:923)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closedInternal(ServerImpl.java:930)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closed(ServerImpl.java:888)
        at io.grpc.internal.AbstractServerStream$TransportState.closeListener(AbstractServerStream.java:339)
        at io.grpc.internal.AbstractServerStream$TransportState.access$100(AbstractServerStream.java:184)
        at io.grpc.internal.AbstractServerStream$TransportState$1.run(AbstractServerStream.java:289)
        at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:241)
        at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:234)
        at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:198)
        at io.grpc.internal.AbstractServerStream$TransportState.transportReportStatus(AbstractServerStream.java:293)
        at io.grpc.servlet.jakarta.ServletAdapter$GrpcReadListener.lambda$onError$2(ServletAdapter.java:347)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102)
        at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95)
        at io.grpc.servlet.jakarta.ServletServerStream$ServletTransportState.runOnTransportThread(ServletServerStream.java:144)
        at io.grpc.servlet.jakarta.ServletAdapter$GrpcReadListener.onError(ServletAdapter.java:345)
        at org.eclipse.jetty.server.HttpInput.run(HttpInput.java:403)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1448)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:596)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:457)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
        at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.handleWithContext(HttpChannelOverHTTP2.java:688)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

A̶s̶ ̶a̶ ̶t̶e̶m̶p̶o̶r̶a̶r̶y̶ ̶w̶o̶r̶k̶a̶r̶o̶u̶n̶d̶,̶ ̶t̶h̶e̶ ̶u̶s̶e̶r̶ ̶c̶a̶n̶ ̶s̶e̶t̶ ̶t̶h̶e̶ ̶c̶o̶n̶f̶i̶g̶u̶r̶a̶t̶i̶o̶n̶ ̶p̶r̶o̶p̶e̶r̶t̶y̶ ̶`̶h̶t̶t̶p̶.̶s̶e̶s̶s̶i̶o̶n̶.̶d̶u̶r̶a̶t̶i̶o̶n̶M̶s̶`̶ ̶t̶o̶ ̶3̶0̶0̶0̶0̶ ̶(̶3̶0̶ ̶s̶e̶c̶o̶n̶d̶s̶ ̶i̶n̶s̶t̶e̶a̶d̶ ̶o̶f̶ ̶d̶e̶f̶a̶u̶l̶t̶ ̶o̶f̶ ̶5̶ ̶m̶i̶n̶u̶t̶e̶s̶)̶.̶

This ^ does *NOT* work.

**Comment by supernomad** [comment]
For what its worth, I just tested out 0.24.0 and I am still seeing this behavior with a slowly updating table.

**Comment by devinrsmith** [comment]
Interesting. I'll reopen and investigate.

**Comment by supernomad** [comment]
After chatting with @devinrsmith this looks like it was on my end, I will report back tomorrow if anything changes, otherwise I am good to go.
