### ISSUE TITLE
Ambiguous error when deephaven-plugin fails to load

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#3756]
**Description**

@jjbrosnan encountered this error when he was trying out the `streamlit-deephaven` plugin. The error was actually with another plugin installed on his environment, but the error message did not give any clues as to what plugin was causing the error.
It might be a good idea to print off each plugin that is loaded; at the very least, provide the name of the plugin that fails to load.

**Steps to reproduce**
1. Set up a python venv
2. `pip install streamlit-deephaven` to install deephaven and the streamlit-deephaven plugin.
3. `pip install deephaven-plugin-plotly-js` to install a "bad" plugin. (`deephaven-plugin-plotly-js` was a dev plugin we created using a new format and never released.)
4. Start a python session and run the following:
```
from deephaven_server import Server
s = Server(port=8080)
s.start()
```

**Expected results**
4. An error message identifying the plugin that failed to load

**Actual results**
4. A confusing error message not identifying what plugin failed.
```
(.venv) ➜  bad-plugin JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deephaven_server import Server
>>> s = Server(port=8080)
1 compiler directives added
# Starting io.deephaven.python.server.EmbeddedServer
deephaven.cacheDir=/home/bender/.cache/deephaven
deephaven.configDir=/home/bender/.config/deephaven
deephaven.dataDir=/home/bender/.local/share/deephaven
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: searching for 'io.deephaven.internal.log.LoggerFactory'...
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: found 'io.deephaven.internal.log.LoggerFactorySlf4j'
>>> s.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bender/dev/deephaven/tmp/bad-plugin/.venv/lib/python3.10/site-packages/deephaven_server/server.py", line 60, in start
    self.j_server.start()
RuntimeError: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'NotImplementedError'>
Value: 
Line: 31
Namespace: register
File: /home/bender/dev/deephaven/tmp/bad-plugin/.venv/lib/python3.10/site-packages/deephaven/server/plugin/register.py
Traceback (most recent call last):
  File "/home/bender/dev/deephaven/tmp/bad-plugin/.venv/lib/python3.10/site-packages/deephaven/server/plugin/__init__.py", line 18, in initialize_all_and_register_into
  File "/home/bender/dev/deephaven/tmp/bad-plugin/.venv/lib/python3.10/site-packages/deephaven/server/plugin/register.py", line 17, in initialize_all_and_register_into
  File "/home/bender/dev/deephaven/tmp/bad-plugin/.venv/lib/python3.10/site-packages/deephaven/plugin/__init__.py", line 68, in register_all_into
  File "/home/bender/dev/deephaven/tmp/bad-plugin/.venv/lib/python3.10/site-packages/deephaven_plugin_plotly_js/__init__.py", line 36, in register_into
  File "/home/bender/dev/deephaven/tmp/bad-plugin/.venv/lib/python3.10/site-packages/deephaven/server/plugin/register.py", line 31, in register

	at org.jpy.PyLib.callAndReturnValue(Native Method)
	at org.jpy.PyProxyHandler.invoke(PyProxyHandler.java:120)
	at io.deephaven.server.plugin.python.$Proxy5.initialize_all_and_register_into(Unknown Source)
	at io.deephaven.server.plugin.python.PythonPluginsRegistration.registerInto(PythonPluginsRegistration.java:33)
	at io.deephaven.server.plugin.PluginRegistration.registerAll(PluginRegistration.java:40)
	at io.deephaven.server.runner.DeephavenApiServer.run(DeephavenApiServer.java:128)
	at io.deephaven.python.server.EmbeddedServer.start(EmbeddedServer.java:104)

>>> 
```

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 0.23.0

**Comment by mofojed** [comment]
@jjbrosnan I'm confused by that comment. The PyPi page for the plotly express plugin is https://pypi.org/project/deephaven-plugin-plotly-express/, and doesn't mention the incorrect plugin.

The page you linked is for deephaven-plugin-plotly-js, which is bad and shouldn't be linked from anywhere: https://pypi.org/project/deephaven-plugin-plotly-js/

**Comment by jjbrosnan** [comment]
Basically, I went to the wrong PyPi page, installed the wrong package, and that was the cause. Definite user error.
