### ISSUE TITLE
Creating a `deephaven_server` without calling `start()` results in an unusable Deephaven server

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#3764]
**Description**

Creating a Deephaven server with the the `deephaven_server` package without explicitly starting it results in some weird and undesirable behavior, where you'll get errors about no `ExecutionContext`, etc.

**Steps to reproduce**

From a Python session, Jupyter, or JupyterLab (whichever you want, they all produce this behavior), run the following code:

```python
from deephaven_server import Server

s = server(port=8080, jvm_args=["-Xmx10g"])
```

Give it a few seconds. It should produce some output, but stop short of saying `Server started on port 8080`.

Then, run some simple Deephaven code, like:

```python
from deephaven import empty_table

t = empty_table(1).update(["X = 1"])
```

**Expected results**

One of the following:

- The server not to start without being told to start (would be nice if it produced output saying "Server ready to start!").
- The server to start properly.
- The server starting, and the subsequent Deephaven code to work as expected.

**Actual results**

An error with the following stack trace:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~/miniconda3/lib/python3.9/site-packages/deephaven/table.py:796, in Table.update(self, formulas)
    795     with _query_scope_ctx(), auto_locking_ctx(self):
--> 796         return Table(j_table=self.j_table.update(*formulas))
    797 except Exception as e:

RuntimeError: io.deephaven.engine.table.impl.select.FormulaCompilationException: Formula compilation error for: i
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:214)
	at io.deephaven.engine.table.impl.select.SwitchColumn.initDef(SwitchColumn.java:67)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:104)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:56)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$33(QueryTable.java:1267)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$34(QueryTable.java:1249)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3163)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1248)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1227)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:104)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:90)
caused by io.deephaven.util.NoExecutionContextRegisteredException: ExecutionContext not registered
	at io.deephaven.engine.context.PoisonedQueryScope.fail(PoisonedQueryScope.java:22)
	at io.deephaven.engine.context.PoisonedQueryScope.getParamNames(PoisonedQueryScope.java:27)
	at io.deephaven.engine.table.impl.select.codegen.FormulaAnalyzer.getCompiledFormula(FormulaAnalyzer.java:99)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:194)
	... 11 more


The above exception was the direct cause of the following exception:

DHError                                   Traceback (most recent call last)
Input In [3], in <module>
      1 from deephaven import empty_table
----> 3 t = empty_table(10).update(["X = i"])

File ~/miniconda3/lib/python3.9/site-packages/deephaven/table.py:798, in Table.update(self, formulas)
    796         return Table(j_table=self.j_table.update(*formulas))
    797 except Exception as e:
--> 798     raise DHError(e, "table update operation failed.") from e

DHError: table update operation failed. : io.deephaven.util.NoExecutionContextRegisteredException: ExecutionContext not registered
Traceback (most recent call last):
  File "/Users/john.brosnan/miniconda3/lib/python3.9/site-packages/deephaven/table.py", line 796, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: io.deephaven.engine.table.impl.select.FormulaCompilationException: Formula compilation error for: i
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:214)
	at io.deephaven.engine.table.impl.select.SwitchColumn.initDef(SwitchColumn.java:67)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:104)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:56)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$33(QueryTable.java:1267)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$34(QueryTable.java:1249)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3163)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1248)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1227)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:104)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:90)
caused by io.deephaven.util.NoExecutionContextRegisteredException: ExecutionContext not registered
	at io.deephaven.engine.context.PoisonedQueryScope.fail(PoisonedQueryScope.java:22)
	at io.deephaven.engine.context.PoisonedQueryScope.getParamNames(PoisonedQueryScope.java:27)
	at io.deephaven.engine.table.impl.select.codegen.FormulaAnalyzer.getCompiledFormula(FormulaAnalyzer.java:99)
	at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:194)
	... 11 more
```

**Additional details and attachments**

This also happens in Chip's new demo system in the JupyterLab experience, so it shouldn't be OS-dependent.

**Versions**
 - Deephaven: deephaven-server 0.23.0
 - OS: OS X Monterey 12.3.1
 - Browser: Chrome
 - Docker: N/A

**Comment by jjbrosnan** [comment]
The [PyPi page](https://pypi.org/project/deephaven-server/) for `deephaven_server` has this for code:

```
from deephaven_server import Server
server = Server()
server.start()
```

If a user runs the second line without running the third line at the same time, they will likely encounter this error.

**Comment by jmao-denver** [comment]
Because deephaven-core package doesn't have a single entry-point, checking if the server has been started whenever it is accessed from Python is not a sensible solution. I see two options to mitigate the issue:
1. The fact that a Python user (an experienced one in this case) simply forgot to call `start()` tells use that this two step process of setting up the Deephaven server probably isn't so Pythonic.  So the obvious solution should be combining the two steps into one, that's when a Server instance is created, it should automatically be started as well. For backwards compatibility, we could keep the `start` method but use an internal flag to prevent it being called more than once.
2. Offer a factory function `start_deephaven` or  `start_server` with the same signature as the `__init__()` on the Server class, which creates and starts a Server instance if one doesn't exist already. This is arguably a more Pythonic way to implement the singleton pattern. This of course assumes Deephaven will never allow one than more Servers in one worker process.

**Comment by chipkent** [comment]
We generally want less surface area and ways to do things.  If we don't want the user calling `start`, we should remove it.  Similarly, we shouldn't provide multiple ways to do something without a compelling reason.  I don't feel like I'm hearing that compelling reason.  It is better to break a couple of people right now than many people later.

#2522 isn't as time critical, so it could come later if necessary.

The module-level singleton seems fine.  We should make sure that there is a nice message if the requested port is already in use.

I would also get feedback from @niloc132 and @devinrsmith, since I think they did the original server work.

**Comment by devinrsmith** [comment]
I think option 2 makes most sense as well. There is some discussion we might need modulo potential for shutdown in the future.

**Comment by niloc132** [comment]
This is a regression caused by https://github.com/deephaven/deephaven-core/pull/2539, and appears to be simple to fix - we need to open the execution context earlier.

The original purpose was to allow the user to create the server, but not yet expose it to the world (i.e. so health/tcp checks can see that the server is there and ready to query). That is, `start()` is optional, and should not be required to use the rest of the engine.

There are three important, separate steps here:

```python
from deephaven_server import Server
```
Unlike any other `deephaven.*` import, this does not require the JVM and DH engine to already be running, so this is safe to put at the top of a script.

```python
s = Server(...)
```
At this time, the JVM has started, and the DH engine is running. It should now be safe to not only import other `deephaven` packages, but also use them. Stopping here is appropriate, and suitable for script initialization, contacting other upstream servers, or simply writing a batch script to run without any involvement/interference from clients.

```python
s.start()
```
Now the HTTP port (default 8080) is running and exposed, and the script session as accessible from gRPC services (including the browser-based IDE) has the state of the current globals.

**Comment by chipkent** [comment]
Let me echo a few details here to confirm my understanding:
1) `s.start()` is only needed to start the HTTP server.
2) If `s.start()` is not called, the query engine will function fine for both static and real-time data.
3) If `s.start()` is not called, the IDE will not work, and Jupyter widgets will not work, but other Jupyter operations will work.
4) The query engine working without `s.start()` is not currently working because of a regression caused by #2539.

Assuming the above is true, there is still some weirdness with the server start:
1) having to import the `deephaven_server` lib and create a server before being able to import `deephaven` is very weird and non-pythonic.  We have been living with this.
2) Creating a server variable and then never using or referencing it again is somewhat weird.
3) The naming of `s.start()` doesn't make clear that only the HTTP server is started and that the RT query engine is already working.
4) If a Jupyter user forgets `s.start()`, they are going to have widgets failing with weird `no path to host` type errors.  This will be very cryptic for end users.  If this is the way we are going, some part of the widget rendering would need to do checking or provide better error messages.

**Comment by niloc132** [comment]
First four are correct to the best of my knowledge.

Changing these semantics is mostly fine, here's my thoughts based on your second four:
 * Some moderate number of users will want to control jvmargs and dh config properties, and thus will want to still directly instantiate the Server. Or, at least the first two steps (import vs invoke) will need to be kept separate. Otherwise, we could just always auto-start the jvm with a vanilla `import deephaven`, and you get what you get.
 * Removing the third step mostly sounds like it is what you are asking for, or better docs/logging/naming? If we make it optional (say, some named param to the constructor, `auto_start=True`), then by passing False explicitly, we can handle the minority cases of "I just want to run the engine for some batch operation" or "I want to explicitly finish all setup before starting the http server, so that health checks are accurate and easy to set up".

**Comment by jmao-denver** [comment]
- the HTTP server is also responsible for gRPC/flight/barrage? 
- conceptually we could make it explicit that DH engine and DH server aren't the same but one must be started (the engine) before the other (the HTTP server), this is too much mental burden for the users and probably doesn't fit the their expectation
