### ISSUE TITLE
Python Table.columns property causes an error when the table has vector columns

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#3777]
This works as expected:
```python
t = empty_table(0).update_view("I=i").group_by()
print(t.columns)
```
Results in:
```
[Column(name='I', data_type=io.deephaven.vector.IntVector, component_type=int, column_type=NORMAL)]
```

---
However, this does not
```python
t = empty_table(0).update_view("StringColumn=`abc`").group_by()
print(t.columns)
```
Note that `print(t)` will also cause an error.

```
java.lang.RuntimeException: Error in Python interpreter:

Type: <class 'RuntimeError'>
Value: java.lang.IllegalArgumentException: Can't create Vector types as custom types
	at io.deephaven.qst.type.CustomType.checkNotVector(CustomType.java:59)
	at io.deephaven.qst.type.ImmutableCustomType.validate(ImmutableCustomType.java:79)
	at io.deephaven.qst.type.ImmutableCustomType.of(ImmutableCustomType.java:75)
	at io.deephaven.qst.type.CustomType.of(CustomType.java:27)
	at io.deephaven.qst.type.Type.find(Type.java:34)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:183)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:182)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:145)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:129)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:140)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:128)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:145)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:170)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1352)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:896)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:162)
	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.call(PyObject.java:449)
	at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

Line: 27
Namespace: _qst_custom_type
File: /home/colin/.pyenv/versions/3.10.10/lib/python3.10/site-packages/deephaven/dtypes.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/colin/.pyenv/versions/3.10.10/lib/python3.10/site-packages/deephaven/table.py", line 564, in columns
  File "/home/colin/.pyenv/versions/3.10.10/lib/python3.10/site-packages/deephaven/table.py", line 497, in _td_to_columns
  File "/home/colin/.pyenv/versions/3.10.10/lib/python3.10/site-packages/deephaven/dtypes.py", line 190, in from_jtype
  File "/home/colin/.pyenv/versions/3.10.10/lib/python3.10/site-packages/deephaven/dtypes.py", line 46, in __init__
  File "/home/colin/.pyenv/versions/3.10.10/lib/python3.10/site-packages/deephaven/dtypes.py", line 27, in _qst_custom_type

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
        at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:183)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
        at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:182)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:145)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:129)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:140)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:128)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:145)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:113)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:170)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1352)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:896)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:162)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:829)
```

---

This error prevents some diagnostic information from working easily, and also prevents other operations such as using `deephaven.table_listener.listen(...)` on tables with vector columns.

**Comment by devinrsmith** [comment]
This seems to be pointing out a fundamental issue of how python is currently trying to represent column info:

```python
class DType:
    def __init__(...):
        self.qst_type = qst_type if qst_type else _qst_custom_type(j_name)
        ...
```

```python
class Column:
    """ A Column object represents a column definition in a Deephaven Table. """
    name: str
    data_type: DType
    component_type: DType = None
    column_type: ColumnType = ColumnType.NORMAL
```

I column should have a _single_ `io.deephaven.qst.type.Type`; in this case, the python layer is mirroring `io.deephaven.engine.table.ColumnDefinition` "incorrectly"; and should either switch `data_type` / `component_type` to classes, or have a single qst Type field.
