### ISSUE TITLE
Stream table reverse assertion failure

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#3858]
```groovy
import io.deephaven.engine.table.impl.TimeTable
x1 = TimeTable.newBuilder().streamTable(true).period(1000).build()
x2 = x1.reverse()
```

fails shortly after execution with:

```
2023-05-22T20:23:00.626Z | EFAULT.refreshThread | ERROR | rumentedTableListenerBase | Uncaught exception for entry= reverse(), added.size()=999673, modified.size()=0, removed.size()=1, shifted.size()=0, modifiedColumnSet={EMPTY}:
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted update.shifted.empty().
        at io.deephaven.base.verify.Assert.fail(Assert.java:86)
        at io.deephaven.base.verify.Assert.assertion(Assert.java:116)
        at io.deephaven.engine.table.impl.BaseTable.notifyListeners(BaseTable.java:637)
        at io.deephaven.engine.table.impl.ReverseOperation.onUpdate(ReverseOperation.java:225)
        at io.deephaven.engine.table.impl.ReverseOperation$2.onUpdate(ReverseOperation.java:104)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:283)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:261)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1285)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1461)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1164)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1109)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$11(UpdateGraphProcessor.java:1744)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:33)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1732)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1719)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1573)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$new$3(UpdateGraphProcessor.java:270)
        at java.lang.Thread.run(Thread.java:833)

2023-05-22T20:23:00.629Z | EFAULT.refreshThread | ERROR | .AsyncClientErrorNotifier | Error in table update: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted update.shifted.empty().
        at io.deephaven.base.verify.Assert.fail(Assert.java:86)
        at io.deephaven.base.verify.Assert.assertion(Assert.java:116)
        at io.deephaven.engine.table.impl.BaseTable.notifyListeners(BaseTable.java:637)
        at io.deephaven.engine.table.impl.ReverseOperation.onUpdate(ReverseOperation.java:225)
        at io.deephaven.engine.table.impl.ReverseOperation$2.onUpdate(ReverseOperation.java:104)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:283)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:261)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1285)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1461)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1164)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1109)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$11(UpdateGraphProcessor.java:1744)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:33)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1732)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1719)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1573)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$new$3(UpdateGraphProcessor.java:270)
        at java.lang.Thread.run(Thread.java:833)
```

**Comment by devinrsmith** [comment]
This was tested against 0.24.1 release:

```shell
docker run --rm -p 10000:10000 ghcr.io/deephaven/server-slim:0.24.1
```
