### ISSUE TITLE
Server error when subscribing to some large tables in a figure

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#3863]
I don't yet know how to reproduce this in DHC, only in DnD.

Contrary to https://github.com/deephaven/deephaven-core/issues/3862, it seems that sometimes the server will not split a snapshot of a static table into multiple flight payloads, resulting in this server-side exception:
```
java.lang.IllegalStateException: Subset {0-65999} is out of bounds for chunk of size 65536

        at io.deephaven.extensions.barrage.chunk.BaseChunkInputStreamGenerator$BaseChunkInputStream.<init>(BaseChunkInputStreamGenerator.java:92)
        at io.deephaven.extensions.barrage.chunk.LongChunkInputStreamGenerator$LongChunkInputStream.<init>(LongChunkInputStreamGenerator.java:62)
        at io.deephaven.extensions.barrage.chunk.LongChunkInputStreamGenerator.getInputStream(LongChunkInputStreamGenerator.java:57)
        at io.deephaven.extensions.barrage.BarrageStreamGeneratorImpl.appendAddColumns(BarrageStreamGeneratorImpl.java:898)
        at io.deephaven.extensions.barrage.BarrageStreamGeneratorImpl$SubView.lambda$forEachStream$1(BarrageStreamGeneratorImpl.java:391)
        at io.deephaven.extensions.barrage.BarrageStreamGeneratorImpl.getInputStream(BarrageStreamGeneratorImpl.java:686)
        at io.deephaven.extensions.barrage.BarrageStreamGeneratorImpl.processBatches(BarrageStreamGeneratorImpl.java:780)
        at io.deephaven.extensions.barrage.BarrageStreamGeneratorImpl$SubView.forEachStream(BarrageStreamGeneratorImpl.java:391)
        at io.deephaven.server.arrow.ArrowModule$1.onNext(ArrowModule.java:48)
        at io.deephaven.server.arrow.ArrowModule$1.onNext(ArrowModule.java:43)
        at io.deephaven.server.barrage.BarrageMessageProducer.propagateSnapshotForSubscription(BarrageMessageProducer.java:1534)
        at io.deephaven.server.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:1398)
        at io.deephaven.server.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:945)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:162)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
```

Steps to reproduce in DHC-in-DHE: 
Run this python query
```python
t = db.historical_table("LearnDeephaven","StockTrades")\
    .where("Date=`2017-08-25`").head(66000)
```
Create a chart using the chart builder: select "Scatter", pick Timestamp as the X-Axis, and Last as the series.

Next, click the downsample icon, next to the warning `!` that will appear on the chart's header, to confirm that downsampling should be disabled.

Expected: data appears.

Actual: no data appears, instead a stack trace appears in the web IDE.

---

Related to https://github.com/deephaven/deephaven-core/issues/3862 - note that if the plot is created in the console, instead 3862's behavior is seen instead.

**Comment by niloc132** [comment]
Fixed by #3866.
