### ISSUE TITLE
`ReinterpretUtils.convertToOriginal` is missing `ZonedDateTime` case

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#3936]
`ReinterpretUtils#maybeConvertToPrimitive` allows reinterpreting `ZonedDateTime` as primitive, but the inverse operation `ReinterpretUtils#convertToOriginal` does not handle this case.

This is causing ring tables to fail when the source table has a `ZonedDateTime` column.

To reproduce:

```groovy
import io.deephaven.engine.util.TableTools
import io.deephaven.engine.table.impl.sources.ring.RingTableTools

blinkTable = TableTools.timeTableBuilder()
    .period("PT1s")
    .blinkTable(true)
    .build()
    .updateView("ZonedTimestamp=Timestamp.atZone(java.time.ZoneId.systemDefault())")

ringTable = RingTableTools.of(blinkTable, 32)
```

produces stacktrace:

```
java.lang.UnsupportedOperationException: Unsupported original type class java.time.ZonedDateTime
        at io.deephaven.engine.table.impl.sources.ReinterpretUtils.convertToOriginal(ReinterpretUtils.java:232)
        at io.deephaven.engine.table.impl.sources.ring.AddsToRingsListener.of(AddsToRingsListener.java:64)
        at io.deephaven.engine.table.impl.sources.ring.RingTableTools$RingTableSnapshotFunction.call(RingTableTools.java:103)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1222)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1061)
        at io.deephaven.engine.table.impl.BaseTable.initializeWithSnapshot(BaseTable.java:1250)
        at io.deephaven.engine.table.impl.sources.ring.RingTableTools$RingTableSnapshotFunction.constructResults(RingTableTools.java:96)
        at io.deephaven.engine.table.impl.sources.ring.RingTableTools.lambda$of$0(RingTableTools.java:47)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:444)
        at io.deephaven.engine.table.impl.sources.ring.RingTableTools.of(RingTableTools.java:44)
        at io.deephaven.engine.table.impl.sources.ring.RingTableTools.of(RingTableTools.java:28)
        at io.deephaven.engine.table.impl.sources.ring.RingTableTools$of.call(null:-1)
```

**Comment by devinrsmith** [comment]
This code from above is in 0.25.0, but I have verified the same issue can be demonstrated in 0.24.2 (so, it's _not_ an issue introduced as part of the time library refactoring).

**Comment by rcaudy** [comment]
This was surely introduced when support for storing `ZoneDateTime` and `Instant` types as `longs` was added in #3385.
We need to decide internally if `maybeReinterpretToPrimitive` must be symmetric with `convertToOriginal` (I think yes), and if so what should be done with `ZonedDateTime`; it's not obvious that we can do this entirely symmetrically.
