### ISSUE TITLE
Unable to upload csv

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#3949]
**Description**

If you try and upload CSV, you get an error.

**Steps to reproduce**
1. Drag a CSV file over Console, and choose to upload file

**Expected results**
1. Table should appear

**Actual results**
1. Table does not appear, error is logged in console about `Can't parse LOCAL_TIME`.

**Additional details and attachments**

```
[CsvInputBar] Error: java.lang.UnsupportedOperationException: Can't parse LOCAL_TIME
    at UnsupportedOperationException_0.createError (dh-core.js:1217:10)
    at UnsupportedOperationException_0.initializeBackingError (dh-core.js:1237:46)
    at UnsupportedOperationException_0.Throwable_0 (dh-core.js:1182:8)
    at UnsupportedOperationException_0.Exception_1 (dh-core.js:1261:18)
    at UnsupportedOperationException_0.RuntimeException_1 (dh-core.js:1274:18)
    at new UnsupportedOperationException_0 (dh-core.js:2158:25)
    at JsDataHandler$14.write_1 [as write_0] (dh-core.js:22765:14)
    at Object.$lambda$74 (dh-core.js:14746:94)
    at WorkerConnection$lambda$74$Type.fetch_22 [as fetch_1] (dh-core.js:16691:9)
    at Object.$lambda$32_1 (dh-core.js:34125:23)
    at ClientTableState$lambda$32$Type.accept_87 [as accept] (dh-core.js:34846:9)
    at Function.onInvoke_2 (dh-core.js:7837:12)
    at lambda (dh-core.js:173:22)
    at new Promise (<anonymous>)
    at Object.$refetch_1 (dh-core.js:34246:13)
    at Object.$newState (dh-core.js:14884:16)
    at Object.$newTable (dh-core.js:14909:16)
    at IdeSession.newTable (dh-core.js:33036:16)
    at CsvParser.handleCreateTable (CsvParser.ts:278:8)
    at CsvParser.handleChunk (CsvParser.ts:224:9)
    at c.parseChunk (papaparse.min.js:7:6346)
    at c._chunkLoaded (papaparse.min.js:7:9318)
    at FileReader.<anonymous> (papaparse.min.js:7:18166)
o
```

**Comment by niloc132** [comment]
Dup of https://github.com/deephaven/deephaven-core/issues/1041

**Comment by niloc132** [comment]
Is it possible that the web UI is sending them as long/double instead of big int/decimal? The linked ticket was wrong, while barrage has support for reading those types, we don't have parser support yet.

**Comment by mofojed** [comment]
[table-2023-06-12-104308 (1).csv](https://github.com/deephaven/deephaven-core/files/11724839/table-2023-06-12-104308.1.csv)

There is also an exception with the `datetime` type. Try importing the attached csv, and you'll get the following exception:
```
2023-06-12T14:46:55.376Z | qtp1250644519-59     | ERROR | .s.SessionServiceGrpcImpl | Internal Error '4ed0493e-1e51-45e4-9b23-a622502a0143' io.deephaven.UncheckedDeephavenException: Could not load class from schema
        at io.deephaven.extensions.barrage.util.BarrageUtil.lambda$convertArrowSchema$13(BarrageUtil.java:419)
        at io.deephaven.extensions.barrage.util.BarrageUtil.lambda$convertArrowSchema$5(BarrageUtil.java:377)
        at io.deephaven.extensions.barrage.util.BarrageUtil.convertArrowSchema(BarrageUtil.java:414)
        at io.deephaven.extensions.barrage.util.BarrageUtil.convertArrowSchema(BarrageUtil.java:369)
        at io.deephaven.extensions.barrage.util.ArrowToTableConverter.parseSchema(ArrowToTableConverter.java:166)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoPutObserver.onNext(ArrowFlightUtil.java:168)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoPutObserver.onNext(ArrowFlightUtil.java:110)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
        at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
        at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.lambda$onMessage$0(SessionServiceGrpcImpl.java:352)
        at io.deephaven.server.session.SessionServiceGrpcImpl.rpcWrapper(SessionServiceGrpcImpl.java:393)
        at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.onMessage(SessionServiceGrpcImpl.java:352)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:333)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:316)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:835)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.messagesAvailable(ServerImpl.java:846)
        at io.grpc.internal.AbstractStream$TransportState.messagesAvailable(AbstractStream.java:182)
        at io.grpc.internal.MessageDeframer.processBody(MessageDeframer.java:413)
        at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:276)
        at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:178)
        at io.grpc.internal.AbstractStream$TransportState.deframe(AbstractStream.java:210)
        at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:262)
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl$WebsocketTransportState.inboundDataReceived(AbstractWebsocketStreamImpl.java:25)
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl.inboundDataReceived(AbstractWebsocketStreamImpl.java:99)
        at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.onMessage(MultiplexedWebSocketServerStream.java:218)
        at io.grpc.servlet.web.websocket.AbstractWebSocketServerStream.lambda$onOpen$0(AbstractWebSocketServerStream.java:115)
        at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.invoke(AbstractDecodedMessageSink.java:61)
        at org.eclipse.jetty.websocket.jakarta.common.messages.DecodedBinaryMessageSink.onWholeMessage(DecodedBinaryMessageSink.java:60)
        at org.eclipse.jetty.websocket.core.internal.messages.ByteBufferMessageSink.accept(ByteBufferMessageSink.java:64)
        at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.accept(AbstractDecodedMessageSink.java:80)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.acceptMessage(JakartaWebSocketFrameHandler.java:592)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onBinary(JakartaWebSocketFrameHandler.java:642)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onFrame(JakartaWebSocketFrameHandler.java:243)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.lambda$onFrame$1(WebSocketCoreSession.java:671)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1485)
        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.onFrame(WebSocketCoreSession.java:671)
        at org.eclipse.jetty.websocket.core.AbstractExtension.nextIncomingFrame(AbstractExtension.java:145)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:236)
        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.emitFrame(DemandingFlusher.java:145)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.inflate(PerMessageDeflateExtension.java:480)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.handle(PerMessageDeflateExtension.java:413)
        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.process(DemandingFlusher.java:169)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243)
        at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:369)
        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.onFrame(DemandingFlusher.java:104)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.onFrame(PerMessageDeflateExtension.java:93)
        at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:120)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onFrame(WebSocketCoreSession.java:481)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:262)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:455)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.lang.Thread.run(Thread.java:829)
caused by:
java.lang.ClassNotFoundException: datetime
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.lang.Class.forName0(Class.java:-2)
        at java.lang.Class.forName(Class.java:398)
        at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1068)
        at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:1134)
        at io.deephaven.base.ClassUtil.getJavaType(ClassUtil.java:26)
        at io.deephaven.base.ClassUtil.lookupClass(ClassUtil.java:42)
        at io.deephaven.extensions.barrage.util.BarrageUtil.lambda$convertArrowSchema$13(BarrageUtil.java:417)
        at io.deephaven.extensions.barrage.util.BarrageUtil.lambda$convertArrowSchema$5(BarrageUtil.java:377)
        at io.deephaven.extensions.barrage.util.BarrageUtil.convertArrowSchema(BarrageUtil.java:414)
        at io.deephaven.extensions.barrage.util.BarrageUtil.convertArrowSchema(BarrageUtil.java:369)
        at io.deephaven.extensions.barrage.util.ArrowToTableConverter.parseSchema(ArrowToTableConverter.java:166)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoPutObserver.onNext(ArrowFlightUtil.java:168)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoPutObserver.onNext(ArrowFlightUtil.java:110)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
        at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
        at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.lambda$onMessage$0(SessionServiceGrpcImpl.java:352)
        at io.deephaven.server.session.SessionServiceGrpcImpl.rpcWrapper(SessionServiceGrpcImpl.java:393)
        at io.deephaven.server.session.SessionServiceGrpcImpl$SessionServiceCallListener.onMessage(SessionServiceGrpcImpl.java:352)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:333)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:316)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:835)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.messagesAvailable(ServerImpl.java:846)
        at io.grpc.internal.AbstractStream$TransportState.messagesAvailable(AbstractStream.java:182)
        at io.grpc.internal.MessageDeframer.processBody(MessageDeframer.java:413)
        at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:276)
        at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:178)
        at io.grpc.internal.AbstractStream$TransportState.deframe(AbstractStream.java:210)
        at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:262)
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl$WebsocketTransportState.inboundDataReceived(AbstractWebsocketStreamImpl.java:25)
        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl.inboundDataReceived(AbstractWebsocketStreamImpl.java:99)
        at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.onMessage(MultiplexedWebSocketServerStream.java:218)
        at io.grpc.servlet.web.websocket.AbstractWebSocketServerStream.lambda$onOpen$0(AbstractWebSocketServerStream.java:115)
        at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.invoke(AbstractDecodedMessageSink.java:61)
        at org.eclipse.jetty.websocket.jakarta.common.messages.DecodedBinaryMessageSink.onWholeMessage(DecodedBinaryMessageSink.java:60)
        at org.eclipse.jetty.websocket.core.internal.messages.ByteBufferMessageSink.accept(ByteBufferMessageSink.java:64)
        at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.accept(AbstractDecodedMessageSink.java:80)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.acceptMessage(JakartaWebSocketFrameHandler.java:592)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onBinary(JakartaWebSocketFrameHandler.java:642)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onFrame(JakartaWebSocketFrameHandler.java:243)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.lambda$onFrame$1(WebSocketCoreSession.java:671)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1485)
        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.onFrame(WebSocketCoreSession.java:671)
        at org.eclipse.jetty.websocket.core.AbstractExtension.nextIncomingFrame(AbstractExtension.java:145)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:236)
        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.emitFrame(DemandingFlusher.java:145)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.inflate(PerMessageDeflateExtension.java:480)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.handle(PerMessageDeflateExtension.java:413)
        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.process(DemandingFlusher.java:169)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243)
        at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:369)
        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.onFrame(DemandingFlusher.java:104)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.onFrame(PerMessageDeflateExtension.java:93)
        at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:120)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onFrame(WebSocketCoreSession.java:481)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:262)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:455)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.lang.Thread.run(Thread.java:829)
```

**Comment by niloc132** [comment]
New stack trace split to https://github.com/deephaven/deephaven-core/issues/3971

**Comment by mofojed** [comment]
@niloc132 Should we disable setting `LOCAL_TIME` as a type from UI at all right now and just fall back to `String`?
