### ISSUE TITLE
Parquet writing issue... probably incorrect flatness propagation... maybe merge?

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#3969]
```
Caused by: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted rowSet.lastRowKey() == rowSet.size() - 1, instead rowSet == {0-54334574,55567076-56110661}.
    at io.deephaven.base.verify.Assert.fail(Assert.java:100)
    at io.deephaven.base.verify.Assert.assertion(Assert.java:133)
    at io.deephaven.engine.table.impl.QueryTable.isFlat(QueryTable.java:1358)
    at io.deephaven.engine.table.impl.QueryTable.propagateFlatness(QueryTable.java:3253)
    at io.deephaven.engine.table.impl.QueryTable.lambda$viewOrUpdateView$35(QueryTable.java:1640)
    at io.deephaven.engine.table.impl.BaseTable.initializeWithSnapshot(BaseTable.java:1247)
    at io.deephaven.engine.table.impl.QueryTable.lambda$viewOrUpdateView$36(QueryTable.java:1624)
    at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
    at io.deephaven.engine.table.impl.QueryTable.lambda$viewOrUpdateView$37(QueryTable.java:1618)
    at io.deephaven.engine.table.impl.QueryTable$MemoizedResult.getOrCompute(QueryTable.java:3495)
    at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3464)
    at io.deephaven.engine.table.impl.QueryTable.viewOrUpdateView(QueryTable.java:1617)
    at io.deephaven.engine.table.impl.QueryTable.view(QueryTable.java:1595)
    at io.deephaven.engine.table.impl.QueryTable.view(QueryTable.java:109)
    at io.deephaven.parquet.table.ParquetTableWriter.pretransformTable(ParquetTableWriter.java:334)
    at io.deephaven.parquet.table.ParquetTableWriter.write(ParquetTableWriter.java:252)
    at io.deephaven.parquet.table.ParquetTableWriter.write(ParquetTableWriter.java:196)
    at io.deephaven.parquet.table.ParquetTableWriter.write(ParquetTableWriter.java:228)
    at io.deephaven.parquet.table.ParquetTools.writeParquetTableImpl(ParquetTools.java:695)
    ... 8 more
```

**Comment by rcaudy** [comment]
User reports that this was the result of a merge between a parquet table and a blink table (from Kafka, presumably).

**Comment by rcaudy** [comment]
I cannot find anything suggesting that we mark merge results flat. I'm wondering if this was a different kind of issue. Will circle back with the user who reported this issue.

**Comment by rcaudy** [comment]
Consulted a bit with the reporting user. I think this might have been caused by writing from a transform without correct dependency checks. Closing for now, will re-open if new information contradicts that theory.
