### ISSUE TITLE
Numba vectorized functions with string inputs fail

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#4058]
A user wanted to try Numba vectorized functions using string inputs.  Numba documentation for this is very light.  I eventually came up with this query:

```python
from deephaven import time_table
from numba import vectorize, types

t = time_table("PT00:00:01").update(["X=ii", "S=ii%2 == 0 ? `ABC` : `DEFGHIJ`"])

@vectorize([types.int64(types.string)])
def sfunc(s):
    return len(s)

t2 = t.update("SF = sfunc(S)")
```

In `v0.25.0`, this fails with:
```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'numba.core.errors.NumbaNotImplementedError'>
Value: unicode_type cannot be represented as a NumPy dtype
Line: 159
Namespace: as_dtype
File: /opt/deephaven/venv/lib/python3.10/site-packages/numba/np/numpy_support.py
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/opt/deephaven/venv/lib/python3.10/site-packages/numba/np/ufunc/decorators.py", line 131, in wrap
  File "/opt/deephaven/venv/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py", line 175, in add
  File "/opt/deephaven/venv/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py", line 227, in _compile_for_argtys
  File "/opt/deephaven/venv/lib/python3.10/site-packages/numba/np/ufunc/ufuncbuilder.py", line 210, in _build_element_wise_ufunc_wrapper
  File "/opt/deephaven/venv/lib/python3.10/site-packages/numba/np/ufunc/ufuncbuilder.py", line 210, in <listcomp>
  File "/opt/deephaven/venv/lib/python3.10/site-packages/numba/np/numpy_support.py", line 159, in as_dtype

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
        at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:195)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
        at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:195)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$1(AbstractScriptSession.java:150)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:149)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:160)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:148)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:150)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:119)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:175)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1352)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:896)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:174)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
```

It is not clear if this is a problem with numba or how the query is using numba.

**Comment by jmao-denver** [comment]
It definitely is an unsupported mapping in numba, see the source file for details.
https://github.com/numba/numba/blob/39fc546dda0a21b90432e60f3c5e8c34f7892024/numba/np/numpy_support.py

I tried using `types.pyobject' and `forceobj=True' option in the `@vectorize` decorator call, it actually hard crashed DH server with SIGSEGV.

I noticed that in this example, the Python function call can be DH vectorized. I don't think the performance will be as good as numba vectorized if it works, but maybe it is acceptable to the user?
