### ISSUE TITLE
Parallel task double-close error

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#4063]
```
2023-06-16T18:06:14.054Z | [32mEFAULT.refreshThread[0;39m | [34m INFO[0;39m | [33me.u.i.PeriodicUpdateGraph[0;39m | Update Graph Processor cycleTime=55456.845ms, safePointTime=0ms, safePointTimePct=0%, safePointSyncTime=0ms, lockWaitTime=19.015ms, yieldTime=0ms, sleepTime=0ms
Initiating shutdown due to: Unexpected iteration job error
java.lang.IllegalStateException: IterationManager-334517681's reference count has been decreased more than increased
	at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:218)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onTaskError(JobScheduler.java:173)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.accept(JobScheduler.java:279)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.run(JobScheduler.java:251)
	at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.call(PyObject.java:449)
	at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted closed == false, instead closed == true.
		at io.deephaven.base.verify.Assert.fail(Assert.java:100)
		at io.deephaven.base.verify.Assert.eqFalse(Assert.java:1022)
		at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:285)
		at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.accept(JobScheduler.java:278)
		... 9 more
```

**Comment by rcaudy** [comment]
I'm still trying to track this down.

**Comment by edumx90s** [comment]
![Screenshot_20230625_164643](https://github.com/deephaven/deephaven-core/assets/137843547/9f68759c-1e10-4018-a1ec-9e76f18d09fa)
Hi, just want to give more information, I get this error when I use the rolling methods, Im consuming data with redpanda and Im using linux, usually plot charts,  I  use .where(filters=["!isNull(s)"])  to clear the data maybe can be relevant.

**Comment by rcaudy** [comment]
I've made a few changes to `JobScheduler` to try to help us find this, or prevent it, but I have been unable to reproduce or find a smoking gun.
