### ISSUE TITLE
Unexpected error in satisfaction check/probe

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#4064]
```
2023-06-22T16:16:01.187Z | aph-updateExecutor-1 | ERROR | rumentedTableListenerBase | Uncaught exception for entry= by(NORMAL:[Partition{column=ColumnName(__CONSTITUENT__), includeGroupByColumns=true}]), a
dded.size()=1, modified.size()=0, removed.size()=1, shifted.size()=0, modifiedColumnSet={}:
java.lang.IllegalStateException: Missing value in probe
        at io.deephaven.engine.table.impl.by.typed.incopenagg.gen.IncrementalAggOpenHasherLong.probe(IncrementalAggOpenHasherLong.java:122)
        at io.deephaven.engine.table.impl.by.OperatorAggregationStateManagerOpenAddressedAlternateBase.probeTable(OperatorAggregationStateManagerOpenAddressedAlternateBase.java:148)
        at io.deephaven.engine.table.impl.by.IncrementalChunkedOperatorAggregationStateManagerOpenAddressedBase.remove(IncrementalChunkedOperatorAggregationStateManagerOpenAddressedBase.java:174)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doRemovesForChunk(ChunkedOperatorAggregationHelper.java:653)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doRemoves(ChunkedOperatorAggregationHelper.java:647)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.computeDownstreamIndicesAndCopyKeys(ChunkedOperatorAggregationHelper.java:520)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$1.onUpdate(ChunkedOperatorAggregationHelper.java:259)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:297)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:275)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
2023-06-22T16:16:01.193Z | aph-updateExecutor-1 | ERROR | .AsyncClientErrorNotifier | Error in table update: java.lang.IllegalStateException: Missing value in probe
        at io.deephaven.engine.table.impl.by.typed.incopenagg.gen.IncrementalAggOpenHasherLong.probe(IncrementalAggOpenHasherLong.java:122)
        at io.deephaven.engine.table.impl.by.OperatorAggregationStateManagerOpenAddressedAlternateBase.probeTable(OperatorAggregationStateManagerOpenAddressedAlternateBase.java:148)
        at io.deephaven.engine.table.impl.by.IncrementalChunkedOperatorAggregationStateManagerOpenAddressedBase.remove(IncrementalChunkedOperatorAggregationStateManagerOpenAddressedBase.java:174)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doRemovesForChunk(ChunkedOperatorAggregationHelper.java:653)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doRemoves(ChunkedOperatorAggregationHelper.java:647)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.computeDownstreamIndicesAndCopyKeys(ChunkedOperatorAggregationHelper.java:520)
        at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$1.onUpdate(ChunkedOperatorAggregationHelper.java:259)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:297)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:275)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
2023-06-22T16:16:01.245Z | aph-updateExecutor-4 | ERROR | e.u.i.PeriodicUpdateGraph | PeriodicUpdateGraph-updateExecutor-4: Exception while executing PeriodicUpdateGraph notification: Merged Notification 2
86297628 PartitionedTable.merge(): io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted oldRecordedStep < step, instead oldRecordedStep == 620, step == 620.
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)
        at io.deephaven.engine.table.impl.util.StepUpdater.forceUpdateRecordedStep(StepUpdater.java:65)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:343)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
2023-06-22T16:16:01.253Z | aph-updateExecutor-2 | ERROR | e.u.i.PeriodicUpdateGraph | PeriodicUpdateGraph-updateExecutor-2: Exception while executing PeriodicUpdateGraph notification: Merged Notification 1
313397605 PartitionedTable.merge(): io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted oldRecordedStep < step, instead oldRecordedStep == 620, step == 620.
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)
        at io.deephaven.engine.table.impl.util.StepUpdater.forceUpdateRecordedStep(StepUpdater.java:65)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:343)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
2023-06-22T16:16:01.254Z | aph-updateExecutor-1 | ERROR | e.u.i.PeriodicUpdateGraph | PeriodicUpdateGraph-updateExecutor-1: Exception while executing PeriodicUpdateGraph notification: Merged Notification 5
63567161 PartitionedTable.merge(): io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted oldRecordedStep < step, instead oldRecordedStep == 620, step == 620.
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)
        at io.deephaven.engine.table.impl.util.StepUpdater.forceUpdateRecordedStep(StepUpdater.java:65)
        at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:343)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
```

**Comment by rcaudy** [comment]
This is on our radar, but I haven't had time to track it down yet.

**Comment by rcaudy** [comment]
I think this is caused by a user error in previous value tracking. That said, I think this is also manifesting the same Kafka ingest satisfaction bug as, and a MergedListener bug, too. Hijacking the ticket for those fixes.

```
        at io.deephaven.base.verify.Assert.fail(Assert.java:87)
        at io.deephaven.base.verify.Assert.statementNeverExecuted(Assert.java:222)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.<init>(InstrumentedTableListenerBase.java:240)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.<init>(InstrumentedTableUpdateListener.java:32)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener.getNotification(InstrumentedTableUpdateListener.java:23)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener.getNotification(InstrumentedTableUpdateListener.java:10)
        at io.deephaven.engine.table.impl.BaseTable.lambda$notifyListeners$8(BaseTable.java:704)
        at io.deephaven.util.datastructures.SimpleReferenceManager.forEach(SimpleReferenceManager.java:136)
        at io.deephaven.engine.table.impl.BaseTable.notifyListeners(BaseTable.java:703)
        at io.deephaven.stream.StreamToBlinkTableAdapter.doRefresh(StreamToBlinkTableAdapter.java:364)
        at io.deephaven.stream.StreamToBlinkTableAdapter.run(StreamToBlinkTableAdapter.java:296)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$UpdateSourceRefreshNotification.run(PeriodicUpdateGraph.java:1836)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
```
