### ISSUE TITLE
Kafka ingestion needs to be resilient against partially consumed records if KafkaIngester.maxErrs > 0

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#4147]
If users set the property `KafkaIngester.maxErrs` to be greater than `0` (the default), any partially processed records may result in mis-aligned chunks in the downstream publisher. We need to make the parsing code for Simple, JSON, and Avro resilient against this class of cascading failure if we want to make it generally possible to ignore errors.

**Comment by rcaudy** [comment]
Symptomatic logs:
```
11:14:33.702 ERROR ph-updateExecutor-22 | .AsyncClientErrorNotifier | Error in table update: io.deephaven.util.MultiException: Multiple errors encountered while ingesting stream: 
Cause 0: java.lang.IllegalArgumentException: argument "content" is null
Cause 1: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 2: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 3: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 4: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 5: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 6: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 7: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 8: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 9: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 10: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 11: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 12: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 13: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 14: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 15: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 16: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 17: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 18: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 19: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 20: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 21: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 22: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 23: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 24: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 25: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 26: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 27: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 28: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406
Cause 29: java.lang.IllegalStateException: Publisher chunks have size mismatch: 1409, 1409, 1409, 1409, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406, 1406

        at io.deephaven.util.MultiException.maybeWrapInMultiException(MultiException.java:55)
        at io.deephaven.stream.StreamToBlinkTableAdapter.run(StreamToBlinkTableAdapter.java:232)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$UpdateSourceRefreshNotification.run(PeriodicUpdateGraph.java:1836)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:829)
caused by:
java.lang.IllegalArgumentException: argument "content" is null
        at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4980)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3217)
        at io.deephaven.kafka.ingest.JsonNodeUtil.makeJsonNode(JsonNodeUtil.java:29)
        at io.deephaven.kafka.KafkaTools.lambda$static$5(KafkaTools.java:2094)
        at io.deephaven.kafka.ingest.KafkaStreamPublisher.consumeRecords(KafkaStreamPublisher.java:270)
        at io.deephaven.kafka.KafkaTools$SimpleKafkaRecordConsumer.consume(KafkaTools.java:2302)
        at io.deephaven.kafka.ingest.KafkaIngester.pollOnce(KafkaIngester.java:354)
        at io.deephaven.kafka.ingest.KafkaIngester.consumerLoop(KafkaIngester.java:284)
        at java.lang.Thread.run(Thread.java:829)
```

**Comment by rcaudy** [comment]
Note that the current `SimpleKafkaRecordConsumer` effectively ignored the setting anyway, since it immediately forwards any errors in consumption.
