### ISSUE TITLE
assertion failure in head

### ISSUE THREAD

**Issue by cpwright** [deephaven/deephaven-core#4196]
**Description**

**Steps to reproduce**

On a DnD worker run the following script:

```
pel=db.liveTable("DbInternal", "ProcessEventLog").where("Date=today()")
mypel=pel.where("ProcessInfoId=`" + System.getenv(io.deephaven.enterprise.dispatcher.client.DispatcherClientEnvironment.KEY_PROCESS_INFO_ID) + "`")
myport = mypel.where("LogEntry.startsWith(`Server started on port`)").head(1)
println(myport.columnIterator("LogEntry").next())
```

The output is:
```
Server started on port 24116
aph-updateExecutor-7 | rumentedTableListenerBase | Uncaught exception for entry= slice(0, 1), added.size()=1, modified.size()=0, removed.size()=0, shifted.size()=0, modifiedColumnSet={}:
aph-updateExecutor-7 | .AsyncClientErrorNotifier | Error in table update: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted update.removed.empty().
```

It is probably worth noting that the last command will add some rows to mypell, which will not meet the filter of myport.

**Expected results**

No assertion.

**Actual results**

```
aph-updateExecutor-7 | rumentedTableListenerBase | Uncaught exception for entry= slice(0, 1), added.size()=1, modified.size()=0, removed.size()=0, shifted.size()=0, modifiedColumnSet={}:
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted update.removed.empty().
        at io.deephaven.base.verify.Assert.fail(Assert.java:87)
        at io.deephaven.base.verify.Assert.assertion(Assert.java:117)
        at io.deephaven.engine.table.impl.BaseTable.notifyListeners(BaseTable.java:670)
        at io.deephaven.engine.table.impl.SliceLikeOperation.onUpdate(SliceLikeOperation.java:164)
        at io.deephaven.engine.table.impl.SliceLikeOperation$3.onUpdate(SliceLikeOperation.java:126)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:297)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:275)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
```
**Versions**
 - Deephaven: 0.25.3

**Comment by rcaudy** [comment]
I think we are mistakenly propagating add-only attributes in some scenarios when we should not.

**Comment by rcaudy** [comment]
We think this is fixed in main already. For a community reproducer, make two slow-ticking time tables and merge them together, so that rows will be added in the middle, and be sure to design the experiment such that rows must be deleted from the head result.

**Comment by rcaudy** [comment]
If we do make a change, we should look at L141:
```
                resultTable.setAttribute(Table.APPEND_ONLY_TABLE_ATTRIBUTE, true);
```
Any time that we can set APPEND_ONLY, we can also set ADD_ONLY.

**Comment by malhotrashivam** [comment]
Like Ryan mentioned, this issue is present in v0.25.3 and has been fixed in the main. Following is an example that reproduces this assertion:
```
source1 = timeTable("PT00:00:01").update("X=i")
source2 = timeTable("PT00:00:05").update("X=i")
merged = merge(source1, source2)
merged.setAttribute(Table.ADD_ONLY_TABLE_ATTRIBUTE, true)
mySlice = merged.head(5)
```
In this example, mySlice wrongfully gets tagged as ADD_ONLY even though rows can be removed from this slice.
The fix is present in this [change](https://github.com/deephaven/deephaven-core/pull/4066) and has been merged in the main.

Sidenote: Merged is technically not an ADD_ONLY table but for the sake of reproducing this bug, we have forcefully tagged it as ADD_ONLY.
