### ISSUE TITLE
ClassCastException during kafka publishing

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#4222]
Based on the stacktrace, this is hitting a key_spec SimpleKeyOrValueSerializer whose source column seems to include a formula derived from Instants. It's possible the column source in the SimpleKeyOrValueSerializer constructor needs a `ReinterpretUtils#maybeConvertToPrimitive`.

```
java.lang.ClassCastException: class io.deephaven.engine.table.ChunkSource$1 cannot be cast to class io.deephaven.engine.table.impl.sources.ArraySourceHelper$FillContext (io.deephaven.engine.table.ChunkSource$1 and io.deephaven.engine.table.impl.sources.ArraySourceHelper$FillContext are in unnamed module of loader 'app')
        at io.deephaven.engine.table.impl.sources.LongArraySource.fillPrevChunk(LongArraySource.java:530)
        at io.deephaven.engine.table.impl.sources.NanosBasedTimeArraySource.fillPrevChunk(NanosBasedTimeArraySource.java:119)
        at io.deephaven.engine.table.impl.DefaultChunkSource$WithPrev.getPrevChunkByFilling(DefaultChunkSource.java:67)
        at io.deephaven.engine.table.impl.sources.NanosBasedTimeArraySource.getPrevChunk(NanosBasedTimeArraySource.java:130)
        at io.deephaven.engine.table.impl.sources.UnionColumnSource$GetContext.getPrevChunk(UnionColumnSource.java:434)
        at io.deephaven.engine.table.impl.sources.UnionColumnSource.getPrevChunk(UnionColumnSource.java:596)
        at io.deephaven.temp.c_89ca4838630f120e7e732b7ba789ae2b3c94d6b6f32f8c4081718e9fc6412f6cv61_0.Formula.fillPrevChunk(Formula.java:133)
        at io.deephaven.engine.table.impl.select.Formula.getPrevChunk(Formula.java:170)
        at io.deephaven.engine.table.impl.sources.ViewColumnSource.getPrevChunk(ViewColumnSource.java:211)
        at io.deephaven.temp.c_0aa05cbd625d10acb49a866677cdeca92752c735a20322f2d6a79e981d0b7390v61_0.Formula.fillPrevChunk(Formula.java:134)
        at io.deephaven.engine.table.impl.select.Formula.getPrevChunk(Formula.java:170)
        at io.deephaven.engine.table.impl.sources.ViewColumnSource.getPrevChunk(ViewColumnSource.java:211)
        at io.deephaven.kafka.publish.SimpleKeyOrValueSerializer.handleChunk(SimpleKeyOrValueSerializer.java:35)
        at io.deephaven.kafka.publish.PublishToKafka.publishMessages(PublishToKafka.java:141)
        at io.deephaven.kafka.publish.PublishToKafka$PublishListener.onUpdate(PublishToKafka.java:264)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:324)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:308)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1288)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1339)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1868)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
```

**Comment by supernomad** [comment]
Understood, and sounds good I will leave it off for now just to continue testing out the new logic we are working on. Will follow this ticket for updates on the possible bug. Just wanted to let you know that if I don't call that this error goes away. Hopefully helpful 😅

**Comment by rcaudy** [comment]
That makes perfect sense; the nature of the bug is that it requires hitting a particular code path in `LongArraySource.fillPrevChunk`. I don't see any way to hit the issue if you're always doing current-value fetches, but that exposes you to correctness issues if you're doing shifts, removes, or modifies.
