### ISSUE TITLE
Error reading timestamps in parquet data

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#4250]
We encountered an NPE in a DHC worker in DHE (20230511) while reading a directory of `*.snappy.parquet files`. The error occurs when we try to look at a `java.time.Instant` column (it did not occur when we did a `.view()` to only include other columns with other datatypes).

(The same error occurred when reading a single parquet file within the directory.)

```
Internal Error '827c8f66-7d7c-42eb-a2ce-14cfdcf4fafd' io.deephaven.UncheckedDeephavenException: Failure to execute snapshot function with unchanged clock
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1208)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1059)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:613)
        at io.deephaven.server.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:2203)
        at io.deephaven.server.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:1315)
        at io.deephaven.server.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:991)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:174)
        at java.lang.Thread.run(Thread.java:833)
caused by: java.lang.NullPointerException: Cannot invoke "org.apache.parquet.io.api.Binary.getBytesUnsafe()" because "results[ri]" is null
        at io.deephaven.parquet.table.pagestore.topage.ToInstantPageFromInt96.convertResult(ToInstantPageFromInt96.java:94)
        at io.deephaven.parquet.table.pagestore.topage.ToInstantPageFromInt96.convertResult(ToInstantPageFromInt96.java:24)
        at io.deephaven.parquet.table.pagestore.topage.ToPage.toPage(ToPage.java:84)
        at io.deephaven.parquet.table.pagestore.ColumnChunkPageStore.toPage(ColumnChunkPageStore.java:91)
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPage(VariablePageSizeColumnChunkPageStore.java:122)
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:161)
        at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:20)
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:75)
        at io.deephaven.parquet.table.region.ParquetColumnRegionBase.fillChunk(ParquetColumnRegionBase.java:50)
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:79)
        at io.deephaven.engine.table.impl.sources.regioned.DeferredColumnRegionBase.fillChunk(DeferredColumnRegionBase.java:72)
        at io.deephaven.engine.page.PageStore.fillChunk(PageStore.java:79)
        at io.deephaven.engine.table.impl.sources.regioned.RegionedColumnSourceBase.fillChunk(RegionedColumnSourceBase.java:51)
        at io.deephaven.engine.table.impl.sources.RedirectedColumnSource$FillContext.doOrderedFillAscending(RedirectedColumnSource.java:807)
        at io.deephaven.engine.table.impl.sources.RedirectedColumnSource.doFillChunk(RedirectedColumnSource.java:520)
        at io.deephaven.engine.table.impl.sources.RedirectedColumnSource.fillChunk(RedirectedColumnSource.java:498)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.getSnapshotDataAsChunkList(ConstructSnapshot.java:1500)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.serializeAllTable(ConstructSnapshot.java:1399)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.lambda$constructBackplaneSnapshotInPositionSpace$2(ConstructSnapshot.java:608)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1129)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1059)
        at io.deephaven.engine.table.impl.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:613)
        at io.deephaven.server.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:2203)
        at io.deephaven.server.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:1315)
        at io.deephaven.server.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:991)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:174)
        at java.lang.Thread.run(Thread.java:833)
```

**Comment by rcaudy** [comment]
Looks like we just need an appropriate null check. We should audit the `ToPage.convertResult` implementations generally.

**Comment by malhotrashivam** [comment]
There seems to be a missing null check in the reader code for int96 timestamps. Following is a python  example for reproducing this issue. Note that Deephavan's writing code doesn't currently support writing int96 based timestamps. Therefore, I had to do the writing through pyarrow. Although, the feature is deprecated in pyarrow as well.

```
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from deephaven import empty_table
from deephaven.parquet import write, read

# Create a table with null timestamp value and write it down. This will use int64 as a backend for timestamps.
dh_table = empty_table(5).update(formulas=[
    "nullInstantColumn = (Instant)null",
])
write(dh_table, "/Users/shivammalhotra/deephaven/projects/data_from_dh.parquet")

# Read it as a pandas dataframe and write it as parquet with int96 timestamps
dataframe = pd.read_parquet("/Users/shivammalhotra/deephaven/projects/data_from_dh.parquet")
table = pa.Table.from_pandas(dataframe)
pq.write_table(table, '/Users/shivammalhotra/deephaven/projects/data_from_pyarrow.parquet', use_deprecated_int96_timestamps=True)

# At this point, we have a parquet file which has timestamp columns stored as int96 and containing null values.
# Now read it using deephaven parquet code and we will get an exception for incorrectly reading nulls.

result_table = read('/Users/shivammalhotra/deephaven/projects/data_from_pyarrow.parquet')
```

I can add a fix for it very soon. 
Also, as Ryan mentioned, other implementations of convertResult also might have same issue.
