### ISSUE TITLE
Python client does not handle `pyarrow.flight` missing on some platforms

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#4327]
On Mac M1, I am unable to run the python client.

```
  File "client.py", line 1, in <module>
    from pydeephaven import Session
  File "/Users/chip/TEMP/plugin/venv/lib/python3.8/site-packages/pydeephaven/__init__.py", line 26, in <module>
    from .session import Session
  File "/Users/chip/TEMP/plugin/venv/lib/python3.8/site-packages/pydeephaven/session.py", line 14, in <module>
    import pyarrow.flight as paflight
  File "/Users/chip/TEMP/plugin/venv/lib/python3.8/site-packages/pyarrow/flight.py", line 18, in <module>
    from pyarrow._flight import (  # noqa:F401
ModuleNotFoundError: No module named 'pyarrow._flight'
```

This link seems to indicate that flight is not present on some platforms, like M1.
https://community.dremio.com/t/how-to-run-dremio-client-applications-in-python-with-no-arrow-flight-package/9314

The presence can be easily tested using:
```
>>> import pyarrow.flight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chip/TEMP/plugin/venv/lib/python3.8/site-packages/pyarrow/flight.py", line 18, in <module>
    from pyarrow._flight import (  # noqa:F401
ModuleNotFoundError: No module named 'pyarrow._flight'
```

**Comment by chipkent** [comment]
This problem has been resolved.  On Mac, python installed via `brew` must be 3.11.  Arrow does not provide `flight` for earlier versions.
