### ISSUE TITLE
Engine thinks deephaven.learn compute func is using `i`, `ii`, or `k` when it's not.

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#4337]
**Description**

While trying to reproduce a bug for a user with deephaven.learn, I encountered a separate bug. Their bug contained the variable `i` in a function passed to `computer.compute`. It resulted in the error:

```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: failed to complete the learn function. : RuntimeError: java.lang.IllegalArgumentException: Formula '__computer.compute(k)' uses i, ii, k, or column array variables, and is not safe to refresh. Note that some usages, such as on an append-only table are safe. To allow unsafe refreshing formulas, set the system property io.deephaven.engine.table.impl.select.AbstractFormulaColumn.allowUnsafeRefreshingFormulas.
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 792, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: java.lang.IllegalArgumentException: Formula '__computer.compute(k)' uses i, ii, k, or column array variables, and is not safe to refresh. Note that some usages, such as on an append-only table are safe. To allow unsafe refreshing formulas, set the system property io.deephaven.engine.table.impl.select.AbstractFormulaColumn.allowUnsafeRefreshingFormulas.
	at io.deephaven.engine.table.impl.select.AbstractFormulaColumn.validateSafeForRefresh(AbstractFormulaColumn.java:104)
	at io.deephaven.engine.table.impl.select.SwitchColumn.validateSafeForRefresh(SwitchColumn.java:130)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:145)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:59)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$32(QueryTable.java:1445)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$33(QueryTable.java:1427)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3468)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1426)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1404)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:109)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:94)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:197)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:197)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:150)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:149)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:160)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:148)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:150)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:105)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:175)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1380)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:921)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:78)
	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.call(PyObject.java:449)
	at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/learn/__init__.py", line 148, in learn
    return (table
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 794, in update
    raise DHError(e, "table update operation failed.") from e
deephaven.dherror.DHError: table update operation failed. : RuntimeError: java.lang.IllegalArgumentException: Formula '__computer.compute(k)' uses i, ii, k, or column array variables, and is not safe to refresh. Note that some usages, such as on an append-only table are safe. To allow unsafe refreshing formulas, set the system property io.deephaven.engine.table.impl.select.AbstractFormulaColumn.allowUnsafeRefreshingFormulas.
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 792, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: java.lang.IllegalArgumentException: Formula '__computer.compute(k)' uses i, ii, k, or column array variables, and is not safe to refresh. Note that some usages, such as on an append-only table are safe. To allow unsafe refreshing formulas, set the system property io.deephaven.engine.table.impl.select.AbstractFormulaColumn.allowUnsafeRefreshingFormulas.
	at io.deephaven.engine.table.impl.select.AbstractFormulaColumn.validateSafeForRefresh(AbstractFormulaColumn.java:104)
	at io.deephaven.engine.table.impl.select.SwitchColumn.validateSafeForRefresh(SwitchColumn.java:130)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:145)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:59)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$32(QueryTable.java:1445)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$33(QueryTable.java:1427)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3468)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1426)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1404)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:109)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:94)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:197)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:197)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:150)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:149)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:160)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:148)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:150)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:105)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:175)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1380)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:921)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:78)
	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.call(PyObject.java:449)
	at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)



Line: 168
Namespace: learn
File: /opt/deephaven/venv/lib/python3.10/site-packages/deephaven/learn/__init__.py
Traceback (most recent call last):
  File "<string>", line 56, in <module>
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/learn/__init__.py", line 168, in learn

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
        at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:197)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
        at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:197)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:150)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:149)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:160)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:148)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:150)
        at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:87)
        at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:105)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:175)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1380)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:921)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:78)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
```

So, I fixed the function using the variable `i` to use `idx` instead. Subsequent runs _still_ generated this same error. Scripts in question are below.

**Steps to reproduce**

This needs `SciKit-Learn` installed.

First script generates some fake data

```python
from deephaven import time_table

trigger = time_table("PT00:00:05")
live_propensity = time_table("PT0.833333s").update([
    "website_id = randomLong(0, 10000)",
    "device_id = randomLong(1000000000000000000, 2000000000000000000)",
    "count_visits = randomLong(0, 2)",
    "count_conversion = randomLong(0, 2)",
    "count_view_category = randomLong(0, 2)",
    "count_view_item = randomLong(0, 2)",
    "count_add_to_cart = randomLong(0, 2)",
    "amount = randomLong(0, 2)",
    "last_updated = Timestamp"
]).drop_columns(["Timestamp"])

live_propensity_data = live_propensity.snapshot_when(trigger_table=trigger)
```

Second script creates a dummy random forest classifier

```python
# Create a random forest classifier and fit it
from deephaven import empty_table
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
import pandas as pd, numpy as np

colnames = ["Col" + str(idx) for idx in range(6)]

X, y = make_classification(
    n_samples=1000,
    n_features=6,
    n_informative=2,
    n_redundant=0,
    random_state=0,
    shuffle=False
)
neigh = RandomForestClassifier(max_depth=2, random_state=0)
neigh.fit(pd.DataFrame(data=X, columns=colnames), y)
```

Third script does ML stuff

```python
# Deephaven imports
from deephaven.learn import gather
from deephaven import learn
import os
from joblib import dump, load
import numpy as np
import warnings

# warnings.filterwarnings("ignore", category=UserWarning)

# Load the model
# neigh = load('neigh.joblib')
print(neigh)

# Use the RandomForest classifier on the dataset
def use_rf(features):
    if features.ndim == 1:
        features = np.expand_dims(features, 0)

    predictions = np.zeros(len(features))
    probabilities = np.zeros((len(features), 2))  
    for idx in range(0, len(features)):
        predictions[idx] = neigh.predict([features[idx]])
        probabilities[idx, :] = neigh.predict_proba([features[idx]])[0]  

    return predictions, probabilities

# A function to gather data from columns into a NumPy array of doubles
def table_to_array_double(rows, cols):
    return gather.table_to_numpy_2d(rows, cols, np_type=np.int_)

# A function to extract a list element and cast to an integer
def get_predicted_class(data, idx):
    return int(data[0][idx]) 

def get_predicted_proba(data, idx):
    return data[1][idx, 1]  # We want the probability of the second class

# Function to categorize probabilities
def categorize_probability(data, idx):
    prob = data[1][idx, 1]
    if prob > 0.95:
        return "highest"
    elif prob > 0.75:
        return "high"
    elif prob > 0.5:
        return "moderate"
    elif prob > 0.25:
        return "mild"
    elif prob > 0.05:
        return "low"
    else:
        return "lowest"

# Use the learn function to create a new table that contains classified values
propensity_predictions_live = learn.learn(
    table=live_propensity_data,
    model_func=use_rf,
    inputs=[learn.Input(["count_visits", "count_conversion", "count_view_category", "count_view_item", "count_add_to_cart", "amount"], table_to_array_double)],
    outputs=[
        learn.Output("ClassifiedClass", get_predicted_class, "int"),
        learn.Output("ClassifiedProbability", get_predicted_proba, "double"),
        learn.Output("ClassifiedCategory", categorize_probability, "java.lang.String")  # Added this line for categories
    ],
    batch_size=150
)
```

Note that the function `use_rf` was the one that used the variable `i` instead of `idx` where it is now. I restarted DH, and even deleted and recreated the container, and still got the error.

**Expected results**

The code to work, or complain about something else.

**Actual results**

The error in the description.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 0.26.0
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by jjbrosnan** [comment]
The deephaven.learn code (`py/server/deephaven/learn/__init__.py`) explicitly uses the variable `k`, which is probably causing this. The answer should either be to change the use of `k` or automatically enable the flag to allow "unsafe" usage of it when it's called.

**Comment by ilyanoskov** [comment]
I am experiencing the same issue
