### ISSUE TITLE
Unable to export a custom object using `connection.on_data` from Plugin framework

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#4338]
**Description**

If you try and export a custom object in the `connection.on_data` method in the Plugin framework, you get an error. You can export `Table` objects using the same method successfully, and also export a custom object if it's assigned to it's own variable name, but trying to export the object in a `MessageStream` throws an error:

**Steps to reproduce**
1. Install custom plugin that has a custom object that exports another custom object type in a MessageStream

**Expected results**

1. Custom object should export correctly

**Actual results**

1. Exception is thrown. Object is not exported successfully.

**Additional details and attachments**
```sh
2023-08-18T15:08:40.392Z | heduler-Concurrent-1 | ERROR | i.d.s.s.SessionService    | Internal Error '032d618f-9f48-4127-9fb5-7250c41d48ca' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'ValueError'>
Value: cannot convert a Python 'TextInput' to a Java 'java.lang.Object'
Line: 51
Namespace: on_data
File: /home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven_internal/plugin/object/__init__.py
Traceback (most recent call last):
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven_internal/plugin/object/__init__.py", line 87, in create_client_connection
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/ui/__init__.py", line 64, in create_client_connection
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/ui/__init__.py", line 32, in start
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/ui/__init__.py", line 41, in send_result
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven_internal/plugin/object/__init__.py", line 51, in on_data

        at org.jpy.PyLib.callAndReturnValue(Native Method)
        at org.jpy.PyObject.call(PyObject.java:474)
        at org.jpy.PyObject.call(PyObject.java:482)
        at io.deephaven.server.plugin.python.ObjectTypeAdapter.compatibleClientConnection(ObjectTypeAdapter.java:58)
        at io.deephaven.plugin.type.ObjectTypeBase.clientConnection(ObjectTypeBase.java:23)
        at io.deephaven.server.object.ObjectServiceGrpcImpl$SendMessageObserver.lambda$onNext$0(ObjectServiceGrpcImpl.java:145)
        at io.deephaven.server.object.ObjectServiceGrpcImpl$SendMessageObserver$EnqueuedStreamOperation.lambda$run$0(ObjectServiceGrpcImpl.java:97)
        at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1380)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:921)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:78)
        at org.jpy.PyLib.callAndReturnObject(Native Method)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
**Versions**
Engine Version: 0.28.0
Web UI Version: 0.45.1
Java Version: 11.0.20
Barrage Version: 0.6.0

**Comment by niloc132** [comment]
This issue is broader - the original ObjectType implementation also mentioned https://github.com/deephaven/deephaven-core/issues/1775, but I have concerns about the workaround that even let the first iteration work, since nothing is explicitly calling PyObject.close() to decr the python reference count on that object (so any exported object leaks forever).

We likely have existing bugs around this: any pure-python plugin being exported ends up with a SessionState.ExportObject instance wrapping a PyObject, but never closing it even when the ExportObject is released, causing that object instance to leak - matplotlib charts, pandas dataframes, plotly charts are all affected by this.

I think at the very least our "wrap/unwrap" logic (which assumes that python objects wrap java objects when transiting jpy) needs to be made more generic, something like pythonify()/javaify() to cover all of our cases:

1. Object passed from Java into python:
    1. Java instance, has no python wrapper, should be used as a jpy.JType directly.
    2. Java instance, has a python wrapper type, should be wrapped (likely in Python code) before being used in Python.
    3. PyObject instance, wrapped with LivenessNode/etc, so that when it is no longer referenced from a session it can be decr'd from python. This signifies that the Python object is not itself a wrapper around a Java object, so the underlying Python instance can be passed directly into Python.
5. Object passed from Python into Java:
    1. Java instance with no python wrapper, should be passed directly into Java
    2. Python instance wrapping a Java instance, should be unwrapped and the Java instance passed directly into Java.
    3. Python instance, not wrapping a Java instance. Will be represented in Java as a PyObject, should further be wrapped in a LivenessNode/etc, so that it can be correctly cleaned up when that PyObject will no longer be used from Java.
