### ISSUE TITLE
update_by assertion failure

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#4358]
Triggered while creating kafka query.

```
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < updateGraph.clock().currentStep(), instead lastNotificationStep == 933, updateGraph.clock().currentStep() == 933.
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)
        at io.deephaven.engine.table.impl.BaseTable.notifyListenersOnError(BaseTable.java:806)
        at io.deephaven.engine.table.impl.updateby.UpdateBy.deliverUpdateError(UpdateBy.java:1059)
        at io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.onError(UpdateBy.java:1010)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:183)
        at io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
        at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:292)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:284)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:256)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
        at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1322)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1373)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1911)
        at org.jpy.PyLib.callAndReturnObject(Native Method)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Code looked something like:

```python
from deephaven import dtypes
from deephaven.execution_context import get_exec_ctx
from deephaven.stream.kafka.consumer import (
    consume_to_partitioned_table,
    simple_spec,
    TableType,
    ALL_PARTITIONS_SEEK_TO_BEGINNING,
)
from deephaven.table import Table
from deephaven.updateby import cum_max


ctx = get_exec_ctx()


def max_date(t: Table) -> Table:
    with ctx:
        return (
            t.update_by([cum_max(["MaxTimestamp = KafkaTimestamp"])])
            .update_view(["Date=formatDate(MaxTimestamp, java.time.ZoneOffset.UTC)"])
            .drop_columns(["MaxTimestamp"])
        )


# todo: is there a way to do this without merge()? ie, re-partition?
my_partitioned_table = (
    consume_to_partitioned_table(
        kafka_config={
            "bootstrap.servers": "myserver:9092",
        },
        topic="my_topic",
        offsets=ALL_PARTITIONS_SEEK_TO_BEGINNING,
        key_spec=simple_spec("KafkaKey", dtypes.byte_array),
        value_spec=simple_spec("KafkaValue", dtypes.byte_array),
        table_type=TableType.append(),
    )
    .transform(max_date)
    .merge()
    .partition_by(["KafkaPartition", "Date"])
)
```

I'm not sure if other interactive snippets I executed may have caused the error.

**Comment by devinrsmith** [comment]
Potentially related to satisfaction changes. Maybe https://github.com/deephaven/deephaven-core/pull/4096

**Comment by devinrsmith** [comment]
Appears to be an error while error handling.
