### ISSUE TITLE
ClassCastException aggregating timestamp column produced by FunctionGeneratedTableFactory

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#4425]
It is possible for the engine to become confused about the column source backing a timestamp (`Instant`) column and then crash when updating an aggregation (at least when the timestamp column is an aggregation key).

Exception (v0.27.1):

```
ph-updateExecutor-8 | rumentedTableListenerBase | Uncaught exception for entry= by(NORMAL:[ColumnAggregation{spec=AggSpecFirst{}, pair=PairImpl{input=ColumnName(Price), output=ColumnName(FirstPrice)}}, ColumnAggregation{spec=AggSpecLast{}, pair=PairImpl{input=ColumnName(Price), output=ColumnName(LastPrice)}}, ColumnAggregation{spec=AggSpecMin{}, pair=PairImpl{input=ColumnName(Price), output=ColumnName(MinPrice)}}, ColumnAggregation{spec=AggSpecMax{}, pair=PairImpl{input=ColumnName(Price), output=ColumnName(MaxPrice)}}, Count{column=ColumnName(NRows)}]), added.size()=0, modified.size()=1000, removed.size()=0, shifted.size()=0, modifiedColumnSet={Ticker,RowIdx,Timestamp,Price,TimeBin}:
java.lang.ClassCastException: class io.deephaven.chunk.ResettableWritableObjectChunk cannot be cast to class io.deephaven.chunk.WritableLongChunk (io.deephaven.chunk.ResettableWritableObjectChunk and io.deephaven.chunk.WritableLongChunk are in unnamed module of loader 'app')
	at io.deephaven.chunk.WritableChunk.asWritableLongChunk(WritableChunk.java:131)
	at io.deephaven.engine.table.impl.util.copy.LongCopyKernel.conditionalCopy(LongCopyKernel.java:67)
	at io.deephaven.engine.table.impl.sources.LongArraySource.lambda$fillPrevChunk$6(LongArraySource.java:601)
	at io.deephaven.engine.table.impl.sources.LongArraySource.lambda$fillPrevChunk$7(LongArraySource.java:658)
	at io.deephaven.engine.rowset.RowSequence.lambda$forAllRowKeyRanges$1(RowSequence.java:182)
	at io.deephaven.engine.rowset.impl.singlerange.SingleRangeMixin.forEachRowKeyRange(SingleRangeMixin.java:25)
	at io.deephaven.engine.rowset.RowSequence.forAllRowKeyRanges(RowSequence.java:181)
	at io.deephaven.engine.table.impl.sources.LongArraySource.fillPrevChunk(LongArraySource.java:639)
	at io.deephaven.engine.table.impl.sources.NanosBasedTimeArraySource.fillPrevChunk(NanosBasedTimeArraySource.java:124)
	at io.deephaven.engine.table.impl.DefaultChunkSource$WithPrev.getPrevChunkByFilling(DefaultChunkSource.java:67)
	at io.deephaven.engine.table.impl.DefaultChunkSource$WithPrev.getPrevChunk(DefaultChunkSource.java:53)
	at io.deephaven.temp.c_b2b6cac0cc6a1a8ef4185d38525ae03700e28518e3d8abedaf56d32d3b50517bv61_0.Formula.fillPrevChunk(Formula.java:123)
	at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillPrevChunk(ViewColumnSource.java:227)
	at io.deephaven.engine.table.impl.sources.UnboxedTimeBackedColumnSource.fillPrevChunk(UnboxedTimeBackedColumnSource.java:98)
	at io.deephaven.engine.table.impl.DefaultChunkSource$WithPrev.getPrevChunkByFilling(DefaultChunkSource.java:67)
	at io.deephaven.engine.table.impl.DefaultChunkSource$WithPrev.getPrevChunk(DefaultChunkSource.java:53)
```

Here is an example query. If you add a ticker to `my_input_table`, it works. When you add another ticker (causing the function-generated table to refresh), the aggregation blows up.

```python
import deephaven.dtypes as dht
from deephaven import input_table
from deephaven.jcompat import j_lambda
from deephaven.table import Table
from deephaven import agg
import random

my_col_defs = {
    "Ticker":dht.string
}
my_input_table = input_table(col_defs = my_col_defs)

exec_context = execution_context.get_exec_ctx()

def create_table_function():
    with exec_context:
        print('Running create_table_function')
        current_ticker_table = my_input_table.last_by()


        price_holder = [random.uniform(50, 150)]
        def get_and_update_price(px_holder) -> float:
            px_holder.set(0, px_holder.get(0) * random.uniform(0.95, 1.05))
            return px_holder.get(0)

        generated_table_fake_data = current_ticker_table\
            .select(["Ticker", "RowIdx= java.util.stream.LongStream.range(0,1000).toArray()"])\
            .ungroup()\
            .update(["Timestamp = now() + RowIdx * SECOND", "Price = get_and_update_price(price_holder)"])

        return generated_table_fake_data

create_table_function_py = j_lambda(create_table_function, jpy.get_type('java.util.function.Supplier'))
function_generated_table = Table(jpy.get_type('io.deephaven.engine.table.impl.util.FunctionGeneratedTableFactory').create(create_table_function_py, my_input_table.j_table))

ten_sec_bars = function_generated_table.update_view("TimeBin=upperBin(Timestamp, 10*SECOND)").agg_by([
    agg.first("FirstPrice=Price"),
    agg.last("LastPrice=Price"),
    agg.min_("MinPrice=Price"),
    agg.max_("MaxPrice=Price"),
    agg.count_("NRows")
], ["Ticker", "TimeBin"])
```

If you replace `.update(["Timestamp = now() + RowIdx * SECOND"` with `.update(["Timestamp = epochNanos(now() + RowIdx * SECOND)"`, it works.

**Comment by rcaudy** [comment]
The bug is in:
`io.deephaven.engine.table.impl.sources.LongArraySource#fillPrevChunk(io.deephaven.engine.table.ColumnSource.FillContext, io.deephaven.chunk.WritableChunk<? super io.deephaven.chunk.attributes.Values>, io.deephaven.engine.rowset.RowSequence, java.util.function.LongFunction<R>)`:
```
                effectiveContext.copyKernel.conditionalCopy(destination, baseInput, overInput,
                        inUse, srcOffset, destOffset.intValue(), length);
```
We cannot copy into the destination chunk, as this is a _converting_ `fillPrevChunk`. Probably the solution lies in looking at the converting `fillChunk` implementation.
