### ISSUE TITLE
test_function_generated_table flakiness

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#4476]
test_function_generated_table python tests is causing failures in unrelated PRs. Seen a few so far, there more be more:

```
2023-09-08T22:02:38.2501245Z ======================================================================
2023-09-08T22:02:38.2501890Z FAIL [0.021s]: test_generated_table_2triggers (tests.test_function_generated_table.TableTestCase)
2023-09-08T22:02:38.2502793Z ----------------------------------------------------------------------
2023-09-08T22:02:38.2503320Z Traceback (most recent call last):
2023-09-08T22:02:38.2503935Z   File "/python/tests/test_function_generated_table.py", line 107, in test_generated_table_2triggers
2023-09-08T22:02:38.2504545Z     self.assertEqual(result_int, 54321)
2023-09-08T22:02:38.2505034Z AssertionError: 12345 != 54321
```

```
2023-09-08T20:48:57.1451774Z ======================================================================
2023-09-08T20:48:57.1452760Z FAIL [0.032s]: test_generated_table_1trigger (tests.test_function_generated_table.TableTestCase)
2023-09-08T20:48:57.1453750Z ----------------------------------------------------------------------
2023-09-08T20:48:57.1454456Z Traceback (most recent call last):
2023-09-08T20:48:57.1455282Z   File "/python/tests/test_function_generated_table.py", line 53, in test_generated_table_1trigger
2023-09-08T20:48:57.1456158Z     self.assertEqual(result_str, 'test string')
2023-09-08T20:48:57.1456947Z AssertionError: None != 'test string'
2023-09-08T20:48:57.1457340Z 
2023-09-08T20:48:57.1457681Z ======================================================================
2023-09-08T20:48:57.1458531Z FAIL [0.011s]: test_generated_table_2triggers (tests.test_function_generated_table.TableTestCase)
2023-09-08T20:48:57.1459442Z ----------------------------------------------------------------------
2023-09-08T20:48:57.1460143Z Traceback (most recent call last):
2023-09-08T20:48:57.1460961Z   File "/python/tests/test_function_generated_table.py", line 84, in test_generated_table_2triggers
2023-09-08T20:48:57.1461849Z     self.assertEqual(result_str, 'test string')
2023-09-08T20:48:57.1462625Z AssertionError: None != 'test string'
2023-09-08T20:48:57.1463025Z 
2023-09-08T20:48:57.1463434Z ----------------------------------------------------------------------
2023-09-08T20:48:57.1464108Z Ran 352 tests in 273.385s
2023-09-08T20:48:57.1464474Z 
2023-09-08T20:48:57.1464783Z FAILED (failures=2, skipped=8)
2023-09-08T20:48:57.1465161Z 
```

**Comment by devinrsmith** [comment]
I would also suggest looking to remove the call to `sleep`.
