### ISSUE TITLE
Python array type inference fails for integer and float arrays

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#4656]
The below is run on v0.29.0rc.

This code runs fine:

```python
from typing import List, Sequence, Tuple
from deephaven import empty_table
import numpy as np

def f1() -> np.ndarray[str]:
    return ["a"]

def f2() -> Sequence[str]:
    return ["a"]

def f3() -> List[str]:
    return ["a"]

def f4() -> Tuple[str]:
    return ["a"]


t = empty_table(10).update(["X1 = f1()","X2 = f2()","X3 = f3()","X4 = f4()"])

t2 = t.ungroup()
```

But if I change to an integer type parameter, it fails:

```python
from typing import List, Sequence, Tuple
from deephaven import empty_table
import numpy as np

def f1() -> np.ndarray[np.int64]:
    return np.ndarray([1,2],dtype=np.int64)

def f2() -> Sequence[int]:
    return [1,2]

def f3() -> List[int]:
    return [1,2]

def f4() -> Tuple[int]:
    return (1,2)


t = empty_table(10).update(["X1 = f1()","X2 = f2()","X3 = f3()","X4 = f4()"])

t2 = t.ungroup()
```
Error:
```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : TypeError: only integer scalar arrays can be converted to a scalar index
Traceback (most recent call last):
  File "/private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/table.py", line 893, in update
    return Table(j_table=self.j_table.update(*formulas))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: io.deephaven.engine.table.impl.select.FormulaEvaluationException: In formula: X1 = (long[]) f1.call()
	at io.deephaven.temp.c_c6e86993d50d6ccdbab2f88ed083f3a928195c562ef8e1a38474716dd8d09da6v55_0.Formula.applyFormulaPerItem(Formula.java:149)
	at io.deephaven.temp.c_c6e86993d50d6ccdbab2f88ed083f3a928195c562ef8e1a38474716dd8d09da6v55_0.Formula.lambda$fillChunkHelper$4(Formula.java:138)
	at io.deephaven.engine.rowset.RowSequence.lambda$forAllRowKeys$0(RowSequence.java:175)
	at io.deephaven.engine.rowset.impl.singlerange.SingleRangeMixin.forEachRowKey(SingleRangeMixin.java:17)
	at io.deephaven.engine.rowset.RowSequence.forAllRowKeys(RowSequence.java:174)
	at io.deephaven.temp.c_c6e86993d50d6ccdbab2f88ed083f3a928195c562ef8e1a38474716dd8d09da6v55_0.Formula.fillChunkHelper(Formula.java:136)
	at io.deephaven.temp.c_c6e86993d50d6ccdbab2f88ed083f3a928195c562ef8e1a38474716dd8d09da6v55_0.Formula.fillChunk(Formula.java:114)
	at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillChunk(ViewColumnSource.java:219)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doApplyUpdate(SelectColumnLayer.java:412)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$doSerialApplyUpdate$2(SelectColumnLayer.java:264)
	at io.deephaven.engine.util.systemicmarking.SystemicObjectTracker.executeSystemically(SystemicObjectTracker.java:56)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doSerialApplyUpdate(SelectColumnLayer.java:263)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$1(SelectColumnLayer.java:212)
	at io.deephaven.engine.table.impl.util.ImmediateJobScheduler.submit(ImmediateJobScheduler.java:23)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.onAllRequiredColumnsCompleted(SelectColumnLayer.java:210)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:589)
	at io.deephaven.engine.table.impl.select.analyzers.BaseLayer.applyUpdate(BaseLayer.java:76)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$30(QueryTable.java:1502)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$31(QueryTable.java:1452)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3458)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1451)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1429)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:109)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:94)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:194)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:194)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:147)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:149)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:160)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:148)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:147)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:84)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:102)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:175)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1384)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:920)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:78)
	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.call(PyObject.java:449)
	at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
caused by java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: failed to create a Java long array. : TypeError: only integer scalar arrays can be converted to a scalar index
Traceback (most recent call last):
  File "/private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/dtypes.py", line 276, in array
    return jpy.array(dtype.j_type, seq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: only integer scalar arrays can be converted to a scalar index

Line: 278
Namespace: array
File: /private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/dtypes.py
Traceback (most recent call last):
  File "/private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/table.py", line 434, in wrapper
  File "/private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/dtypes.py", line 278, in array

	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.callMethod(PyObject.java:432)
	at io.deephaven.engine.util.PyCallableWrapperJpyImpl.call(PyCallableWrapperJpyImpl.java:210)
	at io.deephaven.temp.c_c6e86993d50d6ccdbab2f88ed083f3a928195c562ef8e1a38474716dd8d09da6v55_0.Formula.applyFormulaPerItem(Formula.java:147)
	... 53 more


Line: 895
Namespace: update
File: /private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/table.py
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "/private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/table.py", line 895, in update

	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:194)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:194)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:147)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:149)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:160)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:148)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:147)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:84)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:102)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:175)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1384)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:920)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:78)
	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.call(PyObject.java:449)
	at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

A similar failure happens with floating point arrays:
```python

from typing import List, Sequence, Tuple
from deephaven import empty_table
import numpy as np

def f1() -> np.ndarray[np.float64]:
    return np.ndarray([1.1,2.2],dtype=np.float64)

def f2() -> Sequence[float]:
    return [1.1,2.2]

def f3() -> List[float]:
    return [1,1,2.2]

def f4() -> Tuple[float]:
    return (1.1,2.2)


t = empty_table(10).update(["X1 = f1()","X2 = f2()","X3 = f3()","X4 = f4()"])

t2 = t.ungroup()
```

Removing the type hint results in the prior behavior, so it is likely a minor regression.  The following works fine.

```python
def f5():
    return (1.1,2.2)


t = empty_table(10).update(["X5 = f5()"])
```

**Comment by jmao-denver** [comment]
There is a user mistake in the test code, specifically `np.array` should be used in place of `np.ndarray`.  The modified code
```
from typing import List, Sequence, Tuple
from deephaven import empty_table
import numpy as np

def f1() -> np.ndarray[np.int64]:
    return np.array([1,2],dtype=np.int64)

def f2() -> Sequence[int]:
    return [1,2]

def f3() -> List[int]:
    return [1,2]

def f4() -> Tuple[int]:
    return (1,2)


t = empty_table(10).update(["X1 = f1()","X2 = f2()","X3 = f3()","X4 = f4()"])

t2 = t.ungroup()
```
and
```
from typing import List, Sequence, Tuple
from deephaven import empty_table
import numpy as np

def f1() -> np.ndarray[np.float64]:
    return np.array([1.1,2.2],dtype=np.float64)

def f2() -> Sequence[float]:
    return [1.1,2.2]

def f3() -> List[float]:
    return [1.1,2.2]

def f4() -> Tuple[float]:
    return (1.1,2.2)


t = empty_table(10).update(["X1 = f1()","X2 = f2()","X3 = f3()","X4 = f4()"])

t2 = t.ungroup()
```
work as expected.

**Comment by chipkent** [comment]
I agree that there was user error.  My bad.  But, `np.array` calls `np.ndarray` under the covers.  This can be observed via:

```python

import numpy as np

x = np.array([1,2])
y = np.ndarray([1,2])

print(x)
print(y)

print(type(x))
print(type(y))

z = np.ndarray(shape=[2])
z[:] = [1,2]
print(z)
print(type(z))
```
<img width="178" alt="image" src="https://github.com/deephaven/deephaven-core/assets/5250374/614a0d12-9051-4399-aac9-8b3dfbb737ec">

Now, the case can be reformulated using only `np.ndarray`.  Here it runs fine.  

```python
from typing import List, Sequence, Tuple
from deephaven import empty_table
import numpy as np

def f1() -> np.ndarray[np.int64]:
    return np.array([1,2],dtype=np.int64)

def f2() -> Sequence[int]:
    return [1,2]

def f3() -> List[int]:
    return [1,2]

def f4() -> Tuple[int]:
    return (1,2)

def f5() -> np.ndarray[np.int64]:
    z = np.ndarray(shape=[2], dtype=np.int64)
    z[:] = [1,2]
    return z

t = empty_table(10).update(["X1 = f1()","X2 = f2()","X3 = f3()","X4 = f4()", "X5 = f5()"])

t2 = t.ungroup()
```

I think the problem is that we need to raise an error if the shape of `np.ndarray` is improper, which it was in my original failing example.  Here is a tweak to the example that fails because of shape:

```python
from typing import List, Sequence, Tuple
from deephaven import empty_table
import numpy as np

def f1() -> np.ndarray[np.int64]:
    return np.array([1,2],dtype=np.int64)

def f2() -> Sequence[int]:
    return [1,2]

def f3() -> List[int]:
    return [1,2]

def f4() -> Tuple[int]:
    return (1,2)

def f5() -> np.ndarray[np.int64]:
    z = np.ndarray(shape=[2,2], dtype=np.int64)
    z[:] = [1,2]
    return z

t = empty_table(10).update(["X1 = f1()","X2 = f2()","X3 = f3()","X4 = f4()", "X5 = f5()"])

t2 = t.ungroup()
```

The output error is `TypeError: only integer scalar arrays can be converted to a scalar index`, which only makes sense after going through this whole exercise.  I think a clear error would have avoided this bug report.

**Comment by jmao-denver** [comment]
jpy only supports 1D array, so it is not a bad idea to make it explicit.
