### ISSUE TITLE
Calling imported signature-less numpy ufuncs would raise a formula compilation exception

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#4737]
```
from deephaven import empty_table
import numpy as np
from numba import vectorize, float64
from numpy import sin as npsin
from time import time

@vectorize([float64(float64)])
def npsin2(x):
    return np.sin(x)

n_tries = 1
source = empty_table(100_000).update("X = 0.1 * i")

start = time()
for idx in range(n_tries):
    result_builtin = source.update("Y = sin(X)")
end = time()
elapsed = (end - start) / n_tries
print(elapsed)

start = time()
for idx in range(n_tries):
    result_builtin = source.update("Y = npsin(X)")
end = time()
elapsed = (end - start) / n_tries
print(elapsed)
```
This script fails with the following exception.  Function `npsin2` is the workaround.
```
Having trouble with the following expression:
Full expression           : npsin(X)
Expression having trouble : 
Exception type            : java.lang.RuntimeException
Exception message         : Error in Python interpreter:
Type: <class 'ValueError'>
Value: callable <ufunc 'sin'> is not supported by signature
Line: 2558
Namespace: _signature_from_callable
File: /usr/lib/python3.10/inspect.py
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 390, in _encode_signature
  File "/usr/lib/python3.10/inspect.py", line 3247, in signature
  File "/usr/lib/python3.10/inspect.py", line 2995, in from_callable
  File "/usr/lib/python3.10/inspect.py", line 2558, in _signature_from_callable
```

This looks to be a regression introduced in the Py UDF return-type inference change.

**Comment by jmao-denver** [comment]
Two things we could do here:
1. fix the wrong assumption that any Python function always has a signature (most do, but numpy ufuncs don't, and there might be other types of callables that don't)
2. since a numpy ufunc is a “vectorized" wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs, there might be a way to add numpy ufuncs to the vectorization support
