### ISSUE TITLE
grpc server log shows a resource not found issue for Calendars whenever a Python session is made.

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#487]
As first reported by @jcferretti in the slack channel and investigated briefly by @devinrsmith. I think we need to fix it if we will allow users to use Calendars.

```
grpc-api_1    | java.io.IOException: None of the specified resource paths exist: [.//configs/calendar]
grpc-api_1    |         at io.deephaven.util.files.ResourceResolution.findResources(ResourceResolution.java:145)
grpc-api_1    |         at io.deephaven.util.files.ResourceResolution.findResources(ResourceResolution.java:145)
grpc-api_1    |         at io.deephaven.util.calendar.Calendars.load(Calendars.java:144)
grpc-api_1    |         at io.deephaven.util.calendar.Calendars.loadProperty(Calendars.java:115)
grpc-api_1    |         at io.deephaven.util.calendar.Calendars.<init>(Calendars.java:105)
grpc-api_1    |         at io.deephaven.util.calendar.Calendars.<clinit>(Calendars.java:38)
grpc-api_1    |         at org.jpy.PyLib.executeScript(Native Method)
grpc-api_1    |         at org.jpy.PyObject.executeScript(PyObject.java:158)
grpc-api_1    |         at io.deephaven.db.util.PythonEvaluatorJpy.runScript(PythonEvaluatorJpy.java:61)
grpc-api_1    |         at io.deephaven.db.util.IrisDbPythonSession.runScript(IrisDbPythonSession.java:120)
grpc-api_1    |         at io.deephaven.db.util.IrisDbPythonSession.<init>(IrisDbPythonSession.java:81)
grpc-api_1    |         at io.deephaven.grpc_api.console.python.PythonConsoleSessionModule.bindIrisDbPythonSession(PythonConsoleSessionModule.java:30)
grpc-api_1    |         at io.deephaven.grpc_api.console.python.PythonConsoleSessionModule_BindIrisDbPythonSessionFactory.bindIrisDbPythonSession(PythonConsoleSessionModule_BindIrisDbPythonSessionFactory.java:35)
grpc-api_1    |         at io.deephaven.grpc_api.console.python.PythonConsoleSessionModule_BindIrisDbPythonSessionFactory.get(PythonConsoleSessionModule_BindIrisDbPythonSessionFactory.java:26)
grpc-api_1    |         at io.deephaven.grpc_api.console.python.PythonConsoleSessionModule_BindIrisDbPythonSessionFactory.get(PythonConsoleSessionModule_BindIrisDbPythonSessionFactory.java:8)
grpc-api_1    |         at io.deephaven.grpc_api.console.python.PythonConsoleSessionModule_BindScriptSessionFactory.get(PythonConsoleSessionModule_BindScriptSessionFactory.java:31)
grpc-api_1    |         at io.deephaven.grpc_api.console.python.PythonConsoleSessionModule_BindScriptSessionFactory.get(PythonConsoleSessionModule_BindScriptSessionFactory.java:10)
grpc-api_1    |         at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl.lambda$null$1(ConsoleServiceGrpcImpl.java:67)
grpc-api_1    |         at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:622)
grpc-api_1    |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
grpc-api_1    |         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
grpc-api_1    |         at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:98)
grpc-api_1    |         at java.lang.Thread.run(Thread.java:748)

```

**Comment by danshelley-illumon** [comment]
FYI - Ran in to this again during Windows testing on 9/10/2021.

**Comment by mofojed** [comment]
Closing in favour of #1085
