### ISSUE TITLE
JSAPI Cannot aggregate BigInteger or BigDecimal type columns

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#4877]
**Description**

Using the JS API you cannot aggregate `BigInteger` or `BigDecimal` columns.

**Steps to reproduce**
1. Open a JS API demo page, e.g.: http://localhost:10000/jsapi/table_basic.html
2. Run the following in the browser console, to open a connection, create a table, and use the JS API to aggregate that table (assumes using PSK set to `iris`) :
```
var dh = (await import('./dh-core.js')).default

var c = new dh.CoreClient(window.location.protocol + "//" + window.location.host)
await c.login({type: 'io.deephaven.authentication.psk.PskAuthenticationHandler', token: 'iris'})

console.log('Logged in...')

var connection = await c.getAsIdeConnection()
var ide = await connection.startSession('python')

console.log('Session started...')

await ide.runCode(`
from deephaven import empty_table
t = empty_table(100).update(["x=i%5", "MyBigInteger= new java.math.BigInteger(Integer.toString(i))"])
`)
var t = await connection.getObject({ type: 'Table', name: 't' })

console.log('Table t obtained...', t)

var tt = await t.getTotalsTable({
    "operationMap": {
        "MyBigInteger": ["Sum"]
    },
    "defaultOperation": "Skip"
})

console.log('Totals table tt obtained...', tt)
```

**Expected results**

2. Totals table result with `MyBigInteger` summed, or an error saying `MyBigInteger` aggregations are not supported (they _should_ be supported though)

**Actual results**

2. An error about not having any aggregations:
```
dh-internal.js:2 Uncaught Error: io.deephaven.proto.backplane.grpc.AggregateRequest must have at least one aggregations (5)
    at Object.onEnd (dh-internal.js:1:1535974)
    at dh-internal.js:1:55831
    at dh-internal.js:1:42819
    at Array.forEach (<anonymous>)
    at e.rawOnEnd (dh-internal.js:1:42781)
    at e.onTransportEnd (dh-internal.js:1:42488)
    at Object.$onMessage (dh-core.js:20865:35)
    at MultiplexedWebsocketTransport$3methodref$onMessage$Type.handleEvent_2 [as handleEvent] (dh-core.js:21007:10)
```

**Versions**
 - Deephaven: 0.31.0-dev

**Comment by mofojed** [comment]
Another way to reproduce from the UI:
1. Create a table `complex_ticking` with BigDecimal and BigInteger columns:
```
from deephaven import empty_table, time_table

simple_ticking = time_table("PT00:00:01").update([
        "MyString=new String(`a`+i)",
        "MyInt=new Integer(i)",
        "MyLong=new Long(i)",
        "MyDouble=new Double(i+i/10)",
        "MyFloat=new Float(i+i/10)",
        "MyBoolean=new Boolean(i%2==0)",
        "MyChar= new Character((char) ((i%26)+97))",
        "MyShort=new Short(Integer.toString(i%32767))",
        "MyByte= new java.lang.Byte(Integer.toString(i%127))"])

complex_ticking = simple_ticking.update([
        "MyBigDecimal= new java.math.BigDecimal(i+i/10)",
        "MyBigInteger= new java.math.BigInteger(Integer.toString(i))"
])
```
2. From the table sidebar, select aggregations and add a Sum aggregation
3. Notice that the sum is not being applied to the `MyBigDecimal` or `MyBigInteger` columns.

**Comment by mofojed** [comment]
And a table with actual BigInteger/BigDecimal values that are larger than a long:
```
from deephaven import empty_table, time_table

simple_ticking = time_table("PT00:00:01").update([
        "MyString=new String(`a`+i)",
        "MyInt=new Integer(i)",
        "MyLong=new Long(i)",
        "MyDouble=new Double(i+i/10)",
        "MyFloat=new Float(i+i/10)",
        "MyBoolean=new Boolean(i%2==0)",
        "MyChar= new Character((char) ((i%26)+97))",
        "MyShort=new Short(Integer.toString(i%32767))",
        "MyByte= new java.lang.Byte(Integer.toString(i%127))"])

complex_ticking = simple_ticking.update([
        "MyBigDecimal= new java.math.BigDecimal(Long.toString(Long.MAX_VALUE) + `000` + i+i/10)",
        "MyBigInteger= new java.math.BigInteger(Long.toString(Long.MAX_VALUE) + `000` + Integer.toString(i))"
])
```
