### ISSUE TITLE
ZeroKeyUpdateByManager NPE

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#4952]
This happened after I switched a workload from release 0.28.0 to 0.31.0, so it might not be 0.31.0 specific.

```
Server shutdown: Uncaught exception in thread PeriodicUpdateGraph.DEFAULT.refreshThread

java.lang.NullPointerException: Cannot read field "result" because "this.zeroKeyUpdateBy" is null
io.deephaven.engine.table.impl.updateby.ZeroKeyUpdateByManager.upstreamSatisfied(ZeroKeyUpdateByManager.java:138)
io.deephaven.engine.table.impl.updateby.UpdateBy$UpdateByListener.canExecute(UpdateBy.java:1092)
io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.canExecute(InstrumentedTableListenerBase.java:311)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.flushNormalNotificationsAndCompleteCycle(BaseUpdateGraph.java:564)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.flushNotificationsAndCompleteCycle(BaseUpdateGraph.java:518)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.lambda$doRefresh$5(BaseUpdateGraph.java:915)
io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:33)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.doRefresh(BaseUpdateGraph.java:900)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.refreshAllTables(BaseUpdateGraph.java:887)
io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.refreshAllTables(PeriodicUpdateGraph.java:1090)
io.deephaven.engine.updategraph.impl.BaseUpdateGraph.refreshTablesAndFlushNotifications(BaseUpdateGraph.java:779)
io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.refreshTablesAndFlushNotifications(PeriodicUpdateGraph.java:1014)
io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.lambda$new$0(PeriodicUpdateGraph.java:139)
java.base/java.lang.Thread.run(Thread.java:1583)
```

Not sure if the after shutdown is relevant or not:
```
After shutdown initiated: Unexpected iteration job error
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < updateGraph.clock().currentStep(), instead lastNotificationStep == 14, updateGraph.clock().currentStep() == 14.
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)
        at io.deephaven.engine.table.impl.BaseTable.notifyListenersOnError(BaseTable.java:838)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailureInternalWithDependent(InstrumentedTableListenerBase.java:181)
        at io.deephaven.engine.table.impl.BaseTable$ListenerImpl.onFailureInternal(BaseTable.java:979)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailure(InstrumentedTableListenerBase.java:172)
        at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onError(SelectAndViewAnalyzer.java:637)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:195)
        at io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
        at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:305)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportTaskCompleteAndResumeIteration(JobScheduler.java:288)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
        at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)
        at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:829)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1103)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        Suppressed: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted logicalClock.currentState() == LogicalClock.State.Updating, instead logicalClock.currentState() == Idle, LogicalClock.State.Updating == Updating.
                at io.deephaven.base.verify.Assert.fail(Assert.java:100)
                at io.deephaven.base.verify.Assert.eq(Assert.java:1380)
2023-12-15T07:07:20.421Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Done invoking FIRST shutdown tasks
                at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.addNotification(BaseUpdateGraph.java:398)
                at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.addNotification(PeriodicUpdateGraph.java:403)
                at io.deephaven.engine.table.impl.BaseTable.lambda$notifyListeners$8(BaseTable.java:735)
                at io.deephaven.util.datastructures.SimpleReferenceManager.forEach(SimpleReferenceManager.java:136)
                at io.deephaven.engine.table.impl.BaseTable.notifyListeners(BaseTable.java:734)
2023-12-15T07:07:20.421Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Starting to invoke MIDDLE shutdown tasks
                at io.deephaven.engine.table.impl.SelectOrUpdateListener.completionRoutine(SelectOrUpdateListener.java:126)
                at io.deephaven.engine.table.impl.SelectOrUpdateListener$1.onAllRequiredColumnsCompleted(SelectOrUpdateListener.java:98)
                at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:627)
                at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$prepareParallelUpdate$1(SelectColumnLayer.java:252)
                at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:192)
                ... 12 more
```

Not sure if related at all to https://github.com/deephaven/deephaven-core/issues/4391

**Comment by rcaudy** [comment]
The shutdown error is claiming a double-notify in a select or update.

**Comment by devinrsmith** [comment]
```
Server shutdown: Unexpected iteration job error

java.lang.NullPointerException: Cannot read field "isDirty" because "bucket.windowContexts[winIdx]" is null
io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.cleanUpAfterError(UpdateBy.java:996)
io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.onError(UpdateBy.java:978)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:184)
io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:305)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:297)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:184)
io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:305)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:297)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:184)
io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:305)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:297)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:268)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
io.deephaven.engine.table.impl.util.OperationInitializationPoolJobScheduler.lambda$submit$0(OperationInitializationPoolJobScheduler.java:32)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:180)
io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:191)
io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:179)
io.deephaven.engine.table.impl.OperationInitializationThreadPool$1.lambda$newThread$0(OperationInitializationThreadPool.java:53)
java.base/java.lang.Thread.run(Thread.java:1583)
```

```
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < updateGraph.clock().currentStep(), instead lastNotificationStep == 
        at io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
        at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:305)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:297)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:268)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
        at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)
        at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:829)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1103)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        Suppressed: java.lang.IllegalStateException: May not call prepareForParallelPopulation twice on one clock cycle!
                at io.deephaven.engine.table.impl.sources.LongSparseArraySource.prepareForParallelPopulation(LongSparseArraySource.java:430)
                at io.deephaven.engine.table.impl.updateby.internal.BaseLongUpdateByOperator.prepareForParallelPopulation(BaseLongUpdateByOperator.java:235)
                at io.deephaven.engine.table.impl.updateby.UpdateByWindow.prepareForParallelPopulation(UpdateByWindow.java:189)
                at io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.lambda$prepareForParallelPopulation$11(UpdateBy.java:544)
                at io.deephaven.engine.table.impl.util.JobScheduler.lambda$iterateParallel$1(JobScheduler.java:353)
                at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:255)
                ... 6 more
Initiating shutdown due to: Unexpected iteration job error
java.lang.NullPointerException: Cannot read field "isDirty" because "bucket.windowContexts[winIdx]" is null
        at io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.cleanUpAfterError(UpdateBy.java:996)
        at io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.onError(UpdateBy.java:978)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:184)
        at io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
        at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:305)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:297)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:184)
        at io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
        at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:305)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:297)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:184)
        at io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)
        at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:305)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:297)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:268)
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
        at io.deephaven.engine.table.impl.util.OperationInitializationPoolJobScheduler.lambda$submit$0(OperationInitializationPoolJobScheduler.java:32)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:180)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:191)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:179)
        at io.deephaven.engine.table.impl.OperationInitializationThreadPool$1.lambda$newThread$0(OperationInitializationThreadPool.java:53)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        Suppressed: java.lang.NullPointerException: Cannot read field "isDirty" because "bucket.windowContexts[winIdx]" is null
                at io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.lambda$processWindowOperatorSet$24(UpdateBy.java:833)
                at io.deephaven.engine.table.impl.util.JobScheduler.lambda$iterateParallel$1(JobScheduler.java:353)
                at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:255)
                ... 11 more
 ```

**Comment by devinrsmith** [comment]
The workflow that produces this error is checked in https://github.com/devinrsmith/kafka-to-parquet.

**Comment by devinrsmith** [comment]
```
Initiating shutdown due to: Unexpected iteration job error                                                                                                                                    
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted lastNotificationStep < updateGraph.clock().currentStep(), instead lastNotificationStep == 17, updateGraph.clock().curren
tStep() == 17.                                                                                                                                                                                
        at io.deephaven.base.verify.Assert.fail(Assert.java:100)                                                                                                                              
        at io.deephaven.base.verify.Assert.lt(Assert.java:674)                                                                                                                                
        at io.deephaven.engine.table.impl.BaseTable.notifyListenersOnError(BaseTable.java:838)                                                                                                
        at io.deephaven.engine.table.impl.updateby.UpdateBy.deliverUpdateError(UpdateBy.java:1032)                                                                                            
        at io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.onError(UpdateBy.java:981)                                                                                  
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onReferenceCountAtZero(JobScheduler.java:184)                                                                    
        at io.deephaven.util.referencecounting.ReferenceCounted.tryDecrementReferenceCount(ReferenceCounted.java:180)                                                                         
        at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:216)                                                                            
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:305)                                                                         
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:297)                                                                   
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:268)                                                                       
        at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)                                                                       
        at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)                                                                                 
        at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)                                                                                     
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:829)                               
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1103)                                      
        at java.base/java.lang.Thread.run(Thread.java:1583)                                                                                                                                   
        Suppressed: java.lang.IllegalStateException: May not call prepareForParallelPopulation twice on one clock cycle!                                                                      
                at io.deephaven.engine.table.impl.sources.LongSparseArraySource.prepareForParallelPopulation(LongSparseArraySource.java:430)                                                  
                at io.deephaven.engine.table.impl.updateby.internal.BaseLongUpdateByOperator.prepareForParallelPopulation(BaseLongUpdateByOperator.java:235)
                at io.deephaven.engine.table.impl.updateby.UpdateByWindow.prepareForParallelPopulation(UpdateByWindow.java:189)
                at io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.lambda$prepareForParallelPopulation$11(UpdateBy.java:544)
                at io.deephaven.engine.table.impl.util.JobScheduler.lambda$iterateParallel$1(JobScheduler.java:353)
                at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:255)
                ... 6 more
 ```

**Comment by devinrsmith** [comment]
This doesn't appear to be a new issue, as I think I'm also able to reproduce this now on 0.28.0
