### ISSUE TITLE
Merge error found in `FuzzerTest.testLargeSetOfFuzzerQueriesSimTime`

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#4987]
We encountered an error in `FuzzerTest.testLargeSetOfFuzzerQueriesSimTime` when updating the base layer of a rollup downstream of a merge. We have not been able to reproduce.

[https://scans.gradle.com/s/j5zgbiln2ukre/tests/task/:engine-table:testSerial/details/io.deephaven.engine.table.impl.FuzzerTest/testLargeSetOfFuzzerQueriesSimTime/1/output](url)

```

[PeriodicUpdateGraph-updateExecutor-2] ERROR io.deephaven.engine.table.impl.InstrumentedTableListenerBase - Uncaught exception for entry= by(ROLLUP_BASE:[ColumnAggregation{spec=AggSpecStd{}, pair=ColumnName(MyShort)}, ColumnAggregation{spec=AggSpecMin{}, pair=ColumnName(MyInt)}, ColumnAggregation{spec=AggSpecMax{}, pair=ColumnName(MyDouble)}, ColumnAggregation{spec=AggSpecVar{}, pair=ColumnName(MyBigInteger)}, NullColumns{resultColumns={__ROLLUP__=interface io.deephaven.engine.table.Table}}]), added.size()=1, modified.size()=0, removed.size()=40, shifted.size()=0, modifiedColumnSet={}:
java.lang.NullPointerException: Cannot invoke "io.deephaven.engine.table.Table.getColumnSource(String)" because "table" is null
	at io.deephaven.engine.table.impl.sources.UnionSourceManager$TableSourceLookup.sourceFromTable(UnionSourceManager.java:724)
	at io.deephaven.engine.table.impl.sources.UnionSourceManager$TableSourceLookup.slotToCurrSource(UnionSourceManager.java:709)
	at io.deephaven.engine.table.impl.sources.UnionColumnSource$SlotState.prepare(UnionColumnSource.java:293)
	at io.deephaven.engine.table.impl.sources.UnionColumnSource$FillContext.fillChunkAppend(UnionColumnSource.java:369)
	at io.deephaven.engine.table.impl.sources.UnionColumnSource.fillChunk(UnionColumnSource.java:475)
	at io.deephaven.engine.table.impl.sources.ReversedColumnSource.fillChunk(ReversedColumnSource.java:163)
	at io.deephaven.engine.table.impl.DefaultChunkSource.getChunkByFilling(DefaultChunkSource.java:44)
	at io.deephaven.engine.table.impl.DefaultChunkSource.getChunk(DefaultChunkSource.java:31)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.getChunk(ChunkedOperatorAggregationHelper.java:1537)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.propagateInsertsToOperators(ChunkedOperatorAggregationHelper.java:794)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doInsertsForChunk(ChunkedOperatorAggregationHelper.java:755)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doInserts(ChunkedOperatorAggregationHelper.java:741)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.computeDownstreamIndicesAndCopyKeys(ChunkedOperatorAggregationHelper.java:632)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$1.onUpdate(ChunkedOperatorAggregationHelper.java:281)
	at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
	at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:334)
	at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:316)
	at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:835)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Received error notification: java.lang.NullPointerException: Cannot invoke "io.deephaven.engine.table.Table.getColumnSource(String)" because "table" is null
	at io.deephaven.engine.table.impl.sources.UnionSourceManager$TableSourceLookup.sourceFromTable(UnionSourceManager.java:724)
	at io.deephaven.engine.table.impl.sources.UnionSourceManager$TableSourceLookup.slotToCurrSource(UnionSourceManager.java:709)
	at io.deephaven.engine.table.impl.sources.UnionColumnSource$SlotState.prepare(UnionColumnSource.java:293)
	at io.deephaven.engine.table.impl.sources.UnionColumnSource$FillContext.fillChunkAppend(UnionColumnSource.java:369)
	at io.deephaven.engine.table.impl.sources.UnionColumnSource.fillChunk(UnionColumnSource.java:475)
	at io.deephaven.engine.table.impl.sources.ReversedColumnSource.fillChunk(ReversedColumnSource.java:163)
	at io.deephaven.engine.table.impl.DefaultChunkSource.getChunkByFilling(DefaultChunkSource.java:44)
	at io.deephaven.engine.table.impl.DefaultChunkSource.getChunk(DefaultChunkSource.java:31)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper.getChunk(ChunkedOperatorAggregationHelper.java:1537)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.propagateInsertsToOperators(ChunkedOperatorAggregationHelper.java:794)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doInsertsForChunk(ChunkedOperatorAggregationHelper.java:755)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.doInserts(ChunkedOperatorAggregationHelper.java:741)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$KeyedUpdateContext.computeDownstreamIndicesAndCopyKeys(ChunkedOperatorAggregationHelper.java:632)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$1.onUpdate(ChunkedOperatorAggregationHelper.java:281)
	at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
	at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:334)
	at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:316)
	at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:835)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Exception in thread "PeriodicUpdateGraph-updateExecutor-2" junit.framework.AssertionFailedError: Cannot invoke "io.deephaven.engine.table.Table.getColumnSource(String)" because "table" is null
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:223)
	at io.deephaven.engine.testutil.testcase.RefreshingTableTestCase.reportUpdateError(RefreshingTableTestCase.java:107)
	at io.deephaven.engine.table.impl.util.AsyncClientErrorNotifier.reportError(AsyncClientErrorNotifier.java:29)
	at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailureInternalWithDependent(InstrumentedTableListenerBase.java:186)
	at io.deephaven.engine.table.impl.BaseTable$ListenerImpl.onFailureInternal(BaseTable.java:979)
	at io.deephaven.engine.table.impl.by.ChunkedOperatorAggregationHelper$1.onFailureInternal(ChunkedOperatorAggregationHelper.java:299)
	at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailure(InstrumentedTableListenerBase.java:172)
	at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:364)
	at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:316)
	at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:835)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by nbauernfeind** [comment]
This is the gradle scan output in case we don't get to it before it disappears.
[output.txt](https://github.com/deephaven/deephaven-core/files/13757394/output.txt)
