### ISSUE TITLE
Feature request: Support multidimensional arrays in query strings returned from Python functions

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#4989]
As a user, I'd like to have the ability to more easily use a Python function that returns a multidimensional array. For instance, something like:

```python
from numpy import typing as npt
from deephaven import empty_table
import numpy as np

def testA() -> npt.NDArray[np.double]:
  return np.array([[1,2],[2,3]], dtype=np.double)

table = empty_table(1).update([
  "testA = testA()"
])
```

Thanks to `Miek` in community slack, we now know that you can do this in Deephaven:

```python
import jpy 

def testD():
  arrA = jpy.array("double", [1,2])
  arrB = jpy.array("double", [3,4])
  arrC = jpy.array(jpy.get_type('[D'), [arrA, arrB])
  return arrC

table = empty_table(1).update([
  "double_matrix = (double[][]) testD()",
  "top_left = double_matrix[0][0]",
  "top_right = double_matrix[0][1]",
  "bottom_left = double_matrix[1][0]",
  "bottom_right = double_matrix[1][1]",
])
meta = table.meta_table
```

However, it would be nice if it were easier, as in the first example, to get multi-dimensional arrays into a table.

**Comment by kzk2000** [comment]
Also, do add to this, ideally the type hint in the 1st example, 
`-> npt.NDArray[np.double]` automatically resolves to the double[][] cell type.

and similarly, in the 2nd example, we still need to cast via
`(double[][]) testD() ` as no proper type hint exists yet

**Comment by chipkent** [comment]
Here is the slack thread:  https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703716929535119

```
miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703716929535119)
qq: Does DH natively support double[][] as cell types?
I'm doing this

def testA() -> List[List[np.float64]]
  return [[1,2],[2,3]]

table = my_table.update([
  "testA = testA()"  # returns "org.jpy.PyObject" but how can I cast this to double[][]
])
I tried a few other type hints but none of them seem to cast to Java double[][] - is this doable?
41 replies


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717055811469?thread_ts=1703716929.535119&cid=C0370B33SQ4)
note that "casting" in a lot of these cases is more like a python cast (i.e. coerce/convert) than a java cast (i.e. clarify the actual runtime type and fail if it isn't exactly right) - so, you might need more of a "convert this array, in a loop to another array" function


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717265144259?thread_ts=1703716929.535119&cid=C0370B33SQ4)
[@Colin Alworth](https://deephavencommunity.slack.com/team/U02V6TEGHT6)
 fair, I'm probably abusing proper terms here.
I tried this as well
def testA() -> npt.NDArray:
  return np.array([[1,2],[2,3]])
  
but it also returns org.jpy.PyObject


JJ Brosnan
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717265368959?thread_ts=1703716929.535119&cid=C0370B33SQ4)
Hi Miek, I tried NumPy, but to no avail:
from numpy import typing as npt
from deephaven import empty_table
import numpy as np

def testA() -> npt.NDArray[np.double]:
  return np.array([[1,2],[2,3]], dtype=np.double)

table = empty_table(1).update([
  "testA = testA()"
])


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717295257059?thread_ts=1703716929.535119&cid=C0370B33SQ4)
yeah, same, see above :slightly_smiling_face:


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717307308489?thread_ts=1703716929.535119&cid=C0370B33SQ4)
ah, so if numpy doesn't like it either, it might limit our options for "how can DH do it in a way that numpy will like"


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717320986779?thread_ts=1703716929.535119&cid=C0370B33SQ4)
it works for 1D arrays


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717333357589?thread_ts=1703716929.535119&cid=C0370B33SQ4)
but 2D somehow faults back to org.jpy.PyObject


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717356643179?thread_ts=1703716929.535119&cid=C0370B33SQ4)
1D examples are here: https://deephaven.io/blog/2023/12/19/release-notes-31/


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717444533959?thread_ts=1703716929.535119&cid=C0370B33SQ4)
ok, i misunderstood, jj pointed out my error here


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717501583989?thread_ts=1703716929.535119&cid=C0370B33SQ4)
i think you will need to use jpy.array() directly on your constituent 1d arrays at this time


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717645578329?thread_ts=1703716929.535119&cid=C0370B33SQ4)
jpy.array(
  jpy.get_type('[[D')
  [
    jpy.array(jpy.get_type('[D'), [1.0, 2.0]),
    jpy.array(jpy.get_type('[D'), [3.0, 4.0])
  ]
)


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717692752189?thread_ts=1703716929.535119&cid=C0370B33SQ4)
deephaven.dtypes.array() could be used to create the inner arrays, but i think the effect will be the same


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717726339839?thread_ts=1703716929.535119&cid=C0370B33SQ4)
both the attempt i wrote above or replacing the inner expressions with dtypes.array() calls will give you a java double[][]


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717790348689?thread_ts=1703716929.535119&cid=C0370B33SQ4)
weird, JJ's example above actually throws this error now on my end (maybe I messed up my DH session) BUT... it states that 2D is not supported for array() -- see very last line of this log

from numpy import typing as npt
from deephaven import empty_table
import numpy as np

def testA() -> npt.NDArray[np.double]:
  return np.array([[1,2],[2,3]], dtype=np.double)

table = empty_table(1).update([
  "testA = testA()"
])
meta = test_table.meta_table
-
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : java.lang.RuntimeException: Error in Python interpreter:
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 757, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: io.deephaven.engine.table.impl.select.FormulaEvaluationException: In formula: testA = (double[]) testA.call()
	at io.deephaven.temp.c_1fef7053f4874c6d33ead55a700f8703a99a300aac8143b8c77f3da484f2910dv65_0.Formula.applyFormulaPerItem(Formula.java:149)
	at io.deephaven.temp.c_1fef7053f4874c6d33ead55a700f8703a99a300aac8143b8c77f3da484f2910dv65_0.Formula.lambda$fillChunkHelper$4(Formula.java:138)
	at io.deephaven.engine.rowset.RowSequence.lambda$forAllRowKeys$0(RowSequence.java:175)
	at io.deephaven.engine.rowset.impl.singlerange.SingleRangeMixin.forEachRowKey(SingleRangeMixin.java:17)
	at io.deephaven.engine.rowset.RowSequence.forAllRowKeys(RowSequence.java:174)
	at io.deephaven.temp.c_1fef7053f4874c6d33ead55a700f8703a99a300aac8143b8c77f3da484f2910dv65_0.Formula.fillChunkHelper(Formula.java:136)
	at io.deephaven.temp.c_1fef7053f4874c6d33ead55a700f8703a99a300aac8143b8c77f3da484f2910dv65_0.Formula.fillChunk(Formula.java:114)
	at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillChunk(ViewColumnSource.java:219)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doApplyUpdate(SelectColumnLayer.java:412)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$doSerialApplyUpdate$2(SelectColumnLayer.java:264)
	at io.deephaven.engine.util.systemicmarking.SystemicObjectTracker.executeSystemically(SystemicObjectTracker.java:56)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doSerialApplyUpdate(SelectColumnLayer.java:263)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$1(SelectColumnLayer.java:212)
	at io.deephaven.engine.table.impl.util.ImmediateJobScheduler.submit(ImmediateJobScheduler.java:23)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.onAllRequiredColumnsCompleted(SelectColumnLayer.java:210)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:627)
	at io.deephaven.engine.table.impl.select.analyzers.BaseLayer.applyUpdate(BaseLayer.java:76)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$30(QueryTable.java:1501)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$31(QueryTable.java:1450)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3446)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1449)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1427)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:106)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:94)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:218)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:218)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:151)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:180)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:191)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:179)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:151)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:84)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:102)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:186)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$3(SessionState.java:1499)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:1008)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:97)
	at java.base/java.lang.Thread.run(Thread.java:1583)
caused by java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'ValueError'>
Value: array() does not support multi-dimensional arrays
Line: 276
Namespace: array


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717823373369?thread_ts=1703716929.535119&cid=C0370B33SQ4)
correct - but that appears to be a DH limitation (rather than a numpy one, as i incorrectly stated above)


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717885297559?thread_ts=1703716929.535119&cid=C0370B33SQ4)
[@Colin Alworth](https://deephavencommunity.slack.com/team/U02V6TEGHT6)
 what type hint did you use for your
jpy.array(
  jpy.get_type('[[D')
  [
    jpy.array(jpy.get_type('[D'), [1.0, 2.0]),
    jpy.array(jpy.get_type('[D'), [3.0, 4.0])
  ]
)


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717909359689?thread_ts=1703716929.535119&cid=C0370B33SQ4)
i'm just throwing it together from my read of how deephaven.dtypes.array() works


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703717923075449?thread_ts=1703716929.535119&cid=C0370B33SQ4)
i will try to make a working version soonish
:raised_hands:
1



Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703718003356589?thread_ts=1703716929.535119&cid=C0370B33SQ4)
oh i did it wrong, sorry


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703718020316399?thread_ts=1703716929.535119&cid=C0370B33SQ4)
it might be simpler than i had thought


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703718079104889?thread_ts=1703716929.535119&cid=C0370B33SQ4)
...sorry, i'll give this another shot after dinner, there's something i'm misunderstanding
:white_check_mark:
1



miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703718115842219?thread_ts=1703716929.535119&cid=C0370B33SQ4)
thanks! (edited) 


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703719871299469?thread_ts=1703716929.535119&cid=C0370B33SQ4)
[@Colin Alworth](https://deephavencommunity.slack.com/team/U02V6TEGHT6)
 Still toying with it but got it working so far
with float
arrA = jpy.array("float", [1,2])
arrB = jpy.array("float", [3,4])
arrC = jpy.array(jpy.get_type('[F'), [arrA, arrB])
and double
arrA = jpy.array("double", [1,2])
arrB = jpy.array("double", [3,4])
arrC = jpy.array(jpy.get_type('[D'), [arrA, arrB])
(edited)


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703720451021729?thread_ts=1703716929.535119&cid=C0370B33SQ4)
[@Colin Alworth](https://deephavencommunity.slack.com/team/U02V6TEGHT6)
 
[@JJ Brosnan](https://deephavencommunity.slack.com/team/U02UQRPLPNG)
 ok, I figured it out:
import jpy 

def testD():
  arrA = jpy.array("double", [1,2])
  arrB = jpy.array("double", [3,4])
  arrC = jpy.array(jpy.get_type('[D'), [arrA, arrB])
  return arrC

table = empty_table(1).update([
  "double_matrix = (double[][]) testD()",
  "top_left = double_matrix[0][0]",
  "top_right = double_matrix[0][1]",
  "bottom_left = double_matrix[1][0]",
  "bottom_right = double_matrix[1][1]",
])
meta = table.meta_table
However, the only catch is that the double[][] double_matrix column is not human-readable in the final table table, however, you can extract its values and the above yields below.
[@JJ Brosnan](https://deephavencommunity.slack.com/team/U02UQRPLPNG)
 maybe worth adding this to the examples under https://deephaven.io/core/docs/how-to-guides/use-jpy/#java-arrays (edited) 
image.png
 
image.png


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703720817408359?thread_ts=1703716929.535119&cid=C0370B33SQ4)
Extracting rows is easy
  "row_1 = double_matrix[0]",
  "row_2 = double_matrix[1]",
but is there a "Java way" of extracting the matrix columns as lists? (edited) 


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703725090057809?thread_ts=1703716929.535119&cid=C0370B33SQ4)
nice work! what do you want to do with the lists once you have them?


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703725850917779?thread_ts=1703716929.535119&cid=C0370B33SQ4)
in my case, I can just create the transposed matrix within my UDF and then I'm all set (can use other build in Java funcs like cumsum, product, sum, etc).  context: this is just another twist of parsing orderbooks, so my lists are prices & sizes. once I have the lists, I can unfold them via .ungroup() (similar to how we designed it a few months ago but overall a bit more efficient)
One thing I haven't figured out: I still need to use (double[][]) , 
[@Colin Alworth](https://deephavencommunity.slack.com/team/U02V6TEGHT6)
 
[@JJ Brosnan](https://deephavencommunity.slack.com/team/U02UQRPLPNG)
 is there  a type hint I can use for the function definition?
def testD() -> <proper type hint here to return double[][]>:
  arrA = jpy.array("double", [1,2])
  arrB = jpy.array("double", [3,4])
  arrC = jpy.array(jpy.get_type('[D'), [arrA, arrB])
  return arrC


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726000541439?thread_ts=1703716929.535119&cid=C0370B33SQ4)
[@Colin Alworth](https://deephavencommunity.slack.com/team/U02V6TEGHT6)
 here's a full example
def testD():
  level = jpy.array("double", range(0,3))
  prices = jpy.array("double", [100, 101, 102])
  sizes = jpy.array("double", [2.1, 0.3, 1.7])
  arrC = jpy.array(jpy.get_type('[D'), [level, prices, sizes])  
  return arrC

table = empty_table(1).update([
  "double_matrix = (double[][]) testD()",  
  "level = double_matrix[0]",
  "price = double_matrix[1]",
  "size = double_matrix[2]",
]).ungroup(['level', 'price', 'size'])
meta = table.meta_table


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726120496109?thread_ts=1703716929.535119&cid=C0370B33SQ4)
there is no typehint that will handle this to my knowledge, but we'll be able to get you a straight answer and/or roadmap next week


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726183735969?thread_ts=1703716929.535119&cid=C0370B33SQ4)
if you have [[a, b], [c, d]] in a single cell, ungroup() will already function to extract to [a, b] in the first row and [c, d] in the second - and a second ungroup will further unwrap to a, b, c, d


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726235594379?thread_ts=1703716929.535119&cid=C0370B33SQ4)
yup, example above generates this
image.png
 
image.png


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726270456649?thread_ts=1703716929.535119&cid=C0370B33SQ4)
from ungroup's perspective, list/vector/array are all close enough to being the same to not matter


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726304667629?thread_ts=1703716929.535119&cid=C0370B33SQ4)
oh, good to know. I vaguely recall that it had to be jpy.array (edited) 


Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726325194369?thread_ts=1703716929.535119&cid=C0370B33SQ4)
note that the above statement is true of java types
:+1:
1



Colin Alworth
:deephaven:  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726346912489?thread_ts=1703716929.535119&cid=C0370B33SQ4)
your double_matrix col looks like a java list or dhjava vector of java double[] (that is, array)


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726371394659?thread_ts=1703716929.535119&cid=C0370B33SQ4)
the main problem with
def testA() -> List[List[np.float64]]
  return [[1,2],[2,3]]
though is that I cannot access the rows in query language as it's a org.jpy.PyObject (edited) 


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726431947249?thread_ts=1703716929.535119&cid=C0370B33SQ4)
hence I was looking for the double[][] so I can access the rows individually


miek
  [21 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703726636180509?thread_ts=1703716929.535119&cid=C0370B33SQ4)
[@Colin Alworth](https://deephavencommunity.slack.com/team/U02V6TEGHT6)
 here's the example that does NOT work
def testA() -> List[List[np.double]]:
  return [[1,2],[2,3]]


table = empty_table(1).update([
  "double_matrix = testA()",  
  "level = double_matrix[0]",
]).ungroup(['level'])
meta = table.meta_table


miek
  [20 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703745508434829?thread_ts=1703716929.535119&cid=C0370B33SQ4)
[@Colin Alworth](https://deephavencommunity.slack.com/team/U02V6TEGHT6)
 I put it all together here and bumped my repo to 0.31.0, checkout https://github.com/kzk2000/deephaven-clickhouse, build it per instructions, then run
[notebooks/stream_orderbooks.py](https://github.com/kzk2000/deephaven-clickhouse/blob/master/data/deephaven/notebooks/stream_orderbooks.py) to see all the above in action

GitHubGitHub
[GitHub - kzk2000/deephaven-clickhouse](https://github.com/kzk2000/deephaven-clickhouse)
Contribute to kzk2000/deephaven-clickhouse development by creating an account on GitHub. (36 kB)
https://github.com/kzk2000/deephaven-clickhouse

:raised_hands:
1



JJ Brosnan
:deephaven:  [20 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703774112243319?thread_ts=1703716929.535119&cid=C0370B33SQ4)
Hi 
[@miek](https://deephavencommunity.slack.com/team/U037V7Y2KBL)
, thanks for posting this question and the subsequent thread. I’ve filed a feature request in deephaven-core: [4989](https://github.com/deephaven/deephaven-core/issues/4989). Feel free to add any relevant information to that ticket.

GitHubGitHub
[Feature request: Support multidimensional arrays in query strings returned from Python functions · Issue #4989 · deephaven/deephaven-core](https://github.com/deephaven/deephaven-core/issues/4989)
As a user, I'd like to have the ability to more easily use a Python function that returns a multidimensional array. For instance, something like: from numpy import typing as npt from deephaven impo... (106 kB)
https://github.com/deephaven/deephaven-core/issues/4989

:raised_hands:
1



miek
  [20 days ago](https://deephavencommunity.slack.com/archives/C0370B33SQ4/p1703775038865119?thread_ts=1703716929.535119&cid=C0370B33SQ4)
Thanks 
[@JJ Brosnan](https://deephavencommunity.slack.com/team/U02UQRPLPNG)
 , added another comment but you had captured most of it.
```
