### ISSUE TITLE
Wildcard imports of built-in packages don't work

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#4994]
A wildcard import like:

```
import java.util.concurrent.*
```

throws:

```
com.illumon.iris.controller.exception.ScriptException: java.lang.RuntimeException: Attempting to import a path that does not exist: import java.util.concurrent.*;
	at io.deephaven.engine.util.GroovyDeephavenSession.updateScriptImports(GroovyDeephavenSession.java:582)
	at io.deephaven.engine.util.GroovyDeephavenSession.grepScriptImports(GroovyDeephavenSession.java:592)
	at io.deephaven.engine.util.GroovyDeephavenSession.evaluate(GroovyDeephavenSession.java:307)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:147)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:149)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:160)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:148)
```

This is basically because `groovyShell.getClassLoader().getDefinedPackage("java.util.concurrent")` returns null. (Using `.getPackage()`, which is deprecated, does work. It eventually calls `jdk.internal.loader.BootLoader.getDefinedPackage()`)

**Comment by rcaudy** [comment]
Eww. Why do we still have things that grep script imports?

Regardless, I'm pretty confident that `getPackage` is internally racy and unreliable.

**Comment by niloc132** [comment]
`ClassLoader.getDefinedPackage` is expected to return null in these cases for the first import -  we have a unit test that validates that null must be returned before trying to run a wildcard import:
https://github.com/deephaven/deephaven-core/blob/e4d69fd299a517a273bb433aec76299a06605d6d/engine/table/src/test/java/io/deephaven/engine/util/scripts/TestGroovyDeephavenSession.java#L131-L140

However, changing `groovy.time` to `java.util.concurrent` (or `java.util`) in that test produces a failure, as this bug describes (contrast with `io.deephaven.engine.util`, which will _not_ return null from that test on line 136, and so the test cannot run).

In GroovyDeephavenSession.createClassImport, after getDefinedPackage fails, ClassGraph is used to look up the class. ClassGraph has a specific config that must be applied to be able to scan system modules/packages - enabling that appears to resolve this.
