### ISSUE TITLE
Can't create columns with unicode in python

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/deephaven-core#5010]
In a groovy worker I can use unicode stuff in a column:
```t = emptyTable(1).update("x = `🏁 🎌 🚩 🏳️‍🌈 🏴‍☠️`")```

![image](https://github.com/deephaven/deephaven-core/assets/1576283/9bf255bd-256d-4b81-be1a-c17500e067b7)

However, running the same query in python it errors:
```t = empty_table(1).update("x = `🏁 🎌 🚩 🏳️‍🌈 🏴‍☠️`")```

```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'SyntaxError'>
Value: (unicode error) 'utf-8' codec can't decode byte 0xed in position 5: invalid continuation byte (<string>, line 1)
Line: <not available>
Namespace: <not available>
File: <not available>
Traceback (most recent call last):

	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
```

I would like to be able to use unicode.

**Comment by niloc132** [comment]
Dup of https://github.com/deephaven/deephaven-core/issues/1948 - mostly this is a jpy issue, there are too many ways to pass strings through jpy.
