### ISSUE TITLE
Double error notification

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#5015]
While working on some new kafka StreamPublishing code, I've been able to demonstrate a double error notification behavior - first, a detailed message is shown in the UI:

![first-error](https://github.com/deephaven/deephaven-core/assets/6764691/9de64085-bbc3-4837-855b-ca6ddc2f6a7e)

followed shortly there-after flashing into:

![second-error](https://github.com/deephaven/deephaven-core/assets/6764691/bc189d0e-6679-42f2-826e-2a215c94aab1)

This was a bit jarring from web UX, but also strange as usually error details are obscured.

On the server side, we see the following stack traces:

```
2024-01-08T22:38:14.359Z | ph-updateExecutor-17 | ERROR | .AsyncClientErrorNotifier | Error in table update: org.apache.kafka.clients.consumer.OffsetOutOfRangeException: Fetch position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[192.168.52.17:9092 (id: 1 rack: null)], epoch=absent}} is out of range for partition homeassistant-0
        at org.apache.kafka.clients.consumer.internals.Fetcher.handleOffsetOutOfRange(Fetcher.java:1408)
        at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1360)
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:659)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1314)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.pollAndAccept(KafkaPublisherDriver.java:128)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.runOnce(KafkaPublisherDriver.java:107)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.run(KafkaPublisherDriver.java:93)
        at java.base/java.lang.Thread.run(Thread.java:829)

2024-01-08T22:38:14.781Z | heduler-Concurrent-4 | ERROR | i.d.s.s.SessionService    | Internal Error '35a05ec6-08f0-4ae3-a1ee-e60a18303ab0' org.apache.kafka.clients.consumer.OffsetOutOfRangeException: Fetch position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[192.168.52.17:9092 (id: 1 rack: null)], epoch=absent}} is out of range for partition homeassistant-0
        at org.apache.kafka.clients.consumer.internals.Fetcher.handleOffsetOutOfRange(Fetcher.java:1408)
        at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1360)
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:659)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1314)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.pollAndAccept(KafkaPublisherDriver.java:128)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.runOnce(KafkaPublisherDriver.java:107)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.run(KafkaPublisherDriver.java:93)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by devinrsmith** [comment]
Note - it may be useful for us to unconditionally log out the caller's stacktrace in these sorts of situations, as it reveals useful details:

```
2024-01-08T23:19:20.514Z | aph-updateExecutor-4 | ERROR | .AsyncClientErrorNotifier | Error in table update: java.lang.RuntimeException: org.apache.kafka.clients.consumer.OffsetOutOfRangeException: Fetch position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[192.168.52.17:9092 (id: 1 rack: null)], epoch=absent}} is out of range for partition homeassistant-0
        at io.deephaven.server.log.LogInit.lambda$run$0(LogInit.java:42)
        at io.deephaven.engine.table.impl.util.AsyncClientErrorNotifier.reportError(AsyncClientErrorNotifier.java:29)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailureInternalWithDependent(InstrumentedTableListenerBase.java:186)
        at io.deephaven.engine.table.impl.BaseTable$ListenerImpl.onFailureInternal(BaseTable.java:979)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase.onFailure(InstrumentedTableListenerBase.java:172)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$ErrorNotification.run(InstrumentedTableListenerBase.java:259)
        at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:712)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:835)
        at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.clients.consumer.OffsetOutOfRangeException: Fetch position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[192.168.52.17:9092 (id: 1 rack: null)], epoch=absent}} is out of range for partition homeassistant-0
        at org.apache.kafka.clients.consumer.internals.Fetcher.handleOffsetOutOfRange(Fetcher.java:1408)
        at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1360)
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:659)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1314)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.pollAndAccept(KafkaPublisherDriver.java:128)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.runOnce(KafkaPublisherDriver.java:107)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.run(KafkaPublisherDriver.java:93)
        ... 1 more

2024-01-08T23:19:20.819Z | heduler-Concurrent-4 | ERROR | i.d.s.s.SessionService    | Internal Error '8fc3593e-a060-4b61-b05f-c98394f5d9dc' java.lang.RuntimeException: org.apache.kafka.clients.consumer.OffsetOutOfRangeException: Fetch position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[192.168.52.17:9092 (id: 1 rack: null)], epoch=absent}} is out of range for partition homeassistant-0
        at io.deephaven.extensions.barrage.util.GrpcUtil.securelyWrapError(GrpcUtil.java:33)
        at io.deephaven.extensions.barrage.util.GrpcUtil.securelyWrapError(GrpcUtil.java:23)
        at io.deephaven.server.session.SessionService$ObfuscatingErrorTransformer.transform(SessionService.java:75)
        at io.deephaven.server.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:1496)
        at io.deephaven.server.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:1012)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:97)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.clients.consumer.OffsetOutOfRangeException: Fetch position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[192.168.52.17:9092 (id: 1 rack: null)], epoch=absent}} is out of range for partition homeassistant-0
        at org.apache.kafka.clients.consumer.internals.Fetcher.handleOffsetOutOfRange(Fetcher.java:1408)
        at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1360)
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:659)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1314)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.pollAndAccept(KafkaPublisherDriver.java:128)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.runOnce(KafkaPublisherDriver.java:107)
        at io.deephaven.kafka.v2.KafkaPublisherDriver.run(KafkaPublisherDriver.java:93)
        ... 1 more
```

**Comment by devinrsmith** [comment]
The `AsyncClientErrorNotifier` error message printed to the server is not actually part of the suspected double notification at play here - it's just additional logging (which in this case, shows a time gap between the async notification and the "Internal Error" notification).
