### ISSUE TITLE
Replaying inappropriate data crashes server

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/deephaven-core#5016]
**Description**

Replaying a table that violates the conditions of a replayable table crashes the server.

**Steps to reproduce**
Run this code (you need the example data):
```
from deephaven import read_csv

crypto = read_csv("/data/examples/CryptoCurrencyHistory/CSV/CryptoTrades_20210922.csv")

from deephaven.replay import TableReplayer

replayer = TableReplayer("2021-09-22T16:00:11.78Z", "2021-09-22T20:11:34.60Z")
replayed_crypto = replayer.add_table(crypto, "Timestamp")
replayer.start()
```

**Expected results**

I expect an error in the IDE log that tells me I've done something wrong.

**Actual results**

Here is the error upon crash:
<img width="1728" alt="Screenshot 2024-01-08 at 8 07 35 PM" src="https://github.com/deephaven/deephaven-core/assets/80283343/90f2e326-10dc-45ec-879b-525ad2662a55">

And the Docker logs:
```
examples-deephaven-1  | crypto = read_csv("/data/examples/CryptoCurrencyHistory/CSV/CryptoTrades_20210922.csv")
examples-deephaven-1  | 
examples-deephaven-1  | from deephaven.replay import TableReplayer
examples-deephaven-1  | 
examples-deephaven-1  | replayer = TableReplayer("2021-09-22T16:00:11.78Z", "2021-09-22T20:11:34.60Z")
examples-deephaven-1  | replayed_crypto = replayer.add_table(crypto, "Timestamp")
examples-deephaven-1  | replayer.start()
examples-deephaven-1  | 2024-01-09T02:07:16.584Z | aph-updateExecutor-2 | ERROR | e.u.i.PeriodicUpdateGraph | PeriodicUpdateGraph-updateExecutor-2: Exception while executing UpdateGraph notification: UpdateSourceRefreshNotification{1802521732, for UpdateSource{443362842}}: java.lang.RuntimeException: The historical table contains a null or decreasing time that cannot be replayed.
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.advanceIterators(ReplayTable.java:66)
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.advanceToCurrentTime(ReplayTable.java:84)
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.run(ReplayTable.java:94)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph$UpdateSourceRefreshNotification.run(BaseUpdateGraph.java:955)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:829)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1103)
examples-deephaven-1  | 	at java.base/java.lang.Thread.run(Thread.java:1583)
examples-deephaven-1  | 
examples-deephaven-1  | Initiating shutdown due to: Exception while processing UpdateGraph notification
examples-deephaven-1  | java.lang.RuntimeException: The historical table contains a null or decreasing time that cannot be replayed.
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.advanceIterators(ReplayTable.java:66)
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.advanceToCurrentTime(ReplayTable.java:84)
examples-deephaven-1  | 	at io.deephaven.engine.table.impl.replay.ReplayTable.run(ReplayTable.java:94)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph$UpdateSourceRefreshNotification.run(BaseUpdateGraph.java:955)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:702)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:829)
examples-deephaven-1  | 	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1103)
examples-deephaven-1  | 	at java.base/java.lang.Thread.run(Thread.java:1583)
examples-deephaven-1  | 2024-01-09T02:07:16.594Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Initiating shutdown processing
examples-deephaven-1  | 2024-01-09T02:07:16.595Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Starting to invoke FIRST shutdown tasks
examples-deephaven-1  | 2024-01-09T02:07:16.598Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Done invoking FIRST shutdown tasks
examples-deephaven-1  | 2024-01-09T02:07:16.598Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Starting to invoke MIDDLE shutdown tasks
examples-deephaven-1  | 2024-01-09T02:07:16.599Z | Thread-0             |  INFO | portedTableUpdateListener | ExportedTableUpdateListener(10b1bbd1) is complete
examples-deephaven-1  | 2024-01-09T02:07:16.602Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Done invoking MIDDLE shutdown tasks
examples-deephaven-1  | 2024-01-09T02:07:16.602Z | Thread-0             |  WARN | d.u.p.ShutdownManagerImpl | Starting to invoke LAST shutdown tasks
examples-deephaven-1  | 2024-01-09T02:07:16.622Z | qtp935520971-63      |  INFO | i.d.s.s.SessionService    | No AuthenticationRequestHandler registered for type Bearer
examples-deephaven-1  | 2024-01-09T02:07:16.622Z | qtp935520971-63      |  INFO | i.d.s.s.SessionService    | No AuthenticationRequestHandler registered for type Bearer
examples-deephaven-1  | 2024-01-09T02:07:16.622Z | qtp935520971-63      |  INFO | i.d.s.s.SessionService    | No AuthenticationRequestHandler registered for type Bearer
examples-deephaven-1  | 2024-01-09T02:07:16.642Z | Thread-26            |  INFO | o.e.jetty.server.Server   | Stopped Server@3c28e5b6{STOPPING}[11.0.17,sto=5000]
examples-deephaven-1  | 2024-01-09T02:07:16.642Z | Thread-26            |  INFO | o.e.jetty.server.Server   | Shutdown Server@3c28e5b6{STOPPING}[11.0.17,sto=5000]
examples-deephaven-1  | 2024-01-09T02:07:16.644Z | Thread-26            |  INFO | o.e.j.s.AbstractConnector | Stopped ServerConnector@26d820eb{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:10000}
examples-deephaven-1 exited with code 1
```

**Additional details and attachments**

I'm working with the image [here](https://raw.githubusercontent.com/deephaven/deephaven-core/main/containers/python-examples/base/docker-compose.yml).

**Versions**
 - Deephaven: 0.31.0
 - OS: MacOS 13.2.1
 - Browser: Safari
 - Docker: 4.19.0

**Comment by rcaudy** [comment]
We should decide if this code is still important. It's a trivial fix if we want to apply it... instead of throwing exceptions, we should deliver a failure notification.

**Comment by chipkent** [comment]
Supporting a replayer is very important.
