### ISSUE TITLE
engine-test:time failures

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#5023]
A few new unit test failures that are blocking some PRs. Unable to reproduce locally, but has happened at least 3 times in CI.

```
junit.framework.AssertionFailedError: expected:<2024-01-10> but was:<2024-01-09>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:86)
	at junit.framework.TestCase.assertEquals(TestCase.java:246)
	at io.deephaven.time.calendar.TestCalendar.testCurrentDate(TestCalendar.java:162)
```

```
2024-01-10T01:20:23.8901220Z > Task :engine-table:test
2024-01-10T01:20:23.8904136Z 1 compiler directives added
2024-01-10T01:20:53.3896228Z 
2024-01-10T01:20:53.3899750Z > Task :engine-time:test
2024-01-10T01:22:25.7899338Z 1 compiler directives added
2024-01-10T01:22:26.9896107Z 
2024-01-10T01:22:26.9900424Z io.deephaven.time.calendar.TestBusinessCalendar > testFutureNonBusinessDate FAILED
2024-01-10T01:22:26.9905263Z     junit.framework.AssertionFailedError at TestBusinessCalendar.java:1518
2024-01-10T01:22:27.1896130Z 
2024-01-10T01:22:27.1905079Z io.deephaven.time.calendar.TestBusinessCalendar > testFutureBusinessDate FAILED
2024-01-10T01:22:27.1910054Z     junit.framework.AssertionFailedError at TestBusinessCalendar.java:1507
2024-01-10T01:22:27.2127322Z 
2024-01-10T01:22:27.2131458Z io.deephaven.time.calendar.TestBusinessCalendar > testPastBusinessDate FAILED
2024-01-10T01:22:27.2137304Z     junit.framework.AssertionFailedError at TestBusinessCalendar.java:1512
2024-01-10T01:22:27.4896452Z 
2024-01-10T01:22:27.4900881Z io.deephaven.time.calendar.TestBusinessCalendar > testPastNonBusinessDate FAILED
2024-01-10T01:22:27.4907836Z     junit.framework.AssertionFailedError at TestBusinessCalendar.java:1528
2024-01-10T01:22:27.7897931Z 
2024-01-10T01:22:27.7902255Z io.deephaven.time.calendar.TestBusinessCalendar > testFutureDate FAILED
2024-01-10T01:22:27.7906425Z     junit.framework.AssertionFailedError at Assert.java:57
2024-01-10T01:22:27.7908125Z 
2024-01-10T01:22:27.7909725Z io.deephaven.time.calendar.TestBusinessCalendar > testCurrentDate FAILED
2024-01-10T01:22:27.7912981Z     junit.framework.AssertionFailedError at Assert.java:57
2024-01-10T01:22:27.7914660Z 
2024-01-10T01:22:27.7916207Z io.deephaven.time.calendar.TestBusinessCalendar > testPastDate FAILED
2024-01-10T01:22:27.7919383Z     junit.framework.AssertionFailedError at Assert.java:57
2024-01-10T01:22:27.7921025Z 
2024-01-10T01:22:27.7922475Z io.deephaven.time.calendar.TestCalendar > testFutureDate FAILED
2024-01-10T01:22:27.7925827Z     junit.framework.AssertionFailedError at TestCalendar.java:166
2024-01-10T01:22:27.7927609Z 
2024-01-10T01:22:27.7929172Z io.deephaven.time.calendar.TestCalendar > testCurrentDate FAILED
2024-01-10T01:22:27.7932392Z     junit.framework.AssertionFailedError at TestCalendar.java:162
2024-01-10T01:22:27.8895891Z 
2024-01-10T01:22:27.8900138Z io.deephaven.time.calendar.TestCalendar > testPastDate FAILED
2024-01-10T01:22:27.8904027Z     junit.framework.AssertionFailedError at TestCalendar.java:172
2024-01-10T01:22:28.2900146Z 1 compiler directives added
2024-01-10T01:22:29.9905713Z 
2024-01-10T01:22:29.9909226Z 187 tests completed, 10 failed
2024-01-10T01:22:30.0899186Z 
2024-01-10T01:22:30.0903256Z > Task :engine-time:test FAILED
```

Given timing, seems very likely related to https://github.com/deephaven/deephaven-core/pull/4201.

**Comment by devinrsmith** [comment]
Fixed by https://github.com/deephaven/deephaven-core/pull/5025
