### ISSUE TITLE
Unable to use formulas in Python 3.12

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#5127]
`view`, `update_view`, `select`, and `update` do not work on recent versions of DH with Python 3.12 (as of https://github.com/deephaven/deephaven-core/pull/4502)

```python
from deephaven import new_table

foo = new_table({"Foo": [1, 2, 3]})
bar = foo.view(["Bar = Foo + 1"])
```

Essentially, `io.deephaven.engine.util.PyCallableWrapperJpyImpl` depends on `_udf.py` depends on `numba`, which was not previously a hard requirement.

```
java.lang.NoClassDefFoundError: Could not initialize class io.deephaven.engine.util.PyCallableWrapperJpyImpl                                                                   
        at io.deephaven.engine.util.PythonScopeJpyImpl.convertInternal(PythonScopeJpyImpl.java:122)                                                                                          
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)                                                                                                                    
        at io.deephaven.engine.util.PythonScopeJpyImpl.convert(PythonScopeJpyImpl.java:113)                                                                                                  
        at io.deephaven.engine.util.PythonScopeJpyImpl.convertValue(PythonScopeJpyImpl.java:77)                                                                                              
        at io.deephaven.engine.util.PythonScopeJpyImpl.convertValue(PythonScopeJpyImpl.java:18)                                                                                              
        at java.base/java.util.Optional.map(Optional.java:260)                                                                                                                               
        at io.deephaven.engine.util.PythonScope.getValue(PythonScope.java:96)                                                                                                                
        at io.deephaven.integrations.python.PythonDeephavenSession.getVariable(PythonDeephavenSession.java:182)                                                                              
        at io.deephaven.engine.util.AbstractScriptSession$ScriptSessionQueryScope.readParamValue(AbstractScriptSession.java:338)                                                             
        at io.deephaven.engine.util.AbstractScriptSession$ScriptSessionQueryScope.createParam(AbstractScriptSession.java:329)                                                                
        at io.deephaven.engine.context.QueryScope.getParams(QueryScope.java:76)                                                                                                              
        at io.deephaven.engine.table.impl.select.codegen.FormulaAnalyzer.getCompiledFormula(FormulaAnalyzer.java:99)                                                                         
        at io.deephaven.engine.table.impl.select.DhFormulaColumn.initDef(DhFormulaColumn.java:194)                                                                                           
        at io.deephaven.engine.table.impl.select.SwitchColumn.initDef(SwitchColumn.java:56)                                                                                                  
        at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:115)                                                                      
        at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer.create(SelectAndViewAnalyzer.java:63)                                                                       
        at io.deephaven.engine.table.impl.QueryTable.lambda$viewOrUpdateView$33(QueryTable.java:1642)                                                                                        
        at io.deephaven.engine.table.impl.BaseTable.initializeWithSnapshot(BaseTable.java:1293)                                                                                              
        at io.deephaven.engine.table.impl.QueryTable.lambda$viewOrUpdateView$34(QueryTable.java:1640)                                                                                        
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)                                                                        
        at io.deephaven.engine.table.impl.QueryTable.lambda$viewOrUpdateView$35(QueryTable.java:1634)                                                                                        
        at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3438)                                                                                                     
        at io.deephaven.engine.table.impl.QueryTable.viewOrUpdateView(QueryTable.java:1633)                                                                                                  
        at io.deephaven.engine.table.impl.QueryTable.view(QueryTable.java:1611)                                                                                                              
        at io.deephaven.engine.table.impl.QueryTable.view(QueryTable.java:104)                                                                                                               
        at io.deephaven.api.TableOperationsDefaults.view(TableOperationsDefaults.java:79)
```

**Comment by devinrsmith** [comment]
Related to https://github.com/deephaven/deephaven-core/issues/3082
