### ISSUE TITLE
`deephaven.learn` fails with null pointer exception where no null value exists

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#5182]
**Description**

Nightly docs testing indicates an issue introduced in 0.33.0 where `deephaven.learn` can fail with a null pointer exception when no null data exists.

I've tried to repro this with a simpler use case, but haven't been able to yet. The reproducer shown below requires installing scikit-learn into DH.

**Steps to reproduce**

```python
# Deephaven imports
from deephaven import DynamicTableWriter
import deephaven.dtypes as dht
from deephaven.learn import gather
from deephaven import read_csv
from deephaven import learn

# Machine learning imports
from sklearn.neighbors import KNeighborsClassifier as knn

# Additional required imports
import numpy as np, random, threading, time

iris_raw = read_csv("https://media.githubusercontent.com/media/deephaven/examples/main/Iris/csv/iris.csv")
classes = {}
num_classes = 0
def get_class_number(c) -> np.intc:
    global classes, num_classes
    if c not in classes:
        classes[c] = num_classes
        num_classes += 1
    return classes[c]

iris = iris_raw.update(formulas=["Class = get_class_number(Class)"])

neigh = 0

# Construct and classify the Iris dataset
def fit_knn(X_train, Y_train):
    global neigh
    neigh = knn(n_neighbors=3)
    neigh.fit(X_train, Y_train)

# A function to gather data from columns into a NumPy array of doubles
def table_to_array_double(rows, cols):
    a = gather.table_to_numpy_2d(rows, cols, np_type=np.double)
    return a

# A function to gather data from columns into a NumPy array of integers
def table_to_array_int(rows, cols):
    b = np.squeeze(gather.table_to_numpy_2d(rows, cols, np_type=np.intc))
    return b

# A function to extract a list element and cast to an integer
def get_predicted_class(data, idx):
    return int(data[idx])

# Use the learn function to fit our KNN classifier
learn.learn(
    table=iris,
    model_func=fit_knn,
    inputs=[learn.Input(["SepalLengthCM", "SepalWidthCM", "PetalLengthCM", "PetalWidthCM"], table_to_array_double), learn.Input("Class", table_to_array_int)],
    outputs=None,
    batch_size=150
)
```

**Expected results**

The code to return successfully. This happens in 0.32 (and I presume earlier releases as well).

**Actual results**

An error with the following stack trace:

```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: failed to complete the learn function. : java.lang.NullPointerException: Cannot invoke "io.deephaven.integrations.learn.Future.get()" because the return value of "io.deephaven.integrations.learn.FutureOffset.getFuture()" is null
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 757, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: io.deephaven.engine.exceptions.TableInitializationException: Error while initializing Update([__FutureOffset, __Result, __CleanComputer]): an exception occurred while performing the initial select or update
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$30(QueryTable.java:1507)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$31(QueryTable.java:1444)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3458)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1443)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1421)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:105)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:94)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:205)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:205)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:148)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:148)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$3(SessionState.java:1519)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:992)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:97)
	at java.base/java.lang.Thread.run(Thread.java:1583)
caused by io.deephaven.engine.table.impl.select.FormulaEvaluationException: In formula: __Result = __FutureOffset.getFuture().get()
	at io.deephaven.temp.c_4debfe8900122018c116eb97503bec3e829fc33d0c45e5647a33fc49f8a50ef9v65_0.Formula.applyFormulaPerItem(Formula.java:154)
	at io.deephaven.temp.c_4debfe8900122018c116eb97503bec3e829fc33d0c45e5647a33fc49f8a50ef9v65_0.Formula.lambda$fillChunkHelper$4(Formula.java:143)
	at io.deephaven.engine.rowset.RowSequence.lambda$forAllRowKeys$0(RowSequence.java:175)
	at io.deephaven.engine.rowset.impl.singlerange.SingleRangeMixin.forEachRowKey(SingleRangeMixin.java:17)
	at io.deephaven.engine.rowset.RowSequence.forAllRowKeys(RowSequence.java:174)
	at io.deephaven.temp.c_4debfe8900122018c116eb97503bec3e829fc33d0c45e5647a33fc49f8a50ef9v65_0.Formula.fillChunkHelper(Formula.java:141)
	at io.deephaven.temp.c_4debfe8900122018c116eb97503bec3e829fc33d0c45e5647a33fc49f8a50ef9v65_0.Formula.fillChunk(Formula.java:118)
	at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillChunk(ViewColumnSource.java:219)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doApplyUpdate(SelectColumnLayer.java:412)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$doSerialApplyUpdate$2(SelectColumnLayer.java:264)
	at io.deephaven.engine.util.systemicmarking.SystemicObjectTracker.executeSystemically(SystemicObjectTracker.java:56)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doSerialApplyUpdate(SelectColumnLayer.java:263)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$1(SelectColumnLayer.java:212)
	at io.deephaven.engine.table.impl.util.ImmediateJobScheduler.lambda$submit$0(ImmediateJobScheduler.java:37)
	at io.deephaven.engine.table.impl.util.ImmediateJobScheduler.submit(ImmediateJobScheduler.java:51)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.onAllRequiredColumnsCompleted(SelectColumnLayer.java:210)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:627)
	at io.deephaven.engine.table.impl.select.analyzers.BaseLayer.applyUpdate(BaseLayer.java:76)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$30(QueryTable.java:1494)
	... 29 more
caused by java.lang.NullPointerException: Cannot invoke "io.deephaven.integrations.learn.Future.get()" because the return value of "io.deephaven.integrations.learn.FutureOffset.getFuture()" is null
	at io.deephaven.temp.c_4debfe8900122018c116eb97503bec3e829fc33d0c45e5647a33fc49f8a50ef9v65_0.Formula.applyFormulaPerItem(Formula.java:152)
	... 50 more


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/learn/__init__.py", line 156, in learn
    return (table
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 759, in update
    raise DHError(e, "table update operation failed.") from e
deephaven.dherror.DHError: table update operation failed. : java.lang.NullPointerException: Cannot invoke "io.deephaven.integrations.learn.Future.get()" because the return value of "io.deephaven.integrations.learn.FutureOffset.getFuture()" is null
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 757, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: io.deephaven.engine.exceptions.TableInitializationException: Error while initializing Update([__FutureOffset, __Result, __CleanComputer]): an exception occurred while performing the initial select or update
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$30(QueryTable.java:1507)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$31(QueryTable.java:1444)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3458)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1443)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1421)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:105)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:94)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:205)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:205)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:148)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:148)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$3(SessionState.java:1519)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:992)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:97)
	at java.base/java.lang.Thread.run(Thread.java:1583)
caused by io.deephaven.engine.table.impl.select.FormulaEvaluationException: In formula: __Result = __FutureOffset.getFuture().get()
	at io.deephaven.temp.c_4debfe8900122018c116eb97503bec3e829fc33d0c45e5647a33fc49f8a50ef9v65_0.Formula.applyFormulaPerItem(Formula.java:154)
	at io.deephaven.temp.c_4debfe8900122018c116eb97503bec3e829fc33d0c45e5647a33fc49f8a50ef9v65_0.Formula.lambda$fillChunkHelper$4(Formula.java:143)
	at io.deephaven.engine.rowset.RowSequence.lambda$forAllRowKeys$0(RowSequence.java:175)
	at io.deephaven.engine.rowset.impl.singlerange.SingleRangeMixin.forEachRowKey(SingleRangeMixin.java:17)
	at io.deephaven.engine.rowset.RowSequence.forAllRowKeys(RowSequence.java:174)
	at io.deephaven.temp.c_4debfe8900122018c116eb97503bec3e829fc33d0c45e5647a33fc49f8a50ef9v65_0.Formula.fillChunkHelper(Formula.java:141)
	at io.deephaven.temp.c_4debfe8900122018c116eb97503bec3e829fc33d0c45e5647a33fc49f8a50ef9v65_0.Formula.fillChunk(Formula.java:118)
	at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillChunk(ViewColumnSource.java:219)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doApplyUpdate(SelectColumnLayer.java:412)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$doSerialApplyUpdate$2(SelectColumnLayer.java:264)
	at io.deephaven.engine.util.systemicmarking.SystemicObjectTracker.executeSystemically(SystemicObjectTracker.java:56)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doSerialApplyUpdate(SelectColumnLayer.java:263)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$1(SelectColumnLayer.java:212)
	at io.deephaven.engine.table.impl.util.ImmediateJobScheduler.lambda$submit$0(ImmediateJobScheduler.java:37)
	at io.deephaven.engine.table.impl.util.ImmediateJobScheduler.submit(ImmediateJobScheduler.java:51)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.onAllRequiredColumnsCompleted(SelectColumnLayer.java:210)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:627)
	at io.deephaven.engine.table.impl.select.analyzers.BaseLayer.applyUpdate(BaseLayer.java:76)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$30(QueryTable.java:1494)
	... 29 more
caused by java.lang.NullPointerException: Cannot invoke "io.deephaven.integrations.learn.Future.get()" because the return value of "io.deephaven.integrations.learn.FutureOffset.getFuture()" is null
	at io.deephaven.temp.c_4debfe8900122018c116eb97503bec3e829fc33d0c45e5647a33fc49f8a50ef9v65_0.Formula.applyFormulaPerItem(Formula.java:152)
	... 50 more



Line: 168
Namespace: learn
File: /opt/deephaven/venv/lib/python3.10/site-packages/deephaven/learn/__init__.py
Traceback (most recent call last):
  File "<string>", line 49, in <module>
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/learn/__init__.py", line 168, in learn

	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:205)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:205)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:148)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:148)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$3(SessionState.java:1519)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:992)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:97)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Additional details and attachments**

It's worth noting that our nightly docs tests have failed since the run at 1:40AM ET on Wednesday, February 21. Nightly docs tests use edge images. This would lead me to believe that the code would work in 0.33.0, but not edge. However, it fails with the same error in both.

**Versions**
 - Deephaven: 0.33 or edge
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by alexpeters1208** [comment]
After some poking around, I have a smaller repro:
```
import jpy
_JLearnComputer = jpy.get_type("io.deephaven.integrations.learn.Computer")

from deephaven import empty_table
from deephaven import learn
from deephaven.learn import gather
import numpy as np

table = empty_table(10).update(["X = ii", "Y = Math.sin(X)"])

# Function that gets called on each row of inputs
def model_func(x, y):
    return 1

# A function to gather data from columns into a NumPy array of longs
def table_to_array_long(rows, cols):
    return learn.gather.table_to_numpy_2d(rows, cols, np_type=np.int_)

# A function to gather data from columns into a NumPy array of doubles
def table_to_array_double(rows, cols):
    return learn.gather.table_to_numpy_2d(rows, cols, np_type=np.double)

# here we recreate the arguments passed to learn
inputs=[learn.Input(["X"], table_to_array_long), learn.Input("Y", table_to_array_double)]
outputs=None
batch_size=10

__computer = _JLearnComputer(table.j_table, model_func,
        [input_.input for input_ in inputs], batch_size)

table.update(formulas=[
    "future_offset = __computer.compute(k)",
    "result = future_offset.getFuture().get()",
    "clean = __computer.clear()",
])
```

Interestingly, the error goes away if I remove `clean = __computer.clear()`:
```
import jpy
_JLearnComputer = jpy.get_type("io.deephaven.integrations.learn.Computer")

from deephaven import empty_table
from deephaven import learn
from deephaven.learn import gather
import numpy as np

table = empty_table(10).update(["X = ii", "Y = Math.sin(X)"])

# Function that gets called on each row of inputs
def model_func(x, y):
    return 1

# A function to gather data from columns into a NumPy array of longs
def table_to_array_long(rows, cols):
    return learn.gather.table_to_numpy_2d(rows, cols, np_type=np.int_)

# A function to gather data from columns into a NumPy array of doubles
def table_to_array_double(rows, cols):
    return learn.gather.table_to_numpy_2d(rows, cols, np_type=np.double)

# here we recreate the arguments passed to learn
inputs=[learn.Input(["X"], table_to_array_long), learn.Input("Y", table_to_array_double)]
outputs=None
batch_size=10

__computer = _JLearnComputer(table.j_table, model_func,
        [input_.input for input_ in inputs], batch_size)

table.update(formulas=[
    "future_offset = __computer.compute(k)",
    "result = future_offset.getFuture().get()"
])
```

I've confirmed that the error thrown by the former code block _does not_ appear in 0.32.0.

**Comment by alexpeters1208** [comment]
Additionally, the snapshots first failed at 12:40 AM on Feb 21, so I looked over the commits made on Feb 20. That would be [5167](https://github.com/deephaven/deephaven-core/commit/6356a7cf1cddd8c3ac7c4ca813065440bb1ec6dd), [5119](https://github.com/deephaven/deephaven-core/commit/b31fe87f42db7cb7a23b6bf9e36f8e735faeae5c), and [5172](https://github.com/deephaven/deephaven-core/commit/637d844c3920ca60874978899ef5fc8170f32e67). None of these are obviously related to the problems we're seeing here.
