### ISSUE TITLE
Adding a ticking table to an InputTable appears to be deadlocking under locks.

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#5240]
Running this script in the web IDE locks up the server:
```python
import time
from deephaven import time_table, input_table

t = time_table("PT1s", blink_table=True)
it = input_table({c.name: c.data_type for c in t.columns})
it.add(t)
```

**Comment by jmao-denver** [comment]
The right solution should be to check for the potential dead lock condition and throw an exception from the engine.

**Comment by rcaudy** [comment]
Groovy reproducer:
```
tt = timeTableBuilder().period("PT1s").blinkTable(true).build()
it = io.deephaven.engine.table.impl.util.AppendOnlyArrayBackedInputTable.make(tt.getDefinition())
itu = it.inputTable()

itu.add(tt)
```

Java thread dump:
```
"DeephavenApiServer-Scheduler-Serial-1@9886" daemon prio=5 tid=0x4e nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks DeephavenApiServer-Scheduler-Concurrent-1@9840
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	  at io.deephaven.engine.table.impl.BaseTable$$Lambda$1177.1888612530.run(Unknown Source:-1)
	  at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:33)
	  at io.deephaven.engine.table.impl.BaseTable.awaitUpdate(BaseTable.java:523)
	  at io.deephaven.engine.table.impl.util.BaseArrayBackedInputTable$ArrayBackedInputTableUpdater.waitForSequence(BaseArrayBackedInputTable.java:312)
	  at io.deephaven.engine.table.impl.util.BaseArrayBackedInputTable$ArrayBackedInputTableUpdater.blockingContinuation(BaseArrayBackedInputTable.java:266)
	  at io.deephaven.engine.table.impl.util.BaseArrayBackedInputTable$ArrayBackedInputTableUpdater.add(BaseArrayBackedInputTable.java:201)
	  at io.deephaven.engine.util.input.InputTableUpdater$add.call(Unknown Source:-1)
	  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	  at io.deephaven.dynamic.Script_6.run(Script_6.groovy:6)
	  at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
	  at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
	  at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
	  at io.deephaven.engine.util.GroovyDeephavenSession.evaluateCommand(GroovyDeephavenSession.java:291)
	  at io.deephaven.engine.util.GroovyDeephavenSession.lambda$evaluate$0(GroovyDeephavenSession.java:314)
	  at io.deephaven.engine.util.GroovyDeephavenSession$$Lambda$728.1708779306.run(Unknown Source:-1)
	  at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	  at io.deephaven.engine.util.GroovyDeephavenSession.evaluate(GroovyDeephavenSession.java:314)
	  at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:148)
	  at io.deephaven.engine.util.AbstractScriptSession$$Lambda$642.1381702512.run(Unknown Source:-1)
	  at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	  at io.deephaven.engine.context.ExecutionContext$$Lambda$231.100189132.get(Unknown Source:-1)
	  at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	  at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	  at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:148)
	  - locked <0x26a2> (a io.deephaven.engine.util.GroovyDeephavenSession)
	  at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	  at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	  at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	  at io.deephaven.server.console.ConsoleServiceGrpcImpl$$Lambda$1146.961445791.run(Unknown Source:-1)
	  at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$3(SessionState.java:1519)
	  at io.deephaven.server.session.SessionState$ExportBuilder$$Lambda$1130.1297572700.call(Unknown Source:-1)
	  at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:992)
	  at io.deephaven.server.session.SessionState$ExportObject$$Lambda$1147.1832076372.run(Unknown Source:-1)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	  at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory$$Lambda$756.219286908.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:829)
```

**Comment by rcaudy** [comment]
The bug isn't exactly as described. The issue is that the implementation is assuming there will be an actual change to the input table upon processing an add or a delete, but in this case we are "adding" an empty table.

We should make the code resilient against this pattern. In all cases, we should check for an empty addition or deletion after snapshotting the table-to-add or the table-to-delete. There are a few ways to handle this condition, and I'm ambivalent about which we pick:
1. Return immediately, making an empty add or delete a no-op.
2. Throw an exception to alert the user to their error.
3. (1) for ticking input, (2) for static input.

@rbasralian @jjbrosnan @cpwright opinions as to the best empty-handling behavior?

**Comment by cpwright** [comment]
I would in all cases treat it as a do-nothing, but only after we've verified the definition and other common error checks.

**Comment by rcaudy** [comment]
I think that's a fine answer, so let's make it so unless there are dissenters very soon.
@jmao-denver the change looks like:
1. `enqueueAddition` and `enqueueDeletion` to return `null` if the result of the `snapshot` `isEmpty()`.
2. `add` and `delete` to return immediately if `enqueueAddition` or `enqueueDeletion` returns `null`, rather than calling `blockingContinuation`.
3. `addAsync` and `deleteAsync` to call `listener.onSuccess()` and return immediately if `enqueueAddition` or `enqueueDeletion` returns `null`, rather than calling `asynchronousContinuation`.
