### ISSUE TITLE
`rolling_formula` does not support Boolean operations

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#5308]
**Description**

I've been able to repro behavior reported by one of our users, in which `rolling_formula` does not work on a Boolean column. The goal of the operation is to check if there have been any true values in the past N ticks. Instead of that happening, it complains with an error, which is shown below.

It appears we have no `BooleanVector` type, so I suspect this is what's causing the issue.

**Steps to reproduce**

Run the following query from the Python API (I'm sure the equivalent Groovy/Java query would repro this as well):

```python
from deephaven.updateby import rolling_formula_tick
from deephaven import empty_table

t = empty_table(10).update(["IsEvent = (i % 2 == 0) ? true : false"])
t2 = t.update_by(ops=rolling_formula_tick("or(x)", "x", "HadEvent = IsEvent", 5))
```

**Expected results**

A new column, `HadEvent` being true where any of the last five rows contains a true.

**Actual results**

The following error:

```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update-by operation failed. : java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.Boolean; ([Ljava.lang.Object; and [Ljava.lang.Boolean; are in module java.base of loader 'bootstrap')
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 2037, in update_by
    return Table(j_table=self.j_table.updateBy(j_array_list(ops), *by))
RuntimeError: io.deephaven.engine.exceptions.TableInitializationException: Error while initializing io.deephaven.engine.table.impl.updateby.ZeroKeyUpdateByManager@4ccc70e5-bucket-[]: an exception occurred while initializing zero-key updateBy
	at io.deephaven.engine.table.impl.updateby.ZeroKeyUpdateByManager.<init>(ZeroKeyUpdateByManager.java:117)
	at io.deephaven.engine.table.impl.updateby.UpdateBy.lambda$updateBy$4(UpdateBy.java:1406)
	at io.deephaven.engine.liveness.LivenessScopeStack.computeEnclosed(LivenessScopeStack.java:179)
	at io.deephaven.engine.table.impl.updateby.UpdateBy.updateBy(UpdateBy.java:1405)
	at io.deephaven.engine.table.impl.updateby.UpdateBy.updateBy(UpdateBy.java:1339)
	at io.deephaven.engine.table.impl.QueryTable.lambda$updateBy$69(QueryTable.java:3456)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)
	at io.deephaven.engine.table.impl.QueryTable.updateBy(QueryTable.java:3455)
	at io.deephaven.engine.table.impl.QueryTable.updateBy(QueryTable.java:95)
	at io.deephaven.api.TableOperationsDefaults.updateBy(TableOperationsDefaults.java:356)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:205)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:205)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:148)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:148)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$3(SessionState.java:1519)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:992)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	at java.base/java.lang.Thread.run(Thread.java:1583)
caused by io.deephaven.engine.table.impl.select.FormulaEvaluationException: In formula: HadEvent = or(VectorConversions.nullSafeVectorToArray(__PARAM_COLUMN__))
	at io.deephaven.temp.c_d923e5e729c496a384391c1f6335fddf23e965ecbed302b82d6e53c070e1929cv65_0.Formula.applyFormulaPerItem(Formula.java:164)
	at io.deephaven.temp.c_d923e5e729c496a384391c1f6335fddf23e965ecbed302b82d6e53c070e1929cv65_0.Formula.getBoolean(Formula.java:96)
	at io.deephaven.temp.c_d923e5e729c496a384391c1f6335fddf23e965ecbed302b82d6e53c070e1929cv65_0.Formula.get(Formula.java:111)
	at io.deephaven.engine.table.impl.select.Formula.getByte(Formula.java:45)
	at io.deephaven.engine.table.impl.sources.ViewColumnSource.getByte(ViewColumnSource.java:62)
	at io.deephaven.engine.table.impl.updateby.rollingformula.BaseRollingFormulaOperator.lambda$getChunkSetter$2(BaseRollingFormulaOperator.java:175)
	at io.deephaven.engine.table.impl.updateby.rollingformula.BooleanRollingFormulaOperator$Context.accumulateRolling(BooleanRollingFormulaOperator.java:122)
	at io.deephaven.engine.table.impl.updateby.UpdateByWindowRollingBase.processWindowBucketOperatorSet(UpdateByWindowRollingBase.java:198)
	at io.deephaven.engine.table.impl.updateby.UpdateBy$PhasedUpdateProcessor.lambda$processWindowOperatorSet$24(UpdateBy.java:834)
	at io.deephaven.engine.table.impl.util.JobScheduler.lambda$iterateParallel$1(JobScheduler.java:356)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:258)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:164)
	at io.deephaven.engine.table.impl.util.OperationInitializerJobScheduler.lambda$submit$0(OperationInitializerJobScheduler.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.table.impl.OperationInitializationThreadPool$1.lambda$newThread$0(OperationInitializationThreadPool.java:53)
	... 1 more
caused by java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.Boolean; ([Ljava.lang.Object; and [Ljava.lang.Boolean; are in module java.base of loader 'bootstrap')
	at io.deephaven.temp.c_d923e5e729c496a384391c1f6335fddf23e965ecbed302b82d6e53c070e1929cv65_0.Formula.applyFormulaPerItem(Formula.java:162)
	... 21 more


Line: 2039
Namespace: update_by
File: /opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table.py", line 2039, in update_by

	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:205)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:205)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:148)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:148)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$3(SessionState.java:1519)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:992)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: edge (0.33.4?)
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by jjbrosnan** [comment]
I suspect this is due to no `BooleanVector` existing. If that's the case, I should perhaps file a feature request for that rather than this bug report.
