### ISSUE TITLE
Test failure: io.deephaven.web.client.api.PartitionedTableTestGwt testTickingPartitionedTable

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#5326]
A bad run here: https://github.com/deephaven/deephaven-core/actions/runs/8555223305

```
java.lang.RuntimeException: TypeError: this$static is null
	at java.lang.Throwable.Throwable(Throwable.java:69)
	at java.lang.Exception.Exception(Exception.java:29)
	at java.lang.RuntimeException.RuntimeException(RuntimeException.java:29)
	at io.deephaven.web.client.api.AbstractAsyncGwtTestCase.$report(AbstractAsyncGwtTestCase.java:210)
	at io.deephaven.web.client.api.PartitionedTableTestGwt$7methodref$report$Type.onInvoke(PartitionedTableTestGwt.java:135)
	at Unknown.anonymous(Runtime.java:166)
	at io.deephaven.web.client.api.JsTable.$state(JsTable.java:315)
	at io.deephaven.web.client.api.JsTable.$lastVisibleState(JsTable.java:294)
	at io.deephaven.web.client.api.PartitionedTableTestGwt.lambda$18(JsTable.java:444)
	at io.deephaven.web.client.api.PartitionedTableTestGwt$lambda$18$Type.onInvoke(PartitionedTableTestGwt.java:125)
	at Unknown.anonymous(Runtime.java:166)
	at io.deephaven.web.client.api.subscription.ViewportTestGwt.lambda$76(ViewportTestGwt.java:396)
	at io.deephaven.web.client.api.subscription.ViewportTestGwt$lambda$76$Type.onInvoke(ViewportTestGwt.java:394)
	at Unknown.anonymous(Runtime.java:166)
```

**Comment by mofojed** [comment]
Another run got this error:
```
java.lang.RuntimeException: Error: junit.framework.AssertionFailedError: expected: <0>, actual: <1>
	at java.lang.Throwable.Throwable(Throwable.java:69)
	at java.lang.Exception.Exception(Exception.java:29)
	at java.lang.RuntimeException.RuntimeException(RuntimeException.java:29)
	at io.deephaven.web.client.api.AbstractAsyncGwtTestCase.$report(AbstractAsyncGwtTestCase.java:210)
	at io.deephaven.web.client.api.PartitionedTableTestGwt$9methodref$report$Type.onInvoke(PartitionedTableTestGwt.java:171)
	at Unknown.anonymous(Runtime.java:166)
	at junit.framework.Assert.fail(Assert.java:231)
	at junit.framework.Assert.failNotEquals(Assert.java:237)
	at junit.framework.Assert.assertEquals(Assert.java:132)
	at junit.framework.Assert.assertEquals(Assert.java:61)
	at io.deephaven.web.client.api.PartitionedTableTestGwt.$lambda$23(PartitionedTableTestGwt.java:155)
	at io.deephaven.web.client.api.PartitionedTableTestGwt$lambda$23$Type.onInvoke(PartitionedTableTestGwt.java:154)
	at Unknown.anonymous(Runtime.java:166)
	at io.deephaven.web.client.api.subscription.ViewportTestGwt.lambda$76(ViewportTestGwt.java:396)
	at io.deephaven.web.client.api.subscription.ViewportTestGwt$lambda$76$Type.onInvoke(ViewportTestGwt.java:394)
	at Unknown.anonymous(Runtime.java:166)
```
