### ISSUE TITLE
Inconsistency between FilterComparison eq and geq

### ISSUE THREAD

**Issue by arman-ddl** [deephaven/deephaven-core#5407]
**Steps to reproduce**
1. Start a Core worker.
2. Run a filter with `FilterComparison.geq`:
```
import io.deephaven.api.ColumnName
import io.deephaven.api.filter.FilterComparison
import io.deephaven.api.literal.Literal

test = emptyTable(1)
  .updateView("Test=`Z`")
  .where(FilterComparison.geq(ColumnName.of("Test"), Literal.of("A")))
```

**Expected results**

No error.

**Actual results**

Error:
```
Error running script: java.lang.IllegalArgumentException: String literal not enclosed in quotes ("A")
	at io.deephaven.engine.table.impl.select.MatchFilter$ColumnTypeConvertorFactory$11.convertStringLiteral(MatchFilter.java:316)
	at io.deephaven.engine.table.impl.select.RangeConditionFilter.init(RangeConditionFilter.java:167)
	at io.deephaven.engine.table.impl.QueryTable.lambda$whereInternal$26(QueryTable.java:1191)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)
	at io.deephaven.engine.table.impl.QueryTable.whereInternal(QueryTable.java:1159)
	at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:1146)
	at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:95)
... <groovy and such> ...
```

**Additional details and attachments**

Unlike `FilterComparison.geq`, there is no error when running with `FilterComparison.eq`:
```
import io.deephaven.api.ColumnName
import io.deephaven.api.filter.FilterComparison
import io.deephaven.api.literal.Literal

test = emptyTable(1)
  .updateView("Test=`Z`")
  .where(FilterComparison.eq(ColumnName.of("Test"), Literal.of("Z")))
```

There's inconsistency in whether to require enclosing quotes in the literal, seemingly in the direction of `geq` being erroneous because specifying a string literal should arguably handle enclosing quotes internally. Might want to check other FilterComparison methods too if applicable.

**Versions**
 - Deephaven: 0.33.3
 - OS: rocky9
 - Browser: Chrome
 - Docker: N / A

**Comment by devinrsmith** [comment]
In  addition, it looks like there is a case-sensitivity issue with eq:

```groovy
test = emptyTable(1)
  .updateView("Test=`Z`")
  .where(FilterComparison.eq(ColumnName.of("Test"), Literal.of("z")))
```

will match (notice `Z` vs `z`).

**Comment by devinrsmith** [comment]
This might also be a good motivator to do #3730
