### ISSUE TITLE
Formula code uses wrong index for prev methods on i and ii for ticking tables.

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#544]
Relatively easy to repro w/ my FullAdder demo. (Can give a demo branch later.)

Added some additional non-null checks to trace the culprit, here it is:

```
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:203)
        at io.deephaven.db.v2.utils.TreeIndex.<init>(TreeIndex.java:100)
        at io.deephaven.db.v2.utils.TreeIndex.invert(TreeIndex.java:303)
        at io.deephaven.db.v2.utils.SortedIndex.invert(SortedIndex.java:105)
        at io.deephaven.temp.cm1760100514987228486v52_0.Formula.fillChunkHelper(Formula.java:150)
        at io.deephaven.temp.cm1760100514987228486v52_0.Formula.fillPrevChunk(Formula.java:142)
        at io.deephaven.db.v2.select.Formula.getPrevChunk(Formula.java:166)
        at io.deephaven.db.v2.sources.ViewColumnSource.getPrevChunk(ViewColumnSource.java:234)
        at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.fetchValues(ChunkedOperatorAggregationHelper.java:1769)
        at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.doNoKeyUpdate(ChunkedOperatorAggregationHelper.java:1676)
        at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.doNoKeyRemoval(ChunkedOperatorAggregationHelper.java:1571)
        at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.access$2600(ChunkedOperatorAggregationHelper.java:38)
        at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper$2.onUpdate(ChunkedOperatorAggregationHelper.java:1468)
        at io.deephaven.db.v2.InstrumentedShiftAwareListener$Notification.lambda$run$0(InstrumentedShiftAwareListener.java:36)
        at io.deephaven.db.v2.InstrumentedListenerBase$NotificationBase.doRunInternal(InstrumentedListenerBase.java:223)
        at io.deephaven.db.v2.InstrumentedListenerBase$NotificationBase.doRun(InstrumentedListenerBase.java:205)
        at io.deephaven.db.v2.InstrumentedShiftAwareListener$Notification.run(InstrumentedShiftAwareListener.java:36)
        at io.deephaven.db.tables.live.LiveTableMonitor.runNotification(LiveTableMonitor.java:1308)
        at io.deephaven.db.tables.live.LiveTableMonitor.access$1100(LiveTableMonitor.java:70)
        at io.deephaven.db.tables.live.LiveTableMonitor$QueueNotificationProcessor.doWork(LiveTableMonitor.java:1457)
        at io.deephaven.db.tables.live.LiveTableMonitor.flushNormalNotificationsAndCompleteCycle(LiveTableMonitor.java:1192)
        at io.deephaven.db.tables.live.LiveTableMonitor.flushNotificationsAndCompleteCycle(LiveTableMonitor.java:1141)
        at io.deephaven.db.tables.live.LiveTableMonitor.lambda$doRefresh$14(LiveTableMonitor.java:1717)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:29)
        at io.deephaven.db.tables.live.LiveTableMonitor.doRefresh(LiveTableMonitor.java:1707)
        at io.deephaven.db.tables.live.LiveTableMonitor.drainSingleUpdateQueue(LiveTableMonitor.java:1668)
        at io.deephaven.db.tables.live.LiveTableMonitor.waitForEndTime(LiveTableMonitor.java:1631)
        at io.deephaven.db.tables.live.LiveTableMonitor.waitForNextCycle(LiveTableMonitor.java:1613)
        at io.deephaven.db.tables.live.LiveTableMonitor.refreshTablesAndFlushNotifications(LiveTableMonitor.java:1587)
        at io.deephaven.db.tables.live.LiveTableMonitor.access$300(LiveTableMonitor.java:70)
        at io.deephaven.db.tables.live.LiveTableMonitor$1.run(LiveTableMonitor.java:195)
```

**Comment by devinrsmith** [comment]
Here's a slightly different trace:

```
ERROR EFAULT.refreshThread | .d.v.InstrumentedListener | Uncaught exception for entry= by(Sum), added.size()=2, modified.size()=0, removed.size()=2, shifted.size()=0, modifiedColumnSet={}:
java.lang.IllegalArgumentException: keys argument has elements not in the index
        at io.deephaven.db.v2.utils.sortedranges.SortedRanges.ixInvertOnNew(SortedRanges.java:4888)
        at io.deephaven.db.v2.utils.TreeIndex.invert(TreeIndex.java:302)
        at io.deephaven.db.v2.utils.SortedIndex.invert(SortedIndex.java:105)
        at io.deephaven.temp.cm5333356987228486v52_0.Formula.fillChunkHelper(Formula.java:150)
        at io.deephaven.temp.cm5333356987228486v52_0.Formula.fillPrevChunk(Formula.java:142)
        at io.deephaven.db.v2.select.Formula.getPrevChunk(Formula.java:166)
        at io.deephaven.db.v2.sources.ViewColumnSource.getPrevChunk(ViewColumnSource.java:234)
        at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.fetchValues(ChunkedOperatorAggregationHelper.java:1769)
        at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.doNoKeyUpdate(ChunkedOperatorAggregationHelper.java:1676)
        at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.doNoKeyRemoval(ChunkedOperatorAggregationHelper.java:1571)
        at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper.access$2600(ChunkedOperatorAggregationHelper.java:38)
        at io.deephaven.db.v2.by.ChunkedOperatorAggregationHelper$2.onUpdate(ChunkedOperatorAggregationHelper.java:1468)
        at io.deephaven.db.v2.InstrumentedShiftAwareListener$Notification.lambda$run$0(InstrumentedShiftAwareListener.java:36)
        at io.deephaven.db.v2.InstrumentedListenerBase$NotificationBase.doRunInternal(InstrumentedListenerBase.java:223)
        at io.deephaven.db.v2.InstrumentedListenerBase$NotificationBase.doRun(InstrumentedListenerBase.java:205)
        at io.deephaven.db.v2.InstrumentedShiftAwareListener$Notification.run(InstrumentedShiftAwareListener.java:36)
        at io.deephaven.db.tables.live.LiveTableMonitor.runNotification(LiveTableMonitor.java:1322)
        at io.deephaven.db.tables.live.LiveTableMonitor.access$1000(LiveTableMonitor.java:70)
        at io.deephaven.db.tables.live.LiveTableMonitor$QueueNotificationProcessor.doWork(LiveTableMonitor.java:1471)
        at io.deephaven.db.tables.live.LiveTableMonitor.flushNormalNotificationsAndCompleteCycle(LiveTableMonitor.java:1206)
        at io.deephaven.db.tables.live.LiveTableMonitor.flushNotificationsAndCompleteCycle(LiveTableMonitor.java:1155)
        at io.deephaven.db.tables.live.LiveTableMonitor.lambda$doRefresh$14(LiveTableMonitor.java:1731)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:29)
        at io.deephaven.db.tables.live.LiveTableMonitor.doRefresh(LiveTableMonitor.java:1721)
        at io.deephaven.db.tables.live.LiveTableMonitor.refreshAllTables(LiveTableMonitor.java:1708)
        at io.deephaven.db.tables.live.LiveTableMonitor.refreshTablesAndFlushNotifications(LiveTableMonitor.java:1573)
        at io.deephaven.db.tables.live.LiveTableMonitor.access$300(LiveTableMonitor.java:70)
        at io.deephaven.db.tables.live.LiveTableMonitor$1.run(LiveTableMonitor.java:195)
```

**Comment by devinrsmith** [comment]
Here's a reproducer:

```groovy
zero = 
x = merge(newTable(byteCol("Q", (byte)0)), timeTable("00:00:01").view("Q=(byte)(i%2)"))
    .tail(1)
    .view("Q=Q*i")
    .sumBy()
```

**Comment by jcferretti** [comment]
After discussions with Charles and Corey the root cause of the issue is the same index is used for prev and current methods on generated Formula code.  The fix is relatively simple, to call __index.getPrevIndex() when appropriate, I am working on that fix.
I have changed the title of this issue to reflect this.
