### ISSUE TITLE
SQL can't evaluate statement if any unrelated table in scope is incompatible

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#5443]
**Description**

Deephaven's Java Sql class supports reading tables from scope, though it also supports being given named tables in a map. The python `deephaven.experimental.sql` package on the other hand only supports reading tables from scope.

If any of the provided (or scoped) tables contain a column type that can't be processed (for example `SQLTODO(custom-type)` or `SQLTODO(array-type)`), the entire eval() will fail, even if that table (or its column) won't be used at all during the rest of the operation.

**Steps to reproduce**
1. Import and use the sql for some trivial operation (all tables here have zero rows to confirm that this is specific to schemas, not content):
    ```python
    from deephaven.experimental import sql
    from deephaven import empty_table
    t = empty_table(0)
    a = {} # Not used yet, just in scope to confirm that this doesn't cause a problem by itself
    t2 = sql.evaluate('select * from t')
```
2. Confirm success, t and t2 are empty
3. Create a new table that uses an unsupported type
    ```python
    t3 = empty_table(0).update("A = a")
```
4. Make another sql call without referencing `t3` (same call as above)
    ```python
    t4 = sql.evaluate('select * from t')
```

**Expected results**

`t4` should have a table with no rows and no columns - neither `t3` nor its column `t3.A` are referenced in the sql expression `select * from t`.

**Actual results**

```
Error running script: java.lang.RuntimeException: Error in Python interpreter:

Type: <class 'deephaven.dherror.DHError'>
Value: failed to execute SQL. : RuntimeError: java.lang.UnsupportedOperationException: SQLTODO(custom-type)
Traceback (most recent call last):
  File "/home/colin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/deephaven/experimental/sql.py", line 53, in evaluate
    return Table(j_table=_JSql.evaluate(sql))
RuntimeError: java.lang.UnsupportedOperationException: SQLTODO(custom-type)
	at io.deephaven.sql.TypeAdapter.visit(TypeAdapter.java:126)
	at io.deephaven.sql.TypeAdapter.visit(TypeAdapter.java:31)
	at io.deephaven.qst.type.CustomType.walk(CustomType.java:35)
	at io.deephaven.sql.TypeAdapter.visit(TypeAdapter.java:99)
	at io.deephaven.sql.TypeAdapter.visit(TypeAdapter.java:31)
	at io.deephaven.qst.type.GenericTypeBase.walk(GenericTypeBase.java:10)
	at io.deephaven.sql.TypeAdapter.of(TypeAdapter.java:35)
	at io.deephaven.sql.TypeAdapter.of(TypeAdapter.java:41)
	at io.deephaven.sql.SqlAdapter.reader(SqlAdapter.java:152)
	at io.deephaven.sql.SqlAdapter.parseSql(SqlAdapter.java:71)
	at io.deephaven.engine.sql.Sql.parseSql(Sql.java:64)
	at io.deephaven.engine.sql.Sql.evaluate(Sql.java:52)
	at io.deephaven.engine.sql.Sql.evaluate(Sql.java:42)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:205)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:205)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:163)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:163)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1536)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:995)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	at java.base/java.lang.Thread.run(Thread.java:829)


Line: 55
Namespace: evaluate
File: /home/colin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/deephaven/experimental/sql.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/colin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/deephaven/experimental/sql.py", line 55, in evaluate

	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:205)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:205)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:163)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:163)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1536)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:995)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Versions**
 - Deephaven: 0.34
 - OS: Any
 - Browser: Any
 - Docker: n/a

---
My naive thought here is that SqlAdapter.reader() should wrap the call to `TypeAdapter.of()` in a try/catch, and we should use a more specific exception (extend from UnsupportedOperationException even?) to signal that while _a_ table contains _an_ unsupported column type, this shouldn't be fatal. 

Potentially go further, `TypeAdapter.of()`'s own loop could handle an exception and just skip the column - either pretend that the column wasn't even there, or leave a specific column type in place that, if we ever attempt to reference it from the query itself, we can fail "yes i see the column, no you can't use it, SQLTODO(custom-type)/(array-type)/etc"

**Comment by devinrsmith** [comment]
There's a related SQLTODO I have documented:

```java
// SQLTODO(catalog-reader-implementation)
//
// The current implementation assumes that the user will pass in all the headers they care about. When executing
// a SQL query, this means that either a) the user is explicit about the context they care about or b) all
// possible headers are collected. a) is not very user friendly and b) is inefficient.
//
// A potentially better model would be an interface where the caller could produce the TableHeaders on demand
// instead of requiring them all up-front. This would require implementing / wrapping
// org.apache.calcite.prepare.Prepare.CatalogReader which is possible, but non-trivial. There may also be
// boundary-crossing concerns wrt python.
```

We could also expose a workaround:

```python
t2 = sql.evaluate('select * from t', scope={'t': t})
```

But fundamentally, I agree we should not be failing in this case regardless.
