### ISSUE TITLE
`deephaven.pandas.to_table`: Table object is not iterable

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#5614]
**Description**

`deephaven.pandas.to_table` is failing to convert a simple DataFrame to a table. Here is a reproducer.

```python
from deephaven import pandas as dhpd
from deephaven import empty_table

source = empty_table(10).update(["X = i", "Y = randomDouble(0, 100)"])

df = dhpd.to_pandas(source)

result = dhpd.to_table(source)
```

**Expected results**

A `result` table.

**Actual results**

```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'TypeError'>
Value: 'Table' object is not iterable
Line: 220
Namespace: to_table
File: /opt/deephaven/venv/lib/python3.10/site-packages/deephaven/pandas.py
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/pandas.py", line 220, in to_table

	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:205)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:205)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:163)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:163)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:191)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1537)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:995)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Additional details and attachments**

None

**Versions**

 - Deephaven: 0.34.3
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by jmao-denver** [comment]
The argument to `to_table` should be a DataFrame. @jjbrosnan a user mistake?

**Comment by jjbrosnan** [comment]
I am stupid. User error.
