### ISSUE TITLE
`snapshot_when` history might need some kind of re-design

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#5841]
Deephaven: `0.34.3`

```python
# Imports
import numpy as np
import random
from deephaven import time_table, dtypes, new_table
from deephaven.column import datetime_col, string_col, double_col
from deephaven.table_listener import listen, TableUpdate
from deephaven.stream.table_publisher import table_publisher

# Create a table to be used as input

def gen_label() -> str:
    return random.choice(["Denver", "New York", "Chicago", "Boise"])

source = time_table("PT0.1S").update(formulas=["Label = gen_label()", "X = sqrt(i)", "Y = -sqrt(sqrt(i))"])

# Define the AI model

def compute_ai_model(features):
    return np.sum(features, axis=1, keepdims=True)

# Set up the output tables

preds, preds_publisher = table_publisher("AIOutput", {"Timestamp": dtypes.Instant, "Label": dtypes.string, "Pred": dtypes.float64})

preds_history = preds.snapshot_when(trigger_table=preds, stamp_cols=[], history=True)

# Create a table listener

def on_update(update: TableUpdate, is_replay: bool) -> None:
    cols = ["Timestamp", "Label", "X", "Y"]
    adds = update.added(cols)
    modifies = update.modified(cols)

    # Combine adds and modifies

    data = {}

    for col in cols:
        if adds and modifies:
            data[col] = np.hstack(adds[col], modifies[col])
        elif adds:
            data[col] = adds[col]
        elif modifies:
            data[col] = modifies[col]
        else:
            return

    # Create the input to the AI model

    inputs = np.stack([data[k] for k in ["X", "Y"]], axis=-1)

    # Compute the AI model

    outputs = compute_ai_model(inputs)

    # Populate the output table

    tout = new_table([
        datetime_col("Timestamp", data["Timestamp"]),
        string_col("Label", data["Label"]),
        double_col("Pred", outputs[:, 0]),
    ])

    preds_publisher.add(tout)


handle = listen(source, on_update, do_replay=True)

```

Exception:
```
aph-updateExecutor-1 | rumentedTableListenerBase | Uncaught exception for entry= snapshotHistory[Timestamp, Label, Pred], added.size()=0, modified.size()=20, removed.size()=0, shifted.size()=0, modifiedColumnSet={ALL}:
io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted modified.size() == 0, instead modified == {0-19}.
	at io.deephaven.base.verify.Assert.fail(Assert.java:100)
	at io.deephaven.base.verify.Assert.assertion(Assert.java:133)
	at io.deephaven.engine.table.impl.QueryTable$3.onUpdate(QueryTable.java:2424)
	at io.deephaven.engine.table.impl.ShiftObliviousInstrumentedListener$Notification.lambda$run$0(ShiftObliviousInstrumentedListener.java:50)
	at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:334)
	at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:316)
	at io.deephaven.engine.table.impl.ShiftObliviousInstrumentedListener$Notification.run(ShiftObliviousInstrumentedListener.java:45)
	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:711)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:836)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by rcaudy** [comment]
The issue is not that source and trigger are the same. The issue is that for history=True, it's expected that the source does not modify or remove rows.

**Comment by rcaudy** [comment]
We should better document the assumptions around source and trigger table for the various snapshotWhen options.

**Comment by chipkent** [comment]
The restrictions on the source table do not make sense.  `history=True` is to keep an ongoing history of a table.  For example, assume a user has a `positions` table that contains positions of securities in their portfolio.  The rows in this table increase and decrease as they trade in and out of positions.  They might reasonably want a table with the history of their positions every 10 minutes.  The current code would blow up on this.

**Comment by rcaudy** [comment]
> The issue is not that source and trigger are the same. The issue is that for history=True, it's expected that the source does not modify or remove rows.

I was incorrect, before (because I forgo that  `QueryTable.snapshotHistoryInternal` uses trigger as the LHS and source as the RHS. We insist that the trigger be append-only, not the source.

This should be better-documented. In general, I would like us to audit the restrictions and be sure they are included in the JavaDoc and PyDoc.

**Comment by chipkent** [comment]
I agree that the only change is a documentation note for `history` indicating that the trigger table must be append-only.
