### ISSUE TITLE
ArrayIndexOutOfBoundsException in multiJoin

### ISSUE THREAD

**Issue by devonpallison** [deephaven/deephaven-core#5882]
**Description**

My query sporadically fails with this exception:

`java.lang.ArrayIndexOutOfBoundsException: Index 4124 out of bounds for length 4096
	at io.deephaven.engine.table.impl.sources.immutable.ImmutableIntArraySource.getUnsafe(ImmutableIntArraySource.java:79)
	at io.deephaven.engine.table.impl.by.typed.incopen.gen.c_3dbd1b72150545ad02f131af8ff86a9e4417f3d980dec0668f95d0ae7eea5b92v61_0.IncrementalMultiJoinHasherLongLongLong.buildFromTable(IncrementalMultiJoinHasherLongLongLong.java:72)
	at io.deephaven.engine.table.impl.multijoin.IncrementalMultiJoinStateManagerTypedBase$BuildHandler.doBuild(IncrementalMultiJoinStateManagerTypedBase.java:176)
	at io.deephaven.engine.table.impl.multijoin.IncrementalMultiJoinStateManagerTypedBase.buildTable(IncrementalMultiJoinStateManagerTypedBase.java:353)
	at io.deephaven.engine.table.impl.multijoin.IncrementalMultiJoinStateManagerTypedBase.processAdded(IncrementalMultiJoinStateManagerTypedBase.java:310)
	at io.deephaven.engine.table.impl.MultiJoinTableImpl$MultiJoinMergedListener.process(MultiJoinTableImpl.java:508)
	at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:353)
	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:712)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:836)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
	at java.base/java.lang.Thread.run(Thread.java:840)`

**Steps to reproduce**
It has not been reproducible.

**Versions**
 - Deephaven: 0.33.3

**Comment by devonpallison** [comment]
> * Number of tables joined
8
> * Number and types of keys
3 keys, Instant, long and long
> * Table sizes and key cardinalities
Most between 15k to 35k.

**Comment by rcaudy** [comment]
I've generated the hasher class, and compensating for changes in line numbers, it looks like this is the offending line:
```
                int slotValue = slotToOutputRow.getUnsafe(tableLocation);
```

`slotToOutputRow` is intended and required to have capacity `tableSize`.

It appears that we resize it either in `rehashInternalFull` or in `setupNewAlternate`, depending on whether we are doing a full rehash or an incremental rehash. This also applies to `mainModifiedTrackerCookieSource` and `mainKeySources[]`.

**Comment by rcaudy** [comment]
I checked the version of the code in 0.33.3. While there's been some refactoring, I see no change in correctness on the face of it.

**Comment by rcaudy** [comment]
I think I see the issue!
`io.deephaven.engine.table.impl.multijoin.IncrementalMultiJoinStateManagerTypedBase#doRehash` contains a check before  `setupNewAlternate` (which handles the reallocation for table size changes):

```
        if (numEntries == 0) {
            return false;
        }
```

Meaning, if we have nothing to re-hash, we need not setup a new alternate table to hold un-migrated states... which is good, except that means we *also* won't re-size the main table's data structures, even though we may have increased `tableSize`.

Given that the main table starts at `tableSize = 4096` rows by default, with a maximum load factor of 0.75 by default, and we try to add up to `JoinControl.CHUNK_SIZE = 4096` rows at a time, we'll determine that `rehashRequired` pretty easily the first time we try to add a non-trivial number of rows (that is, more than 3072) to a previously-empty (`numEntries == 0`) table.

**Comment by rcaudy** [comment]
Reproducing unit test:
```
    @Test
    public void testRehashWhenEmpty() {
        final QueryTable t1 = TstUtils.testRefreshingTable(stringCol("Key"), intCol("S1"));
        final QueryTable t2 = TstUtils.testRefreshingTable(stringCol("Key"), intCol("S2"));

        final ControlledUpdateGraph updateGraph = ExecutionContext.getContext().getUpdateGraph().cast();

        final Table result = updateGraph.sharedLock().computeLocked(
                () -> MultiJoinFactory.of(new String[] {"Key"}, t1, t2).table());

        updateGraph.runWithinUnitTestCycle(() -> {
            final RowSet additions = RowSetFactory.fromRange(0, 3073);
            TstUtils.addToTable(t1, additions,
                    stringCol("Key", IntStream.rangeClosed(0, 3073).mapToObj(Integer::toString).toArray(String[]::new)),
                    intCol("S1", IntStream.rangeClosed(0, 3073).map(i -> i * 2).toArray()));
            t1.notifyListeners(additions, RowSetFactory.empty(), RowSetFactory.empty());
        });
    }
```

```
Received error notification: java.lang.ArrayIndexOutOfBoundsException: Index 5922 out of bounds for length 4096
	at io.deephaven.engine.table.impl.sources.immutable.ImmutableIntArraySource.getUnsafe(ImmutableIntArraySource.java:79)
	at io.deephaven.engine.table.impl.multijoin.typed.incopen.gen.IncrementalMultiJoinHasherObject.buildFromTable(IncrementalMultiJoinHasherObject.java:62)
	at io.deephaven.engine.table.impl.multijoin.IncrementalMultiJoinStateManagerTypedBase$BuildHandler.doBuild(IncrementalMultiJoinStateManagerTypedBase.java:176)
	at io.deephaven.engine.table.impl.multijoin.IncrementalMultiJoinStateManagerTypedBase.buildTable(IncrementalMultiJoinStateManagerTypedBase.java:353)
	at io.deephaven.engine.table.impl.multijoin.IncrementalMultiJoinStateManagerTypedBase.processAdded(IncrementalMultiJoinStateManagerTypedBase.java:310)
	at io.deephaven.engine.table.impl.MultiJoinTableImpl$MultiJoinMergedListener.process(MultiJoinTableImpl.java:511)
	at io.deephaven.engine.table.impl.MergedListener$MergedNotification.run(MergedListener.java:361)
	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:711)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:836)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
```
