### ISSUE TITLE
Support SQL HAVING clause

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#6013]
A SQL HAVING clause is essentially a filter that is applied on the _results_ of an aggregation. Depending on how calcite exposes this, it may be relatively easy to hook this up to DHC table operation; ideally, calcite would expose a variable into the aggergation regardless of whether it shows up in the end results or not. In that way, it would be trivial to just apply a DHC where filter after the aggregation and then drop the column if it's not in the output. If calcite does _not_ expose the condition into the aggregation, we may want to introspect the query and make it so.

Here's an example where having clause can be computed from the results of the basic aggregation:

```sql
SELECT
  group, COUNT(id)
FROM
  my_table
GROUP BY
  group
HAVING COUNT(id) > 5
```

Here's an example where an additional (simple) aggregation needs to be performed:

```sql
SELECT
  group, COUNT(id)
FROM
  my_table
GROUP BY
  group
HAVING MAX(id) < 42
```

Here's an example of a more complex having aggregation:

```sql
SELECT
  group, COUNT(id)
FROM
  my_table
GROUP BY
  group
HAVING MAX(id) - MIN(id) > 13
```

It may be that only relatively simple having queries can be easily translated; TBD.

Part of #3473

**Comment by devinrsmith** [comment]
I'm also not sure if this is valid syntax or not, but can a having query reference columns that aren't actually declared as part of the projection?

```sql
SELECT
  group, COUNT(id)
FROM
  my_table
GROUP BY
  group
HAVING COUNT(some_other_field)
```

**Comment by pete-petey** [comment]
`failed to execute SQL. : RuntimeError: java.lang.IllegalStateException Traceback (most recent call last): File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/experimental/sql.py", line 53, in evaluate return Table(j_table=_JSql.evaluate(sql)) RuntimeError: java.lang.IllegalStateException at io.deephaven.sql.RelNodeAdapterNamed.visit(RelNodeAdapterNamed.java:55) at io.deephaven.sql.RelNodeAdapterNamed.visit(RelNodeAdapterNamed.java:19) at io.deephaven.sql.RelNodeVisitorAdapter.visit(RelNodeVisitorAdapter.java:70) at org.apache.calcite.rel.logical.LogicalFilter.accept(LogicalFilter.java:156) at io.deephaven.sql.RelNodeVisitor.accept(RelNodeVisitor.java:26) at io.deephaven.sql.RelNodeAdapterNamed.of(RelNodeAdapterNamed.java:22) at io.deephaven.sql.SqlAdapter.parseSql(SqlAdapter.java:107) at io.deephaven.engine.sql.Sql.parseSql(Sql.java:64) at io.deephaven.engine.sql.Sql.evaluate(Sql.java:52) at io.deephaven.engine.sql.Sql.evaluate(Sql.java:42) at org.jpy.PyLib.callAndReturnObject(Native Method) at org.jpy.PyObject.call(PyObject.java:449) at io.deephaven.integrations.python.PythonRunnable.run(PythonRunnable.java:22) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1583)`
