### ISSUE TITLE
Enable S3 to work without explicit region_name

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#6016]
It should be possible to use S3 without a region_name set:

https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/s3-cross-region.html

**Comment by devinrsmith** [comment]
```
RuntimeError: software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.D
efaultAwsRegionProviderChain@3398f283: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@5a077e64: Unable to load region from system settings. Region must be specified either via environment v
ariable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@15cc979f: No region provided in profile: default, software.amazon.awssdk.regions.providers.
InstanceProfileRegionProvider@5bddad11: Unable to contact EC2 metadata service.]                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                                   
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/parquet.py", line 205, in read                                                                                                                    
    return Table(_JParquetTools.readTable(path, read_instructions))                                                                                                                                                  
RuntimeError: software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@3398f283:
 [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@5a077e64: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system proper
ty (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@15cc979f: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@5bddad11
: Unable to contact EC2 metadata service.]                                                                                                                                                                           
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)                                                                                                   
        at software.amazon.awssdk.regions.providers.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:70)                                                                                                 
        at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveRegion(AwsDefaultClientBuilder.java:293)                                                                                     
        at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:600)                                                                                                                  
        at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:589)                                                                                                                         
        at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396)                                                                                                                     
        at software.amazon.awssdk.utils.AttributeMap$Builder.internalGet(AttributeMap.java:389)                                                                                                                      
        at software.amazon.awssdk.utils.AttributeMap$Builder.access$1300(AttributeMap.java:201)                                                                                                                      
        at software.amazon.awssdk.utils.AttributeMap$Builder$1.get(AttributeMap.java:399)                                                                                                                            
        at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveSigningRegion(AwsDefaultClientBuilder.java:260)                                                                              
        at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:600)                                                                                                                  
        at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:589)
        at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at software.amazon.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362)
        at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:232)
        at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeAwsConfiguration(AwsDefaultClientBuilder.java:184)
        at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:161)
        at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:219)
        at software.amazon.awssdk.services.s3.DefaultS3AsyncClientBuilder.buildClient(DefaultS3AsyncClientBuilder.java:51)
        at software.amazon.awssdk.services.s3.DefaultS3AsyncClientBuilder.buildClient(DefaultS3AsyncClientBuilder.java:27)
        at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155)
        at io.deephaven.extensions.s3.S3AsyncClientFactory.getAsyncClient(S3AsyncClientFactory.java:63)
        at io.deephaven.extensions.s3.S3SeekableChannelProvider.<init>(S3SeekableChannelProvider.java:77)
        at io.deephaven.extensions.s3.S3SeekableChannelProviderPlugin.createProvider(S3SeekableChannelProviderPlugin.java:36)
        at io.deephaven.util.channel.SeekableChannelsProviderLoader.fromServiceLoader(SeekableChannelsProviderLoader.java:52)
        at io.deephaven.parquet.table.location.ParquetTableLocationKey.<init>(ParquetTableLocationKey.java:58)
        at io.deephaven.parquet.table.ParquetTools.readSingleFileTable(ParquetTools.java:1040)
        at io.deephaven.parquet.table.ParquetTools.readTable(ParquetTools.java:146)
```
