### ISSUE TITLE
LocalTime Column Error with ui.component

### ISSUE THREAD

**Issue by dgodinez-dh** [deephaven/deephaven-core#6057]
When I create a table with a `LocalTime` column and wrap it in `@ui.component` it throws an exception. Here is example code:

```
from deephaven import empty_table, ui

@ui.component
def test_local_time(table):
    return table;

my_local_time_table = empty_table(1).update(
    ["LocalTime1 = '10:15:30.46'"]
)
my_local_time_componant=test_local_time(my_local_time_table)
```

Here is the exception:
```
dh-internal.js:1 Uncaught Error: java.lang.IllegalArgumentException: Unsupported Time unit: NANOSECOND
    at IllegalArgumentException_0.createError (dh-core.js:1464:10)
    at IllegalArgumentException_0.initializeBackingError (dh-core.js:1490:46)
    at IllegalArgumentException_0.Throwable_0 (dh-core.js:1421:8)
    at IllegalArgumentException_0.Exception_1 (dh-core.js:1515:18)
    at IllegalArgumentException_0.RuntimeException_1 (dh-core.js:1533:18)
    at new IllegalArgumentException_0 (dh-core.js:1547:25)
    at Object.$getReader (dh-core.js:21344:30)
    at Object.$parseFrom (dh-core.js:21003:28)
    at Object.$onFlightData (dh-core.js:27991:22)
    at Function.apply_135 (dh-core.js:28156:11)
    at lambda (dh-core.js:193:22)
    at dh-internal.js:1:321778
    at Array.forEach (<anonymous>)
    at dh-internal.js:1:321757
    at dh-internal.js:1:11539
    at Array.forEach (<anonymous>)
    at e.rawOnMessage (dh-internal.js:1:11501)
    at dh-internal.js:1:9314
    at Array.forEach (<anonymous>)
    at e.onTransportChunk (dh-internal.js:1:9189)
    at Object.$onMessage (dh-core.js:24405:35)
    at MultiplexedWebsocketTransport$3methodref$onMessage$Type.handleEvent_2 [as handleEvent] (dh-core.js:24549:10)
```
Which is followed by this exception:
```
Uncaught Error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at IndexOutOfBoundsException_0.createError (dh-core.js:1464:10)
    at IndexOutOfBoundsException_0.initializeBackingError (dh-core.js:1490:46)
    at IndexOutOfBoundsException_0.Throwable_0 (dh-core.js:1421:8)
    at IndexOutOfBoundsException_0.Exception_1 (dh-core.js:1515:18)
    at IndexOutOfBoundsException_0.RuntimeException_1 (dh-core.js:1533:18)
    at new IndexOutOfBoundsException_0 (dh-core.js:39957:25)
    at Object.checkCriticalElementIndex (dh-core.js:49476:16)
    at Object.$get_34 (dh-core.js:44137:7)
    at Object.$parseFrom (dh-core.js:21049:55)
    at Object.$onFlightData (dh-core.js:27991:22)
    at Function.apply_135 (dh-core.js:28156:11)
    at lambda (dh-core.js:193:22)
    at dh-internal.js:1:321778
    at Array.forEach (<anonymous>)
    at dh-internal.js:1:321757
    at dh-internal.js:1:11539
    at Array.forEach (<anonymous>)
    at e.rawOnMessage (dh-internal.js:1:11501)
    at dh-internal.js:1:9314
    at Array.forEach (<anonymous>)
    at e.onTransportChunk (dh-internal.js:1:9189)
    at Object.$onMessage (dh-core.js:24405:35)
    at MultiplexedWebsocketTransport$3methodref$onMessage$Type.handleEvent_2 [as handleEvent] (dh-core.js:24549:10)
```

**Comment by niloc132** [comment]
LocalDate has a similar issue, here's the sample updated to include LocalDate values, and test nulls for both:
```python
from deephaven import empty_table, ui

@ui.component
def test_local_time(table):
    return table;

my_local_time_table = empty_table(10).update(
    [
        "LocalTime1 = i % 2 == 0 ? '10:15:30.46' : null",
        "LocalDate1 = i % 2 == 1 ? '2020-08-04' : null"
    ]
)
my_local_time_componant=test_local_time(my_local_time_table)
```
