### ISSUE TITLE
JSTreeTable.copy throws "UnsupportedOperationException: reexport"

### ISSUE THREAD

**Issue by vbabich** [deephaven/deephaven-core#6097]
**Description**

Calling `copy` on a `JSTreeTable` instance throws an exception:

```
Error: java.lang.UnsupportedOperationException: reexport
    at UnsupportedOperationException_0.createError (dh-core.js:1383:10)
    at UnsupportedOperationException_0.initializeBackingError (dh-core.js:1409:46)
    at UnsupportedOperationException_0.Throwable_0 (dh-core.js:1348:8)
    at UnsupportedOperationException_0.Exception_1 (dh-core.js:1433:18)
    at UnsupportedOperationException_0.RuntimeException_1 (dh-core.js:1446:18)
    at new UnsupportedOperationException_0 (dh-core.js:35418:25)
    at Object.lambda$56 (dh-core.js:24457:14)
    at JsTreeTable$lambda$56$Type.fetch_25 [as fetch_1] (dh-core.js:25453:10)
    at Object.$lambda$32_0 (dh-core.js:31972:23)
    at ClientTableState$lambda$32$Type.accept_90 [as accept] (dh-core.js:32707:9)
    at Function.onInvoke_2 (dh-core.js:5068:12)
    at lambda (dh-core.js:174:22)
    at new Promise (<anonymous>)
    at Object.$refetch_2 (dh-core.js:32098:13)
    at JsTreeTable.copy_1 [as copy] (dh-core.js:24514:16)
    at Proxy.valuesTable (IrisGridTableModelTemplate.ts:1519:32)
```

The copy is used to get the values table for the Advanced Filter dialog in the Web UI. Works fine on tree tables in Enterprise, and non-tree tables in Community.

**Versions**
Engine Version: 0.36.1
Web UI Version: 0.92.0
Java Version: 21.0.4
Barrage Version: 0.6.0
Browser Name: Chrome 126
OS Name: macOS 10.15.7

**Comment by mofojed** [comment]
Filed as DH-19563
