### ISSUE TITLE
Attempting to convert a BigDecimal to a Double crashes Deephaven server

### ISSUE THREAD

**Issue by elijahpetty** [deephaven/deephaven-core#6112]
When attempting to convert a BigDecimal to a Double, the entire Deephaven server crashes due to an uncaught exception. The server should not crash for errors like this.

**steps to reproduce**

Here is the code block that causes the server to crash (Groovy):

```
import io.deephaven.engine.table.impl.util.DynamicTableWriter

ySquareF = { double x ->
    if (x % 2 < 1) {
        return 1.0
    } else {
        return -1.0
    }
}

yTriangleF = { double x ->
    if (x % 2 >= 1) {
        return (x % 1 - 0.5) * 2
    } else {
        return -((x % 1 - 0.5) * 2)
    }
}

columnNames = ["X", "SawToothWave", "SquareWave", "TriangleWave"] as String[]
columnTypes = [double.class, double.class, double.class, double.class] as Class[]
tableWriter = new DynamicTableWriter(columnNames, columnTypes)

waveforms = tableWriter.getTable()

//this throws an error
for (int i = 1; i < 201; i++) {
    start = now().getNano()
    x = (double)(0.1 * i)
    ySawtooth = (x % 1 - 0.5) * 2
    ySquare = ySquareF(x)
    yTriangle = yTriangleF(x)
    map = [ "X" : x, "SawToothWave": ySawtooth, "SquareWave": ySquare, "TriangleWave": yTriangle ]
    tableWriter.logRow(map)
    end = now().getNano()
    dur = parseDuration("PT0.25S")
    Thread.sleep(dur)
}

//this crashes
def thread = Thread.start {
    for (int i = 1; i < 201; i++) {
        start = now().getNano()
        x = (double)(0.1 * i)
        ySawtooth = (x % 1 - 0.5) * 2
        ySquare = ySquareF(x)
        yTriangle = yTriangleF(x)
        map = [ "X" : x, "SawToothWave": ySawtooth, "SquareWave": ySquare, "TriangleWave": yTriangle ]
        tableWriter.logRow(map)
        end = now().getNano()
        dur = parseDuration("PT0.25S")
        Thread.sleep(dur)
    }
}
```

**Expected results**

An error in the log.

**Actual results**

In the thread, the server crashes. An image is attached of the error.

If the for loop is removed from the thread, this error is thrown:
```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.ClassCastException: class java.math.BigDecimal cannot be cast to class java.lang.Double (java.math.BigDecimal and java.lang.Double are in module java.base of loader 'bootstrap')
	at io.deephaven.engine.table.impl.util.DynamicTableWriter$DoubleRowSetterImpl.set(DynamicTableWriter.java:628)
	at io.deephaven.engine.table.impl.util.DynamicTableWriter.logRow(DynamicTableWriter.java:240)
	at io.deephaven.engine.table.impl.util.DynamicTableWriter$logRow$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.deephaven.dynamic.Script_14.run(Script_14.groovy:35)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
	at io.deephaven.engine.util.GroovyDeephavenSession.lambda$evaluate$0(GroovyDeephavenSession.java:352)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.engine.util.GroovyDeephavenSession.evaluate(GroovyDeephavenSession.java:352)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:165)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:165)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:193)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1537)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:995)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by elijahpetty** [comment]
<img width="1415" alt="Screenshot 2024-09-23 at 3 09 18 PM" src="https://github.com/user-attachments/assets/db00bac9-2390-45fa-adbc-4056d8aa7449">

**Comment by rcaudy** [comment]
You're running your own threads, not catching exceptions, and thus hitting the default uncaught exception handler, which is fatal in this case.
If you want to do this, you should either catch your exceptions or install your preferred exception handler.

**Comment by rcaudy** [comment]
I'm not sure I want to loosen the default uncaught exception handler, but I'm open to discussing it.

**Comment by rcaudy** [comment]
Consensus is to keep the status quo.
