### ISSUE TITLE
RowSet handling bug in where?

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#6159]
User reported an exception:
```
ERROR aph-updateExecutor-3 | .AsyncClientErrorNotifier | Error in table update: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "rowSet" is null
	at io.deephaven.engine.rowset.impl.WritableRowSetImpl.getInnerSet(WritableRowSetImpl.java:544)
	at io.deephaven.engine.rowset.impl.WritableRowSetImpl.insert(WritableRowSetImpl.java:130)
	at io.deephaven.engine.table.impl.AbstractFilterExecution.lambda$doFilterParallel$0(AbstractFilterExecution.java:195)
	at io.deephaven.engine.table.impl.AbstractFilterExecution.doFilter(AbstractFilterExecution.java:144)
	at io.deephaven.engine.table.impl.AbstractFilterExecution.lambda$doFilterParallel$1(AbstractFilterExecution.java:221)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:258)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:164)
	at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:49)
	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:711)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:836)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Source operation is likely:
```
time_window(consumer.table(), "timeout", 0, "pending").where(filters=["pending == false"]) 
```

Where `consumer.table()` returns a merge call on a partitioned table.

**Comment by rcaudy** [comment]
This was already fixed in https://github.com/deephaven/deephaven-core/issues/5960.
