### ISSUE TITLE
JS API cannot read numeric array columns, such as from DISTINCT in a UI-created rollup

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#6201]
Display a table with some numeric array columns, such as via a rollup with a distinct agg:

Steps to reproduce:
1. Create a table with a column that can be grouped, and a column to aggregate by distinct in the rollup
    ```python
    from deephaven import empty_table
    t = empty_table(100).update(["A = i % 3", "B = i % 7"])
    ```
1. In the web IDE, open the advanced options > rollup rows, and group by one of the columns
1. Then open the aggregate columns view and specify "distinct" for remaining columns

Expected: data is visible in the UI
Actual: No data loads (and no error shows, see browser console for details)

```
Uncaught Error: java.lang.ClassCastException
    createError dh-core.js:1464
    initializeBackingError dh-core.js:1490
    Throwable_0 dh-core.js:1421
    Exception_1 dh-core.js:1515
    RuntimeException_1 dh-core.js:1533
    ClassCastException_0 dh-core.js:40658
    checkCriticalType dh-core.js:49930
    castTo dh-core.js:324
    asObjectChunk dh-core.js:5204
    contract_7 dh-core.js:11368
    $readChunk_7 dh-core.js:10900
    readChunk_9 dh-core.js:10954
    $parseFrom dh-core.js:21237
    $onFlightData dh-core.js:28343
    apply_144 dh-core.js:28508
    lambda dh-core.js:193
    doExchange dh-internal.js:1
```

Found while testing #6200
Should be fixed by #6065

**Comment by nbauernfeind** [comment]
#6065 is nearly complete and this bug still persists, but the error differs (making it clear that ObjectExpansionKernel is being selected over the IntExpansionKernel).

Will investigate this separately and right after 6065 is ready for review.
```
Uncaught Error: java.lang.ClassCastException
    at ClassCastException_0.createError (dh-core.js:1472:10)
    at ClassCastException_0.initializeBackingError (dh-core.js:1498:46)
    at ClassCastException_0.Throwable_0 (dh-core.js:1429:8)
    at ClassCastException_0.Exception_1 (dh-core.js:1523:18)
    at ClassCastException_0.RuntimeException_1 (dh-core.js:1541:18)
    at new ClassCastException_0 (dh-core.js:41288:25)
    at Object.checkCriticalType (dh-core.js:50564:16)
    at castTo (dh-core.js:326:7)
    at WritableIntChunk$1.asObjectChunk (dh-core.js:5209:10)
    at ObjectArrayExpansionKernel.contract_7 [as contract] (dh-core.js:11079:24)
    at Object.$readChunk_5 (dh-core.js:10297:34)
    at ListChunkReader.readChunk_4 [as readChunk] (dh-core.js:10352:16)
    at Object.$parseFrom (dh-core.js:21040:63)
    at Object.$onFlightData (dh-core.js:28905:22)
    at Function.apply_157 (dh-core.js:29074:11)
    at lambda (dh-core.js:195:22)
    at dh-internal.js:1:350285
    at Array.forEach (<anonymous>)
    at dh-internal.js:1:350264
    at dh-internal.js:1:11539
    at Array.forEach (<anonymous>)
    at e.rawOnMessage (dh-internal.js:1:11501)
    at dh-internal.js:1:9314
    at Array.forEach (<anonymous>)
    at e.onTransportChunk (dh-internal.js:1:9189)
    at Object.lambda$1_12 (dh-core.js:25219:21)
    at Function.onChunk (dh-core.js:25261:10)
    at lambda (dh-core.js:195:22)
    at Object.$onMessage (dh-core.js:25299:35)
    at MultiplexedWebsocketTransport$3methodref$onMessage$Type.handleEvent_2 [as handleEvent] (dh-core.js:25441:10)
```

**Comment by nbauernfeind** [comment]
Colin and I discussed. I'm going to `transformToObject` all primitives in `WebChunkReaderFactory` making sure to convert to `null` from the QueryConstant values. Sub-classes of `WebColumnData` are going to be removed and the `WebObjectColumnData` is going to be promoted to the base class (and is now the real class).

We're confident on this approach as if the test uses long columns instead of int columns things will be working fine. (Noting that long's are promoted to Object earlier in the web barrage parsing logic.)


HeirarchicalTableTestGwt line 373 needs uncommenting to add the automated unit tests for this.
