### ISSUE TITLE
Rollup snapshot error

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#6203]
Seen on 0.34, no additional details yet.

```
13:46:49.218 ERROR heduler-Concurrent-2 | i.h.HierarchicalTableImpl | HierarchicalTable.snapshot error at nodeId=4294967296: java.lang.IllegalArgumentException: size 512 is incompatible with capacity 488
	at io.deephaven.chunk.ChunkBase.internalSetSize(ChunkBase.java:48)
	at io.deephaven.chunk.WritableChunk.setSize(WritableChunk.java:75)
	at io.deephaven.engine.table.impl.sources.immutable.ImmutableConstantIntSource.fillChunk(ImmutableConstantIntSource.java:59)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl$NodeFillContext.fillNormalDestinations(HierarchicalTableImpl.java:1492)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.consumeRowsUntilNextExpansion(HierarchicalTableImpl.java:1390)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.visitExpandedNode(HierarchicalTableImpl.java:1320)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.visitExpandedNode(HierarchicalTableImpl.java:1196)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.visitExpandedNode(HierarchicalTableImpl.java:1327)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.traverseExpansionsAndFillSnapshotChunks(HierarchicalTableImpl.java:1190)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.lambda$snapshotData$7(HierarchicalTableImpl.java:1156)
	at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1262)
	at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1168)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.snapshotData(HierarchicalTableImpl.java:1153)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.snapshot(HierarchicalTableImpl.java:959)
	at io.deephaven.engine.table.impl.hierarchical.RollupTableImpl.snapshot(RollupTableImpl.java:59)
	at io.deephaven.server.hierarchicaltable.HierarchicalTableViewSubscription.buildAndSendSnapshot(HierarchicalTableViewSubscription.java:321)
	at io.deephaven.server.hierarchicaltable.HierarchicalTableViewSubscription.process(HierarchicalTableViewSubscription.java:286)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	at java.base/java.lang.Thread.run(Thread.java:1583)
13:46:49.219 ERROR heduler-Concurrent-2 | i.d.s.s.SessionService    | Internal Error '8ed4bb06-72da-4ae0-ae4b-f83c685fac8f' io.deephaven.engine.exceptions.SnapshotUnsuccessfulException: Failed to execute function concurrently despite consistent state
	at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1340)
	at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1168)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.snapshotData(HierarchicalTableImpl.java:1153)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.snapshot(HierarchicalTableImpl.java:959)
	at io.deephaven.engine.table.impl.hierarchical.RollupTableImpl.snapshot(RollupTableImpl.java:59)
	at io.deephaven.server.hierarchicaltable.HierarchicalTableViewSubscription.buildAndSendSnapshot(HierarchicalTableViewSubscription.java:321)
	at io.deephaven.server.hierarchicaltable.HierarchicalTableViewSubscription.process(HierarchicalTableViewSubscription.java:286)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.deephaven.engine.table.impl.hierarchical.HierarchicalTableSnapshotException: HierarchicalTable.snapshot error
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.visitExpandedNode(HierarchicalTableImpl.java:1344)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.visitExpandedNode(HierarchicalTableImpl.java:1196)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.visitExpandedNode(HierarchicalTableImpl.java:1327)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.traverseExpansionsAndFillSnapshotChunks(HierarchicalTableImpl.java:1190)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.lambda$snapshotData$7(HierarchicalTableImpl.java:1156)
	at io.deephaven.engine.table.impl.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1262)
	... 13 more
Caused by: java.lang.IllegalArgumentException: size 512 is incompatible with capacity 488
	at io.deephaven.chunk.ChunkBase.internalSetSize(ChunkBase.java:48)
	at io.deephaven.chunk.WritableChunk.setSize(WritableChunk.java:75)
	at io.deephaven.engine.table.impl.sources.immutable.ImmutableConstantIntSource.fillChunk(ImmutableConstantIntSource.java:59)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl$NodeFillContext.fillNormalDestinations(HierarchicalTableImpl.java:1492)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.consumeRowsUntilNextExpansion(HierarchicalTableImpl.java:1390)
	at io.deephaven.engine.table.impl.hierarchical.HierarchicalTableImpl.visitExpandedNode(HierarchicalTableImpl.java:1320)
	... 18 more
```

**Comment by rcaudy** [comment]
This appears to be the result of a very embarrassing bug that would never be hit without:
1. viewport size > 512
2. a node that doesn't _exactly_ fit into the remaining viewport, but that does need to supply more than 512 contiguous rows in the viewport

I was able to reproduce by changing the chunk size constant from 512 to 16, with this test query:
`t=emptyTable(1_000_000).updateView("II=ii", "Cat=ii%100")`
Then rolled up by "Cat" in the UI.
