### ISSUE TITLE
ChunkerParserTest failure

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#631]
```
Condition failed with Exception:

testSearch 5, ChunkerIdent,  '', 'd', 'b'
|             |
|             class io.deephaven.lang.generated.ChunkerIdent
Assertion failed: 
 
assert match == at
       |     |  |
       d     |  i
             false
 
	at io.deephaven.lang.completion.CompletionAssertion.isValid(CompletionAssertion.groovy:63)
	at io.deephaven.lang.completion.ChunkerParseTestMixin$Trait$Helper.testSearch(ChunkerParseTestMixin.groovy:30)
	at io.deephaven.lang.completion.ChunkerParserTest.Completion should work with many types of quotes(ChunkerParserTest.groovy:136)

	at io.deephaven.lang.completion.ChunkerParserTest.Completion should work with many types of quotes(ChunkerParserTest.groovy:136)
Caused by: Assertion failed: 

assert match == at
       |     |  |
       d     |  i
             false

	at io.deephaven.lang.completion.CompletionAssertion.isValid(CompletionAssertion.groovy:63)
	at io.deephaven.lang.completion.ChunkerParseTestMixin$Trait$Helper.testSearch(ChunkerParseTestMixin.groovy:30)
	... 1 more
```

**Comment by devinrsmith** [comment]
This *should* be exercised by our long check ci - and I can verify from the logs that open-api-lang-tools:test *is* being run, but isn't failing there. Maybe some sort of non-determinism?

**Comment by devinrsmith** [comment]
Verifying my code that exercised this in CI is up-to-date.

**Comment by devinrsmith** [comment]
Is a personal branch issue after making some db.timeTable fixes. Sorry.
