### ISSUE TITLE
NPE in StreamToBlinkTableAdapter via ProtobufDescriptorParserImpl for a message with an empty repeated message field

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#6393]
**Description**
```
import io.deephaven.enterprise.webclientdata2.*
ctx = new PersistentQueryConfigTableContext(ccf.getSubscribed(), ExecutionContext.getContext().getUpdateGraph())
aph-updateExecutor-4 | StreamToBlinkTableAdapter | Error refreshing StreamToBlinkTableAdapter-ProtoMessageTablePublisher: java.lang.NullPointerException: Cannot invoke "com.google.protobuf.Message.getRepeatedFieldCount(com.google.protobuf.Descriptors$FieldDescriptor)" because "message" is null
	at io.deephaven.protobuf.ProtobufDescriptorParserImpl.toArray(ProtobufDescriptorParserImpl.java:535)
	at io.deephaven.protobuf.ProtobufDescriptorParserImpl$FieldContext$RepeatedFieldObject.lambda$mapGenerics$8(ProtobufDescriptorParserImpl.java:398)
	at io.deephaven.function.ObjectFunctions$FunctionImpl.apply(ObjectFunctions.java:171)
	at io.deephaven.function.ObjectFunctions$ObjectMap.apply(ObjectFunctions.java:194)
	at io.deephaven.function.ObjectFunctions$ObjectMap.apply(ObjectFunctions.java:194)
	at io.deephaven.protobuf.ProtobufDescriptorParserImpl.toArray(ProtobufDescriptorParserImpl.java:539)
	at io.deephaven.protobuf.ProtobufDescriptorParserImpl$FieldContext$RepeatedFieldObject.lambda$mapGenerics$8(ProtobufDescriptorParserImpl.java:398)
	at io.deephaven.function.ObjectFunctions$FunctionImpl.apply(ObjectFunctions.java:171)
	at io.deephaven.protobuf.BypassOnNull.apply(BypassOnNull.java:137)
	at io.deephaven.protobuf.BypassOnNull.lambda$of$0(BypassOnNull.java:49)
	at io.deephaven.function.ObjectFunctions$FunctionImpl.apply(ObjectFunctions.java:171)
	at io.deephaven.function.ObjectFunctions$ObjectMap.apply(ObjectFunctions.java:194)
	at io.deephaven.function.ObjectFunctions$ObjectMap.apply(ObjectFunctions.java:194)
	at io.deephaven.processor.function.ChunkUtils.applyInto(ChunkUtils.java:133)
	at io.deephaven.processor.function.ObjectProcessorFunctionsImpl.append(ObjectProcessorFunctionsImpl.java:421)
	at io.deephaven.processor.function.ObjectProcessorFunctionsImpl$ObjectAppender.append(ObjectProcessorFunctionsImpl.java:247)
	at io.deephaven.processor.function.ObjectProcessorFunctionsImpl.processAll(ObjectProcessorFunctionsImpl.java:87)
	at io.deephaven.kafka.ingest.FieldCopierProcessorImpl.copyField(FieldCopierProcessorImpl.java:28)
	at io.deephaven.enterprise.webclientdata2.ProtoMessageTableContext$KeyOrValueProcessorImpl.handleChunk(ProtoMessageTableContext.java:559)
	at io.deephaven.enterprise.webclientdata2.ProtoMessageTablePublisher.flush(ProtoMessageTablePublisher.java:66)
	at io.deephaven.stream.StreamToBlinkTableAdapter.doRefresh(StreamToBlinkTableAdapter.java:370)
	at io.deephaven.stream.StreamToBlinkTableAdapter.run(StreamToBlinkTableAdapter.java:318)
	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph$UpdateSourceRefreshNotification.run(BaseUpdateGraph.java:964)
	at io.deephaven.engine.updategraph.impl.BaseUpdateGraph.runNotification(BaseUpdateGraph.java:711)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:836)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1109)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Versions**
0.36.1 (via DHE sanluis dependency)
 - Deephaven: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by devinrsmith** [comment]
https://github.com/deephaven/deephaven-core/blob/main/extensions/protobuf/src/main/java/io/deephaven/protobuf/ProtobufDescriptorParserImpl.java#L219-L236 is relevant, and has a useful comment:

```java
// The majority of the time, we need to BypassOnNull b/c the Message may be null. In the
// case where the message is part of a repeated field though, the Message is never null
// (it's always implicitly present based on the repeated count).
```

it would be worth it to step through this with the message descriptor in question.

**Comment by jcferretti** [comment]
The issue is not the repeated message itself, but one of the fields of the repeated message, which is optional:

```
message PersistentQueryStateMessage {
  int64 serial = 1;
  int64 version = 2;

  PersistentQueryStatusEnum status = 3;
  int64 initializationStartNanos = 4;
  int64 initializationCompleteNanos = 5;
  int64 lastUpdateNanos = 6;

  string dispatcherHost = 7;

  repeated NamedStringList tableGroups = 8;
  repeated ExportedObjectInfoMessage scopeTypes = 9;

  optional ProcessorConnectionDetailsMessage connectionDetails = 10;   //  <=== HERE
[...]
```

![image](https://github.com/user-attachments/assets/3d429dc8-b8e3-47fd-8167-a8daaf1eb335)

**Comment by jcferretti** [comment]
The unit test in DHE that repros (requires code in the same branch):
https://github.com/deephaven-ent/iris/blob/4daef3bcc37684bb3016b8fdb7072dde946eb1e2/DhcInDhe/WebClientData2/src/test/java/io/deephaven/enterprise/webclientdata2/ProtoMessageTablePublisherTest.java#L141

Note that if replicas is empty, the bug is not triggered.  Namely if the lines below are removed (so that replicas is empty as per the builder default when not set), then the NPE does not happen:
```
                            .addReplicas(
                                    PersistentQueryStateMessage.newBuilder()
                                            .setSerial(serial)
                                            .build()
                            )
```
