### ISSUE TITLE
Failure in reading Iceberg tables partitiond by date

### ISSUE THREAD

**Issue by malhotrashivam** [deephaven/deephaven-core#6419]
On reading an iceberg table partitioned by date, the core app fails with the following error:

```
Caused by: io.deephaven.engine.table.impl.locations.TableDataException: Partitioning column event_date has type java.lang.Integer but expected java.time.LocalDate
	at io.deephaven.iceberg.layout.IcebergKeyValuePartitionedLayout.keyFromDataFile(IcebergKeyValuePartitionedLayout.java:96)
	at io.deephaven.iceberg.layout.IcebergBaseLayout.findKeys(IcebergBaseLayout.java:197)
```
Basically, the partitioning value is being read as an integer from the `PartitionData` associated with the `DataFile` instead of being casted to the right type.

As part of this issue, we should fix it. I have linked the steps to reproduce this error in the comment.

**Comment by malhotrashivam** [comment]
First create such a table using Pyiceberg

```
import boto3
from pyiceberg.catalog import load_catalog
from pyiceberg.schema import Schema
from pyiceberg.types import NestedField, StringType, DoubleType
from pyiceberg.partitioning import PartitionSpec, PartitionField
from pyiceberg.transforms import IdentityTransform

# I am working with MinIO here, following values depend on the MinIO configuration

session = boto3.Session(
    aws_access_key_id='admin',
    aws_secret_access_key='password',
    region_name='us-east-1'
)

catalog = load_catalog(
    name='minio-iceberg',
    uri='http://rest:8181',
    warehouse='s3a://warehouse/wh',
    session=session,
    **{
        "s3.endpoint": "http://127.0.0.1:9000",
        "s3.access-key-id": "admin",
        "s3.secret-access-key": "password",
    }
)

# Creating a table partitioned on date

schema = Schema(
    NestedField(1, "city", StringType(), required=False),
    NestedField(2, "lat", DoubleType(), required=False),
    NestedField(3, "event_date", DateType(), required=False),
)

partition_spec = PartitionSpec(
    PartitionField(
        source_id=3, field_id=1000, transform=IdentityTransform(), name="event_date"
    )
)

tbl = catalog.create_table("default.cities", schema=schema, partition_spec=partition_spec)

# Add some data to it

import pyarrow as pa
from datetime import date

df = pa.Table.from_pylist(
    [
        {"city": "Amsterdam", "lat": 52.371807, "event_date": date(2023, 11, 23)},
        {"city": "San Francisco", "lat": 37.773972, "event_date": date(2023, 11, 23)},
        {"city": "Drachten", "lat": 53.11254, "event_date": date(2023, 11, 24)},
        {"city": "Paris", "lat": 48.864716, "event_date": date(2023, 11, 24)},
    ],
)

tbl.append(df)

# Print the data
tbl = catalog.load_table("default.cities")
print(tbl.scan().to_pandas())
```


Then read this table using deephaven:
```
tableAdapter = catalogAdapter.loadTable("default.cities")
fromIceberg = tableAdapter.table()
```
