### ISSUE TITLE
QueryTestTest.testReverseClipping CI failure on occassion

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#642]
```
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertNotNull(Assert.java:256)
	at junit.framework.Assert.assertNotNull(Assert.java:248)
	at junit.framework.TestCase.assertNotNull(TestCase.java:417)
	at io.deephaven.db.v2.QueryTableTest.testReverseClipping(QueryTableTest.java:1007)
```

Lots of stdout and stderr (too much to paste here, can link if necessary).

But, this stderr may be relevant:
```
[LiveTableMonitor-unitTestRefresh-1] ERROR io.deephaven.db.v2.InstrumentedListener - Uncaught exception for entry= ungroup([Y]), added.size()=1, modified.size()=0, removed.size()=0, shifted.size()=0, modifiedColumnSet={ALL}:
java.lang.IllegalStateException: Key overflow detected, perhaps you should flatten your table before calling ungroup.  ,lastKey=36028797018963968, base=10
        at io.deephaven.db.v2.QueryTable.getUngroupIndex(QueryTable.java:2596)
        at io.deephaven.db.v2.QueryTable.access$1000(QueryTable.java:67)
        at io.deephaven.db.v2.QueryTable$5.evaluateIndex(QueryTable.java:2215)
        at io.deephaven.db.v2.QueryTable$5.onUpdate(QueryTable.java:2130)
        at io.deephaven.db.v2.InstrumentedListener$Notification.lambda$run$0(InstrumentedListener.java:48)
        at io.deephaven.db.v2.InstrumentedListenerBase$NotificationBase.doRunInternal(InstrumentedListenerBase.java:223)
        at io.deephaven.db.v2.InstrumentedListenerBase$NotificationBase.doRun(InstrumentedListenerBase.java:205)
        at io.deephaven.db.v2.InstrumentedListener$Notification.run(InstrumentedListener.java:43)
        at io.deephaven.db.tables.live.LiveTableMonitor.runNotification(LiveTableMonitor.java:1174)
        at io.deephaven.db.tables.live.LiveTableMonitor.access$1000(LiveTableMonitor.java:68)
        at io.deephaven.db.tables.live.LiveTableMonitor$QueueNotificationProcessor.doWork(LiveTableMonitor.java:1323)
        at io.deephaven.db.tables.live.LiveTableMonitor.flushNormalNotificationsAndCompleteCycle(LiveTableMonitor.java:1058)
        at io.deephaven.db.tables.live.LiveTableMonitor.flushNotificationsAndCompleteCycle(LiveTableMonitor.java:1007)
        at io.deephaven.db.tables.live.LiveTableMonitor.completeCycleForUnitTestsInternal(LiveTableMonitor.java:837)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by rcaudy** [comment]
Sorry, closed by accident.

**Comment by rcaudy** [comment]
I think the listener stack trace in the description is a red herring. There are unit tests in the same suite that deliberately test key overflow in ungroup, and this test doesn't appear to do any ungroup. Please link or attach full stdout/stderr logs.

**Comment by devinrsmith** [comment]
https://github.com/devinrsmith/deephaven-core/suites/2788960108/artifacts/61998531
