### ISSUE TITLE
`TestSpecialPrimitives.testRandomGaussian` random failures delaying pull request merges

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#668]
The following naughty test sometimes causes CI runs to fail:
```
junit.framework.AssertionFailedError: expected:<4.5> but was:<4.291127424675369>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:120)
	at junit.framework.Assert.assertEquals(Assert.java:129)
	at junit.framework.TestCase.assertEquals(TestCase.java:288)
	at io.deephaven.libs.primitives.TestSpecialPrimitives.testRandomGaussian(TestSpecialPrimitives.java:121)
```
Please fix or remove the test.

**Comment by devinrsmith** [comment]
Also, this:

```
junit.framework.AssertionFailedError: expected:<50.04999923706055> but was:<52.86131051063538>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:120)
	at junit.framework.Assert.assertEquals(Assert.java:129)
	at junit.framework.TestCase.assertEquals(TestCase.java:288)
	at io.deephaven.libs.primitives.TestSpecialPrimitives.testRandomFloat(TestSpecialPrimitives.java:93)
```

**Comment by devinrsmith** [comment]
IMO, we should get rid of any "random" tests that involve fine float math like this. We should structure the condition-under-test more explicitly if we think they are valuable tests. As a middle ground, and something that will likely be a really easy fix, we can seed the Random w/ a seed we know "works".

**Comment by chipkent** [comment]
I agree that we should target determinism.  These tests are all for the old primitives library.  We have a new primitives library that will replace the old stuff.  I don't want to waste time on the old stuff, since it is dead.  The commit should reduce the frequency of the problem.  We can reopen this ticket if we see non-determinism when the new primitives library gets in.
