### ISSUE TITLE
Investigate if there is any way to better utilize numba @njit decorated functions in DH

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#700]
@njit is another numba annotation that lets numba to compile  the decorated Python function down to C++ code to speed it up. Usually it is used in conjunction with numba arrays or when the function needs to iterate through a large collection.  Currently a @njit decorated function is called the same way as a regular Python function and that may or may not be the best we can do to fully utilize this capability of numba

**Comment by jmao-denver** [comment]
```
# from deephaven import TableTools
# from deephaven import java
# from deephaven.numba import njit, vectorize
# import time


# table_size = 1000000

# @njit
# def my_manual(x: java.int, y: java.int) -> java.int:
#     return (x % 3) + y

# start_time = time.time()
# IJ = TableTools.emptyTable(1000).view("I=(int)i", "J=(int)(i * 2)").update(java.formula(my_manual, name = "K", column_names = ["I", "J"])).sumBy()
# print("numba njit : ", time.time() - start_time, "secs")

from deephaven import TableTools
from numba import njit, vectorize
import numpy as np
import random
import time

table_size = 1000000


# @njit (parallel=True, nogil=True )
@njit
def njit_monte_carlo_pi(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return 4.0 * acc / nsamples

def plain_monte_carlo_pi(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return 4.0 * acc / nsamples

start_time = time.time()
njit_sum  = TableTools.emptyTable(1000).view("I=i", "J=(i * 2) + 1").update("K = (double)njit_monte_carlo_pi(J)").sumBy()
print("numba njit : ", time.time() - start_time, "secs")

start_time = time.time()
njit_sum  = TableTools.emptyTable(1000).view("I=i", "J=(i * 2) + 1").update("K = (double)njit_monte_carlo_pi(J)").sumBy()
print("numba njit cached: ", time.time() - start_time, "secs")

start_time = time.time()
plain_sum  = TableTools.emptyTable(1000).view("I=i", "J=(i * 2) + 1").update("K = (double)plain_monte_carlo_pi(J)").sumBy()
print("plain : ", time.time() - start_time, "secs")


@njit
def logistic_regression(Y, X, w, iterations):
    for i in range(iterations):
        w -= np.dot(((1.0 /
              (1.0 + np.exp(-Y * np.dot(X, w)))
              - 1.0) * Y), X)
    return w

start_time = time.time()
njit_sum  = TableTools.emptyTable(1000).view("I=i", "J=(i * 2) + 1").update("K = (double)logistic_regression(I, J, 50, 10)").sumBy()
print("numba njit mixed parameter types: ", time.time() - start_time, "secs")
```

```
08:55:30.494 STDOUT numba njit :  0.1644740104675293 secs
08:55:30.528 STDOUT numba njit cached:  0.03329038619995117 secs
08:55:30.917 STDOUT plain :  0.38938164710998535 secs
08:55:30.957 ERROR r-Scheduler-Serial-1 | i.d.g.s.SessionState      | Internal Error 'b113382c-54cd-4f88-9646-a0755e730c3b' java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'RuntimeError'>
Value: io.deephaven.db.v2.select.FormulaEvaluationException: In formula: K = doubleCast(logistic_regression.call(I, J, 50, 10))
	at io.deephaven.temp.cm260865630987228486v52_0.Formula.applyFormulaPerItem(Formula.java:177)
	at io.deephaven.temp.cm260865630987228486v52_0.Formula.lambda$fillChunkHelper$4(Formula.java:166)
	at io.deephaven.db.v2.utils.OrderedKeys.lambda$forAllLongs$0(OrderedKeys.java:198)
	at io.deephaven.db.v2.utils.singlerange.SingleRangeMixin.forEachLong(SingleRangeMixin.java:13)
	at io.deephaven.db.v2.utils.OrderedKeys.forAllLongs(OrderedKeys.java:197)
	at io.deephaven.temp.cm260865630987228486v52_0.Formula.fillChunkHelper(Formula.java:164)
	at io.deephaven.temp.cm260865630987228486v52_0.Formula.fillChunk(Formula.java:140)
	at io.deephaven.db.v2.select.Formula.getChunk(Formula.java:157)
	at io.deephaven.db.v2.sources.ViewColumnSource.getChunk(ViewColumnSource.java:227)
	at io.deephaven.db.v2.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:116)
	at io.deephaven.db.v2.QueryTable.lambda$null$45(QueryTable.java:1141)
	at io.deephaven.db.tables.utils.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:469)
	at io.deephaven.db.v2.QueryTable.lambda$selectOrUpdate$46(QueryTable.java:1120)
	at io.deephaven.db.v2.QueryTable.memoizeResult(QueryTable.java:2746)
	at io.deephaven.db.v2.QueryTable.selectOrUpdate(QueryTable.java:1119)
	at io.deephaven.db.v2.QueryTable.update(QueryTable.java:1099)
	at io.deephaven.db.tables.Table.update(Table.java:531)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.db.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:53)
	at io.deephaven.db.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:155)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:44)
	at io.deephaven.db.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:154)
	at io.deephaven.db.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:101)
	at io.deephaven.db.util.ScriptSession.evaluateScript(ScriptSession.java:57)
	at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl.lambda$null$8(ConsoleServiceGrpcImpl.java:150)
	at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$1(SessionState.java:1036)
	at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:615)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:44)
	at io.deephaven.grpc_api.session.SessionState$ExportObject.doExportUnderExclusiveLock(SessionState.java:663)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:141)
	at java.lang.Thread.run(Thread.java:748)
caused by java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'numba.core.errors.TypingError'>
Value: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function dot at 0x7fe4c0022c80>) found for signature:
 
 >>> dot(int64, int64)
 
There are 2 candidate implementations:
    - Of which 2 did not match due to:
    Overload of function 'dot': File: numba/core/typing/npydecl.py: Line 957.
      With argument(s): '(int64, int64)':
     No match.

During: resolving callee type: Function(<function dot at 0x7fe4c0022c80>)
During: typing of call at <string> (63)


File "<string>", line 63:
<source missing, REPL/exec in use?>

Line: 361
Namespace: error_rewrite
File: /usr/local/lib/python3.7/dist-packages/numba/core/dispatcher.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
  File "/usr/local/lib/python3.7/dist-packages/numba/core/dispatcher.py", line 361, in error_rewrite

	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.callMethod(PyObject.java:432)
	at io.deephaven.db.util.PythonScopeJpyImpl$CallableWrapper.call(PythonScopeJpyImpl.java:86)
	at io.deephaven.temp.cm260865630987228486v52_0.Formula.applyFormulaPerItem(Formula.java:175)
	... 35 more

Line: 68
Namespace: <module>
File: <string>
Traceback (most recent call last):
  File "<string>", line 68, in <module>

        at org.jpy.PyLib.executeCode(PyLib.java:-2)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
        at io.deephaven.db.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:53)
        at io.deephaven.db.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:155)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:44)
        at io.deephaven.db.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:154)
        at io.deephaven.db.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:101)
        at io.deephaven.db.util.ScriptSession.evaluateScript(ScriptSession.java:57)
        at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl.lambda$null$8(ConsoleServiceGrpcImpl.java:150)
        at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$1(SessionState.java:1036)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:615)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:44)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExportUnderExclusiveLock(SessionState.java:663)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:141)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by jmao-denver** [comment]
1. unlike @vectorized decorator, the @njit decorator doesn't cause numba to change the signature of the decorated function and demand the input parameters to be 'array' types.
2. @njit decorated functions can be called in DH query strings just as regular Python functions. The requirement is the same as well, that is all the input parameters and return value must be of scalar types.
3. @njit decorated functions, because it is compiled into machine code when called, will make the query run faster than with regular Python functions,  especially on large data tables
4. although there might be use cases where supporting numpy arrays in parameters and return values, the semantics of calling such Python functions in query strings are ambiguous and even if we force some artificial restrictions, it is most likely more confusing for the users than beneficial. 

Conclusion: there is no urgency or clear benefits to support calling @njit decorated Python functions in query strings beyond what's currently implemented even though it has significant limitations.

**Comment by jmao-denver** [comment]
@devinrsmith please review the comments and conclustion.

**Comment by devinrsmith** [comment]
Agreed.

We may want to eventually do wrapper-vectorization for singular python functions ourselves. This essentially amounts to moving the logic from FormulaKernelPythonSingularFunction into python itself, such that java only makes the java -> python boundary call once per chunk. But it's only useful for very specific instances, where njit is super fast compared to our cpython transition. And even if not, we can always work around it with user explicit @vectorized.
