### ISSUE TITLE
Ungrouping Java arrays with nulls in different elements causes the IDE to crash

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#807]
**Description**

Attempting to use `ungroup` on a table with Java arrays in the same row that have nulls in different array elements appears to cause DH to crash.

**Steps to reproduce**

The following Python code segment will cause DH to crash:

```python
from deephaven.TableTools import emptyTable
t = emptyTable(1).update("X = new Integer[]{null, 2, 3}", "Z = new Integer[]{4, 5, null}")
t_ungrouped = t.ungroup()
```

**Expected results**

The table `t` looks like this:
```
X         Z
[,2,3]. [4,5,]
```
I would expect the table `t_ungrouped` to have elements in table cells that correspond to the elements in the arrays.

**Actual results**

The following error is generated:

Could not handle barrage update propagation: io.deephaven.UncheckedDeephavenException: Failure to execute snapshot function with unchanged clock.

The stack trace is much longer.  Also, the spinning DH logo comes up and won't stop.  You also can't click "cancel" to stop it.  The only way I've found to remedy this is to reload the webpage altogether.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: OSS
 - OS: OS X Big Sur
 - Browser: Chrome
 - Docker: 20.10.6

**Comment by jjbrosnan** [comment]
Here's the full error text:

heduler-Concurrent-1 | .b.BarrageMessageProducer | BarrageMessageProducer(1b1d59b2): Could not handle barrage update propagation: io.deephaven.UncheckedDeephavenException: Failure to execute snapshot function with unchanged clock
        at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1081)
        at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:942)
        at io.deephaven.db.v2.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:543)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:1492)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:934)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer.access$1300(BarrageMessageProducer.java:84)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:796)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:141)
        at java.lang.Thread.run(Thread.java:748)
caused by:
java.lang.NullPointerException: null
        at io.deephaven.db.v2.sources.UngroupedBoxedIntArrayColumnSource.getInt(UngroupedBoxedIntArrayColumnSource.java:48)
        at io.deephaven.db.v2.sources.chunk.util.chunkfillers.IntChunkFiller.lambda$fillByIndices$1(IntChunkFiller.java:38)
        at io.deephaven.db.v2.utils.ReadOnlyIndex.lambda$forAllLongs$0(ReadOnlyIndex.java:261)
        at io.deephaven.db.v2.utils.singlerange.SingleRange.ixForEachLong(SingleRange.java:87)
        at io.deephaven.db.v2.utils.TreeIndex.forEachLong(TreeIndex.java:216)
        at io.deephaven.db.v2.utils.ReadOnlyIndex.forAllLongs(ReadOnlyIndex.java:260)
        at io.deephaven.db.v2.sources.chunk.util.chunkfillers.IntChunkFiller.fillByIndices(IntChunkFiller.java:37)
        at io.deephaven.db.v2.sources.AbstractColumnSource.defaultFillChunk(AbstractColumnSource.java:369)
        at io.deephaven.db.v2.sources.AbstractColumnSource.fillChunk(AbstractColumnSource.java:358)
        at io.deephaven.db.v2.remote.ConstructSnapshot.getSnapshotDataAsChunk(ConstructSnapshot.java:1433)
        at io.deephaven.db.v2.remote.ConstructSnapshot.serializeAllTable(ConstructSnapshot.java:1247)
        at io.deephaven.db.v2.remote.ConstructSnapshot.lambda$constructBackplaneSnapshotInPositionSpace$2(ConstructSnapshot.java:540)
        at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1010)
        at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:942)
        at io.deephaven.db.v2.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:543)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:1492)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:934)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer.access$1300(BarrageMessageProducer.java:84)
        at io.deephaven.grpc_api.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:796)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:141)
        at java.lang.Thread.run(Thread.java:748)
