### ISSUE TITLE
Worker should communicate fatal errors to client APIs / Web UI

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-core#888]
**Description**

When using DynamicTableWriter, identical mistakes in Java/Groovy cause very different behaviors.  In Python, the expected error is raised.  In Groovy, a TransientFailure occurs which kills the session, forcing a restart of Docker and the GUI.

The error is caused by giving the wrong data type to a particular column (e.g. a string value to an int column).

**Steps to reproduce**

In Python, run the following code to get a working example using DynamicTableWriter to write a row to a table every second. The table has two columns: one with random integers, and one with random ascii characters:

```python
from deephaven import jpy
import random, string, threading, time

DynamicTableWriter = jpy.get_type("io.deephaven.db.v2.utils.DynamicTableWriter")

tableWriter = DynamicTableWriter(["A", "B"], [jpy.get_type("int"), jpy.get_type("java.lang.String")])

t = tableWriter.getTable()

def thread_func():
    for i in range(10):
        a = random.randint(1, 100)
        b = random.choice(string.ascii_letters)
        tableWriter.logRow(a, b)
        time.sleep(1)

thread = threading.Thread(target = thread_func)
thread.start()
```

Now, to get an error, replace `tableWriter.logRow(a, b)` with `tableWriter.logRow("ABC", b)`.  As expected, the console spits out an error telling you you cant cast a Java string to a Java int.

Now, run the following analogue in Groovy:

```groovy
import io.deephaven.db.v2.utils.DynamicTableWriter

chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890".toCharArray()

columnNames = ["A", "B"] as String[]
columnTypes = [int.class, char.class] as Class[]

tableWriter = new DynamicTableWriter(columnNames, columnTypes)

t = tableWriter.getTable()

def thread = Thread.start {
    for (int i = 0; i < 10; i++) {
        a = (int)Math.abs(new Random().nextInt() % [100]) + 1
        charIndex = (int)Math.abs(new Random().nextInt() % [62]) + 1
        b = (char)chars[charIndex]
        tableWriter.logRow(a, b)
        sleep(1000)
    }
    return
}
```

Once again, the code writes ten new rows to a table.  Make the same replacement as in Python (`tableWriter.logRow(a, b)` to `tableWriter.logRow("ABC", b)`).  Instead of an error with stack trace, you get a TransientError and nothing telling you that you just wrote the wrong data type to a column.

**Expected results**

An error telling you to not write strings to an integer column (this is the case in Python)

**Actual results**

A TransientFailure (in Groovy only)

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: OSS
 - OS: Big Sur
 - Browser: Chrome
 - Docker: 20.10.6

**Comment by nbauernfeind** [comment]
This is a pretty curious use case. The primary concern is that the groovy script already has an error. In particular the character array is 0 indexed. So one way the script fails is like this:

```
grpc-api_1    | Initiating shutdown due to: Uncaught exception in thread Thread-8
grpc-api_1    | java.lang.ArrayIndexOutOfBoundsException: 62
grpc-api_1    | 	at org.codehaus.groovy.runtime.dgmimpl.arrays.CharacterArrayGetAtMetaMethod.invoke(CharacterArrayGetAtMetaMethod.java:38)
grpc-api_1    | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
grpc-api_1    | 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.invoke(PojoMetaMethodSite.java:48)
grpc-api_1    | 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
grpc-api_1    | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
grpc-api_1    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
grpc-api_1    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
grpc-api_1    | 	at io.deephaven.dynamic.Script_6$_run_closure1.doCall(Script_6.groovy:47)
grpc-api_1    | 	at io.deephaven.dynamic.Script_6$_run_closure1.doCall(Script_6.groovy)
grpc-api_1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
grpc-api_1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
grpc-api_1    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
grpc-api_1    | 	at java.lang.reflect.Method.invoke(Method.java:498)
grpc-api_1    | 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
grpc-api_1    | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
grpc-api_1    | 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
grpc-api_1    | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
grpc-api_1    | 	at groovy.lang.Closure.call(Closure.java:423)
grpc-api_1    | 	at groovy.lang.Closure.call(Closure.java:417)
grpc-api_1    | 	at groovy.lang.Closure.run(Closure.java:504)
grpc-api_1    | 	at java.lang.Thread.run(Thread.java:748)
```

I rewrote your thread impl to reduce some of the noise:
```groovy
def thread = Thread.start {
    r = new Random()
    for (int i = 0; i < 10; i++) {
        a = r.nextInt(100) + 1
        charIndex = r.nextInt(chars.length)
        b = (char)chars[charIndex]
        tableWriter.logRow(b, a)
        sleep(1000)
    }
}
```

If I do swap the `a` and `b` params, then I get the follow error (the one you expect to see):
```
grpc-api_1    | Initiating shutdown due to: Uncaught exception in thread Thread-10
grpc-api_1    | java.lang.ClassCastException: java.lang.Character cannot be cast to java.lang.Integer
grpc-api_1    | 	at io.deephaven.db.v2.utils.DynamicTableWriter$IntRowSetterImpl.set(DynamicTableWriter.java:432)
grpc-api_1    | 	at io.deephaven.db.v2.utils.DynamicTableWriter.logRow(DynamicTableWriter.java:229)
grpc-api_1    | 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
grpc-api_1    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
grpc-api_1    | 	at java.lang.reflect.Method.invoke(Method.java:498)
grpc-api_1    | 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:189)
grpc-api_1    | 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
grpc-api_1    | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
grpc-api_1    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
grpc-api_1    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
grpc-api_1    | 	at io.deephaven.dynamic.Script_18$_run_closure1.doCall(Script_18.groovy:51)
grpc-api_1    | 	at io.deephaven.dynamic.Script_18$_run_closure1.doCall(Script_18.groovy)
grpc-api_1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
grpc-api_1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
grpc-api_1    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
grpc-api_1    | 	at java.lang.reflect.Method.invoke(Method.java:498)
grpc-api_1    | 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
grpc-api_1    | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
grpc-api_1    | 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
grpc-api_1    | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
grpc-api_1    | 	at groovy.lang.Closure.call(Closure.java:423)
grpc-api_1    | 	at groovy.lang.Closure.call(Closure.java:417)
grpc-api_1    | 	at groovy.lang.Closure.run(Closure.java:504)
grpc-api_1    | 	at java.lang.Thread.run(Thread.java:748)
```

However, these errors are _not_ making it to the browser window. Normally we catch these errors and propagate them back to you on your behalf. In this case you are creating a new thread and there is "practically" no way for us to catch this error. 

Now, we also listen for uncaught exceptions. When we receive one we assume something has gone wildly wrong and terminate ASAP to not mask some issue for a long time.

I do think that we can look for `io.deephaven.dynamic` somewhere in the stack trace to know to treat it like a non-fatal exception.

**Comment by rcaudy** [comment]
@niloc132 @mofojed Just making sure this ticket is on your radar once Nate adds an error notification.
