### ISSUE TITLE
Failed barrage subscriptions result in hung UI

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#896]
I am calling ParquetTools.readTable('/data/file.parquet') from the web UI for a file that I know we don't support (data nested > 1 levels).  The method throws an exception, which is expected.  The Web UI seems to be left in a bad state tho; the table window has that "spinning DH logo" that is there while you load, that never goes away.  Clicking the "cancel" button just seems to re-trigger the same exception (judging by the log).  The bad user experience potentially here is that the table window never goes away, which is what I would expect to happen if I click "cancel".

See attached image:
![Deephaven - Google Chrome_025](https://user-images.githubusercontent.com/37232625/126849138-0f1a41c0-f0a9-430b-8ef9-5d3be546aa07.png)

The exception:
```
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1116)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:977)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:578)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:1524)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:926)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.access$1400(BarrageMessageProducer.java:89)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:790)
grpc-api_1    |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
grpc-api_1    |         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
grpc-api_1    |         at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
grpc-api_1    |         at java.lang.Thread.run(Thread.java:748)
grpc-api_1    | caused by:
grpc-api_1    | java.lang.UnsupportedOperationException: Nested optional levels not supported
grpc-api_1    |         at io.deephaven.parquet.ColumnPageReaderImpl.materializeWithNulls(ColumnPageReaderImpl.java:679)
grpc-api_1    |         at io.deephaven.parquet.ColumnPageReaderImpl.materialize(ColumnPageReaderImpl.java:344)
grpc-api_1    |         at io.deephaven.parquet.ColumnPageReaderImpl.readPageV1(ColumnPageReaderImpl.java:334)
grpc-api_1    |         at io.deephaven.parquet.ColumnPageReaderImpl.readDataPage(ColumnPageReaderImpl.java:201)
grpc-api_1    |         at io.deephaven.parquet.ColumnPageReaderImpl.materialize(ColumnPageReaderImpl.java:75)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.topage.ToPage.getResult(ToPage.java:52)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.topage.ToPage.toPage(ToPage.java:77)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.ColumnChunkPageStore.toPage(ColumnChunkPageStore.java:158)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.VariablePageSizeColumnChunkPageStore.getPage(VariablePageSizeColumnChunkPageStore.java:111)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:150)
grpc-api_1    |         at io.deephaven.db.v2.locations.parquet.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:17)
grpc-api_1    |         at io.deephaven.db.v2.sources.chunk.page.PageStore.fillChunk(PageStore.java:67)
grpc-api_1    |         at io.deephaven.db.v2.sources.regioned.ParquetColumnRegionBase.fillChunk(ParquetColumnRegionBase.java:50)
grpc-api_1    |         at io.deephaven.db.v2.sources.regioned.DeferredColumnRegionBase.fillChunk(DeferredColumnRegionBase.java:71)
grpc-api_1    |         at io.deephaven.db.v2.sources.chunk.page.PageStore.fillChunk(PageStore.java:71)
grpc-api_1    |         at io.deephaven.db.v2.sources.regioned.RegionedColumnSourceBase.fillChunk(RegionedColumnSourceBase.java:31)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.getSnapshotDataAsChunk(ConstructSnapshot.java:1365)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.serializeAllTable(ConstructSnapshot.java:1285)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.lambda$constructBackplaneSnapshotInPositionSpace$2(ConstructSnapshot.java:575)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:1045)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.callDataSnapshotFunction(ConstructSnapshot.java:977)
grpc-api_1    |         at io.deephaven.db.v2.remote.ConstructSnapshot.constructBackplaneSnapshotInPositionSpace(ConstructSnapshot.java:578)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.getSnapshot(BarrageMessageProducer.java:1524)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.updateSubscriptionsSnapshotAndPropagate(BarrageMessageProducer.java:926)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer.access$1400(BarrageMessageProducer.java:89)
grpc-api_1    |         at io.deephaven.grpc_api.barrage.BarrageMessageProducer$UpdatePropagationJob.run(BarrageMessageProducer.java:790)
grpc-api_1    |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
grpc-api_1    |         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
grpc-api_1    |         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
grpc-api_1    |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
grpc-api_1    |         at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
grpc-api_1    |         at java.lang.Thread.run(Thread.java:748)
grpc-api_1    |
```

The code that triggers:

```
from deephaven.ParquetTools import *
t = readTable('/data/nulls_v1_NULLS_SNAPPY.parquet')
```

The file `nulls_v1_NULLS_SNAPPY.parquet` can be obtained from the deephaven-core-test-data repository, here:
https://github.com/deephaven/deephaven-core-test-data/blob/main/parquetFiles/nulls_v1_NULLS_SNAPPY.parquet

One last note:  Judging from the log, every time I press "cancel" the exception is re-triggered, which makes it seem like the readTable operation is retrying.  If this is true this is a potentially very worrisome/bad user experience: re-doing something that a user is trying to cancel when it failed sounds like something that can get very bad very quickly, with the right "destructive" code.

**Comment by nbauernfeind** [comment]
What it looks like is happening to me is that the table exception occurs during the BarrageSourceTable initial propagation to a subscriber.

So, the console command actually succeeded. This is why it tried to load the table. The subscription failed. 
Either:
- We didn't notify the client that the subscription is over.
- Or, the js api client does not yet propagate that to the thing trying to open the table.

**Comment by rcaudy** [comment]
It seems likely that @niloc132 is the next person to own work for this ticket, in order for the JS API to correctly understand that the subscription is broken and inform the web UI. This should come after app_metadata changes land, in order to avoid any duplicative work.

**Comment by niloc132** [comment]
It turns out this isn't a JS API issue after all - having fixed the client so that when a DoExchange (or a ETUM, or a few others) stream dies with an error I retested this, and it appears that this class of error doesn't propagate to any client

BarrageMessageProducer.java
```
                try {
                    if (needsRun.compareAndSet(true, false)) {
                        updateSubscriptionsSnapshotAndPropagate();
                    }
                } catch (final Exception exception) {
                    // TODO: global error notification core/#55
                    log.error().append(logPrefix).append("Could not handle barrage update propagation: ")
                            .append(exception).endl();
                } finally {
                    runLock.unlock();
                }
```

The TODO here is _probably_ where we intended to pass this along, but that would end up being a global error, as opposed to being specific to the table, the export, or the subscription. Can we do better to get this error to only interested parties than just broadcasting it (as I understand, that's all we did in enterprise)?

**Comment by nbauernfeind** [comment]
Thanks for retesting after the other error-handling fixes @niloc132. I'll take it over from here; it is natural to propagate this error to all subscribers. The fix will be small.
