### ISSUE TITLE
Autocompletion triggers "Internal Error [...] Requirement failed: required offset <= command.length()."

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#929]
While in the middle of typing a command I get this exception to show up in the web UI:

```
15:57:17.138 ERROR heduler-Concurrent-1 | i.d.g.s.SessionState      | Internal Error '46f08ee3-f4ae-4255-ae9a-63765f34a2c4' io.deephaven.base.verify.RequirementFailure: Requirement failed: required offset <= command.length().
        at io.deephaven.base.verify.Require.fail(Require.java:95)
        at io.deephaven.base.verify.Require.requirement(Require.java:126)
        at io.deephaven.base.verify.Require.requirement(Require.java:131)
        at io.deephaven.lang.completion.CompletionRequest.<init>(CompletionRequest.java:57)
        at io.deephaven.lang.completion.CompletionRequest.<init>(CompletionRequest.java:48)
        at io.deephaven.lang.completion.ChunkerCompleter.runCompletion(ChunkerCompleter.java:110)
        at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl.lambda$null$24(ConsoleServiceGrpcImpl.java:324)
        at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$1(SessionState.java:1166)
        at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:759)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
        at java.lang.Thread.run(Thread.java:748)
```

James believes this is related to an out-of-order issue with autocomplete requests, per slack exchange here:
https://illumon.slack.com/archives/G01K6UHJ00K/p1627502650324000

**Comment by jcferretti** [comment]
![Deephaven - Google Chrome_028](https://user-images.githubusercontent.com/37232625/127389223-b07943d5-aa48-410d-9b94-f1326a6ee244.png)

**Comment by nbauernfeind** [comment]
There are two JS/Browser patterns I intended to support for any client-streaming style protocols.

1. The client has a strict ordering and there should be no automatic parallelism (only controlled parallelism).
2. The client wants to replace the previous request if it has not yet been processed. 

The first is how DoPut works. I am going to abstract the helper because I also need it for Arrow Flight auth.
The second, IMO, is a minor variation of the first, and I intended to include it in this abstraction. If this is what you think you need to fix the problem, then I will ask for your (@JamesXNelson) feedback to see if it fits what you need, too.

**Comment by JamesXNelson** [comment]
This issue has more than one moving part.

The server **must** wait to process completion until all document change are processed. Then, so long as latestVersion == versionWhenCompleteRequested, we process completion (else discard stale request).  This is necessary for correct completion / avoiding exceptions.

The client *should* queue document change requests if there is already one request pending. This is more for improving non-ssl connections, and is not as important.


Extra flavor:
The server methods in question:
`io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl#changeDocument`
`io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl#getCompletionItems`

Both have a version in their request object: `request.getTextDocument().getVersion()`

We need to ensure that changeDocument are done before getCompletionItems.
I can't remember offhand, but I'm pretty sure version is monatomic, so:
`getCompletion.version > changeDocument.version -> wait`
`getCompletion.version > changeDocument.version -> process`
`getCompletion.version > changeDocument.version -> discard`

so long as the changeDocument are submitted to the parser, the parser is smart enough to handle waiting until parsing is complete, but it presupposes ordered requests, so never needed extra synchronization. So whatever synchronization mechanism we use, we can consider a changeDocument processed once it has been submitted to the parser (changeDocument never blocks on parsing, it just submits and returns; the parser handles its own threading / interruption).
